### ISSUE TITLE
Syntax error on optional parameter default value negative number

### ISSUE THREAD

**Issue by yawaramin** [ocaml/ocaml#10019]
Getting a syntax error when trying to set a negative number as an optional parameter default value:

```ocaml
$ utop
│ Welcome to utop version 2.6.0 (using OCaml version 4.11.1)! │
utop # let f ?(x=-1) y = x + y;;
Error: Syntax error
utop # let f ?(x=~-1) y = x + y;;
Error: Syntax error
```

Wrapping in parentheses works: `let f?(x=(-1)) y  = x + y`

But as I understood it, the `~-1` syntax should have been unambiguous for parsing.

**Comment by johnwhitington** [comment]
You need a space before the ~:

```
# let f ?(x= ~-1) y = x + y;;
val f : ?x:int -> int -> int = <fun>
```

This is true when using the equals sign for equality too, since any string of operator-like symbols is an operator:

```
# 4=~-1;;
Error: Unbound value =~-
Hint: Did you mean ~-?
```

I suppose optional arguments could be parsed differently, looking explicitly for token ?, token (, token =, and then parsing everything else before the matching ) on its own?

You can, of course, just use spaces before and after all the time, though this style is unfashionable:

```
# let f ?(x = ~-1) y = x + y;;
val f : ?x:int -> int -> int = <fun>
```

**Comment by yawaramin** [comment]
Ah, yes, that makes sense. Thank you!
