### ISSUE TITLE
Documentation: the description of Array.to_list and Array.of_list does not specify the chosen order

### ISSUE THREAD

**Issue by louisGarde** [ocaml/ocaml#10082]
When you create a list, the 1st added element becomes, when the list is completed, the last element of the list.
When you create an array, the 1st added element is usually the 1st element of the array (index 0)
Depending if you are interested in the creation order or not, you would like to one order or the other in the list.

The description of to_list and of_list does not specify the choice that was made.

**Comment by dra27** [comment]
> When you create a list, the 1st added element becomes, when the list is completed, the last element of the list.

This is not true. A list is constructed from a single head item and an existing tail list - the resulting list has the new item at the start. I guess you are confusing this with tail recursive list functions such as `let rec rev a = function [] -> a | x::xs -> rev (x::a) xs` where the list accumulated in `a` is indeed in reverse, but it was not _constructed_ in reverse, that is a semantic effect of the function's evaluation.

> When you create an array, the 1st added element is usually the 1st element of the array (index 0)
> Depending if you are interested in the creation order or not, you would like to one order or the other in the list.

Indeed, and where this happens, the Standard Library uses the prefix `rev_` to show that the _unexpected_ reversing will have taken place (cf. [List.rev_map](https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALrev_map), [List.rev_map2](https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALrev_map2) and [List.rev_append](https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALrev_append))

> The description of to_list and of_list does not specify the choice that was made.

These are conversion functions - it would be most unexpected for either of them to return/process a list in reverse order. I'd find the statement that these functions process the lists in order to be stating the obvious, somewhat.

**Comment by louisGarde** [comment]
The order is obvious within the List module, not within the Array module where starting from the start or from the end of the Array is equally "obvious".
Indeed, Array.of_list accesses the array by increasing index, whereas Array.to_list accesses the array ... by decreasing index !
This is consistent so that the composition of of_list and to_list is the identity.
But the reverse choice could have been made - of_list with decreasing order, to_list with increasing order. Depending on your context, one choice is "better" that the other.

The purpose of a good documentation is to remove the possible ambiguities: you do not know the context of the reader, what it obvious in -your- context may not be obvious in -all- contexts.

**Comment by gasche** [comment]
The order in which `Array.to_list` traverses the list is not observable by users, as no side-effects occur when a list element is accessed. So this traversal order does not need to be mentioned in the documentation, it is an implementation detail.

What the user can see is the order in which the elements are returned, and this is the obvious natural order: the first element of the array is the first element of the list (and same thing when converting in the other direction). Said otherwise, `Array.get a i` and `List.nth i (Array.to_list a)` return the same value, as they should.

I have the impression that you are confused by something, but what you write is not clear at all so it is hard to tell what you mean. (Which is slightly ironical for a message that tries to improve the clarity of the documentation.) If you want to discuss this topic further, could you please:
- show a concrete example of code that computes something, using those functions, and
- explain why the behavior you observe in this code could be surprising to someone?

**Comment by xavierleroy** [comment]
It would not hurt to have a semi-formal explanation to complement the English wording, like we do for many other list and array functions:
```
 [to_list a] returns the list of all the elements of [a].
In other words, [to_list a] is the list [ [a.(0); ...; a.(length a - 1)] ].

[of_list l] returns a fresh array containing the elements of [l].
In other words, [ of_list  [a1; ...; an] ] is the array [ [| a1; ....; an |] ].
```

**Comment by louisGarde** [comment]
In my context, I know how my data are sorted in my lists, and how they are sorted in my arrays, and I want to check if I can use Array.to_list or not to convert a sorted list into a sorted array. The current description does not help much.
Instead, I need to think:  the first element according to my order is stored at the list tail, so I am using the list in a reverse order, so, knowing the List module, I should expect a function starting with "rev_", so to_list won't fit.

**Comment by gasche** [comment]
If I understand correctly, you mean that you are storing your elements in reverse order in a list, and you were looking for a conversion to an array that would un-reverse the list in passing. This is not a completely uncommon need, but indeed not fulfilled by the stdlib for the moment.

(Personally I would rather have a proper module for "snoc lists" in OCaml (we have `RevList` in the compiler codebase now) rather than adding many `rev_*` functions to the List module.)

**Comment by louisGarde** [comment]
That's it. It is certainly a beginner issue, but it was not obvious to me how to check the order management in Array.to_list and Array.of_list. From my perspective, lists and arrays were just two sorts of containers, and both possibilities were equally valid.
