### ISSUE TITLE
Improve documentation of type constraints for the update of C variable of type value

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#10094]
The foreign C interface rules in the documentation does not say anything about respecting typing constraints. If a registered variable (via Caml_paramX, Caml_local X or global roots) hold a value of type value, can it be updated with any data of type value? Or should the programmer respect some level of typing contraints?

The section 20.5 of the documentation should probably say a word on this?

(see also the [thread on caml-list](https://inbox.ocaml.org/caml-list/X+Erq7mY7etyzucJ@oulala/T/#t))

**Comment by craff** [comment]
Moreover, there are some subtelties with acquiring the runtime lock and doing a callback to C.
The callback can only have arguments which are registered global roots and therefore pointer to value, 
or non pointer value like int. 

The code looking like:

```
/* pointer to value should be registered to the GC by the caller */
static void protect_callback(char *name, value *f, value *v1)
{
  caml_acquire_runtime_system();
  {
    CAMLparam0();
    CAMLlocal1(res);
    res = caml_callback_exn(*f, *v1);
    if(Is_exception_result(res))
      fprintf(stderr, "Egl.main_loop: "
	      "WARNING: %s raised an exception\n", name) ;
    CAMLdrop;
  }
  caml_release_runtime_system();
}
```

Not sure the inner block is necessary (found it on the internet)

So the documentation should also include a similar example.

**Comment by dra27** [comment]
I would say there's nothing _wrong_ with the documentation, but the C interface can always be clarified, for which PRs are very welcome (it's easier to discuss actual proposed text). For your two specific points:

- The only two types which the runtime has are unboxed integers and pointers to blocks (20.2). The types were used to construct a program whose execution with those two types will always be sound, but C code written directly does not _have_ to respect that soundness. While code holds the master lock, the only thing which must be respected is the GC rules. If the code releases the master lock leaving values in a semantically unsound state then the program may crash, but there's no "rule" about this (of course, new code should remember that multicore is on the horizon and therefore holding a lock may no longer provide a guarantee that the OCaml-compiled part of the program doesn't see any intermediate unsoundness in values).
- Unless I'm missing something, there's nothing special about the parameters to `caml_callback` which aren't covered by GC rules 1 and 2 (`value`s must be declared using local root macros) and GC rule 4 (`value` which are globals must be registered).

**Comment by xavierleroy** [comment]
The given example is pretty bad:
```
/* pointer to value should be registered to the GC by the caller */
static void protect_callback(char *name, value *f, value *v1)
{
  caml_acquire_runtime_system();
  {
    CAMLparam0();
    CAMLlocal1(res);
    res = caml_callback_exn(*f, *v1);
    if(Is_exception_result(res))
      fprintf(stderr, "Egl.main_loop: "
	      "WARNING: %s raised an exception\n", name) ;
    CAMLdrop;
  }
  caml_release_runtime_system();
}
```
The result of `caml_callback_exn` is NOT a well-formed value, so it must NOT be registered as a root and exposed to the GC.  There is already a warning to this effect in the documentation, https://ocaml.org/releases/4.11/htmlman/intfc.html#s%3Ac-callback.  Here it doesn't really matter because no GC can occur between the return of `caml_callback_exn` and the `CAMLdrop`.  But this is useless and confusing code.

**Comment by craff** [comment]
Thanks for the remark Xavier ... and I actually read the par of the doc about caml_callback_exn ... This code resulted from
me trying to pin the segfault ... forgot to go back ...

**Comment by craff** [comment]
I suggest the following for the documentation (will submit a PR if we converge):

As the beginning of 20.2, I would had a third bullet with a sentence describing the typing constraint on values. Which in fact I do not know exactly and tried to guess in the following sentence

> C code should only construct value with the provided interface described below. These value must be typable, i.e. you should be able to construct the same value using some OCaml code. However, registered global roots, i.e. C pointer to OCaml value, may change type as they can not be accessed directly by OCaml code. For instance, a global root may be initialized to `Val_unit` and mutated later to a value of another type. 

may be the end of this paragraph comes too soon and should be in section 20.5.1

And at the end of 20.12.2:

> When the master lock is released, your program must not manipulate values in the OCaml heap because they might change at any time and in particular be moved by the GC. As a consequence, when you want to do a callback to ocaml while holding the master lock, you can only pass value by reference, i.e. pointer to value that were registered to the GC while holding the lock. Here is an example of such a code:

```
static void protect_callback(char *name, value *f, value *v1)
{
  caml_acquire_runtime_system();
  {
    CAMLparam0();
    if (Is_exception_result( caml_callback_exn(*f, *v1)))
      fprintf(stderr, "WARNING: callback %s raised an exception\n", name) ;
    CAMLdrop;
  }
  caml_release_runtime_system();
}
```

Remains two questions:

Can we use `caml_named_value` when not holding the master lock ?
 Is the inner block really necessary in the above code? I read that CAMLparamX macros can only appear 
at the beginning of a block on the internet ... But I can not find this in the documentation.

**Comment by gadmm** [comment]
> > C code should only construct value with the provided interface described below. These value must be typable, i.e. you should be able to construct the same value using some OCaml code.

This sounds overly constrained to me. If you pass a value in a context where OCaml expects a certain type, the contents should be a valid value for that type.

> > However, registered global roots, i.e. C pointer to OCaml value, may change type as they can not be accessed directly by OCaml code. For instance, a global root may be initialized to `Val_unit` and mutated later to a value of another type.

This would be the case for all values (including e.g. local roots), for initialisation purposes.

> > When the master lock is released, your program must not manipulate values in the OCaml heap because they might change at any time and in particular be moved by the GC. As a consequence, when you want to do a callback to ocaml while holding the master lock, you can only pass value by reference, i.e. pointer to value that were registered to the GC while holding the lock. Here is an example of such a code:

The first sentence is good. For the rest, simply put, only pointers to values that are immediates or registered as roots are guaranteed to still be valid after re-acquiring the lock.

> 
> ```
> static void protect_callback(char *name, value *f, value *v1)
> {
>   caml_acquire_runtime_system();
>   {
>     CAMLparam0();
>     if (Is_exception_result( caml_callback_exn(*f, *v1)))
>       fprintf(stderr, "WARNING: callback %s raised an exception\n", name) ;
>     CAMLdrop;
>   }
>   caml_release_runtime_system();
> }
> ```
> 
> Remains two questions:
> 
> Can we use `caml_named_value` when not holding the master lock ?

Only the master lock protects the table from data races, so if you use systhreads, you will need to hold the lock.

> Is the inner block really necessary in the above code? I read that CAMLparamX macros can only appear
> at the beginning of a block on the internet ... But I can not find this in the documentation.

The CAMLparam/CAMLdrop macros are unnecessary here since you do not declare any local root. The documentation does not go into special cases for simplicity, so you are in the right to infer that you need them. On the other hand, if you follow the documentation then you would need to move the body after acquiring the lock into a second function and use CAMLreturn instead of the undocumented CAMLdrop (which is fine otherwise).

If you actually needed a local root, the inner block would be needed if: - you used C89 without gcc/clang extensions, or - you already had a CAMLparam/CAMLreturn in the enclosing block.

(To clarify, the gist is that the actual rules are not too well documented, and that the documentation offers a simple discipline that is easy to check syntactically, where values are always rooted, but which is insufficiently expressive for your use-case.)

There might be room for improvement in the documentation, the best is to please open the PR you proposed directly and for us to continue the discussion there.
