### ISSUE TITLE
unexpected interaction between or-patterns, as-patterns and polymorphic variants

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10193]
The following program is typed as expected (see result in comment):

```ocaml
let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) as _x) -> `B
  | ((_, `B) as _x) -> `B
(*
val f : [< `A | `B ] -> [> `A | `B ]
*)
```

However, merging the two `B branches changes the type, this is unexpected.

```ocaml
let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) as _x)
  | ((_, `B) as _x) -> `B
(*
val f : [< `A | `B > `B ] -> [> `A | `B ]
*)
```

Another way to observe the same issue makes it look like an `as`-pattern problem, as the unexpected change of type is then introduced by the `as`-pattern:

```ocaml
let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) | (_, `B)) -> `B
(*
val f : [< `A | `B ] -> [> `A | `B ]
*)

let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) | (_, `B)) as _x -> `B
(*
val f : [< `A | `B > `B ] -> [> `A | `B ]
*)
```

This last example comes from @aantron, the maintainer of `ppx_bisect` ( https://github.com/aantron/bisect_ppx/issues/358#issuecomment-772409889 ). The code-coverage instrumentation of `ppx_bisect` inserts `as`-patterns, and ideally it should not affect the type -- but in practice there are case where this insertions breaks typability, such as in the example above.

I would expect that `p` and `p as _` always have the same typing behavior. In #1655 we discussed as-pattern typing, with in particular an [informal specification](https://github.com/ocaml/ocaml/pull/1655#issuecomment-648808376), but not the interaction with polymorphic variants.

**Comment by garrigue** [comment]
Thinking on the way the typing of as-patterns, I'm not that surprised by this behavior.
The problem is that the `_` parts are shared between the original pattern and the `as` variable. If you merge two `as` variables, this is going to cause unifications.
I'll try to find a more understandable explanation, but I think this is the correct behavior (i.e., just the result of the semantics).

The more shocking one is maybe your last example. Why would adding a single `as` change the type. There could maybe be another definition, but this one probably just reflects the fact that it is treated as if it were the 2nd example, which is kind of reasonable too.

**Comment by gasche** [comment]
Yes, our specification from #1655 suggests that

```ocaml
((`B, _) | (_,  `B)) as x
```

should be equivalent to

```ocaml
((`B as x1), x2) | (x1, (`B as x2)) where x = (x1, x2)
```

And indeed, we give the same type to this case:

```ocaml
let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B as x1, x2) | (x1, (`B as x2))) ->
    ignore (x1, x2); `B
(*
val f : [< `A | `B > `B ] -> [> `A | `B ]
*)
```

If I understand correctly what you suggest, `` `B as x1``  gets the type ``[> `B ]``, which is then unified by the or-pattern with the type of `x1` on the right, whose type is shared with the scrutinee.

But then, ``(`B, _) | (_, `B)`` also appears to get typed in the same way:

```ocaml
let f m =
  match m, m with
  | (`B, _) | (_, `B) -> `B
(*
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(`AnyOtherTag, `AnyOtherTag)
val f : [> `B ] -> [> `B ]
*)
```
(here adding `as _x` makes no difference)

A difference then occurs between the two programs when adding the line `` `A, `A -> `A``. Without as-patterns, the input type changes from ``[> `B ]`` to ``[< `A | `B ]``, while with as-patterns it becomes ``[< `A | `B > `B ]``.

**Comment by garrigue** [comment]
Indeed, only in the case of polymorphic variants, the typing of the pattern-matching as a whole also depends on whether the type-checker could find a set of possible constructors such that all polymorphic variant clauses are useful. This is the case if you add the `(A, A)` line, but not if you have only the `(B, _)` and `(_, B)` cases (assuming `_` to mean `B` results in the last line to be useless).

The precise semantics is defined in my paper "Typing deep pattern-matching in presence of polymorphic variants" [PDF](http://www.math.nagoya-u.ac.jp/~garrigue/papers/matching.pdf).

**Comment by gasche** [comment]
I still don't understand why the presence of `as` changes the pressuring behavior.

```ocaml
(* f and g have the same type *)
let f m =
  match m, m with
  | ((`B, _) | (_, `B)) -> `B
let g m =
  match m, m with
  | ((`B, _) | (_, `B)) as _x -> `B
(*
val f : [> `B ] -> [> `B ]
val g : [> `B ] -> [> `B ]
*)

(* f and g now have different types *)
let f m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) | (_, `B)) -> `B
let g m =
  match m, m with
  | `A, `A -> `A
  | ((`B, _) | (_, `B)) as _x -> `B
(*
val f : [< `A | `B ] -> [> `A | `B ]
val g : [< `A | `B > `B ] -> [> `A | `B ]
*)
```

does your paper explain this difference?

**Comment by trefis** [comment]
> I still don't understand why the presence of as changes the pressuring behavior.

I think the key part is that in both cases the alias forces sharing on the type of the wildcards (inside the `or-pat` through `enter_orpat_variables`, outside through `build_as_type`), whilst the two types are separate without it.
Then you can indeed read Jacques paper to understand how the result can differ because of sharing. (note: I won't pretend to fully understand, especially since I've a hard time relating the implementation to the algorithm described in that paper; but I am definitely not surprised that this sharing has an impact)
