### ISSUE TITLE
Non-html manual no longer builds

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#10241]
When running "make" in `manual/` we see:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/john/repos/ocaml/api_docgen latex
make[3]: Circular latex/Stdlib.tex <- latex dependency dropped.
```
...

```
latex/ocamldoc.sty: No such file or directory
latex/Ocaml_operators.tex: No such file or directory
latex/Format_tutorial.tex: No such file or directory
latex/CamlinternalFormatBasics.tex: No such file or directory
latex/CamlinternalAtomic.tex: No such file or directory
latex/Stdlib.tex: No such file or directory
```
...

(`make html` works fine, which I assume is why this was not noticed before).

I presume it is something to do with https://github.com/ocaml/ocaml/commit/4fe88c6a6b8028901607c635df8af4816f9da763#diff-37c5a15bbcf54d720bf8c69c103479bc1125cf932c63d88aef53b857c9ac5ac4 or https://github.com/ocaml/ocaml/commit/5e3cc24f0a278f9a50eb3e7500fa8bb8c7448cfa#diff-37c5a15bbcf54d720bf8c69c103479bc1125cf932c63d88aef53b857c9ac5ac4 so cc @Octachron

**Comment by Octachron** [comment]
This is probably a linuxism that has sneaked inside the Makefile (all targets and the manual work fine for me) . Does the `man` target work?

**Comment by gasche** [comment]
I see, from 4fe88c6a6b8028901607c635df8af4816f9da763#:

```
$(DIRS):   #[Gabriel] $(DIRS) contains latex/
	$(MKDIR) $@

latex: latex/Stdlib.tex

latex/alldoc.tex:alldoc.tex | latex/
```

This looks circular if you consider that `latex` and `latex/` are the same. If there is a difference here, it may come from the version of `make` (different versions of gnu make, or gnu make vs. non-gnu make).

My impression is that the `latex: latex/Stdlib.tex` rule is meant to provide a convenient target named `latex`, and the choice of a name that is also a directory name is accidental. Would it make sense to rename those rules `doc-latex` instead of `latex `(and `doc-html`, etc.), to avoid even the smell of circularity? (I think this directory is fairly new, so probably no one has a long habit of invoking those targets directly?)

**Comment by Octachron** [comment]
I have been discussing with @shindere the idea to move all the output directories under `build` (e.g `latex/` ⇒ `build/latex` ) which will also solve the issue.

**Comment by johnwhitington** [comment]
For reference, OS X make is GNU make 3.81.

With regard to the `man` target, that is by default with `make world.opt` I think? So yes, it works:

```
gorge:ocaml john$ make man
make: Nothing to be done for `man'.
gorge:ocaml john$ cd manual/
gorge:manual john$ make man
make: *** No rule to make target `man'.  Stop.`
```

**Comment by Octachron** [comment]
This should be fixed by the improved makefile that puts all generated files in `api_docgen/build`.
