### ISSUE TITLE
Confusing error message when making a typo in exception name

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#10253]
It takes me a while to realize that I made a typo

```ocaml
  let oo_wrap _env _b f a = f a 
  let reset_labels () : unit = ()
  exception Weird1
  exception Weird3
  let transl_store_label_init _ _ _ _ : int * _  =   raise Weird1
  let transl_label_init _ : _ * 'a = 
      raise Werid3
```
The error message is
```
Error: This variant expression is expected to have type exn
       The constructor Werid3 does not belong to type exn
```
Expected error message: `Werid3` is unbound (+1 if having `did you mean `Werid3`)

**Comment by Octachron** [comment]
The current error message is more detailed than your feature wish: the typechecker knows that `Werid3` should be an `exn`, that `exn` is some variant kind ; and that there are no `exn` constructors in scope named `Werid3`.

We could maybe reorganize the presentation of this available information, but we should not discard it with a `Werid3 is unbound` message. 

Moreover since 4.11, spelling mistake hints are enabled for extensible variant types: the error message raised with your code is:
```ocaml
Error: This variant expression is expected to have type exn
       The constructor Werid3 does not belong to type exn
Hint: Did you mean Weird3?
```

**Comment by dra27** [comment]
I think @bobzhang's point is that there are _no_ constructors called `Werid3`. In the presence of the 4.11+ hint, I think it's already pretty clear, although you could make a case for using the same error as you'd get for `Werid3` in any other context:

```
Error: Unbound constructor Werid3
       This variant expression is expected to have type exn
Hint: Did you mean Weird3?
```
and the existing message when the constructor is known, but is not a member of `exn`? In other words, treat the constructor not being defined at all as more serious than the constructor not being a member of `exn`.

**Comment by Octachron** [comment]
Except that not being in scope is not necessarily an error here. For instance, in
```ocaml
module In_a_compilation_unit_far_away = struct
  type t = A
 end
module In_a_compilation_unit_further_away = struct
  type t = B
end
 let ok    = (A:In_a_compilation_unit_far_away.t)
 let error = (A:In_a_compilation_unit_further_away.t)
 ``` 
the constructor `A` is not more bound in scope in the `ok` case than in the `error` case.

**Comment by dra27** [comment]
@Octachron - indeed, but by "not defined at all" I meant _never defined_ (as in a typo) vs out of scope. I agree that the existing error is considerably better if the constructor has ever been used. But given, for example:

```ocaml
(* as above *)
let error = (B:In_a_compilation_unit_further_away.t)
```

it is more useful here to say "What on earth is `B`?!" 🙂 before talking about type and scoping errors!

**Comment by Octachron** [comment]
Never defined is not a notion that the compiler can ever know: imagine that using `In_a_compilation_unit_further_away` is a typo, and the user was thinking of `In_a_compilation_unit_far_away` which is a module from another library. Then at compilation time, even the cmi file for `In_a_compilation_unit_far_away` might be unavailable.
This is why in general we don't try to guess information from beyond the scope in error messages.
Also remember that our user messages should be read from the last line to the first line.
```ocaml
Error: This variant expression is expected to have type exn
       The constructor Werid3 does not belong to type exn
Hint: Did you mean Weird3?
```
In that order we have:
- a possible fix
- an explanation that there is a mismatch between the expected type and constructor
- the general classification of the error: a type error.

I have the impression than rather than changing the general classification of the error, we could refine the explanation. In particular, could it be that `belong` is unclear in:
```
 The constructor Werid3 does not belong to type exn
```
because it suggests that `Werid3` exists (since most entities exist before they belong).
Maybe reversing the presentation?
```
 The type exn does not define a constructor Werid3
```
or insisting on the negative result of the query 
```
There is no constructor Werid3 in the type exn
```
?

**Comment by xavierleroy** [comment]
> There is no constructor Werid3 in the type exn

This is much better, indeed.

**Comment by bobzhang** [comment]
I tested on 4.12.0 and the error message looks good to me(thanks to the hint), so feel free to close the issue.
```
# let h () = raise Werid1;;
Error: This variant expression is expected to have type exn
       The constructor Werid1 does not belong to type exn
Hint: Did you mean Weird1?
```
To add it a bit, the new error message `The variant expression` is a bit misleading, it indicates that the expression is already type checked which it is not.
Note that the typo is so hard to spot (for a non-native speaker) that by reading the old error message, I thought there must be some bug in the compiler.
