### ISSUE TITLE
Flambda changes the side effect semantic

### ISSUE THREAD

**Issue by Ngoguey42** [ocaml/ocaml#10283]
I'm not sure if this is actually a bug, but depending on the compilation mode, the order of evaluation of side effects differs between a normal and an flambda OCaml.

When `main.ml` contains
```ocaml
let f a b = Printf.printf "%d %d\n" a b

let () =
  let i = ref 0 in
  f (incr i; !i) (incr i; !i)
```

Under `opam switch 4.11.1`, this shell script,
```sh
type ocamlopt

echo > main.mli
rm -f main.exe main.cmx main.o main.cmi main.cmo
ocamlopt -o main.exe main.mli main.ml
./main.exe

rm -f main.mli
rm -f main.exe main.cmx main.o main.cmi main.cmo
ocamlopt -o main.exe main.ml
./main.exe
```

outputs
```
ocamlopt is /Users/nico/.opam/4.11.1/bin/ocamlopt
2 1
2 1
```

and under `opam switch 4.11.2+flambda`, the same shell script outputs
```
ocamlopt is /Users/nico/.opam/4.11.2+flambda/bin/ocamlopt
1 2
2 1
```

**Comment by lthls** [comment]
Thanks for the report. I've proposed a fix in #10284.

**Comment by lthls** [comment]
Some explanations:
The wrong order is caused by a combination of simplifications in `Simplif`. The function `f` is local, so it is transformed into static catch and static raise by `simplify_local_functions`, and then the handler of the static catch is inlined by `simplify_exits` but with a left-to-right evaluation order.
The reason why it only triggers with flambda (and only when there is an empty mli) is that when there is no mli, `f` is exported so cannot be made local; and when flambda is disabled, a different compilation scheme for producing lambda code is used, which stores `f` in a global module block (even though it is not exported), and that in turn means that `f` is not local either.

For reference, here are the various Lambda outputs:
- With closure, `-drawlambda`:
```
(seq
  (let
    (f/80 =
       (function a/82[int] b/83[int]
         (apply (field 1 (global Stdlib__printf!))
           [0: [4: 0a 0a 0a [12: ' ' [4: 0a 0a 0a [12: '\n' 0a]]]] "%d %d\n"]
           a/82 b/83)))
    (setfield_ptr(root-init) 0 (global Test!) f/80))
  (let
    (*match*/119 =
       (let (i/117 = (makemutable 0 (int) 0))
         (apply (field 0 (global Test!)) (seq (+:=1 i/117) (field 0 i/117))
           (seq (+:=1 i/117) (field 0 i/117)))))
    0a)
  0a)
```

- With closure, `-dlambda`:
```
(seq
  (let
    (f/80 =
       (function a/82[int] b/83[int]
         (apply (field 1 (global Stdlib__printf!))
           [0: [4: 0a 0a 0a [12: ' ' [4: 0a 0a 0a [12: '\n' 0a]]]] "%d %d\n"]
           a/82 b/83)))
    (setfield_ptr(root-init) 0 (global Test!) f/80))
  (let
    (*match*/119 =
       (let (i/117 =v[int] 0)
         (apply (field 0 (global Test!))
           (seq (assign i/117 (1+ i/117)) i/117)
           (seq (assign i/117 (1+ i/117)) i/117))))
    0a)
  0a)
```

- With flambda, `-drawlambda`:
```
(let
  (f/80 =
     (function a/82[int] b/83[int]
       (apply (field 1 (global Stdlib__printf!))
         [0: [4: 0a 0a 0a [12: ' ' [4: 0a 0a 0a [12: '\n' 0a]]]] "%d %d\n"]
         a/82 b/83))
   *match*/120 =
     (let (i/117 = (makemutable 0 (int) 0))
       (apply f/80 (seq (+:=1 i/117) (field 0 i/117))
         (seq (+:=1 i/117) (field 0 i/117)))))
  (makeblock 0))
```

- With flambda, `-dlambda`:
```
(let
  (*match*/120 =
     (let
       (i/117 =v[int] 0
        a/121 =[int] (seq (assign i/117 (1+ i/117)) i/117)
        b/122 =[int] (seq (assign i/117 (1+ i/117)) i/117))
       (apply (field 1 (global Stdlib__printf!))
         [0: [4: 0a 0a 0a [12: ' ' [4: 0a 0a 0a [12: '\n' 0a]]]] "%d %d\n"]
         a/121 b/122)))
  (makeblock 0))
```

**Comment by lthls** [comment]
@Ngoguey42 I'm going to add your example (slightly modified) to our testsuite. Do you want to be credited with your github handle or do you prefer a full name ?

**Comment by Ngoguey42** [comment]
GitHub handle is fine, thanks
