### ISSUE TITLE
OCaml INSTALL/manual should mention xcode-select

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10281]
Follow-up issue to https://github.com/ocaml/ocaml/issues/10275#issuecomment-791993400, noting [CompCert's manual](https://compcert.org/man/manual002.html#sec20).

**Comment by Aman9026** [comment]
@dra27 Hi! I'm an outreachy applicant, I want to work on this issue.
Should I update this in [INSTALL.adoc](https://github.com/ocaml/ocaml/blob/trunk/INSTALL.adoc)

**Comment by dra27** [comment]
Thanks, @Aman9026! This would go in INSTALL.adoc, yes - and the text from the CompCert manual is a good template. The only additional check is to ensure that it's sufficient for OCaml (I don't have a spare Mac to be able to check that)

**Comment by kirisky** [comment]
Hi @dra27!  Is this issue still available? I'd like to take it. :smiley:

**Comment by kirisky** [comment]
Hi @gasche ! Can I take this issue?

**Comment by gasche** [comment]
Yes, please feel free. In general, unless someone has explicitly said otherwise, any open issue is available. But asking explicitly can be an occasion to get extra information on the issue; in this case I have no recommendation other than "read the linked Compcert doc and see how to adapt it to OCaml's INSTALL file".

**Comment by kirisky** [comment]
Got it, thank you, @gasche!
