### ISSUE TITLE
[build] Support for composing the compiler in a dune build

### ISSUE THREAD

**Issue by ejgallego** [ocaml/ocaml#10315]
Dear OCaml devs,

a very convenient feature the Dune build system has is the ability to create a compound build of several project just by simply placing their sources under the same workspace. I use this all the time to work on projects involving several components, but the only big missing piece is the OCaml compiler itself.

Ideally, I'd like just to do:
```
$ ln -s $my_ocaml_tree
```

and have my project use OCaml under that tree.

I don't see any, a priori, serious road blocks towards achieving this functionality, and I'd be happy to contribute to it would the developers think it can be upstreamed.

Having the ability to compose with the OCaml compiler itself seems essential to me as to have an effective development workflow in upcoming work we are doing for example porting Coq to multicore OCaml; we'd like to try / debug new things, and the current workflow is just pretty painful to work with, as opposed to simple calling `dune build` and have the whole toolchain regenerated correctly.

Kind regards.

**Comment by gasche** [comment]
(As you probably know) there is a work-in-progress Dune build system inside the compiler codebase. The current consensus is that the compiler folks do not commit to maintain it / keep it working, but that PRs to fix and improve it are welcome. (The main use-case today is to enable Merlin on the compiler codebase, so we don't actually need to produce useful binaries with it, just to compile source modules.) If you want to contribute to that, you are of course welcome.

But would just "a full working Dune build system" solve your problem? How would Dune figure out that, if a compiler is in the tree, it should use *that* compiler to build the other projects? (Or if you don't expect this property to hold, then what are your expectations on the behavior of vendoring the compiler? Just compiler-libs?) My understanding is that currently Dune is not able to be told, within the compiler build, "please use the bootstrap compiler for building". So I would expect that using the in-tree compiler in other projects would not work either; there may be work required upstream in Dune?

**Comment by dra27** [comment]
There's some work going on for the flambda2 backend which at present builds the upstream compiler (ocaml/ocaml) using Dune and then bootstraps itself also using Dune (this is @mshinwell's work). We're working to upstream the fixes to the _existing_ `dune` files to the main compiler with the objective that the Dune build of the compiler produces a correct installation tree.

I don't think Dune would cope with the vendoring, at least at present. Unless it's changed (it's a while since I was able to take a deepish dive in Dune's codebase!), the compiler is determined from the environment as part of the "super context" - I'm not sure if a compiler in the tree is able to override that knowledge.

**Comment by ejgallego** [comment]
> But would just "a full working Dune build system" solve your problem?

Likely a few more tweaks would be needed, but not so many, in my experience Dune is pretty good already in this front I think.

Note that we implemented the same for Coq, so we can just compose Coq with all the libraries, it was quite easy. I expect OCaml to be more challenging.

> How would Dune figure out that, if a compiler is in the tree, it should use that compiler to build the other projects?

For dune, `ocamlc` is just a regular binary, so when resolving it, if a rule to build it is found in the workspace, it will be used; however there are likely some other parts of the system that hardcode ocaml, but once these are fixed, if dune knows how to build `ocamlc`, then it will just add it to the dependency tree. See `Super_context.resolve_program`. Note that existing `.ml -> .cm*` rules in dune already track `ocaml` as a dependency.

So this step is reasonably clean.

> So I would expect that using the in-tree compiler in other projects would not work either; there may be work required upstream in Dune?

Certainly, but not a lot, also, with the upcoming Dune 3.0 model, the build graph is more dynamic so I have better hopes for this to be easy.

The main bit of work is indeed having dune recognize compiler-libs which is a bit special, for example in Coq's bootstrap dune support that's the only really special case, Coq's prelude. We just added a `(boot)` flag to the library stanza so we can inform Dune "this is the prelude library".

> There's some work going on for the flambda2 backend which at present builds the upstream compiler (ocaml/ocaml) using Dune and then bootstraps itself also using Dune (this is @mshinwell's work). We're working to upstream the fixes to the existing dune files to the main compiler with the objective that the Dune build of the compiler produces a correct installation tree.

Great, this is exactly what would be needed! Do you have a pointer to the tree? I'd love to try it out and see where we fail.

> I don't think Dune would cope with the vendoring, at least at present. Unless it's changed (it's a while since I was able to take a deepish dive in Dune's codebase!), the compiler is determined from the environment as part of the "super context" - I'm not sure if a compiler in the tree is able to override that knowledge.

Shouldn't be too much of a deal except for the case when setting the super_context calls the ocaml compiler; if this action can be placed inside the build monad, then you are fine, otherwise, we'd need a case so the needed parameters can be obtained from a different source.

While tricky, I think that is not a huge issue, but I will cc the Dune team so they can comment.

**Comment by avsm** [comment]
This feature would be extremely useful to multicore OCaml ecosystem development as well, as we move into adapting various core libraries (e.g. for multicore IO). I'm maintaining a private monorepo with a large number of opam packages vendored using [opam-monorepo](http://github.com/ocamllabs/opam-monorepo) in a single dune-buildable repository.  Being able to build a particular revision of the OCaml compiler and then build all the packages in a single (and incremental!) `dune build` would save hours and hours of iteration.

(to be clear, I view this is as a strict complement to the Makefile system, and never a replacement)

**Comment by dra27** [comment]
The flambda 2.0 backend is at https://github.com/ocaml-flambda/flambda-backend

**Comment by ghost** [comment]
There is certainly some plumbing to do on the Dune side to make it work, but nothing impossible. Dune supports building the same thing with different configurations in parallel, which would be a natural way to encode the bootstrap. That's how we do cross-compilation for instance.

**Comment by bikallem** [comment]
I wonder if esy can do this feature already? @EduardoRFS ?

**Comment by EduardoRFS** [comment]
@bikallem yes you can do that on esy, but this is not as seamless as what you get with dune vendor, essentially esy can link dependencies locally, nice experience tho.

About this PR, I'm +1 on moving OCaml itself to dune so that this can be achieved and I'm quite happy to know about the work done by @mshinwell to bootstrap OCaml using dune, thank you @dra27

**Comment by ejgallego** [comment]
This would still be extremely useful to me, since I'd love a workflow where I can simultanously hack on OCaml 5.0 and Coq multicore branch, and indeed be able push changes to OCaml in a agile way.

**Comment by gasche** [comment]
My hot take on this issue:

1. Dune is not currently appropriate for complex, non-standard builds, in particular for the way the compiler uses its bootstrap compiler. Attempts at producing a Dune build system for the OCaml compiler either only cover a small part of the needs (eg. Merlin file generation) or turn into eldritch horrors (the flambda2 stuff).
2. Dune is also not designed for "heterogeneous" situations where it needs to compose with other build systems. If it was, it could try to take to the OCaml compiler's make-based build system inside the monorepo. Not just the compiler is affected, any moderately large monorepo mixing several technologies together will suffer from the same issue. This is one of the reason some people are exploring Bazel for OCaml. (Not that Bazel is necessarily better at dealing with other build systems as blackboxes, but it currently scales better than Dune at supporting projects with a mix of "standard OCaml projects" and "other stuff".)

I think that this problem could be attackd from either angles (1) or (2) -- having a solution to either could fulfill the feature request -- but (2) may in fact be more useful in the grand scheme of things as it would benefit more projects than just OCaml.

**Edit**: see @rgrinberg's suggestion below https://github.com/ocaml/ocaml/issues/10315#issuecomment-1398952084 for how to do (2) in Dune today. Things may just work!

**Comment by rgrinberg** [comment]
Thanks for the interesting hot take gasche.

1. Indeed there's no goal to replace the complex bootstrap process in dune builds. Nor do I see the need to do it as the people interested in using dune for the compiler are doing it for the improved developer workflow or for composition in larger dune workspace. Making releases with this toolchain does not seem to be a priority. For these use cases, it seems fine to use some existing version of the compiler to develop rather than relying on bootstrapping.

2. I think using the compiler's make based build system would contradict the goal in 1 in some ways. People aren't interested in using the existing make rules for whatever reason (concurrency, merlin, etc.), how would it help if dune understood them better? Although if it there was any demand for it, making dune understand a limited subset of Make rules somewhat could certainly be done.

**Comment by gasche** [comment]
I'm missing something regarding (1). I am assuming that the intent of including the OCaml compiler in a monorepo is to be able to modify the OCaml compiler, and see the other parts of the monorepo recompiled with the modified compiler. How would that work? My understanding is that it is the same problem as the bootstrap: if you avoid the issue by just building the monorepo with an existing compiler, what are the benefits of having the compiler in the monorepo?

**Comment by gasche** [comment]
What I had in mind for (2) is more a blackbox approach: for any project relying on a "foreign" (non-dune) build system, copy it in a separate sandbox, build it using its foreign build system (but: monitor/strace to collect dependencies), copy  the results (say the installed layout) back inside the dune world.

I am skeptical about the idea of Dune being good at understanding the makefiles, because in my experience the makefiles grow messy fast (and may not necessarily have correct dependency information, etc.). This "whitebox" approach you suggest may work better for integration of other build systems that rely on a restricted declarative language, for example ninja.

**Comment by rgrinberg** [comment]
> I'm missing something regarding (1). I am assuming that the intent of including the OCaml compiler in a monorepo is to be able to modify the OCaml compiler, and see the other parts of the monorepo recompiled with the modified compiler. How would that work? My understanding is that it is the same problem as the bootstrap: if you avoid the issue by just building the monorepo with an existing compiler, what are the benefits of having the compiler in the monorepo?

We would need a setup where there's a workspace that's roughly:

```
$ ls/
ocaml/
$pkg1/
$pkg2/
```

The installed compiler would be used to build the compiler in `ocaml/`, and the resultant compiler would be used to build the rest of the packages in the workspace. That's not possible today, but it's the workflow we'd be aiming for.

> What I had in mind for (2) is more a blackbox approach: for any project relying on a "foreign" (non-dune) build system, copy it in a separate sandbox, build it using its foreign build system (but: monitor/strace to collect dependencies), copy the results (say the installed layout) back inside the dune world.

Isn't that possible already if you just over-approximate deps?
```
$ cat dune
(rule
 (targets ocamlopt.opt ocamlc.opt ..)
 (deps (source_tree compiler/))
 (action (run make %{targets})))
```

Or is that not good enough?

**Comment by gasche** [comment]
I'm not sure about how your sketch of (2) works in practice (I never tried to include a foreign makefile build in my own dune projects, no sir), but you being the dune expert in the room I would certainly believe that it is "good enough". Thanks!

Does that provide a satisfactory solution for this issue then, can people use this approach to build the compiler from dune and drop it in a monorepo? I understand that you still need to have changes in dune to be able to use this "generated compiler" as an OCaml version it knows about. But this may not require any change to the compiler codebase?

**Comment by ejgallego** [comment]
Hi @gasche , thanks for taking interest in this issue, a few comments:

> * Dune is not currently appropriate for complex, non-standard builds, in particular for the way the compiler uses its bootstrap compiler. Attempts at producing a Dune build system for the OCaml compiler either only cover a small part of the needs (eg. Merlin file generation) or turn into eldritch horrors (the flambda2 stuff).

I'm not familiar with the status of this today, but actually the last time I looked the things weren't so bad, it wouldn't take a lot of effort to make the build (including bootstrapping) 100% Dune-based. It is true that it would require generating some rules using a script, but that's not a big deal IMHO. I didn't see anything too special about the way OCaml is built.

To make things smoother Dune could indeed handle the compiler lib a bit specially for the lib DB, but that's all that is needed IMHO (and of course dune locating ocaml as a regular binary).

> * Dune is also not designed for "heterogeneous" situations where it needs to compose with other build systems. If it was, it could try to take to the OCaml compiler's make-based build system inside the monorepo.

It is indeed not designed to do so, but I regularly use dune with other build systems (make and npm) and it is fairly usable, specially after all the issues regarding directories as targets (and promotion) were improved recently.

But that's is not for me a satisfactory solution; this is of course my opinion, but the compiler tooling is not pleasant to use and overall building OCaml with `make` is far from the smooth experience you can get in other OCaml projects and many key features such as `check` would be missing.

That's for me a barrier to contributing to OCaml, but admittedly I have low tolerance for these kind of "old school" dev setups where a full make + install is required.

> Not just the compiler is affected, any moderately large monorepo mixing several technologies together will suffer from the same issue. This is one of the reason some people are exploring Bazel for OCaml. (Not that Bazel is necessarily better at dealing with other build systems as blackboxes, but it currently scales better than Dune at supporting projects with a mix of "standard OCaml projects" and "other stuff".)

How does Bazel scales better than Dune?

I'm puzzled with OCaml + Bazel, if I understand correctly Bazel can't update module dependencies automatically; if that's the case I'm unsure how such a setup would be every usable with OCaml at any medium-scale project.

**Comment by rgrinberg** [comment]
> Does that provide a satisfactory solution for this issue then, can people use this approach to build the compiler from dune and drop it in a monorepo? I understand that you still need to have changes in dune to be able to use this "generated compiler" as an OCaml version it knows about. But this may not require any change to the compiler codebase?

It's not satisfactory yet. Although you can build the compiler inside the workspace, dune always looks up the compiler from outside the workspace.

Another complication is that the standard library isn't a regular dune library. We have some special handling for the stdlib, but we still need to allow the user to configure which compiler will be used to build what inside the workspace.

The most difficult part is probably adding a way to configure all of this inside one workspace without confusing the user.

**Comment by mobileink** [comment]
> How does Bazel scales better than Dune?

What counts as "better" is going to depend on your needs, but bear in mind that Bazel's build engine was designed from the ground-up to support Google's codebase - one gigantic monorepo, 100s of thousands if not millions of source files, multiple languages, multiple build and execution environments, etc. (see [Distributed Builds](https://bazel.build/basics/distributed-builds).) It's unlikely that Dune will ever support that kind of scale, but then again it probably does not need to for most OCaml projects.

Scalability covers a lot of ground.  Size and complexity obviously, but also replicability, maintainability, optimization, test support, etc.  "Hermeticity" is one of Bazel's primary features.  Polyglot support means more that just running other build systems, it means hermeticity guarantees across languages, something Dune cannot offer even for OCaml. For maintainability and optimization, Bazel can emit tons of metatdata about builds, has a very powerful query language, and has some profiling capabilities that can help spot build bottlenecks. Test support is superb - the test machinery is integrated with the build engine, so testing scales as well. Tests are incremental - no source change, no test rerun -  and you can easily select sets of tests to run based on size, runtime, user-defined tags, etc.

**Comment by mobileink** [comment]
> if I understand correctly Bazel can't update module dependencies automatically; if that's the case I'm unsure how such a setup would be every usable with OCaml at any medium-scale project.

It depends on what you mean by "module dependencies".  It is true that Bazel requires that all inputs (source files, tools, parameters) be explicitly registered with Bazel before the build kicks off - that's how you get replicability - so you cannot add a new dependency during the build.  On the other hand you can _configure_ dependencies during the build; for example, you can select a file for compilation (e.g. a windows v. linux v. macos version) based on a build option, provided you have listed all possible selections ahead of time.

That means that maintaining your list of dependencies must be done separately. Dune does this automatically as part of the build, as do the legacy  makefiles (by running ocamldep); with Bazel you just have to split that functionality from the build program proper.

Which means in turn that either we maintain our BUILD.bazel files by hand (not that hard, but still annoying) or we use a tool that can read the OCaml sources (and maybe some other data) and automatically update the dependencies in the BUILD.bazel files.  I've got a tool that can update BUILD.bazel files but I don't have one that can derive deps from source files in the general case. It's easy to use ocamldep to get module dependencies, but then you have to map them to libraries (archives).

**Comment by mobileink** [comment]
> I didn't see anything too special about the way OCaml is built.

Building one of the compilers is not terribly complicated, but that's only the tip of the iceberg.  The build program must support development workflows and testing.  Since we're talking about multiple versions of "the" compiler, each of which can be built with variant configurations, and two runtimes, each of which can also be built with variant configurations, things get pretty complicated pretty fast.  Then add the fact that the VM compilers can emit a variety of executables, using `-custom` or `-make-runtime`, and furthermore that each "compiler" can function as a driver to run other tools (e.g. compile a C file, tell the type checker to emit intermediate representations, etc.) and you end up with a pretty high degree of complexity.  I personally have never seen a project of similar size whose build is anywhere close to the complexity of OCaml toolchain builds.

**Comment by smuenzel** [comment]
> I'm not familiar with the status of this today, but actually the last time I looked the things weren't so bad, it wouldn't take a lot of effort to make the build (including bootstrapping) 100% Dune-based. It is true that it would require generating some rules using a script, but that's not a big deal IMHO. I didn't see anything too special about the way OCaml is built.
> 

It depends a little on how "proper" you want the dune support to be. The dependencies between files/directories aren't arranged in the way that you would a normal dune project, so there's a couple of things to untangle.
You can see my attempt here:  https://github.com/smuenzel/ocamlc-kit/
It's more of a prototype, but it separates the compiler into multiple libraries, removes circular dependencies, and contains some preliminary attempt at allowing the same binary to compile all architecture.
Obviously, there's a lot mixed in there together, but I think this can provide some inspiration of what can be done, and how much effort it would take. I would say that the majority work is figuring out a sensible library structure and untangling dependencies (since files may need to be split and/or moved around in non-obvious ways)

> That's for me a barrier to contributing to OCaml, but admittedly I have low tolerance for these kind of "old school" dev setups where a full make + install is required.

I think another advantage of the dune setup is that you can then easily produce version of the compiler that link in outside libraries, in case you'd like to do some custom processing that isn't suitable for merging upstream, or would require too many dependencies.

**Comment by ejgallego** [comment]
> It depends a little on how "proper" you want the dune support to be.

In my case I just want to put ocaml in my workspace and the right magic happens so now all my ocaml projects are building with the vendored OCaml.

That kind of zero-config setup really makes a huge difference in real life.

> You can see my attempt here: https://github.com/smuenzel/ocamlc-kit/

That's great! Thanks for sharing the project. Hopefully something like this arrives upstream, exposing the compiler as a library is very useful.
