### ISSUE TITLE
List.append is not tail recursive

### ISSUE THREAD

**Issue by orthose** [ocaml/ocaml#10388]
I have noticed the following issue: when I try to append two big lists I have a Stack overflow error.
```ocaml
# let l = List.init 1000000 (fun i -> i);;
# l@l;;
Stack overflow during evaluation (looping recursion?).
```
I have found the definition of the operator @ in ocaml/stdlib/stdlib.ml.
```ocaml
let rec ( @ ) l1 l2 =
  match l1 with
    [] -> l2
  | hd :: tl -> hd :: (tl @ l2)
```
And then in ocaml/stdlib/list.ml
```ocaml
let append = (@)
```
I can see it's a not tail recursive function. But it could be easy to change that to a tail recursive function with CPS (Continuation Passing Style).
```ocaml
let ( @ ) l1 l2 =
    let rec append cps l = 
        match l with
        | [] -> cps l2
        | x :: s -> 
            append (fun r -> cps (x :: r)) s
    in
    if l2 = [] then l1
    else append (fun x -> x) l1;;
```
I have also noticed in ocaml/stdlib/list.mli the following message.
```ocaml
(** List operations.
   Some functions are flagged as not tail-recursive.  A tail-recursive
   function uses constant stack space, while a non-tail-recursive function
   uses stack space proportional to the length of its list argument, which
   can be a problem with very long lists.  When the function takes several
   list arguments, an approximate formula giving stack usage (in some
   unspecified constant unit) is shown in parentheses.
   The above considerations can usually be ignored if your lists are not
   longer than about 10000 elements.
   The labeled version of this module can be used as described in the
   {!StdLabels} module.
 *)
```
Maybe it's a choice to use not tail recursive functions. But, it could be useful to create another List.append function which is tail
recursive.

**Comment by nojb** [comment]
Hello, as you observed there are several list functions in the stdlib that are not tail-recursive (including `List.map`, which is one of the most commonly used functions). The short explanation is that making the functions tail-recursive has a performance cost and since in the vast majority of cases these functions are applied to small lists, the original developers decided to go for the non-tail-recursive versions, and there hasn't been a consensus to change that ever since.

See some related discussion in #867 and #2199.

You may also be interested in #9760 (tail-recursion modulo cons) which approaches this problem from a different direction.

Lastly, note that your proposal is essentially equivalent to `List.rev_append (List.rev l1) l2` which you can use today in your code if you need to handle `l1`'s which are too long for the non-tail-recursive `List.append`.

**Comment by orthose** [comment]
Thanks for your response, you're absolutely right I haven't thought about the performance. And yes, the actual version is faster than my proposal. Your solution works perfectly.
