### ISSUE TITLE
readdir can raise an exception from a blocking section when OOM

### ISSUE THREAD

**Issue by aalekseyev** [ocaml/ocaml#10403]
From code inspection I could tell that
`Sys.readdir` calls the C function `caml_sys_read_directory` (`runtime/sys.c`),
which releases the runtime lock and calls `caml_read_directory` (`runtime/unix.c`),
which calls `caml_ext_table_add` (`runtime/misc.c`),
which calls `caml_stat_resize` (`runtime/memory.c`),
which raises an OCaml exception with `caml_raise_out_of_memory`.

From my understanding, it's not safe to raise exceptions from within a blocking section, so this is a bug. To be clear, I have not seen manifestations of this bug in the wild.

**Comment by gasche** [comment]
There is a `caml_stat_resize_noexc` version. I guess we could have a `caml_ext_table_add_noexc` version whose return value must be checked, and in the `caml_read_directory` case turn it into an error code.

**Comment by dra27** [comment]
I've in passing noticed other possible places like this in runtime (but usually without enough time to stare properly and convince myself that it's definitely an unsafe use!)

The problem with these cases is that on the rare occasions they actually actually happen you get a segfault instead of the rather clearer OOM (or stack overflow) behaviour (we had a recent issue with a stack overflow in a thread for Merlin / ocaml-lsp taking much longer to debug because the stack overflow was coming up in a corner case like this)

**Comment by aalekseyev** [comment]
In fact you're lucky if your program segfaults quickly because I believe there's nothing to detect this and crash the program early. Instead, the exception handler actually gets a chance to run on the wrong thread, and we only get the segfault when the two threads sharing the stack space step on each other's toes.

**Comment by aalekseyev** [comment]
I just looked at the code and it looks the same, so the bug is still there.

**Comment by xavierleroy** [comment]
Should be fixed by #12202.
