### ISSUE TITLE
[RFC] Stdlib thread-safety - Format

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/ocaml#10453]
Multicore OCaml team has been working on ensuring that the stdlib remains backwards compatible and fast for sequential programs, and provides _reasonable_ behaviour when used in parallel by multiple domains. We've [written down](https://github.com/ocaml-multicore/ocaml-multicore/wiki/Safety-of-Stdlib-under-Multicore-OCaml) the guarantees we expect to provide when stdlib is used in parallel. In particular, we propose not to provide thread-safety by default as this would slow down sequential programs. Hence, mutable data structures such as queues will not be thread-safe but remain type-safe. We would also like observationally pure interfaces to remain so even when used in parallel. We have made the internal mutable states in `random`, `filename` and `hashtbl` to be domain-local ([PR#582](https://github.com/ocaml-multicore/ocaml-multicore/pull/582)). 

## Format

Similarly, `format` also has some global state, which causes [issues in functions such as `Format.printf`](https://github.com/ocaml-multicore/ocaml-multicore/issues/563) when used in parallel, though they appear to be observationally pure. We would like to fix `Format.printf` such that they avoid unexpected behaviours -- such as [raising `Stdlib.Queue.Empty` exception](https://github.com/ocaml-multicore/ocaml-multicore/issues/563). 

However, unlike the other modules, the global state used in `format` is exposed by the interface. In particular, the `formatter` type includes [mutable state](https://github.com/ocaml/ocaml/blob/trunk/stdlib/format.ml#L136-L145), and the interface [exposes this mutable state in
`std_fomatter`, `err_formatter`, `str_formatter`, but also `std_buf`](https://github.com/ocaml/ocaml/blob/trunk/stdlib/format.mli#L950-L973). Since accessing domain-local state in Multicore OCaml needs to [run code on the requesting domain](https://github.com/ocaml-multicore/ocaml-multicore/blob/kayceesrk/stdlib_dls/stdlib/domain.mli#L55), the current interface cannot be supported as is. 

## Proposal

The multicore team would prefer not to introduce a breaking change. Hence, our plan is to

1. Introduce domain-local format buffers for stdout, stderr and string formatters. This will fix [Multicore OCaml Issue #563](https://github.com/ocaml-multicore/ocaml-multicore/issues/563).
2. Update the documentation associated with values `std_formatter`, `err_formatter`, `str_formatter` and `std_buf` to indicate that they are the formatters and buffer used by the initial domain.
3. Provide additional functions to access the domain-local stdout, stderr and string formatters and the string buffer.

We request your comments on this proposal. We plan to adopt a similar strategy for other global states that may be exposed by stdlib.

**Comment by gasche** [comment]
I'm not sure I understand the proposal. After it has been implemented, if I try to `Format.fprintf Format.std_formatter ...` from another domain (than the initial one), what happens? Do I get things handled by an internal buffer, and then eventually flushed to stdout? Do I get an error because I should have used one of the "additional functions"?

Some naive remarks below.

Format is not fast, so I would assume that it is not used for performance-critical printing. This suggests that adding synchronization to its internal datastructures would be an option. We probably want to optimize "reasonable behavior" and "programmer convenience" over raw speed here.

From a user perspective, I think that the most convenient behavior in most cases would be to have thread-safe formatters where the output of distinct threads/domains is only interleaved at flush points. This would suggest making the internal state of all formatters thread-local, with a lock around the use of the output device (channel, buffer, etc.).

On the other hand, there are cases where one may want to have some printing done by an auxiliary function, that for some reason may end up running on another domain; there one may expect the mutable pretty-printing state to be shared by both sides. If we have "shared mutable" formatting state, it's relatively easy to build an unsharing operation on top of that (a formatter-copy operation that separates the formatting states, keeping the output device shared) to fix mangled-output issues. On the other hand, it's hard to share pretty-printing state between domains if the library uses thread-local state by default. So this would suggest putting a lock around the whole formatter, with a copy operation that duplicates the printing state but shares the output device.

```ocaml
val clone : formatter -> formatter
(* returns a new formatter with the same output device (channel, buffer, etc.),
   but separate printing functions and pretty-printing state. *)
```

With this last proposal, looking at the problematic examples from https://github.com/ocaml-multicore/ocaml-multicore/issues/563 , then:

The original code:

```ocaml
let () =
  let domains = Array.init 7 (fun i ->
    Domain.spawn (fun () ->
          for j = 1 to 10000000 do () done;
          Format.printf "Running in domain %d@." i;
      )
    ) in
  Array.iter Domain.join domains
```

is safe, but could interleave outputs from different domains together (`Running in domain Running in domain 21`), while

```ocaml
let () =
  let domains = Array.init 7 (fun i ->
    Domain.spawn (fun () ->
          for j = 1 to 10000000 do () done;
          let ppf = Format.clone Format.stdout_formatter in
          Format.fprintf ppf "Running in domain %d@." i;
      )
    ) in
  Array.iter Domain.join domains
```

always works as expected.

**Comment by kayceesrk** [comment]
Thanks for the suggestions @gasche and your review on multicore [PR#582](https://github.com/ocaml-multicore/ocaml-multicore/pull/582)! 

> I'm not sure I understand the proposal. After it has been implemented, if I try to Format.fprintf Format.std_formatter ... from another domain (than the initial one), what happens? Do I get things handled by an internal buffer, and then eventually flushed to stdout? Do I get an error because I should have used one of the "additional functions"?

Since `Format.std_formatter` refers to the initial domain's formatter, the formatting is handled by the internal buffer, and you may see `Stdlib.Queue.Empty` exception as in the [Multicore OCaml issue #563](https://github.com/ocaml-multicore/ocaml-multicore/issues/563). 

> From a user perspective, I think that the most convenient behavior in most cases would be to have thread-safe formatters where the output of distinct threads/domains is only interleaved at flush points. This would suggest making the internal state of all formatters thread-local, with a lock around the use of the output device (channel, buffer, etc.).

Multicore team is leaning towards this option. We [already have lock](https://github.com/ocaml/ocaml/blob/trunk/runtime/io.c#L702-L710) around the use of the output device in OCaml.

> So this would suggest putting a lock around the whole formatter, with a copy operation that duplicates the printing state but shares the output device.

It is not clear to me what a lock around the whole formatter is buying us here. If multiple domains want to share the same format state, then they may use the same formatter with a lock around its use. There need not be a lock in the `Format` module. 

> val clone : formatter -> formatter

Instead of `Format.clone`, the domains can use `val formatter_of_out_channel : out_channel -> formatter` and `val formatter_of_buffer : Buffer.t -> formatter` to share the underlying output device with distinct formatters.

**Comment by gasche** [comment]
There is more in the mutable formatter state than just the output device, for example I can change the formatting geometry or "semantic tag" functions. Consider a program that first sets some geometry, then traverses a tree to pretty-print its content (with a single flush at the end). If I tried to naively parallelize the program by using `DomainsLib.Task` to use fork-join in the traversal, the global-locked formatter would do "the right thing", while the domain-local formatter would not behave as expected at all.

Of course there are also examples where the domain-local formatter does "the right thing" and the global-locked formatter doesn't; typically, a program that traverses some structure and prints some complete messages (with flushes) along the way. A parallel version would mangle the output with a global-locked formatter (the beginning of some messages would occur in the middle of some other), but do "the right thing" (messages are not interleaved) with a domain-local version. (Except that the geometry settings would not be respected by sub-domains, which is a bit weird but ok.)

In both cases it's reasonably easy to fix the "wrong" situation by changing the user code. If we have domain-local "standard formatters" and we want a global-locked semantics, the user can convert their code to use a fixed formatter, provided they implement their own locking. If all formatters are global-locked, the user would have to use the `clone` operation explicitly to get an independent formatter to the same output device.

(One difficulty is that Format does not delay all its printing effects until the next flush, it knows when it will not backtrack and prints in advance in this case. This may cause unpleasant interleaving even in presence of explicit cloning, as long as the output device is shared. We could probably consider changing the Format implementation to stop doing that -- @Octachron is knowledgeable about the internals of the implementation.)

**Comment by kayceesrk** [comment]
>  If we have domain-local "standard formatters" and we want a global-locked semantics, the user can convert their code to use a fixed formatter, provided they implement their own locking. If all formatters are global-locked, the user would have to use the clone operation explicitly to get an independent formatter to the same output device.

The usual reasoning that the multicore team tries to apply in these situations is to first try to retain the backwards compatibility for sequential code and its performance characteristics. Since the parallel programs using Multicore OCaml do not exist yet, we can specify a mechanism to be followed by the not-yet-written parallel code. With that, I'm leaning towards domain-local "standard formatters" with explicit locks when used in parallel.

> One difficulty is that Format does not delay all its printing effects until the next flush, it knows when it will not backtrack and prints in advance in this case. This may cause unpleasant interleaving even in presence of explicit cloning, as long as the output device is shared.

Yes, I was worried about this. I would gladly take the recommendations from @Octachron about how to do this right.

**Comment by jberdine** [comment]
I'm not sure which flush is being referred to here, the format stream can be flushed and the output device buffer can be flushed. From a Format client's perspective, I think that any interleaving of content reaching the output device when there are any open boxes in the format stream will have suboptimal behavior. One could imaging taking a lock when the first box is opened and releasing it when it is closed. If this lock guarded only the output device, then it would be necessary to queue up much more pending output than is currently done where the implementation sends output to the device when lines are complete. (But maybe I'm the only one who opens a box and sends multiple GB before closing it.) Guarding the whole format state would work I think. But it isn't clear to me that this sort of guarding should be built into Format rather than leaving it to the client to do as it needs.

**Comment by jberdine** [comment]
It might be useful to compare to what happens currently with a multi-processing architecture. In this case, each process has its own complete Format state and shares e.g. stdout. Output from the processes gets interleaved only on line boundaries, as the output device buffer is flushed only after complete lines. If the client wants to restrict the interleaving, some client-specific locking mechanism is needed. I think it would be a good target to aim for similar with domains in place of processes, and AFAIU making the Format state domain-local would work for this.

**Comment by Drup** [comment]
I don't quite understand with the description what happens to boxes (and formatting in general) with parallel printing ? I think the use case of "I open an (indented) box, then starts logging lot's of (potentially parallel) operations, then close it" is pretty common. In that case, you need to share the state of the formatter across your various domains. If a lock around the formatter is necessary to achieve that, it should be the default.

In general, I would argue the default should be the configuration that never results in mangled printing. Improved performance (at the risk of mangled printing) should be opt-in.

**Comment by kayceesrk** [comment]
@Drup we don't plan to make stdlib thread-safe by default. We've [written down](https://github.com/ocaml-multicore/ocaml-multicore/wiki/Safety-of-Stdlib-under-Multicore-OCaml) the reasoning behind this. I'm generally not in favour of slowing down sequential code in order to get the safe behaviour for parallel programs. Hence, I would prefer that the version that you describe be opt-in.

**Comment by Drup** [comment]
While I agree with the reasoning in general, in particular applied to data structures, I'm not sure I do in the specific case of printing.

In any case, if it's opt-in, I think the option should be provided as part of `Format` (maybe as an alternative creation function for formatters).

**Comment by kayceesrk** [comment]
> In any case, if it's opt-in, I think the option should be provided as part of Format (maybe as an alternative creation function for formatters).

This sounds reasonable.

https://github.com/ocaml-multicore/ocaml-multicore/pull/586

I have created a PR https://github.com/ocaml-multicore/ocaml-multicore/pull/586 that makes the Format state domain-local. The program in the issue https://github.com/ocaml-multicore/ocaml-multicore/pull/563:

```ocaml
let () =
  let domains = Array.init 7 (fun i ->
    Domain.spawn (fun () ->
          for j = 1 to 10000000 do () done;
          Format.printf "Running in domain %d@." i;
      )
    ) in
  Array.iter Domain.join domains
```

no longer raises the `Stdlib.Queue.Empty` exception, but interleaves the output from several domains:

```
Running in domain 1
Running in domain 4
Running in domain 6
Running in domain Running in domain Running in domain 5
3
Running in domain 0
2
```

This can be fixed, perhaps in a not-so-satisfying manner as:

```ocaml
let () =
  let domains = Array.init 7 (fun i ->
    Domain.spawn (fun () ->
          for j = 1 to 10000000 do () done;
          print_string @@ Format.sprintf "Running in domain %d@." i;
          flush stdout;
      )
    ) in
  Array.iter Domain.join domains
```

which produces:

```
Running in domain 0
Running in domain 1
Running in domain 5
Running in domain 6
Running in domain 3
Running in domain 4
Running in domain 2
```

It would indeed be nice if this functionality were provided by Format, as an opt-in.

**Comment by jberdine** [comment]
Please forgive me for not being up-to-date, but does multicore already have a solution for interleaving output from multiple domains onto a shared `out_channel` only line-by-line? `Format` sets up the standard formatters to call `unsafe_output_string`, so if multicore already has a solution for plain `out_channel`s then it might be easy to reuse it here.

**Comment by kayceesrk** [comment]
Multicore, similar to stock OCaml, atomically outputs `unsafe_output_string`: https://github.com/ocaml-multicore/ocaml-multicore/blob/6246534275a91e250e418f7f33f3fbce8bd00e1f/runtime/io.c#L653-L659. But I see (as someone who's just started looking at Format) that this is not sufficient to get interleaving only at line boundaries. For example,
```ocaml
Format.printf "Running in domain %d@." i;
```
is output as two separate strings `Running in domain` and ` <N>`. 
```ocaml
print_string @@ Format.sprintf "Running in domain %d@." i;
```
forces the string to be constructed first, which ensures that outputs only interleave at line boundaries.

**Comment by gadmm** [comment]
Regarding the interleaving of printing, there was a proposition [here](https://github.com/ocaml/ocaml/pull/9757#issuecomment-676518735) to implement recursive locking for channels and expose it as a feature similar to POSIX `flockfile`, which could complete the current proposal wrt. printing.

Regarding the general proposal:
- _“Type-safety but not thread-safety for mutable data structures -- No crashes!”_: My only interrogation is in the terminology. By type safety, are you trying to convey something more than memory safety? Because from the point of view where abstract data types convey some specification, for instance that `Stack.t` behaves like a stack (actually in thread-safe manner currently, though perhaps by accident), being type-safe implies being thread-safe. So I was wondering if your sentence loses any meaning if I replace type safety with memory safety. (I first wondered this when reading your type-safety claim in the ICFP 2020 paper.)
- _“Observationally pure interfaces remain so”_: we did something similar recently for `Printexc.register_printer` and `at_exit`. However, I was not entirely sure that `at_exit` was ready for multicore, so it might benefit from some review (also in its specification: should the callback be guaranteed to be called from the same domain, or something along these lines?).
- Another place in the stdlib that would benefit from transparent thread-safety are the refcounted resources, namely channels and bigarray proxies. (In the case of channels, IIRC, the flag `CHANNEL_FLAG_MANAGED_BY_GC` can be removed to reveal that it is just plain refcounting.) Since atomic refcounting is delicate, those resources could benefit from a common header implementing atomic refcounting properly.

**Comment by kayceesrk** [comment]
> By type safety, are you trying to convey something more than memory safety?

Good point. We don't claim anything more than memory safety. I'll make this change. 

> we did something similar recently for Printexc.register_printer and at_exit

can you point me to this please?

> should the callback be guaranteed to be called from the same domain, or something along these lines?

Reg `Stdlib.at_exit`, this is process wide, and the callbacks are run when the initial domain terminates. The callbacks are all run by the initial domain. 

I don't know enough about the other items that you have referenced. I'll have to come back to them later.

**Comment by jberdine** [comment]
So a client of `Format` could call `pp_set_formatter_out_functions` with an `out_string` function that only collects a domain-local list of  strings to be printed, and an `out_newline` function that is implemented similarly to multicore's `caml_ml_output_bytes` but adds an outer loop that walks the list inside the `With_mutex`, and a similar `out_flush` function. I don't know, maybe it is faster to use a `Buffer` instead of a list of strings, or some other implementation. My impression is that this could be implemented by the client, but for convenience "it would be nice" if the stdlib included it as an option.

**Comment by jberdine** [comment]
> My impression is that this could be implemented by the client

This is assuming there is some way to interact with the channel's mutex that `caml_ml_output_bytes` is using.

**Comment by gadmm** [comment]
> can you point me to this please?

This is https://github.com/ocaml/ocaml/pull/9571

**Comment by jberdine** [comment]
I added a test of the client-side synchronization to interleave output from different domains only at flush points using a `Buffer` [here](https://github.com/ocaml-multicore/ocaml-multicore/pull/591/commits/fbfa47b6cade1d5669ecbfcafaa80c6c2adb58a5).

**Comment by jberdine** [comment]
With https://github.com/ocaml-multicore/ocaml-multicore/pull/586, formatters other than the predefined ones are still unsafe in the sense that `Stdlib.Queue.Empty` can be raised. Consider:
```ocaml
let ppf = Format.formatter_of_out_channel Stdlib.stdout

let () =
  let domains = Array.init 7 (fun i ->
    Domain.spawn (fun () ->
          for j = 1 to 10000000 do () done;
          for j = 1 to 100 do
            Format.fprintf ppf "The quick brown fox jumped over the lazy dog@.";
          done
      )
    ) in
  Array.iter Domain.join domains
```
This can raise `Stdlib.Queue.Empty`. Is that considered a problem? It seems to me that it would be reasonable for users to expect this code to work as well as the version with `printf` in place of `fprintf ppf`.

To handle such cases, I guess that each field of the `formatter` record would need its own DLS entry, rather than using one entry for the whole record, or make the `formatter` type be a `DLS.key` over the current record type to force all accesses through `DLS.get`.

**Comment by gasche** [comment]
To me this feels like a big can of worms. It's nice that users are not surprised when they write simple things, but the behavior should also be predictable and easy to understand. Mutable state can be designed to be owned uniquely or shared with a runtime lock, unique state can have one domain-local instance per domain. But what state are we talking about here and how does it work?

`Format.{std,err}_formatter` is *global* state, and I think that having domain-local copies of global state is a predictable pattern that we can explain and reason about. But `Format.formatter_of_out_channel` creates *local* state, and I don't see how one could possibly expect this to be duplicated per-domain. (It's also probably not the right behavior in many cases, typically if a single domain opens and closes a box around the parallel computation.) I would find uniquely-owned or lock-protected mutable state much less surprising here.

(@jberdine : it feels weird to be talking to you about reasoning on concurrent mutable state. Obviously you know much more than I do about this.)

**Comment by jberdine** [comment]
Yes, definitely a can of worms. My personal feeling is that the interaction of clients with `Format` is inherently stateful, and that to send material to a single formatter from concurrent domains will take application-specific logic to determine the granularity of interleaving, how to coordinate indentation, etc. Consider if two domains each open a box, then one performs a flush (closing all open boxes), then the other continues as if in the context of an open box, producing incorrect output.

Because of this sort of issue, I am not sure how useful it would be to have `std_formatter` and friends as lock-protected global state. The current PR is doing something else though: `std_formatter` et al are part of the initial domain's state, and the functions like `printf` that do not take a formatter argument operate over domain-local versions of `std_formatter`. These domain-local formatters will be uniquely-owned, unless the client calls `get_std_formatter` and passes the result to another domain.

(I think that `Stdlib.Queue.Empty` exceptions can be avoided without using DLS by changing `Queue.take` in `advance_left` to `Queue.take_opt`, but there will still be silently dropped output and similar issues.)

So assuming that we can't just remove `Format.printf` and friends, then the design that silently makes domain-local copies of `std_formatter` seems like the way to go.

But there are some equivalences in the current API docs that will no longer hold:
```ocaml
val std_formatter : formatter
(** The standard formatter to write to standard output.

  It is defined as {!formatter_of_out_channel} {!Stdlib.stdout}.
*)
```
It will no longer be true that `std_formatter` is defined as, or even equivalent to, `formatter_of_out_channel Stdlib.stdout`.
```ocaml
val printf : ('a, formatter, unit) format -> 'a
(** Same as [fprintf] above, but output on [std_formatter]. *)
```
This (and other similar cases) will not be true, and will instead satisfy:
```ocaml
val printf : ('a, formatter, unit) format -> 'a
(** Same as [fprintf] above, but output on [get_std_formatter ()]. *)
```

There might be existing code that mixes calls to `Format.printf` with `Format.fprintf std_formatter` and relies on them using the same underlying formatter.

These are not big issues, but they change how one needs to understand the Format API somewhat. In particular, the convenience formatters over standard channels and the convenience functions that do not take a formatter are much more special and involve significant functionality that the code they used to be shorthand for does not have.

**Comment by kayceesrk** [comment]
There is one more surprising behaviour with domain-local formatter state: https://github.com/ocaml-multicore/ocaml-multicore/issues/592, but I suspect this can be fixed. 

I wondered if providing a function `val init_thread_safe_default_fomatters : unit -> unit`, which is an opt-in, which must be called before new domains are created, whose idea is to replace the default formatters with a version that interleaves only at newlines is a possibility. This would be similar to the one @jberdine had implemented in https://github.com/ocaml/ocaml/issues/10453#issuecomment-862709381. This would satisfy my requirement that for sequential code, the performance remains as is. For parallel code, the behaviours would be least surprising.

I can also see the possibility of doing this automatically the first time a new domain is spawned, which might be ok, since this only affects the default formatters (std_formatter, err_formatter, str_formatter).

**Comment by kayceesrk** [comment]
@jberdine I believe that the [updated documentation](https://github.com/ocaml-multicore/ocaml-multicore/pull/586/files#diff-5459bd9130e2794fa37451c8924167ace56b26fa63dc3552563eb24cdbdcbaa1) reflects the current state of https://github.com/ocaml-multicore/ocaml-multicore/pull/586. Let me know if this looks reasonable.

**Comment by kayceesrk** [comment]
> I can also see the possibility of doing this automatically the first time a new domain is spawned, which might be ok, since this only affects the default formatters. 

This is now implemented in https://github.com/ocaml-multicore/ocaml-multicore/pull/586. Thanks @jberdine for the prototype.

**Comment by kayceesrk** [comment]
https://github.com/ocaml-multicore/ocaml-multicore/pull/586 is now merged. In summary, the PR ensures that 

* For sequential programs, the use of pre-defined formatters only incur the additional cost of accessing the formatter from the domain-local state. The access to domain-local state incurs only a few additional instructions. 
* For parallel programs, the pre-defined formatter state is domain-local and only interleave the output when the formatter is flushed. There is no additional work necessary from the user side. The pre-defined formatters are automatically switched to the synchronized one when the first domain is spawned. 
* Since the synchronized formatters are a useful pattern that may come in handy for writing to other channels, two new functions  `make_synchronized_formatter` and `synchronized_formatter_of_out_channel` have been added to Format. 

I shall close this issue for now. Thanks for the comments.
