### ISSUE TITLE
Assert expression must be executed

### ISSUE THREAD

**Issue by mhrde** [ocaml/ocaml#10466]
Hello OCAML team,

on inspection of the code in "lambda/matching.ml" I observed an assert expression, which is important for the code and
must not be ignored by the -noassert switch. The line number is 2521 and the line content is

**2521:   assert (do_store "FAIL" fail = 0);**

The **"do_store "FAIL" fail** expression should be executed outside the "assert" expression to assure, that the **fail** lambda action is stored in the store (with index 0). Otherwise this is not guaranteed. There is no issue if the assert condition is executed. Therefore this glitch can't be detected without -noassert.

Kind regards

Michael Rose

**Comment by dra27** [comment]
This was changed in https://github.com/ocaml/ocaml/commit/fcf3571123e2c914768e34f1bd17e4cbaaa7d212#diff-574a9ed85084e8419a9fdc29c147bd50cf338c63200992a97d330344062fba94L2005 (it was `ignore`'d before).

It's not critical, since the compiler isn't (and shouldn't) be built with `-noassert`, but I agree it's worth the clean-up - would you be able to submit a pull request?
