### ISSUE TITLE
Please document 'Stdlib.raise_notrace'

### ISSUE THREAD

**Issue by mjambon** [ocaml/ocaml#10467]
The [manual says this](https://ocaml.org/api/Stdlib.html) about `raise_notrace`:
> `val raise_notrace : exn -> 'a`
> A faster version `raise` which does not record the backtrace.

We would like to know what to expect when calling `Printexc.get_backtrace ()`. Does it fail with another exception? Does it return a previous trace? Does it do so faster than if it had to reconstruct the correct trace?

**Comment by gasche** [comment]
Do we really want to specify a behavior here? I think that keeping the behavior implementation-defined is a reasonable choice. Currently the emergent behavior is that you observe a "previous" backtrace, but then some alternate libraries made the choice to destroy the previous backtrace in this case, and we may want to change the behavior in the future.

My own mental model is as follows:
- when using `raise` (not notrace), a backtrace is available within the dynamic extent of a `with ... -> <handler>` exception handler; morally it ceases being available when the `<handler>` expression returns
- when trying to extract a backtrace outside this situation, the behavior is not specified

**Comment by jberdine** [comment]
I think that an important aspect of `raise_notrace` is that, since it does not record the backtrace, it can be used to raise and handle exceptions within a handler that goes on to reraise without destroying the backtrace. For instance in `try f x with e -> g e; raise e` if `g` raises an exception with `raise_notrace` and handles it internally, then `raise e` should reraise the original exception with the backtrace coming from the evaluation of `f x`.

One can infer this from the current documentation, but it might be useful for it to be more explicit.

(I appreciate that this specification is incompatible with `Base.Exn.raise_without_backtrace`, but I think that it would globally reduce confusion if it were clearer that `raise_without_backtrace` is not usable as a replacement for `raise_notrace`.)

**Comment by mjambon** [comment]
Hello. Sorry for the long delay.

The documentation for `raise_notrace` is adequate as is indicates what the intent is (a faster version of `raise`). What we need to know is what happens to the `Printexc.get_backtrace ()` function. The documentation redirects us to `print_backtrace` and states:

> val print_backtrace : out_channel -> unit
> Printexc.print_backtrace oc prints an exception backtrace on the output channel oc. The backtrace lists the program locations where the most-recently raised exception was raised and where it was propagated through function calls.
>
> If the call is not inside an exception handler, the returned backtrace is unspecified. If the call is after some exception-catching code (before in the handler, or in a when-guard during the matching of the exception handler), the backtrace may correspond to a later exception than the handled one.

The above is incorrect under various situations:
* recording backtraces was disabled globally when the most-recently raised exception was raised
* the most-recently raised exception was raised with `raise_notrace`
* other conditions I'm not thinking of

I would list all those cases. This would facilitate writing higher-level APIs and how-to guides. For what it's worth, [here's what I wrote](https://github.com/returntocorp/pfff/blob/d636ec733aa9fc5193bdce4b725baf618ed46821/commons/Exception.mli) for our internal `Exception` module which passes exceptions around as a pair (exn, trace).
