### ISSUE TITLE
Fix example in the tutorial

### ISSUE THREAD

**Issue by diegodiasm** [ocaml/ocaml#10494]
The following example in the OCaml Manual excludes 0.0 when computing the square root of a float for no good reason. 
Instead of >, it would make more sense to use >= in this example.

https://github.com/ocaml/ocaml/blob/98a27ddf9d5c2c0e92614b97ff9064660b8e1dde/manual/src/tutorials/coreexamples.etex#L268

**Comment by Octachron** [comment]
I tend to think that both versions are subtly wrong since doing comparison with floating numbers requires to take in account the current approximation error. 
It is true that the `>=` version looks more correct.
At the same time, it feels strange to add the points `0-` and `0+` to the domain when equality is only semi-decidable for real numbers.
Maybe we could use `to_int: number -> int option` as an example to circumvent the issue altogether.

**Comment by stedolan** [comment]
`x >= 0` is precisely the condition under which `sqrt x` is not `NaN`, so it does seem like the right thing to do in this example. (And yes, `float` and `sqrt` are imperfect models of reals and square roots)

**Comment by jteg68** [comment]
But in ocaml the comparasion between floats gives:
-0.0 = 0.0
-0.0 >= 0.0
-0.0 <= 0.0
and 
Float.sqrt(-0.0) results in -0.0 instead of -nan.

The comparasion -0.0 = 0.0 is according to IEEE754 I think, but not Float.sqrt(-0.0) = -0.0

**Comment by xavierleroy** [comment]
> The comparasion -0.0 = 0.0 is according to IEEE754 I think, but not Float.sqrt(-0.0) = -0.0

You're wrong.  IEEE 754-2008, section 5.4.1:
_The operation squareRoot(x) computes √ x. It has a positive sign for all operands ≥ 0, except that squareRoot(−0) shall be −0._

Section 7.2:
_These operations [that signal the invalid operation exception and return a quiet NaN] are [...] squareRoot if the operand is less than zero._

**Comment by xavierleroy** [comment]
I support changing `x > 0.` to  `x >= 0. ` in this example.

**Comment by gasche** [comment]
I fixed this in 7f2069e7d4589f4cbeb616e336ed07f4e7ee8568.
