### ISSUE TITLE
build error on Linux 2.6.32 'O_CLOEXEC' undeclared

### ISSUE THREAD

**Issue by dinojr** [ocaml/ocaml#10501]
I'm trying to build ocaml 4.12.0 on an ARM system (a synology NAS) running Linux 2.6.32. 

Building fails at make world.opt with

```
dup2.c: In function 'unix_dup2':
dup2.c:34: warning: implicit declaration of function 'dup3'
dup2.c:35: error: 'O_CLOEXEC' undeclared (first use in this function)
```
Is there some configure option that would fix this error ?

**Comment by xavierleroy** [comment]
That's a pretty old Linux system: 2.6.32 was released in 2009 and reached end of LTS in 2016.  The C library is probably quite old as well.  However, I'm a bit surprised that the configure script detected the dup3 function.

I would suggest one of the following:
- upgrading your system to a reasonably recent Linux distribution
- installing an old version of OCaml to match your old Linux distribution, e.g. 4.05 or 4.02.3
- try to debug the configuration problem: what happens if you `#undef HAS_DUP3` in runtime/caml/s.h after running configure but before doing make?

**Comment by dra27** [comment]
`configure` only checks whether `dup3` is available when linking, so you could have `HAS_DUP3` and get that warning from the C compiler. Google informs me that `dup3` was added in 2.6.27 but not supported in glibc until 2.9 - it's possible there's disagreement between what's linkable and what's in the headers? What version of glibc do you have?

That said, @xavierleroy is of course correct: upgrade!

**Comment by xavierleroy** [comment]
> it's possible there's disagreement between what's linkable and what's in the headers

I suspect this happens quite often.  It would be safer for configure to check that functions are declared in the appropriate standard headers than to check that they are provided by libc.so for linking.  But that's a topic for a separate report or PR.

**Comment by dinojr** [comment]
Unfortunately, I cannot easily upgrade the kernel. The machine is an old NAS, and I'm reluctant to leave the comfort of using the Synology system to run my own.

I've tried your third suggestion, and the error is now
````
pipe.c: In function 'unix_pipe':
pipe.c:27: warning: implicit declaration of function 'pipe2'
pipe.c:27: error: 'O_CLOEXEC' undeclared (first use in this function)
````

Next I'll try installing an older OCaml

**Comment by dinojr** [comment]
ocaml 4.05 build failed but 4.02.3 passed ! Thanks a lot.

**Comment by XVilka** [comment]
@dinojr you might want to try to build the OCaml statically with the Alpine. Back in time I tried to port Radare2 (then Rizin) to very old Debians, you could be insterested in that work. Due to the GCC being very old on these systems, I tried to compile TinyCC from git first, since it can compile almost anything: https://github.com/XVilka/debian-oldies
Regarding `pipe2` etc, if you really want to build OCaml on such old environment, you will need to do some minimal patching anyway, I am afraid.
