### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by thomasfsteeples** [ocaml/ocaml#10518]
# Preamble

Unicode is arguably the most dominant text encoding in the world. According to [W3Techs](https://w3techs.com/technologies/cross/character_encoding/ranking), 97% of the world's websites are in UTF-8, many editors offer it as the default encoding, and modern (and not so modern) programming languages offer first-class Unicode support. Additionally, [many](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) [have](http://utf8everywhere.org/) spoken about the importance, as well as the benefits, of supporting and using Unicode.

I believe that OCaml should not only support Unicode as a first-citizen, but should also make it the default behaviour for `char`s and `string`s.

# Existing work

Since 4.03, Ocaml has a module for working with Unicode characters, [Uchar](https://ocaml.org/api/Uchar.html), but it is rather limited in functionality. Whilst one can create objects representing Unicode scalar values, they are not inherently _usable_. For example, taking the Bactrian Camel emoji, 🐫, codepoint U+1F42B, we can introduce it into a program by writing (in a utop session),
```
let c = Uchar.of_int 0x1F42B;;
val c : Uchar.t = U+1F42B
```
With this data, we can get its predecessor and successor (in terms of codepoints), convert it back to an `int`, and test if it's a latin1 character. To my knowledge, there is no built-in functionality to print its corresponding glyph (if applicable), or encode it in UTF-8 say. Additionally, we cannot initialise a variable with such a glyph. Running the following yields an error for me,
```
let c : Uchar.t = '🐫';;
Line 1, characters 9-10:
Alert deprecated: ISO-Latin1 characters in identifiers
``` 
Specifically, it seems that the special literal char syntax, `'<char>'`, only allows `char` to be a glyph which corresponds to an (extended?) ASCII character.

We can include such characters in a string, but this yields its own problems:
```
let s = "🐫";; (* works fine *)
val s : string = "🐫"

String.length s;;
- : int = 4  (* Uh-oh *)

String.get s 0;;
- : char = ð (* Oh no *)

String.get s 1;;  (* No output *)

String.get s 2;; (* No output *)

String.get s 3;; 
- : char = « (* Oh no again *)
```

I would define this behaviour as unexpected at best, and dangerous at worst. I would expect the length of 🐫 to be 1, and the length of an extended grapheme cluster, such as a flag, 🇫🇷 , to be 2 (🇫  (regional indicator F) + 🇷 (regional indicator R)). 

Daniel Bünzli has developed an excellent [collection](https://erratique.ch/software) of OCaml libraries which offer a lot of missing functionality, including encoding, segmentation and normalization. However, these build on top of Uchar.t, and don't add what I'd call first-class support to the language.

# Proposal

I believe that the current `char` type should be replaced by the `Uchar.t` type. Moreover, I feel the string type should have `Uchar.t` as the underlying type for its elements, and offer functionality to convert to and from encodings such as UTF-8 (which would also necessitate a `Word8`/`uint8_t` style type). On top of this, I feel a selection of "standard" (whatever that means) string/char algorithms should be implemented for these new types, possibly along with some of encoding, normalisation and segmentation algorithms given in the Unicode standard. 

Whilst this would be a major change for OCaml, I believe the "difficult part" to be a solved problem - the Unicode standard is comprehensive and relatively stable, giving exact details on how Unicode algorithms should be performed. Moreover, first-class Unicode support is a given in many offer modern languages (Python, Go, Rust, Haskell, Swift, to name but a few). Additionally, with tools like Ocsigen and Reason in wide usage, I believe this is a bridge that will need to be crossed sooner rather than later. 

Happy to discuss, and apologies if the above comes across militant at all, I don't mean it (that much)! I'm also an OCaml noob, but would love to help in any way I can.

**Comment by nojb** [comment]
> To my knowledge, there is no built-in functionality to print its corresponding glyph (if applicable), or encode it in UTF-8 say. Additionally, we cannot initialise a variable with such a glyph. Running the following yields an error for me,

> Specifically, it seems that the special literal char syntax, `'<char>'`, only allows `char` to be a glyph which corresponds to an (extended?) ASCII character.

Indeed, and that's because `'<char>'` is the syntax for `char` values which are 1-byte quantities and so cannot be used to represent Unicode codepoints. UTF-8-encoded Unicode scalar values can be specified using the `"\u{XXXXXX}"` syntax, see https://ocaml.org/manual/lex.html. You can also type them inline in an UTF-8 source file, as you observed.

If the Unicode value that you wish to encode is not a constant, you can use the function `Buffer.add_utf_8_uchar` to add its UTF-8 encoding to a `Buffer.t`.

I would suggest to read the discussion in #80, #1091 and #1232 as they may prove useful to learn about some of the design issues around this discussion.

**Comment by Octachron** [comment]
OCaml already support utf-8 encoded unicode string as a first-class citizen. But it also supports `strings` as array of 8-bit chars without making any hypotheses on the human interpretation of these chars. In other words,

```ocaml
String.length s;;
- : int = 4  (* Uh-oh *)
```
 is the right result since the length of the array of chars is `4`. And this length is still useful to know for utf-8 encoded strings. Moreover, neither the number of scalar values nor the number of extended grapheme clusters nor the graphical width of the text contained in a string can be computed in `O(1)`. Thus it is not completely clear if exposing a `Extended_grapheme_cluster.length` is good idea. Similarly, for indexing, this result

```ocaml
s.[0]
- : char = "\240"
```
is the correct result for an array of chars. Moreover an unicode string is neither an array of scalar values nor an array of extended grapheme clusters. Exposing an indexing operator which is in O(n) in the API would probably be a mistake.

Similarly, replacing the char type with the `Uchar.t` type would be a major break of backward compatibility. It would also make it impossible (or harder than needed) to deal with non unicode valid strings (what about non-unicode filenames on Windows for example?). Moreover, it leaves open the question of equality. Equality for texts should not be the equality on array of scalar values since the same extended grapheme clusters can have multiple encodings. This problem extends to pattern matching too: Should the "é" pattern match the decomposed character "é" or not?

It seems better to leave each library or application able to deal with those design choices. And we already have libraries and applications (like Ocsigen) that handle unicode text just fine. In fact, it is not clear how your proposed changes would help them.

I do think that OCaml's support for unicode could be improved by easier to use libraries (since @dbuenzli 's unicode libraries provide very useful but quite low level APIs). Those libraries could potentially propose opt-in length function and indexing operators (or they could choose to not expose those for the reason explained above).
```ocaml
let babylon = "𒆍𒀭𒊏𒆠"
assert Text.Extended_grapheme_cluster.(length babylone  = 4);;
assert Text.Extended_grapheme_cluster.( babylon.!(0) = "𒆍" )
```
However, experience shows that those kinds of libraries are better developed outside of the compiler: like this the library can have shorter development cycles and escapes the stringent backward compatibility constraints of the compiler. If such libraries end up really requiring some compiler support to offer some features, then it would be right time to open a feature wish on this issue tracker. But starting with some half-baked support written by non-unicode expert in the compiler seems more like a recipe for having to support half-wrong APIs for decades.

**Comment by thomasfsteeples** [comment]
I'm not sure I agree with this @Octachron. 

> OCaml already support utf-8 encoded unicode string as a first-class citizen. But it also supports strings as array of 8-bit chars without making any hypotheses on the human interpretation of these chars. In other words,
> ```
> String.length s;;
> - : int = 4  (* Uh-oh *)
> ```
> is the right result since the length of the array of chars is 4. 

In the list of languages I gave above, all of them regard the length of 🐫 to be 1. Whilst yes, the length of it as a UTF-8 encoded sequence of bytes is 4, as a list of characters (nebulous term, here, let's say Unicode scalar values), I feel it should be 1. I also think it's important not to conflate characters and bytes.  As it stands, I feel the OCaml default behaviour violates the principle of least astonishment. 

> And this length is still useful to know for utf-8 encoded strings. 

Agreed, but then I'd argue you want to know the length of a list of bytes, resulting from converting a string into its UTF-8 representation, rather than the length of the string.

> Moreover, neither the number of scalar values nor the number of extended grapheme clusters nor the graphical width of the text contained in a string can be computed in O(1). Thus it is not completely clear if exposing a `Extended_grapheme_cluster.length` is good idea. 

Surely correctness must come before efficiency? Additionally, if codepoints are stored in UTF-32 (as in Python), the number of scalar values can be stored along with the underlying data, and could be accessed in O(1). Swift takes another approach and stores strings internally as UTF-8 - here, codepoint access is O(n). Haskell gives you a choice - strings by default are lists of Unicode code points (therefore, UTF-32), or you can use Data.Text and use UTF-16 encoded strings (due to GHC's OverloadedStrings extension,  the latter "feel" like built-in strings). Depending on the priorities of the OCaml developers, any of these approaches could be taken. 

> Similarly, replacing the char type with the Uchar.t type would be a major break of backward compatibility.

In which case, introduce any changes in the next major version. Or overload the literal syntax for `char`s and `string`s so they can be used to initialise the new types.

>  It would also make it impossible (or harder than needed) to deal with non unicode valid strings (what about non-unicode filenames on Windows for example?).

Do we really want to handle non-Unicode valid strings? Additionally, NTFS does use Unicode filenames - they're just encoded in UTF-16, rather than UTF-8. This is another reason why having Unicode algorithms in OCaml might be A Good Thing™.

> Moreover, it leaves open the question of equality. Equality for texts should not be the equality on array of scalar values since the same extended grapheme clusters can have multiple encodings. This problem extends to pattern matching too: Should the "é" pattern match the decomposed character "é" or not?

Again, these questions are handled by the Unicode standard - [canonical equivalence](https://unicode.org/reports/tr15/) is used to determine if two strings are "effectively" the same. 

> But starting with some half-baked support written by non-unicode expert in the compiler seems more like a recipe for having to support half-wrong APIs for decades.

I would like to think that we could certainly get it beyond half-baked :-)

**Comment by Octachron** [comment]
> In the list of languages I gave above, all of them regard the length of  to be 1.

This is false for Go and Rust where `len(🐪)` and `"🐪".len()` returns `4`. And `🐪` is an easy example  since `🐪` happens to be both a scalar value and an extended grapheme cluster.
A better example is संस्कृतम् where the languages that you cited return


|Language |  Result           |
|--------------|---------------------|
| Go | 27                             |
| Rust | 27                           |
| Python |  9                        |
| Haskell |  9                       |
| Swift |  5                           |



And I personally tend to prefer Swift choice of counting extended grapheme clusters. Like you said, I think it is important to not conflate graphical characters and arbitrary codes.

> As it stands, I feel the OCaml default behaviour violates the principle of least astonishment.

On the contrary, OCaml consider strings as an array of 8-bit integers called chars. This makes the behavior very unsurprising. It is pretending to handle all the complexity of human scripts beyond the back of the developer that violates the principle of least astonishment, because there is no way to escape from the complexity of human scripts. 


> Surely correctness must come before efficiency? 

The result is correct since the `string` is a container and the length returns the size of this container.
Moreover, if a basic operation is inefficient, you have chosen the wrong data structure. 

And there is also the question of what is the point of indexing the extended grapheme clusters of a string? What kind of algorithm requires to update the k-th characters of a text without knowing neither the content nor the context of the extended grapheme clusters? Also it is important to notice that both Python and Haskell do not provide efficient random access to graphical characters (aka extended grapheme clusters). 

Similarly, the length in term of graphical characters is often less useful than expected. For instance, you can try to put my sanskrit and akkadian examples in a terminal. Most terminals will misbehave because they do not compute properly the graphical width of cuneiform or devanagari characters.

>  canonical equivalence is used to determine if two strings are "effectively" the same.

You have left the plural. There are multiple notions of equivalences for unicode strings.

> Do we really want to handle non-Unicode valid strings? Additionally, NTFS does use Unicode filenames 

Yes, we are not dropping support for non-unicode strings. And no, NTFS does not use Unicode filenames: it accepts unpaired surrogates for the sake of backward compatibility.

> I would like to think that we could certainly get it beyond half-baked

I don't know. Honestly, I only know enough about unicode to spot common issues (and play with ancient scripts).

However, the best way to build knowledge and be sure to support unicode in the right way  is to start with an exhaustive and easy-to-use library for human texts. I would be really glad to see such library emerges. And if that library encounters real road-blockers by lack of language support, then it would be the time to extend the language. And without breaking backward compatibility.

Breaking backward compatibility is not something that we do without a very good reason. As far as I can see, you have not proposed any advantages to your changes that could not be achieved by a library. And OCaml doesn't have nor the size nor the momentum to merrily create a python2/python3 split.

**Comment by dra27** [comment]
I agree with @Octachron’s comments, but just to add:

> Yes, we are not dropping support for non-unicode strings. And no, NTFS does not use Unicode filenames: it accepts unpaired surrogates for the sake of backward compatibility.

NTFS Unicode filenames are handled since OCaml 4.06 - they are converted to UTF-8 (same with environment variables and arguments). There is a corner case with the handling of un-paired surrogates which I hope we’ll address some day using [WTF-8](http://simonsapin.github.io/wtf-8/) either directly in the stdlib, or in a way which can be consistently exploited by external libraries (it’s not highest priority at the moment because such filenames tend to exist only to torture standard library implementations!)

**Comment by thomasfsteeples** [comment]
Ok, I'll close the issue, but I'm still not convinced that OCaml handles Unicode in the most _principled_ way imaginable.

**Comment by Octachron** [comment]
Thanks for opening the issue and the discussion. I hope that it will clarify a least a little my current position. 

I don't think that anyone think that OCaml handles Unicode in the most principled way possible.

At the same time, without enough domain knowledge, it seems too easy to get unicode support half-wrong. In particular, I would rather avoid adding a fresh paint of coat on few functions and calling the job done.

And I will reiterate my point: I would really love to have an OCaml library that I could point to and say "That library does the right thing. Yes, even casing for greek or turkish, or computing the width of a text in presence of hieroglyph control characters".
