### ISSUE TITLE
Link time consistency check is incomplete

### ISSUE THREAD

**Issue by lthls** [ocaml/ocaml#10564]
The link time consistency check (that errors when linking object files that were compiled against different versions of the same interface) fails to detect inconsistencies between an object's interface and objects that were linked before it.

To reproduce:
```ocaml
(* foo.mli *)
type t = T

val foo : bool

(* foo.ml *)
type t = T

let foo = Bar.bar2

(* bar.mli *)
val bar : Foo.t

val bar2 : bool

(* bar.ml *)
let bar = Foo.T
let bar2 = true

(* baz.mli *)
val baz : int

(* baz.ml *)
let baz =
  match Bar.bar with
  | T -> 0
```
```shell
$ ocamlc -c foo.mli bar.mli baz.mli bar.ml foo.ml baz.ml
```

Now edit `foo.ml`, `foo.mli` and `baz.ml` to replace them with:
```ocaml
(* foo.mli *)
type t = T of int

val foo : bool

(* foo.ml *)
type t = T of int

let foo = Bar.bar2

(* baz.ml *)
let baz =
  match Bar.bar with
  | T i -> i
```
```shell
$ ocamlc -c foo.mli bar.mli baz.mli foo.ml baz.ml # Note the omission of bar.ml
$ ocamlc -o test bar.cmo foo.cmo baz.cmo
$ ./test
Segmentation fault
```

The same bug exists with `ocamlopt`.

This can be fixed by replacing the use of `Consistbl.set` by `Consistbl.check` in `Bytelink.check_consistency` (and similar in `Asmlink`) but I'm not sure why the distinction was there.

I found this while looking at alternatives for #10563.

**Comment by xavierleroy** [comment]
Re: `Consistbl.set` vs `Consistbl.check`, I seem to remember this was due to an old desire to support multiple bytecode compilation units having the same name, e.g. 
```
   ocamlc 1/A.cmo 1/B.cmo 2/A.cmo 2/C.cmo
```
provided 1/A is only used by 1/B and 2/A by 2/C.

However, this is known to cause issues (see #5461) and warning 31 was introduced (https://github.com/ocaml/ocaml/commit/869feeb00704e0640c45ffe6aee6cc13e4077f79) to warn and by default reject this "multiple linking".

@gasche recently suggested (https://github.com/ocaml/ocaml/issues/5461#issuecomment-826693252) to turn warning 31 into a hard error.  In this case, I would guess that `Consistbl.check` should be used instead of `Consistbl.add` in all cases.

There's a risk that the error message will not be as good as the one for warning 31.  Maybe some of the checking logic needs refactoring.
