### ISSUE TITLE
Difference with @inline always between ocamlc/ocamlopt/ocamlopt with flambda

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#10686]
The following code which try to force inlining works with 
 ocamlc with or without flambda 
 ocamlopt with flambda 
but emit a warning and do not perform inlining with
 ocamlopt without flambda

Here is the warning
52 |   module F = Make [@inlined always] (FloatMin)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 55 [inlining-impossible]: Cannot inline: Function information unavailable

Step to reproduce : ocamlc/ocamopt FieldGen.ml

Here is the file FieldGen.ml
(** {1: General code for fields implementation} *)

(** Minimal signature for a field *)
module type SMin = sig
  type t
  val zero : t
  val one : t
  val ( +. ) : t -> t -> t
  val ( *. ) : t -> t -> t
  val ( -. ) : t -> t -> t
  val ( /. ) : t -> t -> t
  val ( ~-. ) : t -> t
end

(** Complete field signature, with a few extra functions *)
module type S = sig
  include SMin

  (** power function, in O(ln n) *)
  val pow : t -> int -> t
end

module Make(R:SMin) = struct
  include R

  let pow x n =
    let (x,n) = if n < 0 then (one /. x, -n) else (x,n) in
    let rec fn n =
      if n <= 0 then one
      else if n = 1 then x
      else
        let q = fn (n lsr 1) in
        let q2 = q *. q in
        if n land 0x1 = 0 then q2 else q2 *. x
    in
    fn n
end

module FloatMin =
  struct
    type t = float
    let zero = 0.       [@@inlined always]
    let one = 1.        [@@inlined always]
    let ( +. ) = ( +. ) [@@inlined always]
    let ( *. ) = ( *. ) [@@inlined always]
    let ( -. ) = ( -. ) [@@inlined always]
    let ( /. ) = ( /. ) [@@inlined always]
    let ( ~-.) = ( ~-.) [@@inlined always]
  end

module Float = struct
  module F = Make [@inlined always] (FloatMin)
  include F
end

**Comment by lthls** [comment]
There are quite a few misunderstandings here.
- `ocamlc` does not perform any inlining. For this reason, it never emits any inlining-related warnings either.
- the `[@inlined]` attribute is only useful on function applications (it needs to appear on the function being applied, not the whole application). Everywhere else, the attribute gets discarded with a warning. The `[@@inlined]` attribute doesn't make any sense, so it always gets discarded without warning.
- the attribute that you put on a function to ensure it gets inlined later is the `[@@inline]` attribute. It needs to be attached to a let-binding defining a syntactic function (i.e. `let f x = foo [@@inline always]`). You can also use the syntactic sugar `let[@inline always] f x = foo`. But again, the attribute gets discarded if it can't be attached to a function definition; if you define `let[@inline always] f = g` then the attribute disappears because `f` is not a syntactic function (but you get a warning).

Finally, the reason why `ocamlopt` without Flambda does not inline your functor application is that the inlining algorithm in Closure (the non-Flambda mode) never inlines functions whose bodies contain function definitions. Your `Make` functor contains the definition of a `pow` function, so it won't be inlined by Closure. Flambda doesn't have this restriction.
If you want a functor (or a regular function that contains functions) to be always inlined with Flambda but not produce a warning with Closure, you can use `[@inlined hint]`. It is interpreted as `[@inline always]` by Flambda, but only as "inline if you can" by Closure.

**Comment by craff** [comment]
On 21-10-09 02:54:33, Vincent Laviron wrote:
> There are quite a few misunderstandings here.
>
>   • ocamlc does not perform any inlining. For this reason, it never emits any
>     inlining-related warnings either.
>   • the ***@***.*** attribute is only useful on function applications (it needs
>     to appear on the function being applied, not the whole application).
>     Everywhere else, the attribute gets discarded with a warning. The
>     [@@inlined] attribute doesn't make any sense, so it always gets discarded
>     without warning.
>   • the attribute that you put on a function to ensure it gets inlined later is
>     the [@@inline] attribute. It needs to be attached to a let-binding defining
>     a syntactic function (i.e. let f x = foo [@@inline always]). You can also
>     use the syntactic sugar ***@***.*** always] f x = foo. But again, the
>     attribute gets discarded if it can't be attached to a function definition;
>     if you define ***@***.*** always] f = g then the attribute disappears
>     because f is not a syntactic function (but you get a warning).

Thanks for the precisions! Should not any discarding hint produce a warning ?
Otherwise it is hard to know it you are obtaining what you want ?

> Finally, the reason why ocamlopt without Flambda does not inline your functor
> application is that the inlining algorithm in Closure (the non-Flambda mode)
> never inlines functions whose bodies contain function definitions. Your Make
> functor contains the definition of a pow function, so it won't be inlined by
> Closure. Flambda doesn't have this restriction.

Then, the message is misleading: "not enough information" should be
"do not inline function not containing function" ?

> If you want a functor (or a regular function that contains functions) to be
> always inlined with Flambda but not produce a warning with Closure, you can use
> ***@***.*** hint]. It is interpreted as ***@***.*** always] by Flambda, but only as
> "inline if you can" by Closure.

Done, thanks.

**Comment by lthls** [comment]
> Thanks for the precisions! Should not any discarding hint produce a warning ? Otherwise it is hard to know it you are obtaining what you want ?

There is some amount of code in the compiler to detect common cases. In particular if you use the right attribute at the wrong place you will likely get a warning. But typos in the attribute name will cause the attribute to be ignored silently, and using the wrong number of `@` will also often drop attributes silently.


> Then, the message is misleading: "not enough information" should be "do not inline function not containing function" ?

If a function cannot be inlined by Closure, then it is known at the point where the function is defined, and no inlining information is generated. At the call site (where the `[@inlined always]` attribute appears), it is then impossible to know whether the absence of inlining information is because the function contains functions, or was too big, or is recursive, or something else.

**Comment by craff** [comment]
On 21-10-09 06:05:51, Vincent Laviron wrote:
>     Thanks for the precisions! Should not any discarding hint produce a warning
>     ? Otherwise it is hard to know it you are obtaining what you want ?
>
> There is some amount of code in the compiler to detect common cases. In
> particular if you use the right attribute at the wrong place you will likely
> get a warning. But typos in the attribute name will cause the attribute to be
> ignored silently, and using the wrong number of @ will also often drop
> attributes silently.
>
>     Then, the message is misleading: "not enough information" should be "do not
>     inline function not containing function" ?
>
> If a function cannot be inlined by Closure, then it is known at the point where
> the function is defined, and no inlining information is generated. At the call
> site (where the ***@***.*** always] attribute appears), it is then impossible to
> know whether the absence of inlining information is because the function
> contains functions, or was too big, or is recursive, or something else.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. *
>

Thanks for the help. In fact, I was mainly confused by dune that disable some
warnings even when I am very clear that I do not want to:

(env
  (dev     (flags -w +a-70-42-44-45-4 -warn-error +a)
           (ocamlopt_flags -w +a-70-42-44-45-4 -warn-error +a
                           -inline 50000 -O3))
  (release (flags -w +a-70-42-44-45-4 -warn-error +a)
           (ocamlopt_flags -w +a-70-42-44-45-4 -warn-error +a
                           -inline 50000 -O3)))

It is actually strange, because with the same flags I also get significative
speed differences ...  I am invertigating my problem with dune, but you may
close the issue.

Cheers,
Christophe

**Comment by lthls** [comment]
I you have additional questions, you can also ask them on the forum at https://discuss.ocaml.org/
