### ISSUE TITLE
`stdlib`'s  `make depend` needs gnused

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#10708]
The `\u` directive [here](https://github.com/ocaml/ocaml/blob/f44236171d937564571eb145fa13ef422ed8f30a/stdlib/Makefile#L269)  is not recognized by macOS's sed. 

Work around: 

```
brew install gnu-sed
cd stdlib
gsed -i 's/sed -E/gsed -E/g' Makefile
make depend
```

**Comment by dra27** [comment]
Indeed - the idea is that it only affects developers (because the `.depend` files are committed), but it should at the very least be documented and there ought to be better support for switching (unfortunately, `gsed` is also not a standardised alias for installations of GNU sed!). The gold-plated solution would be to have `configure` detect whether `\u` works and cause the `make depend` target to fail with a proper error message (as Windows did/does)

**Comment by dbuenzli** [comment]
> but it should at the very least be documented

I don't think it should be documented, it should fail. 

It's quite confusing as it will happily generate you a broken `.depend` file which leaves you head scratching and loosing your time figuring out what is going on.
