### ISSUE TITLE
Consider providing a mutual exclusion primitive in the Stdlib for 4.14

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#10792]
As per [discussion](https://github.com/ocaml-multicore/ocaml-multicore/issues/750) it seems that as a first step `Lazy.t` will not be thread-safe in multicore. 

A usage pattern for `Lazy.t` is for libraries to trigger initialisation bits on first use. [Here's](https://github.com/dbuenzli/qrc/blob/e745481e504b16624f8b204e5c3a8cf7af093040/src/qrc.ml#L347) an example. Not a very good one, this particular one can be worked around with an `Atomic.t`, at the cost of maybe computing the value more than once. Things are worse if your lazy value performs effects or calls a C library's `init` function.

The problem is that currently `Mutex.t` lives in the `threads` library and not in the `Stdlib`. Some libraries may not afford that dependency (the example above is a good one for that, you may want to have your QR encoder in `js_of_ocaml`). 

Not sure we really need the full `Mutex.t` module a simple:
```ocaml 
 Fun.synchronized : (unit -> 'a) -> (unit -> 'a)
```
 function could do.

**Comment by nojb** [comment]
FYI (not sure if this has been mentioned publicly yet) `Mutex`, `Condition` and `Semaphore` will live in the `Stdlib` in 5.0.

**Comment by dbuenzli** [comment]
At least for `Mutex` it now [has](https://github.com/ocaml-multicore/ocaml-multicore/issues/750#issuecomment-979454622). The problem is rather how do we ensure our libs are multicore-safe on day one while keeping compatibility with (at least the last) stock OCaml.

**Comment by nojb** [comment]
> At least for `Mutex` it now [has](https://github.com/ocaml-multicore/ocaml-multicore/issues/750#issuecomment-979454622).

Right, sorry I had missed the discussion.

**Comment by Octachron** [comment]
Summarizing the maintainer discussion on the subject, it seems better to not anticipate any evolution in the OCaml 5 branch in OCaml 4.14 .

Libraries can be made thread-safe by linking the thread library. Without such precaution, libraries are already thread-unsafe in OCaml 4. Otherwise, it will fall upon the shoulder of library users to implement a thread-safe access pattern.

If we make progress on a simpler to use synchronization API for libraries in OCaml 5, we will still be able to either distribute a compatibility library for OCaml 4, or if the new API ought to be part of the stdlib, we could release a new version 4.15 for the sake of API synchronisation.

**Comment by dbuenzli** [comment]
> Without such precaution, libraries are already thread-unsafe in OCaml 4.

Indeed. 

Good rationale, thanks. Let's close this.

**Comment by xavierleroy** [comment]
Right.  In other words, the best way we know (at this point) to make your libraries safe w.r.t. multiple execution domains in OCaml 5 is to make them safe w.r.t. multiple threads in OCaml 4.  In particular, the Mutex / Condition / Semaphore abstractions work equally well for domains and for threads.
