### ISSUE TITLE
improved simplification for floating point

### ISSUE THREAD

**Issue by markghayden** [ocaml/ocaml#10816]
Ocamlopt does not appear to simplify the identity for floating point addition or multiplication:

`x +. 0.0`
`x -. 0.0`
`x *. 1.0`
`x /. 1.0`

I believe these can all be safely simplified to 'x', even with possibly abnormal floating point values.

We find these cases occur when inlining functions and our software would benefit if these simplifications occurred.

Perhaps there are other useful examples as well, though care is required because of possible abnormal values.

**Comment by xavierleroy** [comment]
> I believe these can all be safely simplified to 'x', even with possibly abnormal floating point values.

There's always a surprise with FP: `-0.0 +. 0.0` is `0.0`, not `-0.0`.

However, `x +. -0.0` is `x`, indeed, and the other 3 simplifications are valid too, AFAIK.

For reference, two other FP optimizations that CompCert performs and are proved sound:
```
  x *. 2.0  ==  x +. x            (saves loading an FP constant)
  x /. 2^N  ==  x *. 2^{-N}       (for appropriate values of N)
```

**Comment by sebfuric** [comment]
Alas, x +. -0.0 is not always x too :

Printf.printf "%LX" Int64.(bits_of_float nan);;
7FF0000000000001- : unit = ()
Printf.printf "%LX" Int64.(bits_of_float (nan +. -0.0));;
7FF8000000000001- : unit = ()

The same remark applies for the other mentioned cases, except the two proved ones (which work because they still perform an operation which triggers the invalid argument exception and leaves a qNaN as result).

**Comment by 4y8** [comment]
Yes, I saw that in the paper where the two last one are proved. I will remove it from the PR.

**Comment by gasche** [comment]
I propose to close this issue in favor of the discussion in the PR #10910. If for some reason we give up on the PR *but* decide that we are interested in the change anyway (which I think is unlikely) we could reopen here.
