### ISSUE TITLE
Unbound module Stdlib when trying to compile with -nostdlib flag, even on empty file

### ISSUE THREAD

**Issue by aaron-jack-manning** [ocaml/ocaml#10821]
I am in the process of implementing my own standard library for OCaml, that is better suited to my needs, and rather trying to shadow existing definitions I wanted to compile without the existing standard library. However when I run the following:

```
ocamlopt -c -nostdlib main.ml
```

on a completely empty file `main.ml`, I get the error:

```
File "command line", line 1:
Error: Unbound module Stdlib
```

I am using an empty file to verify that I'm not calling any standard library functions. What is this `command line` file and how can I resolve this?

**Comment by nojb** [comment]
The flag `-nostdlib` means that the standard library directory will not be added to the load path of the compiler. However, the compiler will still try to open the module `Stdlib` by default, but it won't be able to find it. In order to tell the compiler not to open `Stdlib` you need to pass `-nopervasives` on the command line.

I would encourage to ask these kinds of general usage questions on https://discuss.ocaml.org where your question will get more visibility and better benefit the community.

**Comment by gasche** [comment]
(I'm marking this issue "closed"  given that the compiler works as intended, but please feel free to ask for further clarifications.)

**Comment by aaron-jack-manning** [comment]
Thank you for the help and link to the forum. Happy for this to be marked as closed.
