### ISSUE TITLE
`let exception` is not documented at the right place

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#10847]
`let exception E in …` was introduced in 4.04, according to the changelog, but it's listed in [the core expression chapter](https://ocaml.org/manual/expr.html) rather than [the language extensions](https://ocaml.org/manual/extn.html) as I believe it should. It also doesn't indicate a minimum required version.

I can open a documentation PR to change that if needed.

**Comment by Octachron** [comment]
I am not sure I follow why local exceptions ought to be in the extension section? The semantics of local exceptions is not expected to be modified, or known to be partially non-optimal (contrarily to recursive modules for instance. 

Note also that they were moved to the tutorial and core language chapter in #1831.

**Comment by gasche** [comment]
Yes, we moved some "language extensions" parts to the main manual, but in some cases we kept using explicit "since OCaml ..." warnings, for example "Introduced in OCaml 3.12" right below. The part that describes "let exception" could be a named subsection with such "since" information.

**Comment by c-cube** [comment]
@Octachron is it the case that all features described in "extensions" are unstable or non-optimal? I have a hard time imagining  inline records going away, for example. The divide seems a bit arbitrary. If  I'm looking for a particular feature, now, I don't know which section to look in…

**Comment by Octachron** [comment]
The divide is a bit arbitrary.
But if you see any extension that is clearly stable, I will gladly move it to the main part of the manual. 
In term of discoverability, this is the reason why there are forward links to extensions in the description of the core language.

**Comment by gasche** [comment]
The reasoning to move some content into the main manual was that, on the contrary, having recent features parked in a bag full of unrelated language features made them harder to find for newcomers that would go through the reference manual. (If you want to understand, say, "OCaml patterns", it's natural to look for that section rather than the "Language extensions" section.)

You happen to be of the right OCaml-age that there was a neat split "language features added after I learned OCaml" that would rather precisely let you guess what feature is documented where. But a majority of OCaml users learned the language in the last 5 years, to them already the split made less sense, and we hope to have many more users in the future :-)

But then @Octachron started moving "language extensions" into the main manual piece-by-piece, starting with the least objectionable ones, and some "language extensions" features remain in the "extensions" section, and may stay there for a while if we don't feel completely happy about them.

**Comment by c-cube** [comment]
That makes sense, thank you. For me the extensions were always sort of "what came after a pure-ish ML core with objects", i.e stuff added after 3.11 when I started using the language :innocent: .

If we look at the current list of extension:

1. Recursive definitions of values
2. Recursive modules
3. Private types
4. Locally abstract types
5. First-class modules
6. Recovering the type of a module
7. Substituting inside a signature
8. Type-level module aliases
9. Overriding in open statements
10. Generalized algebraic datatypes
11. Syntax for Bigarray access
12. Attributes
13. Extension nodes
14. Extensible variant types
15. Generative functors
16. Extension-only syntax
17. Inline records
18. Documentation comments
19. Extended indexing operators
20. Empty variant types
21. Alerts
22. Generalized open statements
23. Binding operators

For me (as a mere user), at least these look good and stable
enough to be part of the core language manual:

- 3 Private types
- 8 Type-level module aliases
- 17 Inline records
- 18 Documentation comments

**Comment by Octachron** [comment]
For module aliases, the finer details of their semantics are not yet completely clear, at least in the context of functors and modular explicits, see #10673 and friends.

**Comment by gasche** [comment]
Relatedly, I would not be surprised to see middle-term changes to the handling of inline records (if we manage to land some more work on record unboxing), in particular we may start accepting more programs, but I suppose that the syntax and programs that are currently supported will remain supported forever.

I agree that private types and documentation comments are unlikely to go away. (But the current documentation of documentation comments relies on attributes, which I guess would also need to be moved to the core language. Should attributes and extension points be part of the "main OCaml language"?)
