### ISSUE TITLE
void external functions can return invalid data and trigger crashes

### ISSUE THREAD

**Issue by markghayden** [ocaml/ocaml#10854]
The presence of CAMLreturn0 indicates external C functions may be declared with 'void' return type.  Presumably these should functions declared as externals evaluating to unit.  However, tests show that unless 'Val_unit' is explicitly returned, the ML code may be able to detect that the returned value is not actually unit (0 integer).

This seems to happen with and without use of '@@noalloc' declarations.

See attached zip file for test code, sample output.

It would be helpful if the Ocaml documentation gave explicit guidance on use of void external C functions with no return value.

A test case is provided showing how we can generate crashes by using the unit return value from the external function.

The example is a little contrived.  However, it seems there could be situations where normal code might make use of the returned value and trigger the crashes.

Probably Ocamlopt compiler should change calls to external C functions returning unit, so that the actual C return value is ignored and a Val_unit is inserted (if the value is used by caller).

The testing was done using Ocaml 4.13.0 on MacOS 12.1 on X86 based Macbook.

I hope this helpful!

[test.zip](https://github.com/ocaml/ocaml/files/7825428/test.zip)

**Comment by dra27** [comment]
The manual might want clarifying (although I think it's OK here), but I'm afraid that the error begins in your first sentence 🙂

The first paragraph of _Implementing primitives_ in the _Interfacing C with OCaml_ chapter of the manual has

> User primitives with arity _n_ ≤ 5 are implemented by C functions that take n arguments of type value, and **return a result of type value**.

So a C function intended for use with `external` which doesn't return type `value` is not valid and `CAMLreturn0`/`CAMLreturnT` (unless using the slightly pointless `CAMLreturnT(foo, value)` form) shouldn't be used.

The `CAMLparam`, `CAMLlocal` and `CAMLreturn*` macros are part of the GC interface. `CAMLreturn0` and `CAMLreturnT` are used for C functions which return a type other than `value` but which also allocate (and so need GC root registration) and which will be called _by other C functions_.

As an aside, if you're writing a function to be declared in OCaml with `@@noalloc`, you shouldn't be using `CAMLparam`, because the point of a `@@noalloc` function is that you know _absolutely_ that the GC won't be called during its execution and so you know nothing will move (you can see this in lots of the float functions in `runtime/float.c` in the runtime's sources)

**Comment by markghayden** [comment]
Thanks for the clarification.  I had misunderstood the CAMLreturn0 as being suitable for use with functions returning unit value.  I see now that CAMLreturn0 should only be used for C functions not called from ML.  It might be helpful to edit the documentation to clarify this point.

This situation that motivated this was an attempt to make direct calls from ML to OpenGL C functions (returning void), as a minor optimization.  I see now that this is not possible.  It might be nice if unit type were included as one of the types that can be declared @unboxed.

**Comment by dra27** [comment]
Was the motivation here simplicity of bindings, or performance? For simplicity, might [ocaml-ctypes](https://github.com/ocamllabs/ocaml-ctypes) be appropriate - if you're in a situation where you'd like to call a C function directly, then ctypes should be perfect (it's perfect in lots of - if not all - other situations, too!).

An "unboxed" `unit` value is a contradiction, at least in terms of what the `unboxed` attribute does at the moment. `unit` values are already unboxed (being represented by the OCaml integer `0`) - the issue is that a `void` is the "absence" of a value where a `unit` value is the sole actual value of type `unit`.

**Comment by markghayden** [comment]
Thanks for the additional comments.

I understand the use of "unboxed" for unit types is a misuse of terminology.  The idea is was to trigger the compiler to ensure that any value returned from the C code is discarded, including garbage that might be returned from a void function.  I guess the compiler could do this as a matter-of-course for functions returning 'unit', without requiring an inappropriate/contradictory '[@unboxed]' attribute.

For our case, we're want performance not simplicity.  I've looked at things some more and it seems a method to handle external C functions that return void is to declare the function as returning (nativeint [@unboxed]).  If the calling ML code does not use the returned value, the compiler appears to simply discard the garbage in the return register or on the stack.  In the worst case, the value would be boxed, but this does not appear to happen if the value is unused.  Does this match your understanding as a correct use of (nativeint [@unboxed])?
