### ISSUE TITLE
AFL in OCaml 5.00

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#10864]
On a Linux x86-64 machine with AFL installed, the test testsuite/tests/afl-instrumentation consistently fails.
```
$ afl-showmap -o output-1 -- ./test 1 1
afl-showmap 2.52b by <lcamtuf@google.com>
[*] Executing './test'...

-- Program output begins --
Fatal error: Not enough heap memory to start up
-- Program output ends --

+++ Program killed by signal 6 +++

[-] PROGRAM ABORT : No instrumentation detected
         Location : main(), afl-showmap.c:773
```

This has been discussed previously in the ocaml-multicore project, e.g. https://github.com/ocaml-multicore/ocaml-multicore/issues/611 and https://github.com/ocaml-multicore/ocaml-multicore/pull/731 and perhaps https://github.com/ocaml-multicore/ocaml-multicore/issues/733 .  Still, it looks like more work is needed to bring AFL support back.

**Comment by xavierleroy** [comment]
Configuration details: 128G RAM, Ubuntu 18.04 LTS, afl packages at version 2.52b-2.

**Comment by kayceesrk** [comment]
The most recent update on this issue is https://github.com/ocaml-multicore/ocaml-multicore/issues/795. Compared to https://github.com/ocaml-multicore/ocaml-multicore/issues/733, this proposal is much simpler as it does not propose to change the layout of the minor heap. I have confirmed that with https://github.com/ocaml-multicore/ocaml-multicore/issues/795 both AFL and Valgrind works.

**Comment by dra27** [comment]
On my machine yesterday, I wasn’t getting the startup failure, but afltest.ml was just getting to print the first status line and then terminating (then I went back to looking at mingw, rather than digging further!)

**Comment by avsm** [comment]
I notice the same startup error when running under Valgrind/FreeBSD/amd64.

**Comment by xavierleroy** [comment]
Do we expect AFL to work in 5.00 (the MVP)?  or should we skip AFL configuration for the time being, the way we're about to skip flambda configuration? (#10871) ?

**Comment by kayceesrk** [comment]
It may be best to skip AFL configuration for now and come back later.

I believe there isn't much work to do to get AFL working if we go with small defaults for `Max_domains` and `Minor_heap_max` for AFL. But it is not clear to me what will happen when we have multiple domains running. Does it only affect stability? CC @jmid who had earlier looked at AFL on multicore.

**Comment by gasche** [comment]
It would at least be nice to offer AFL for sequential programs under 5.00; AFL is commonly used to run unit tests, and it sounds plausible to have sequential unit tests even in programs/libraries that are also meant to be used concurrently.

**Comment by jmid** [comment]
I believe [#731](https://github.com/ocaml-multicore/ocaml-multicore/pull/731) did get AFL running sequential programs under 5.00 (...at least for me). 
- It requires a suitable `-m` option to `afl-showmap` and `afl-fuzz` as described in [my comment here](https://github.com/ocaml-multicore/ocaml-multicore/pull/732#issuecomment-963083828)
- Another option is setting a suitable `OCAMLRUNPARAM` based on  [#795](https://github.com/ocaml-multicore/ocaml-multicore#795) as @kayceesrk mentioned above

Reenabling the tests and updating these test runner lines:
https://github.com/ocaml/ocaml/blob/1546e1f86f87485637719c86d92f32df9292997f/testsuite/tests/afl-instrumentation/afltest.run#L14-L15
to either `afl-showmap -m none -q ...` or `afl-showmap -m 513G -q ...` makes the afl-instrumentation tests pass
on my machine (8GB RAM, Linux 5.4.0-92-generic, afl-fuzz 2.52b).
This is because `afl-fuzz` and `afl-showmap` run a tested program [under a virtual memory budget with `setrlimit`](https://github.com/google/AFL/blob/61037103ae3722c8060ff7082994836a794f978e/afl-fuzz.c#L2034-L2040).



I'll be happy to submit a PR with this change! We can also wait until a PR for [#795](https://github.com/ocaml-multicore/ocaml-multicore#795) is in. Either way we should also update the manual to clearly document this.

There are (at least) two things remaining as I see it:
1. As illustrated by the current thread of comments, a better error message from `afl-fuzz` could be helpful to OCaml 5.00 users.
   It is tricky however when `afl-fuzz` runs the tested program with stdout and stderr silenced.
   Ideas for workarounds to this issue are welcome! 

2. In terms of multicore, AFL's coverage-guidance works best with deterministic programs AFAIU.
   As such, it may not be a good idea to support AFL on multi-domain programs (for a start at least, as @gasche suggests).
   ~~If so, it might be helpful to signal an error to the user, e.g., on the first `Domain.spawn`.~~
   ~~I can create a PR if people agree  :)~~
  Unless we figure out a workaround for 1. it will be hard to communicate a multi-domain error message when running under `afl-fuzz` though... 😅 Perhaps stopping early may still be preferable?
