### ISSUE TITLE
Flambda + Multicore

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10878]
Now that Multicore has been merged, building with Flambda enabled raises some errors, for example:

```
File "otherlibs/dynlink/otherlibs/dynlink/dynlink_common.ml", lines 129-130, characters 10-53:
Error (warning 59 [flambda-assignment-to-non-mutable-value]): A potential assignment to a non-mutable value was detected 
in this source file.  Such assignments may generate incorrect code 
when using Flambda.
```

We should investigate how to make the `trunk` branch work with Flambda again.

**Comment by lthls** [comment]
Regarding this particular error: the code generated in `Matching.inline_lazy_force_switch` used to be (in pseudo-code):
```
switch arg {
  Block Forward_tag -> arg[0]
  Block Lazy_tag -> CamlinternalLazy.force_lazy_block arg
  _ -> arg
}
```
However, the new code looks like:
```
switch Obj.get_tag arg {
  Const Forward_tag -> arg[0]
  Const (Lazy_tag | Forcing_tag) -> CamlinternalLazy.force_lazy_block arg
  _ -> arg
}
```
When compiling `lazy "String literal"`, in the first version Flambda knows that a string doesn't have tag `Forward_tag` or `Lazy_tag` and so the corresponding branches are deleted. In the second version however, `Obj.get_tag` is an unknown function so Flambda doesn't know what its result would be, and all the branches are kept.
The forward branch should be safe (it's a mutable read on an immutable structure, but I think Flambda will not complain), but the call to `CamlinternalLazy.force_lazy_block` can be inlined and eventually contain the code of `CamlinternalLazy.do_force_block`, which contains assignments to the value being matched. That is what Flambda is complaining about.

There are multiple possible solutions to this issue:
1. Remove warning 59. This sounds overkill, but then the warning is a bit complex to explain to users anyway.
2. Compile Dynlink without this warning. This is not good, as the same issue will appear in code elsewhere.
3. Restore the switch on blocks directly. I'm not a big fan of this, as switches on non-standard blocks cause trouble with Flambda 2, but Flambda 1 handles it correctly. Of course, I assume that the multicore team had a reason for changing the code here, so that may not work at all.
4. Patch `camlinternalLazy.ml` with annotations to prevent the optimiser from looking too close at this code. I've got a patch that adds a `Sys.opaque_identity` call in `do_force_block`, `[@@inline never]` annotations would work too.

I plan to submit a PR implementing solution 4, but would welcome comments from the multicore developers on solution 3 (why the change to use `caml_obj_tag` instead of a switch).

**Comment by xavierleroy** [comment]
> switch Obj.get_tag arg

I assume `Obj.get_tag` is `Obj.tag`, i.e. a call to the C primitive `caml_obj_tag` ?  If so, this is not only a problem for Flambda, but also a significant performance regression, as `caml_obj_tag` is much more expensive than just loading the tag byte from the block header.

**Comment by lthls** [comment]
Yes, sorry about the misleading name, this is a call to the C function `caml_obj_tag`.

**Comment by lthls** [comment]
Once this issue is fixed, the whole tree compiles in Flambda mode, but there are still 4 failing tests (at least with my configuration) that need to be investigated and fixed:
```
List of failed tests:
    tests/backtrace/'backtrace_dynlink.ml' with 1.1.1.3.1.1 (check-program-output) 
    tests/basic-modules/'anonymous.ml' with 2.1.2.1 (check-ocamlc.byte-output) 
    tests/backtrace/'backtrace_effects_nested.ml' with 1 (native) 
    tests/weak-ephe-final/'finaliser2.ml' with 1 (native) 
```

**Comment by lthls** [comment]
Preliminary investigation results:
- `basic-modules/anonymous.ml`: missing promotion (trivial fix)
- `backtrace/backtrace_effects_nested.ml`: different backtrace with and without flambda (due to inlining). Needs to be either disabled with flambda or have multiple reference outputs
- `backtrace/backtrace_dynlink.ml`: same as above
- `weak-ephe-final/finaliser2.ml`: the finalisers in the definition of `test2` are not run, and it is expected. Need to check with the author what the intent was (@kayceesrk ?), and fix the test accordingly.

So, nothing particularly worrying. Once we've settled on the best way to fix the lazy matching issue, I'll make a PR including the fixes to the testsuite.

**Comment by chambart** [comment]
> > switch Obj.get_tag arg
> 
> I assume `Obj.get_tag` is `Obj.tag`, i.e. a call to the C primitive `caml_obj_tag` ? If so, this is not only a problem for Flambda, but also a significant performance regression, as `caml_obj_tag` is much more expensive than just loading the tag byte from the block header.

Yes, but there is probably no good way around that. `caml_obj_tag` now uses a barrier (and a comment specify that this is related to forward tag). I don't completely understand how it is supposed to work, but this seems important for that specific case.

**Comment by gasche** [comment]
> > switch Obj.get_tag arg
> 
> I assume `Obj.get_tag` is `Obj.tag`, i.e. a call to the C primitive `caml_obj_tag` ? If so, this is not only a problem for Flambda, but also a significant performance regression, as `caml_obj_tag` is much more expensive than just loading the tag byte from the block header.

For reference, we discussed this in https://github.com/ocaml-multicore/ocaml-multicore/pull/760#discussion_r759281321 (that was: before the merge, right before the synchronous-review phase, and we were scrambling to find a solution that was *correct* first, even if it is a performance regression.)

**Comment by gasche** [comment]
On the current issue with flambda: as I understand it, warning 59 (flambda-assignment-to-non-mutable-value) corresponds to a limitation in Flambda's mutability inference, which lacks expressivity and cannot handle certain OCaml programs. (This lazy business is low-level Lambda code, but there are perfectly valid programs using GADTs and no unsafe features that rais this warning.) It's not the first time we had to jump through hoops to deal with precisely this issue with camlinternalLazy: see #9998.

Maybe one option would be to disable the warning in precisely these lazy-related functions (instead of disabling it globally?). 

Another option would be to go ahead and replace this `caml_obj_tag` with a compiler primitive that flambda knows about, so that it can perform complex reasoning about its complex behavior. (If you call `tag` on a value that is known to have tag `Lazy` or `Blocking`, the result may be anything, being of type `Forward` can change on allocation effects, and any other tag will remain unchanged in the future and returned exactly by `tag`.)

On the lazy code itself: we need an atomic read here because the tag of OCaml blocks can be mutated from other threads, in particular in the case of an (incorrectly) shared `Lazy.t` value. Otherwise, if I understand correctly, you may see a value being forced by another thread, that already has tag Forward_tag but whose payload is still the thunk rather than the final value, and the Forward case of the switch is unsound.

We could use something more efficient than `caml_obj_tag`, in particular we know at this point that the value is a block. But I'm not aware of something else that exists, and guarantees that the load synchronizes with the atomic write of the Forward_tag block.

**Comment by kayceesrk** [comment]
> We could use something more efficient than caml_obj_tag, in particular we know at this point that the value is a block. But I'm not aware of something else that exists, and guarantees that the load synchronizes with the atomic write of the Forward_tag block.

It was suggested in https://github.com/ocaml-multicore/ocaml-multicore/pull/760#discussion_r759347315 not to have different C functions that only differ by the memory model used. Perhaps having a primitive that atomically reads the tag in addition to having `caml_obj_tag`which will non-atomically read the tag is less bad?

**Comment by kayceesrk** [comment]
> weak-ephe-final/finaliser2.ml: the finalisers in the definition of test2 are not run, and it is expected. Need to check with the author what the intent was (@kayceesrk ?), and fix the test accordingly.

The finalisers do run and produce the expected output https://github.com/ocaml/ocaml/blob/trunk/testsuite/tests/weak-ephe-final/finaliser2.reference. I must be missing something.

**Comment by lpw25** [comment]
I've long been of the opinion that we should remove warning 59. As Gabriel suggests, it can be emitted on perfectly valid code. It is also quite likely to be emitted in dependencies of the module that contains the code that triggers it because it most often happens after inlining. Originally I think it was useful for debugging issues with flambda, but since then I'm only aware of it ever giving false positives. 5.00 seems a good time to get rid of it.

**Comment by lpw25** [comment]
@kayceesrk Flambda can extended the lifetimes of top-level values indefinitely (e.g. `r` in `test2`). Easiest solution is probably to make `test2` into a function marked `[@inline never]` and then call it. I would make that change to all the `testN` values in that file. I also see that some `foo` functions are marked `rec` without actually being recursive. My guess is that this is to disable inlining in Closure -- if so that should also be replaced with `[@inline never]`.

**Comment by lthls** [comment]
(See also #9978 for some discussion around lifetimes of toplevel values)

**Comment by lthls** [comment]
> On the lazy code itself: we need an atomic read here because the tag of OCaml blocks can be mutated from other threads, in particular in the case of an (incorrectly) shared `Lazy.t` value. Otherwise, if I understand correctly, you may see a value being forced by another thread, that already has tag Forward_tag but whose payload is still the thunk rather than the final value, and the Forward case of the switch is unsound.

If I read the code in `CamlinternalLazy` correctly, the payload is always set before the tag is changed. The only potential problem I can see with multiple domains forcing the same value is when one domain has set the payload but not the tag yet, and the other domain reads the tag. However, in this case the tag is `Lazy` or `Forcing`, and the current code will go through `CamlinternalLazy.force_lazy_block`, which will re-check the tag atomically anyway.

The other potential source of problems is related to short-cutting forward tags. From looking at the relevant pieces of code, I understand that:
- The GC must not run between the read of the Forward tag and the access to the field.
- The read of the tag must be synchronised, which I assume ensures that if some other thread has created a shortcut earlier then we're not reading the now incorrect Forward tag.

The second point seems to be what justifies the heavy `caml_obj_tag` instead of a normal header read. But I don't know enough about the details of the multicore GC to tell if handling the header lookup as a mutable load in Cmm (which is what we do already) is enough or if we really need the acquire semantics.

**Comment by kayceesrk** [comment]
> if handling the header lookup as a mutable load in Cmm (which is what we do already) is enough or if we really need the acquire semantics.

Given the complexity of reasoning about memory models, my aim was to reduce the uncertainty to get something correct working in https://github.com/ocaml-multicore/ocaml-multicore/pull/760. 

In particular, we chose to reason in terms of the C memory model. It is undefined behavior if the C program has data races (concurrent access to non-atomic locations). By reading the header non-atomically in `caml_obj_tag` while concurrently modifying it using CAS is also undefined behavior. Hence, we needed the acquire load. It is unclear to me which memory model semantics we would use to reason about the interaction between mutable load in Cmm and the concurrent CAS update implemented in C. 

(Now is perhaps the time to ask these questions. I have a number of questions that require similar cross-memory-model reasoning. I shall propose a memory model WG to caml-devel.)

**Comment by gasche** [comment]
@lthls 

> If I read the code in `CamlinternalLazy` correctly, the payload is always set before the tag is changed.

The tag is set atomically so if you also read it atomically, then the memory-model(s) should guarantee that you see the writes to the payload that were before the tag write in program order. But if you don't read it atomically, you have no such guarantee; for each location you read, you see one of the values that was written by the other domain since your last synchronization. In particular you could very well read `Forward` on the tag, but observe the previous payload (the lazy thunk, or `Val_unit` which was written in-between to release the closure).

**Comment by gasche** [comment]
Regarding the Forward shortcutting: my understanding was that shortcutting happens inside the minor GC during oldification/copy, so this should be a time where all domains are synchronized in a stop-the-world fashion, with a barrier after the change occurs. So I assume that running OCaml code cannot actually observe Forward shortcutting without itself being synchronized by the GC.

**Comment by lthls** [comment]
@gasche If I understand correctly your argument, then the read of the payload should also be made atomic, otherwise you may still get the old payload even if you correctly pick the new tag. Or does the memory model offer guarantees on non-atomic reads after an atomic read on a different location ?

**Comment by gasche** [comment]
> Or does the memory model offer guarantees on non-atomic reads after an atomic read on a different location ?

Yes, this is my understanding of the memory model ([Bounding data races in space and time](http://kcsrk.info/papers/pldi18-memory.pdf), Dolan, Sivaramakrishnan, Madhavapeddy, 2018):

> Again following Kang et al., we equip every thread with a frontier
F , which is a map from nonatomic locations to timestamps.
Intuitively, each thread’s frontier records, for each nonatomic
location, the latest write known to the thread. More recent
writes may have occurred, but are not guaranteed to be
visible.
> Atomic locations, on the other hand, are mapped by the
store to a pair (F , x), containing a single value x rather than a
history. Additionally, atomic locations carry a frontier, which
is merged with the frontiers of threads that operate on the
location. In this way, nonatomic writes made by one thread
can become known to another by communicating via an
atomic location.

> [..] When reading a nonatomic variable,
rule Read-NA specifies that threads may read an arbitrary
element of the history, as long as it is not older than the
timestamp in the thread’s frontier.
> [..] Atomic operations (rules Read-AT and Write-AT) are
standard sequential operations, except that they also involve
updating frontiers. During atomic writes, the frontiers of
the location and the thread are merged, while during atomic
reads the frontier of the location is merged into that
of the thread, but the location is unmodified.

**Comment by kayceesrk** [comment]
> Yes, this is my understanding of the memory model (Bounding data races in space and time, Dolan, Sivaramakrishnan, Madhavapeddy, 2018):

We can't use the OCaml memory model here. OCaml memory model can only be used for OCaml values. In particular, the header word is not an OCaml atomic reference. If you are to use OCaml memory model for reasoning, then all the header reads and writes should be compiled as explained in Table 3 and 5 in the paper, which we don't. I'm not saying what we have is correct, but it is incorrect to think about this in terms of OCaml memory model.

**Comment by gasche** [comment]
That's a good point, but my understanding was that release-acquire atomics on the C side work similarly, and that the atomic writes in the current implementation are release/acquire or stronger.

**Comment by lthls** [comment]
The load of the forward block in the inlined version of `Lazy.force` uses `Lprim (Pfield(0, Pointer, Mutable), _)` which is not covered by the C semantics and memory model.

**Comment by gasche** [comment]
Yes, but `caml_obj_tag` is used before that load, and loads the tag atomically: https://github.com/ocaml/ocaml/blob/395ad33/runtime/obj.c#L43-L46 .

**Comment by gasche** [comment]
Let me summarize my understanding of the situation:
- we are not fully sure how to reason about the memory-model behavior of mixed C/OCaml programs
- but if we assume that they offer at least release/acquire guarantees when doing atomic reads in either C or OCaml, then the current `Lazy` implementation was reviewed to be memory-safe even under concurrent usage (despite the fact that we consider it invalid/illegal to use lazy thunks concurrently)
- this relies crucially on having an atomic read of the tag before making assumptions on the lazy block contents
- this is why the `inline_lazy_{force,cond}` code in matching.ml was rewritten to use a C call instead of direct (non-atomic) reads as before

Note: there are proposals for alternative implementations/representations that don't mutate tags in this way, but nothing mature enough to consider replacing the current code for now.

**Comment by lthls** [comment]
I believe that in the C memory model, the memory location of the header and the field are independent, so synchronization of one of them doesn't imply synchronization of the other (unlike in the OCaml memory model you referred to). But I think we can wait until @kayceesrk has setup the working group before continuing this discussion.

For the flambda support, I'll submit a PR with Leo's suggestions (removing warning 59 and wrap the tests in functions) when I find the time.

**Comment by gasche** [comment]
> I believe that in the C memory model, the memory location of the header and the field are independent, so synchronization of one of them doesn't imply synchronization of the other (unlike in the OCaml memory model you referred to).

My understanding is that the release/acquire ordering provides the expected guarantees: operations on other locations (atomic or not) become visible to the other thread, unlike the relaxed atomics that behave as you say. See for example <https://en.cppreference.com/w/cpp/atomic/memory_order#Release-Acquire_ordering>:

> If an atomic store in thread A is tagged memory_order_release and an atomic load in thread B from the same variable is tagged memory_order_acquire, all memory writes (non-atomic and relaxed atomic) that happened-before the atomic store from the point of view of thread A, become visible side-effects in thread B. That is, once the atomic load is completed, thread B is guaranteed to see everything thread A wrote to memory.

On the other hand, this discussion got me thinking again about what happens in other parts of the runtime that access the argument of a Forward block; are they all protected by a synchronizing read on the tag? I see several uses of `Forward_val` in the runtime that follow a non-atomic tag check, my intuition is that `Forward_val` should atomically read the tag, and return its argument (instead of dereferencing the first argumnet) if it is not `Forward_tag`.

**Comment by kayceesrk** [comment]
I agree with @gasche that release/acquire provides the expected guarantees. This is a variant of the standard message-passing example, where an atomic flag is used to exchange a message on a non-atomic variable. See Figure 5 in https://people.mpi-sws.org/~viktor/papers/oopsla2013-rsl.pdf. Similar to this example, in Lazy, the header is updated using a CAS (both acquire and release), and read by `caml_obj_tag` using acquire loads. This is sufficient for the reader thread that witnesses the header update to see the field update by the writer thread that was performed before the header was updated. 

@maranget may be able to confirm.

**Comment by lthls** [comment]
My intuition is that the "Sequenced before" relation is stricter in the paper than in the actual specification; in particular, in the example from Figure 5 a C compiler is allowed to permute the order of `[a]_na := 7` and `[c]_rel := 1`, so the first one cannot be considered to happen before the other (the C11 specification I used as reference specifically mentions computational dependencies to define the "happens before" relation).
But in our particular case, the field update actually happens in OCaml-generated code while the tag update occurs in C code, so I think we can be sure that they cannot happen out of order. By this argument, the current code should be safe. (A compiler that produces C code instead might hit the issue.)

**Comment by gasche** [comment]
A comment about a meta-level question I had on reasoning on mixed C/OCaml programs. I'm not sure this is clearly mentioned in the memory-model paper, but I believe that the OCaml memory model is "more defined" than release/acquire atomics, in the following sense.

Let us call "release/acquire program" a version of the mixed C/OCaml program where all OCaml atomics are interpreted exactly as C release/acquire atomics.¹ Then I believe that if this release/acquire program is data-race free, then all behaviors allowed for the C/OCaml program are also allowed for the release/acquire program. In particular, we should be able to reason about correctness by working in the release/acquire model -- when a proof of data-race-freedom succeeds there.

(I would even conjecture that they have the same behaviors, that is that the OCaml memory model is not strictly stronger than release/acquire in this model, but I don't know, this is just because my mental intuition of release/acquire matches the operational semantics of the OCaml memory model.)

¹: it's not completely clear how to define this as a source-to-source program transformation, but note that memory models are not defined on complete source code but on mere sequences of reads and writes / memory events, so at this abstraction level it makes perfect sense to replace an "OCaml memory model write" to a "release write", etc.
