### ISSUE TITLE
inefficient floating point comparison

### ISSUE THREAD

**Issue by markghayden** [ocaml/ocaml#10883]
The floating point comparison on AMD64 for Ocaml 4.13.0 emitted inefficient assembly on AMD64.  There are 4 comparison and 10 or so branches:

```
_camlCompare__float_compare_14:
	.cfi_startproc
L108:
	movsd	(%rax), %xmm0
	movsd	(%rbx), %xmm1
	ucomisd	%xmm1, %xmm1
	jp	L107
	jne	L107
	movl	$1, %eax
	jmp	L106
	.align	2
L107:
	xorl	%eax, %eax
L106:
	ucomisd	%xmm0, %xmm0
	jp	L105
	jne	L105
	movl	$1, %ebx
	jmp	L104
	.align	2
L105:
	xorl	%ebx, %ebx
L104:
	subq	%rax, %rbx
	comisd	%xmm0, %xmm1
	jbe	L103
	movl	$1, %edi
	jmp	L102
	.align	2
L103:
	xorl	%edi, %edi
L102:
	comisd	%xmm1, %xmm0
	jbe	L101
	movl	$1, %eax
	jmp	L100
	.align	2
L101:
	xorl	%eax, %eax
L100:
	subq	%rdi, %rax
	addq	%rbx, %rax
	salq	$1, %rax
	incq	%rax
	ret
```

The assembly comes from the code below.

```ocaml
let mk_compare_floats dbg a1 a2 =
  bind "float_cmp" a1 (fun a1 ->
    bind "float_cmp" a2 (fun a2 ->
      let op1 = Cop(Ccmpf(CFgt), [a1; a2], dbg) in
      let op2 = Cop(Ccmpf(CFlt), [a1; a2], dbg) in
      let op3 = Cop(Ccmpf(CFeq), [a1; a1], dbg) in
      let op4 = Cop(Ccmpf(CFeq), [a2; a2], dbg) in
      (* If both operands a1 and a2 are not NaN, then op3 = op4 = 1,
         and the result is op1 - op2.
         If at least one of the operands is NaN,
         then op1 = op2 = 0, and the result is op3 - op4,
         which orders NaN before other values.
         To detect if the operand is NaN, we use the property:
         for all x, NaN is not equal to x, even if x is NaN.
         Therefore, op3 is 0 if and only if a1 is NaN,
         and op4 is 0 if and only if a2 is NaN.
         See also caml_float_compare_unboxed in runtime/floats.c  *)
      tag_int (add_int (sub_int op1 op2 dbg) (sub_int op3 op4 dbg) dbg) dbg))
```

From floats.c it appears there is the code that motivated mk_compare_float above:

```c
intnat caml_float_compare_unboxed(double f, double g)
{
  /* If one or both of f and g is NaN, order according to the convention
     NaN = NaN and NaN < x for all other floats x. */
  /* This branchless implementation is from GPR#164.
     Note that [f == f] if and only if f is not NaN.
     We expand each subresult of the expression to
     avoid sign-extension on 64bit. GPR#2250.
     See also translation of Pcompare_floats in asmcomp/cmmgen.ml  */
  intnat res =
    (intnat)(f > g) - (intnat)(f < g) + (intnat)(f == f) - (intnat)(g == g);
  return res;
}
```

However, gcc compiles the above on AMD64 to be branchless (as advertised).

```
_xcaml_float_compare_unboxed:           ## @xcaml_float_compare_unboxed
	.cfi_startproc
## %bb.0:
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	xorl	%ecx, %ecx
	ucomisd	%xmm1, %xmm0
	seta	%cl
	xorl	%edx, %edx
	ucomisd	%xmm0, %xmm1
	seta	%dl
	xorl	%eax, %eax
	ucomisd	%xmm0, %xmm0
	setnp	%al
	xorl	%esi, %esi
	ucomisd	%xmm1, %xmm1
	setnp	%sil
	addq	%rcx, %rax
	subq	%rdx, %rax
	subq	%rsi, %rax
	popq	%rbp
	retq
	.cfi_endproc
```

The comparable C code from compare.c requires 1-3 floating point comparisons in the case of normal floats (not NaN).  In cases where sorting varied numbers, this would typically be 1.5 comparison per ML compare.

```
      double d1 = Double_val(v1);
      double d2 = Double_val(v2);
      if (d1 < d2) return LESS;
      if (d1 > d2) return GREATER;
      if (d1 != d2) {
        if (! total) return UNORDERED;
        /* One or both of d1 and d2 is NaN.  Order according to the
           convention NaN = NaN and NaN < f for all other floats f. */
        if (d1 == d1) return GREATER; /* d1 is not NaN, d2 is NaN */
        if (d2 == d2) return LESS;    /* d2 is not NaN, d1 is NaN */
        /* d1 and d2 are both NaN, thus equal: continue comparison */
      }
```

The resulting gcc compiler AMD64 assembly is listed below. 

```
_compare_float:                         ## @compare_float
	.cfi_startproc
## %bb.0:
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	movsd	(%rdi), %xmm1                   ## xmm1 = mem[0],zero
	movsd	(%rsi), %xmm0                   ## xmm0 = mem[0],zero
	movq	$-1, %rax
	ucomisd	%xmm1, %xmm0
	ja	LBB2_6
## %bb.1:
	movl	$3, %eax
	ucomisd	%xmm0, %xmm1
	ja	LBB2_6
## %bb.2:
	jne	LBB2_3
	jnp	LBB2_5
LBB2_3:
	ucomisd	%xmm1, %xmm1
	jp	LBB2_4
LBB2_6:
	popq	%rbp
	retq
LBB2_4:
	ucomisd	%xmm0, %xmm0
	movq	$-1, %rax
	jnp	LBB2_6
LBB2_5:
	movl	$1, %eax
	popq	%rbp
	retq
	.cfi_endproc
```

Some comments:

* The original motivation for the mk_compare_floats appears to have been to create a branchless instruction sequence.  This does not appear to always work out as intended (at least for AMD64).  There are 10 or so branches (including both conditional and unconditional).  The code executes correctly, but it not as efficient as appears was originally intended.

* While the floats.c code appears elegant, it has the disadvantage of always requiring 4 floating point comparisons. The method in compare.c of testing for greater-than, less-than, equality and immediately finishing the comparison lack the elegance but has the advantage of saving instructions in the normal case.  Depending on the situation, it can be substantially faster than the current implementation (with all the branches), and also somewhat faster than the intended branchless compilation.

* Probably better (but processor dependent) would be to use a single floating point comparison instruction for the normal case (no NaN) and set an integer value to the appropriate value based on the processor flags.  I would guess (but don't know) that all instruction sets have an appropriate floating point comparison instruction.

**Comment by gasche** [comment]
I looked at the code out of curiosity:
- The branchless implementation in float.c comes from #164, where it was benchmarked, along with other changes, as improving performance (over the previous branching logic, similar to compare.c) on Intel Xeon machines.
- The generation of Cmm code for float comparisons, instead of calling a C primitive, comes from @gretay-js's #2324; the main argument given at the time was to enable specialization of comparisons with known constants. I don't know if it was remarked at the time that the branchless design didn't work anymore, but there was an amd64 benchmark showing small improvements, including on `compare`-heavy workloads.
- `Ccmpf` instructions that are not already the test of a conditional are handled in the `emit_expr` function of `asmcomp/selectgen.ml` (the generic code selection code, to be overriden/specialized by backends), by converting them to conditionals:

    ```ocaml
    | Cop(Ccmpf _, _, dbg) ->
        self#emit_expr env
          (Cifthenelse (exp,
            dbg, Cconst_int (1, dbg),
            dbg, Cconst_int (0, dbg),
            dbg))
    ```

    The branching code is later generated in emit.mlp, for example for amd64:

    ```ocaml
    let emit_float_test env cmp i lbl =
      [...]
      match cmp with
      [...]
      | CFlt ->
        I.comisd (arg i 0) (arg i 1);
        I.ja lbl                    (* branch taken if y>x i.e. x<y *)
      | CFnlt ->
        I.comisd (arg i 0) (arg i 1);
        I.jbe lbl                   (* taken if unordered or y<=x i.e. !(x<y) *)
      [...]
    ```

    I suppose that one would need to override the `Ccmpf` case above in `emit_expr` to generate branchless code instead, or possibly to move the handling of `Ccmpf` 

- There is support for emitting branchless code on integer comparisons in expressions; trying to use the same approach for float comparisons would suggest small restructurings in the backend. Ccmpf should probably be handled by `select_operation` instead of `emit_expr` directly (like Ccmp{i,a}). `mach.mli` operations have an `Intop of integer_operation` case that includes comparisons (when used as operations rather than tests), but no corresponding `Floatop of float_operation` case, floating-point operations are listed separately, and float comparisons are not included there (only in the separate `test` type representing conditions).

**Comment by gasche** [comment]
The stale bot is reminding me that this issue is ignored for now. I am not myself planning to look into it further. Unless someone stands up to adopt it (possibly @alainfrisch, @smuenzel or @gretay-js?) it is probably going to close itself automatically in six months to a year -- so a "won't fix" resolution due to lack of workforce.

My current assessment is that this is not a high-priority issue but still a real issue:
1. the current code is not "inefficient" in the sense that it was benchmarked several times to be better than what we had before, but
2. there may be efficiency gains left to have (hard to tell without further benchmarking) and 
3. there does seem to be an disconnect between the intent of the code (trying to write a branchless solution) and the actual result, which is if nothing else a readability/understandability bug in the codebase.

**Comment by lthls** [comment]
To me, the most natural way to fix this issue is to introduce a new `Ifloatcomp` operation to the `Mach.operation` type.
But this involves patching every file that pattern-matches on operations, and quite a few pattern matches are fragile so it's not completely straight-forward.
If someone else does the work I can review it. Otherwise I can work on it when I'm out of other things to do, but then someone else will have to review it.

**Comment by chambart** [comment]
If a patch where to be proposed for this, you can assign me as reviewer.

**Comment by xavierleroy** [comment]
> To me, the most natural way to fix this issue is to introduce a new Ifloatcomp operation to the Mach.operation type.

Don't we have a PR for this already?  My vague memory is that the generated asm code was hairy for some target architectures, esp. i386.  But now that we're dropping target architectures in OCaml 5, it might be time to reconsider this approach.

**Comment by smuenzel** [comment]
> Don't we have a PR for this already?

#9945 

> My vague memory is that the generated asm code was hairy for some target architectures, esp. i386. 

It wasn't too much code, but we did have to touch all the architectures. (i386 was a  small refactoring to share code with existing float comparison logic)

**Comment by gasche** [comment]
Ahem, apologies for semi-forgetting about your work, @smuenzel. (Of course there was a reason why I pinged you, but I forgot it was *this* related.)

My understanding is that the right course of action is to make a decision on #9945. I see some general consensus there, but no formal "approval" of the PR. Luckily, both @lthls and @chambart volunteered to review, and one of those two people is reliable ;-). Would you both look at the PR? (I'm glad I learned recently that @lthls is intereted in obscure architectures.)

**Comment by smuenzel** [comment]
#9945 is now merged, so we can close this issue
