### ISSUE TITLE
Wrong type inferred from existential types

### ISSUE THREAD

**Issue by dyzsr** [ocaml/ocaml#10907]
Input the following code into toplevel (both trunk and 4.13.1):

``` ocaml
type 'a t = T : ('a -> 'b) * ('b -> 'a) -> 'a t;;
type 'a t = T : ('a -> 'b) * ('b -> 'a) -> 'a t

let t = T ((fun x -> x), (fun x -> x));;
val t : 'a t = T (<fun>, <fun>)

let T (g, h) = t in h (g 1);;
- : 'a = <poly>

let f x = let T (g, h) = t in h (g x);;
val f : 'a -> 'b = <fun>
```

Seems the typechecker failed to infer the correct type, in comparison with

``` ocaml
type s = S : (int -> 'b) * ('b -> int) -> s;;
type s = S : (int -> 'b) * ('b -> int) -> s

let s = S ((fun x -> x), (fun x -> x));;
val s : s = S (<fun>, <fun>)

let S (g, h) = s in h (g 1);;
- : int = 1
```

**Comment by gasche** [comment]
Impressive: this looks like a large soundness bug that has been there since GADT were introduced in 4.00.

(And I thought the 4.14 release couldn't get more exciting!)

**Comment by gasche** [comment]
I reworded the example of @dyzsr a bit:

```ocaml
(* an isomorphism between 'a and 'b *)
type ('a, 'b) iso = ('a -> 'b) * ('b -> 'a)

(* exists 'b. ('a, 'b) iso *)
type 'a some_iso = Some : ('a, 'b) iso -> 'a some_iso

(* forall 'a. exists 'b. ('a, 'b) iso *)
let t : 'a . 'a some_iso =
  Some ((fun x -> x), (fun x -> x))

let unsound_cast : 'a 'b. 'a -> 'b = fun x ->
  match t with Some (g, h) -> h (g x)
```

**Comment by gasche** [comment]
At first I thought that the issue may be with the fact that `g`, `h` in the match are generalized independently of each other somehow. But this is not the case, as the following variation also works:

```ocaml
let unsound_cast : 'a 'b. 'a -> 'b = fun x ->
  match t with Some iso -> snd iso (fst iso x)
```

One way to understand the unsoundness is that we start from a value of type `forall 'a. exists 'b. ('a, 'b) iso`, which is an inhabited type, and after pattern-matching we have something that looks like `exists 'b. forall 'a. ('a, 'b) iso`, which should be non-inhabited and lets us derive an unsafe cast.
 
However, the relation with GADTs is more subtle than it first looks: I don't think this behavior is simply an implementation bug in pattern-matching in presence of GADTs. For example, the following also works (without GADTs):

```ocaml
type ('a, 'b) iso = ('a -> 'b) * ('b -> 'a)

type 'a unit_iso = ('a, unit) iso

let t : 'a . ('a, unit) iso =
  (fun x -> ()), (fun () -> assert false)

let dangerous_cast : 'a 'b. 'a -> 'b = fun x -> snd t (fst t x)
```

Now this program is not unsound, because the "dangerous cast" fails at runtime. But the point is that, once we managed to build a value of type `forall 'a. ('a, foo) iso` for some `foo`, we can type the `'a -> 'b` cast without involving GADTs; this is not a problem specific to the implementation of GADT pattern-matching.

In absence of GADTs, I don't see how to build a value of type `forall 'a. ('a, foo) iso` for some `foo` that does not mention `'a`. Natural ideas involve "leaking" the `'a` value through a mutable reference (or an extensible variant type), but those ideas involve side-effects and their definition will not be generalized due to the value restriction, so we rather get `('_a, foo) iso`.

I suspect that this is a case where generalization behavior that was sound in absence of existential types has become unsound in presence of existentials. The current generalization behavior of pattern-matching let us swap the quantifiers from `forall 'a. exists 'b. foo['a, 'b]` to `exists 'b. forall 'a. foo['a, 'b]`, so it is causing the unsoundness here.

This suggests the following attempt for a fix: do not generalize the types of sub-patterns that introduce existentials. More precisely, having an instance of a type variable occur under an existential quantification (under a constructor that introduces existentials) should make this type variable non-generalizable, as the existential may capture/mention this variable.

**Comment by gasche** [comment]
I tried to see if one could reproduce the issue using existentials from first-class modules, but I couldn't get anything problematic this way.

```ocaml
module type Iso = sig
  type a
  type b
  val g : a -> b
  val h : b -> a
end

let some_iso (type t) : (module Iso with type a = t) =
  let module M = struct
    type a = t
    type b = t
    let g x = x
    let h x = x
  end in
  (module M)

let rejected_cast (type a b) : a -> b =
  fun x ->
  let (module M) = (some_iso : (module Iso with type a = a)) in
  M.h (M.g x) (*
  ^^^^^^^^^^^
  This expression has type a but an expression was expected of type b
*)
```

**Comment by lpw25** [comment]
One way to look at the issue is that pattern matching that involves generalization, e.g.:
```ocaml
let foo () =
    let id = Some (fun x -> x) in
    match id with
    | None -> 0, "zero"
    | Some id' -> id' 1, id' "one"
```
could be achieved without support for generalization in patterns by a macro translation to something like:
```ocaml
let foo () =
    let id = Some (fun x -> x) in
    match id with
    | None -> 0, "zero"
    | Some _ ->
        let id' =
          match id with
          | None -> assert false
          | Some id' -> id'
        in
        id' 1, id' "one"
```
which only relies on generalization of `let` for syntactic values.

However, this translation would fail to type-check if the type of `id'` referred to an existential type bound by the match of `Some`. So you should not generalize the types of variables that refer to existentials -- which is a slightly more liberal version of the restriction @gasche proposed (@gache's might be the easier one to implement and a better restriction in practice).

**Comment by gasche** [comment]
(To understand Leo's message I needed to remind myself that `assert <value>` counts as a "syntactic value" (a non-expansive expression) for the purpose of generalization.)

> So you should not generalize the types of variables that refer to existentials

(Here "variables" means "pattern variables" and not type/inference variables of course.)

There are several sorts of generalization going on in pattern-clause typing: the type of pattern variables is generalized, but also the "argument type" and the "expected type". Your refine criterion only applies to the first category. This should be correct as I guess that "argument type" and "expected type" cannot mention the existentials anyway. The generalization of the argument type can be explained by another let-introduction, from `match <expr> with ...` to `match let v = <expr> in v with ...`, so it is clearly orthogonal to existentials.

**Comment by garrigue** [comment]
Thanks @gasche for your correct analysis. This is again in the category "we knew it but we still missed it"...
All the more inexcusable as generalization inside pattern-matching was specifically introduced because of GADTs (so that we could use `type_cases` rather than `type_let` as soon as the pattern contains constructors, to avoid handling GADTs in `type_let`.

I think we should, inside `type_pat`, lower type variables inside the arguments of constructors that introduce existentials to a level that will not be generalized in the body of the match, but that still allows to unify with freshly introduced existentials. I don't know whether such a level is already available in `type_cases`, or if we need to introduce yet another level.
I suppose that we could use `nongen_level` to propagate it to `type_pat`, as it has the correct semantics.

**Comment by gasche** [comment]
I tried the following approach to implement my restriction.

```diff
 let solve_Ppat_construct ~refine env loc constr no_existentials
         existential_styp expected_ty =
   (* if constructor is gadt, we must verify that the expected type has the
      correct head *)
   if constr.cstr_generalized then
     unify_head_only ~refine loc env (instance expected_ty) constr;
   begin_def ();
   let expected_ty = instance expected_ty in
   (* PR#7214: do not use gadt unification for toplevel lets *)
   let unify_res ty_res =
     let refine =
       match refine, no_existentials with
       | None, None when constr.cstr_generalized -> Some false
       | _ -> refine
     in
     unify_pat_types_return_equated_pairs ~refine loc env ty_res expected_ty
   in
   let expansion_scope = get_gadt_equations_level () in
+  let lower_if_existentials ty =
+    if constr.cstr_existentials <> [] then begin
+      let var = Ctype.newvar2 (get_gadt_equations_level ()) in
+      Ctype.unify_var !env var ty
+    end
+  in
   let ty_args, ty_res, equated_types, existential_ctyp =
     match existential_styp with
       None ->
         let ty_args, ty_res, _ =
           instance_constructor ~in_pattern:(env, expansion_scope) constr in
+        List.iter lower_if_existentials (ty_res :: ty_args);
         ty_args, ty_res, unify_res ty_res, None
     | Some (name_list, sty) ->
         let in_pattern =
           if name_list = [] then Some (env, expansion_scope) else None in
         let ty_args, ty_res, ty_ex =
           instance_constructor ?in_pattern constr in
         let equated_types = unify_res ty_res in
         let ty_args, existential_ctyp =
           solve_constructor_annotation env name_list sty ty_args ty_ex in
+        List.iter lower_if_existentials (ty_res :: ty_args);
         ty_args, ty_res, equated_types, existential_ctyp
   in
   end_def ();
   generalize_structure expected_ty;
   generalize_structure ty_res;
   List.iter generalize_structure ty_args;
```

(Note: I first tried to push the lowering logic in `instance_constructor` but this is painful because neither `unify_var` nor `get_gadt_equations_level` are defined at this point of ctype.ml, so I thought I'd rather get general feedback on the approach.)

This appears to work: unsafe-cast can get the type `'a -> 'a`, which is sound, but not `'a -> 'b` which isn't. However:
- I don't know whether this is what @garrigue had in mind (in particular, is it correct to use `get_gadt_equations_level` here?)
- There are various principality-related warnings when compiling the compiler codebase, in particular FormatBasics.
- I would rather try to implement Leo's refined criterion if I see how to do it, so I'm not in the "opening a PR" phase yet

On the other hand, implementing Leo's idea looks more difficult. I cannot work in `solve_Ppat_construct`, because at that point I can easily tell if the constructor introduces existentials, but I don't have the pattern variables yet. I would work in `type_cases`, the part that post-processes the inferred type of pattern variables, but at this point it's less clear how to detect existential types:

1. I must admit that I already don't know which is the iterator to use on types to look for all potential occurrences of an existential variable; is repeated `iter_type_expr` enough, or should I use `iterators`, but then do I need to override `it_type_expr` or `do_it_type_expr`? I'm confused.

2. What's a good criterion to detect the presence of an existential type? They have the structure of atomic rigid variables as created by `new_local_type`, and they are scoped at the current `get_gadt_equations_level`? (Does that level still exist at this point of type-checking?)

**Comment by gasche** [comment]
An example of warning I get with my version:

```
File "/home/gasche/Prog/ocaml/github-4.14/otherlibs/dynlink/dynlink_compilerlibs/local_store.ml", line 72, characters 33-38:
72 |     List.iter (fun (Slot s) -> s.value <- !(s.ref)) slots;
                                      ^^^^^
```

The criterion used by label disambiguation to warn here is whether the expected type (at disambiguation point) is generic (typecore.ml:is_principal). Here `s` is under an existential-introducing constructor, so it gets lowered to a non-generic level and the warning fires. (The type of `s` does mention the existential, so Leo's refinement would also lower it.)

I'm not the principality expert here so I'm not sure why we use generic_level in this way. Would saying "higher than the current gadt-introduction level" be correct? I'm afraid not, if we want to detect "pollution" coming from other clauses, whose right-hand-side is type-checked above gadt-introduction level.

**Comment by garrigue** [comment]
@gasche Rather than unifying with a fresh variable, you should probably call a modified version of `Ctype.lower_contravariant`, which only lowers the type of type variables. Currently it is always called with `contra = false`, but you should call it with `contra = true` (this is not optimal, but this seems better than writing a new function).
I'm not sure this is going to suffice, but at least this should avoid some spurious lowering.

**Comment by gasche** [comment]
I tried with the following definition of `lower_if_existentials` (attention les yeux...):

```ocaml
  let lower_if_existentials ty =
    if constr.cstr_existentials <> [] then begin
      let levels = Ctype.save_levels () in
      Ctype.set_levels { levels with nongen_level = get_gadt_equations_level () };
      lower_contravariant !env (newty (Tarrow(Nolabel, ty, ty, commu_ok)));
      Ctype.set_levels levels;
    end
  in
```

This fixes the reproduction case, and I think there are less principality warnings (the one I quoted above does not warn anymore), but I still see many warnings in FormatBasics.

```
File "/home/gasche/Prog/ocaml/github-4.14/stdlib/camlinternalFormatBasics.ml", line 550, characters 4-37:
550 |   | Format_subst_ty (ty1, _ty2, rest) ->
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error (warning 18 [not-principal]): typing this pattern requires considering
($24, $25, $26, $27, $28, $29) format6 -> $30 and a as equal.
But the knowledge of these types is not principal.
```

Somewhat interestingly, most of the warnings do not have a location, for exampel:

```
File "/home/gasche/Prog/ocaml/github-4.14/stdlib/_none_", line 1:
Error (warning 18 [not-principal]): typing this pattern requires considering a/2 and $Float_'y1 as equal.
But the knowledge of these types is not principal.
```

I believe that they come from the type-checking of the result of wildcard-pattern explosion, so subpatterns of the form `(Foo _ | Bar _ | Baz _)`. This corresponds to the case where there are no pattern variables, so Leo's refined criterion that only acts on type variables captured in the type of pattern variables may silence them.

**Comment by gasche** [comment]
I would be happy to make progress on this soundness bug in the type-checker, but I need feedback/guidance from @garrigue or @lpw25.

**Comment by garrigue** [comment]
Sorry I didn't answer earlier, and thank you for your work.
Your remark that you get warnings from counter-examples suggest that those warnings should just be disabled when working on counter-examples, since they do not make sense there.

Implementing Leo's refinement (IIUC, basically do the same but actually only lower if the type variable is exported to the environment) should in theory be possible, but is going to be tricky, as it forces you to mark the candidate type variables in a different way, so it should probably not be a priority.

If you have a problem, I can look into this.

**Comment by garrigue** [comment]
I created PR #10959 by extending @gasche 's code.
@lpw25 , can you look at it.
I didn't implement your improvement because it requires changing things inside `type_cases` itself, rather than locally during constraint solving. I think this can be done later if we find examples where the lost polymorphism matter.
Originally polymorphism in pattern-matching was just introduced for backward compatibility, since `type_let` calls `type_cases` as soon as a pattern contains a constructor. This example falls outside of this, but there might still be code that rely on the extra polymorphism.

**Comment by gasche** [comment]
@dyzsr I wanted to thank you again for this report. It's a big source of unsoundness in the treatment of GADTs that we hadn't noticed; in retrospect it looks hard to miss it, but we probably would have continued merrily for some years without your care, and your work turning an intuition into a proof of unsoundness. Nicely done!
