### ISSUE TITLE
Safety of some non-atomic loads generated by the compiler

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#10944]
In an OCaml program, all reads and writes to mutable values are non-atomic unless explicitly using the Atomic module. This is the expected behavior. However, the code generated by the compiler performs reads and writes that are hidden from the programmer, such as header loads, implicit unboxing…

All those are currently performed as non-atomic loads (save for the reading of the tag in `caml_obj_tag` which is done using an acquire load). The safety of some of those is not entirely clear (to me) in the multicore memory model.

Header loads are the object of a dedicated issue [<https://github.com/ocaml/ocaml/issues/10942>].
Here is a list of the other places where non-atomic loads are used and I am unsure about it being thread-safe:

- OO stuff: method caching (https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L1745), message sending (https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L790).
- The helpers performing unaligned loads, although they are currently not used outside of Cmm_helpers (from https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L1116 onwards).
- The `Psetfield_computed` primitive (https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L2402).

This list does not include:
- Non-atomic loads specific to the bytecode backend, if any.
- Non-atomic loads performed in C code.

Finally, the situation of *stores* generated by the compiler is similar (the vast majority is not atomic), maybe it requires a similar audit.

**Comment by xavierleroy** [comment]
Please keep in mind that most OCaml data structures are immutable.  In this case, there are initializing write, performed before the block can be published and shared with other domains, then just reads, which are never racy.

So, this knocks a number of items off your list, e.g. boxed integers, bigarray dimensions.

Could you please narrow down your analysis taking this fact into account?

**Comment by bluddy** [comment]
It's worth cataloging that issue https://github.com/ocaml/ocaml/issues/7241 is made potentially much worse in multicore. The `match` construct was never atomic to begin with, but it emulates an atomic construct from the user's perspective. A second thread could cause side effects at any time, making the evaluation of patterns unsound.

**Comment by OlivierNicole** [comment]
I have edited my initial message to take immutability into account.

**Comment by gasche** [comment]
@bluddy: this is an interesting point.

The pattern-matching compiler assumes that mutable fields do not change during evaluation of patterns (except for `when` clauses), and that this assumption is broken by `lazy` patterns and by racy programs. Notice that correct concurrent programs (without racy writes) are not an issue currently, as there is no way to perform an atomic read in the middle of a pattern.

So the question is: is it a bug if pattern-matching gives the wrong result on patterns involving reads on non-atomic mutable state that is being mutated in parallel? I think a reasonable answer is "no". (By that interpretation, the problem is not "much worse", there is no problem.)

However, as shown by @stedolan's clever example in #7241, in presence of GADTs we can break type soundness with racy programs. I thought a bit harder about this. The problem with the pattern-matching compiler boils down to an optimization it performs which looks like this:

```ocaml
(* original program (morally) *)
match !r with Foo x ->
  match !r with Foo y ->
    blah

(* transformed program (morally) *)
match !r with Foo x ->
  let y = x in
  blah
```

Note that the transformation is not typability-preserving if `Foo` is a GADT constructor with existential type parameters (`x` and `y` have incompatible types in the source program, and the same type in the optimized program). This increase in typability introduces type-unsoundness.

I am not confident that the pattern-matching compiler is the only part of OCaml that can perform this optimization. If I understand correctly, sharing the two `!r` reads (on a non-atomic mutable location) is allowed by the memory model, and I would not be surprised if the middle-end, today or tomorrow, performed the sharing of tests as well.

So my conclusion is: currently racy programs may be type-unsound in presence of GADTs. If we want to prevent that, we have to think hard about what optimizations we decide to allow or forbid on mutable loads, because it's easy to run into the issue, not only in the pattern-matching compiler. The simplest approach would be to never merge mutable loads (in the pattern-matching compiler and elsewhere; CSE has them for example), but the performance cost may be noticeable. A more complex approach would be to keep track of control-flow coming from GADT constructors in our intermediate representations, and optimize them differently from usual control flow. I'm not sure how much complexity we want to tolerate, and which of the two features (mutable state or GADTs) should pay the cost.

**Comment by kayceesrk** [comment]
I had a quick question before I dug into this more deeply

> currently racy programs may be type-unsound in presence of GADTs.

Wasn't this true with sequential OCaml and Systhreads? The tick threads will periodically interrupt the program and force a preemption. Can the same unsoundness happen in this case?

**Comment by bluddy** [comment]
@gasche Just to make sure we're on the same page

Suppose thread 1 runs the following code

```ocaml
match !r with
| Some x -> x + 1
| None -> 2
```
and suppose thread 2 changes the value of !r from `Some 2` to `None` during thread 1's pattern match.

Thread 1 reads !r as `Some` for the purpose of matching, but then attempts to dereference `x` despite !r being changed to `None` by thread 2, and gets a segmentation fault. This seems to me to be entirely possible under the current model of pattern matching. Is this then a more serious issue than other possible data races?

**Comment by gasche** [comment]
@kayceesrk my mental model of systhreads was that control switches happen when the runtime is called, in particular at allocation points. In the previous example there is no allocation between the two reads of `!r`, and if there was there would be other reasons than concurrency (finalisers, etc.) why sharing the reads would be incorrect. If there is/was arbitrary preemption as you suggest, then sharing mutable loads is always incorrect, isn't it?

@bluddy Accessing the variable `x` in the right-hand-side does not perform a mutable load again, it dereferences a field from the value of `!r` as it was when pattern-matching started. But it is possible to write weirder examples where the pattern-matching will dereference the value twice, which can indeed lead to segfaults -- in general "can segfault" and "is not type-sound" are mostly equivalent.

```ocaml
type t = { b: bool; mutable v : int option * int option }

let () =
  let r = { b = true; v = (Some 21, None)} in 
  let n =
    match r with
    | { b = _; v = (Some _, _) } when (r.v <- (None, Some 21); false) -> 0
    | { b = true; v = (Some a, Some b) } -> a + b
    | { v = (_, _) } -> 1
  in
  print_int n; print_newline ()
```

... I guess I'm getting motivated to look at #717 again.

**Comment by bluddy** [comment]
Indeed, I wasn't sure about the behavior of this specific example, but figured there's an endless supply of complexity along this track which would take advantage of the non-atomicity of pattern matching.

**Comment by lpw25** [comment]
> The problem with the pattern-matching compiler boils down to an optimization it performs which looks like this:
> [...]

Your description seems backwards to me. The problem isn't with replacing two mutable loads with one, which is safe. It is with doing two mutable loads and assuming that they have returned the same result.

I think only the pattern match compiler does this, and only in rare cases because it tries to reuse the result of first mutable load if it can. It should be possible to make it sound by always throwing away information about a mutable field when forced to re-load it. What can't be avoided is that some pattern matches that seem exhaustive will actually fail with a match failure exception due to concurrent mutations. It might be worth adding a warning in such cases.

**Comment by kayceesrk** [comment]
> In the previous example there is no allocation between the two reads of !r,

Right. Does the pattern matching compiler throw away information about a mutable field across GC safe points (allocations / poll points inserted by the compiler / calls into the runtime)? If it does not, then the problem should be there in the presence of systhreads as well.

I am not familiar with the optimisations in the pattern matching compiler. If possible, it would be nice to see a complete example, including the concurrent mutation in order to understand the failure better.

**Comment by bluddy** [comment]
@kayceesrk Look at the original bug report at #7241. They were concerned about possible sources of mutation there, but now there can be mutation all the time. You're probably right that systhreads already had that issue.

**Comment by OlivierNicole** [comment]
Looking again after one year, I managed to convince myself that all non-atomic loads listed in my original message are safe:

- Method caching has been addressed in bytecode (https://github.com/ocaml/ocaml/pull/11512), and is safe in native code ([reason](https://github.com/ocaml/ocaml/issues/10960#issuecomment-1226152291)); message sending performs loads in the array of methods of an object, which I believe is immutable after initialization (they could even be turned into “`Immutable`” loads).
- Unaligned loads are only used for strings, bitstrings, and bytes; nothing that is expected to be atomic.
- `Psetfield_computed` is used to access class instance variables, an operation that is not expected to be atomic.

I’ll therefore close this.

**Comment by gasche** [comment]
We also use `Psetfield_computed` in the tail-modulo-cons transformation, to initialize a destination with a value. So this is an initializing write and it gets compiled to `caml_initialize`. I don't know what that means in terms of memory safety. The destination itself is not shared across domains before this initializing-write happens, so I think that we should be safe.

**Comment by OlivierNicole** [comment]
In this case the same publication safety arguments should be applicable in both cases, I believe, yes.
