### ISSUE TITLE
Stack limit default in 5.00.0

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#10954]
The stack_limit change in 5.00.0 risks to break a lot of existing code. May be the main domain/thread should still have
a stack_limit of 0, while new domain could have a limit of 1024k ?

**Comment by gasche** [comment]
I don't understand what you mean. (Which change? What code will be broken?) Can you elaborate?

**Comment by craff** [comment]
StackOverflow is now raised if the stack is bigger than 1024k. The parameter stack_limit in GC control is 0 in 4.14.0 and 1024k in 5.00.0. 

Any code that uses more than 1024k of stack is broken. Just setting the parameter to 0 for the initial domain should avoid breaking existing code. 

Le 26 janvier 2022 10:54:35 GMT-10:00, Gabriel Scherer ***@***.***> a écrit :

**Comment by gasche** [comment]
On my (Linux) system, `ulimit -s` returns 8192 by default, which I understand means that I have 8192Kio of stack size available for native OCaml programs, which corresponds precisely to 1024K machine words. So on my system, with ocamlopt, there should be no difference on the set of executions raising a Stack Overflow, right?

Do you have your own system-stack limit explicitly set to a value higher than 8192? (Then why not set OCAMLRUNPARAM="l=...." to a high value at the same time?) Or are you maybe talking about bytecode programs?

Relevant issue: #10795, discussing what a good default stack size should be.

**Comment by craff** [comment]
On 22-01-26 15:06:32, Gabriel Scherer wrote:
> On my (Linux) system, ulimit -s returns 8192 by default, which I understand
> means that I have 8192Kio of stack size available for native OCaml programs,
> which corresponds precisely to 1024k machine words. So on my system, with
> ocamlopt, there should be no difference on the set of executions raising a
> Stack Overflow, right?
>

On my machine I have ulimit -s unlimited. The fact that
code behavior is not changed by 5.00.0 should be independant of
the system parameters ?

I encountered the problem for a benchmark.

> Do you have your own system-stack limit explicitly set to a value higher than
> 8192? (Then why not set OCAMLRUNPARAM="l=...." to a high value at the sam
> time?) Or are you maybe talking about bytecode programs?
>
> Relevant issue: #10795, discussing what a good default stack size should be.

I will look at this issue.

Thanks,
Christohpe

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.*Message ID: <ocaml/
> ***@***.***>
>

--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

**Comment by gasche** [comment]
> The fact that code behavior is not changed by 5.00.0 should be independent of the system parameters ?

The change that you propose, setting an unlimited stack by default in 5.00, will break the property you propose for all users that do not have an unlimited system stack: they will be able to observe a change of behavior as some programs will not Stack_overflow anymore. (This is good if the program is useful, but bad if it contains a non-termination bug.) As far as I know, most users have a limited system stack on their system (I don't know of any operating system that provides an unlimited stack by default, do you?), so the change you propose (removing the stack limit by default) would change the observed behavior for most users.

The only way to have the property you propose would be to choose, at startup, the default OCaml stack limit by looking up the system stack limit. I think that this could be a reasonable approach as long as users can set the stack limit to a different value explicitly.

But this approach assumes that preserving the system-stack behavior is desirable (no change in behavior). What if, for most systems, the system stack limit is too low, and choosing a different default *improves* the user experience? This was the reasoning behind #10736 (now reverted) that sets the default stack limit to 1Gio. Should we not consider doing the same for 5.00, instead of preserving a current behavior that may be undesirable? Discussing whether a good/better default exists is the purpose of #10795.

**Comment by gasche** [comment]
I'm closing this, considering it as a duplicate of #10795. (It's not really, but now the two discussions have merge and it's one less issue.)
