### ISSUE TITLE
Means of limiting how much memory is being reserved by the runtime, so that Valgrind and AFL can be used

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml#10971]
It became clear in https://github.com/ocaml/ocaml/pull/10955 that a proper functionality and design discussion needs to happen.

### Feature Proposal

We need a means of limiting how much memory is being reserved by the runtime, so that we can run Valgrind and AFL.

In general, it would be good to give the programmer more control over the amount of virtual memory that the OCaml runtime reserves.

> @kayceesrk in https://github.com/ocaml-multicore/ocaml-multicore/issues/795
> Currently, both [`Max_domains` and `Minor_heap_max`] are defined in runtime/caml/config.h, with `Minor_heap_max` defined as 2GB and `Max_domains` as 128. This makes Multicore OCaml programs use at the minimum 256GB of virtual address space. This causes problems for tools like AFL and Valgrind, which cannot seem to deal with mmap reserve and expects to commit that much memory, and hence run out of memory on Multicore OCaml.

### Failed Implementation
- (https://github.com/ocaml/ocaml/pull/10955).
    1. Lowering the default value of `Minor_heap_max` is not desirable: a large number of existing programs programmatically increase the size of the minor heap using `Gc.set`, and we cannot break this functionality.

### Goals
- No limit on the number of domains that can be spawned
- No limit on the the program changing the size of the minor heap
- No new OCAMLRUNPARAM parameters
- Valgrind works out of the box, AFL works with the `-m none` option

**Comment by gasche** [comment]
I'm trying to follow this discussion, so here is some more basic information.[^1]

## How `Max_domains` is used

In the current implementation, Max_domains is used to allocate per-domain state for various runtime structures.

### Domain memory (domain state + minor heap)

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/domain.c#L570-L583

#10955 proposed to turn this into dynamic allocations.

### Gc Stats

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/major_gc.c#L910

This is discussed in another issue: #10961

### Assigning unique domain identifiers

At startup, `Max_domains` domain descriptors are initialized, with `unique_id` values from `0` to `Max_domains - 1`:

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/domain.c#L600

Then, when a domain is terminated, the `unique_id` value in the corresponding descriptor (which may be reused if another domain is spawned in the future) is incremented by `Max_domains`:

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/domain.c#L1378-L1381

Currently this guarantees unicity: all the domains living at index `i` have a unique id that is equal to `i` modulo Max_domains, and their unique integers are distinct from each other (... assuming no overflow, which I guess could happen on 32bit systems as those are `uintnat` values; we should use `long long` or something).

My understanding is that we only need to pick a new `unique_id` on domain creation, which is expensive/rare, so we could just have a global atomic counter instead.

## Comments

### We can dynamically change the minor-heaps space

We reserve a block for the minor heaps to efficiently check whether an object is in the minor heap:

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/caml/mlvalues.h#L212-L217

However, the check uses global variables that could change (carefully) during program runtime. In particular, we are not trying to use bit tricks relying on reserving an aligned 2^K region in memory.

### We need to reserve virtual memory carefully

In https://github.com/ocaml/ocaml/pull/10955#issuecomment-1024336994. @xavierleroy suggest that the "minor heap area" does not to be rigidly structured as N blocks of size S reserving all the space; we could reserve a larger minor heap area than needed at first, and allocate minor heaps from it on-demand.

However, if I understand correctly the problems we have with valgrind and AFL come from the fact that we reserve a lot of virtual address space, and those tools seem to ignore the difference between pre-reservation and use of the memory, they blow up on large virtual usage. (See the discussion for why AFL does this in https://github.com/ocaml/ocaml/pull/10888.) So we need an approach that reserves virtual memory carefully.

Note: I'm surprised by these limitations in the tools around us, given that other language runtimes use the allocate-large-virtual-space trick, notably Go if I remember correctly discussions with @gadmm. I looked around the web for how Go users work around the AFL issue, but it looks like [they rewrote their own version of afl-fuzz](https://github.com/dvyukov/go-fuzz) instead of using the mainstream tool!

## A simple proposal

We don't need a `Max_domains` parameter if:

- we use dynamic arrays for domain-indexed structures
  (we can reuse slots for domains that were terminated; use a global atomic counter for `unique_id`)
- we start with only a modest reservation for the minor space, and move to a larger reserved region on-demand

If a domain-creation or minor-heap-resize request cannot be accommodated with the current reserved minor space, we unmap it and remap something larger. This introduces a new failure scenario in running programs ("out of large contiguous blocks of virtual memory"), but I think that this is a fact of life. (In fact, by being more economical of virtual address space, we are also better citizens from this point of view, if other language runtimes are loaded in the process for example.)

I think that the current layout strategy (N contiguous blocks of size S) could still be used in presence of this dynamic resizing -- it may not use the whole reserved area. One could also move to something more flexible as @xavierleroy suggests, but I don't know if there is a clear requirement. Being more flexible is helpful if the user programmatically reduces the per-domain minor heap size, and then expects to be able to spawn many more domains without resizing the minor space, but that sounds like a niche scenario.

[^1]: how to include cool code-citation snippets in a Github message: [see documentation](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet). And yes, I am a [footnote](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes).

**Comment by xavierleroy** [comment]
Before we embark on designs, let me recall my requirements:
- Programs should be able to change the minor heap size programmatically, using `Gc.set`.
- There should be no hard limit on minor heap size.
- If there is a hard limit on the number of simultaneously-active domains, the program should also be able to change it programmatically using `Gc.set`.

However, I'm OK with the following limitation, if they facilitate the implementation:
- The minor heap size or max number of domains can be changed only before any domain is spawn.

One reason for adjusting both the minor heap size and the max domain number in the same call to `Gc.set` is to enable applications to trade bigger heaps for fewer domains, or even a single domain for sequential applications.

Now, here is a very simple design that meets my requirements:
- When the run-time system starts, it reserves a virtual memory space of size S * D, where S is the default size for minor heaps and D the default max number of domains.  S and D default to the quantities in <caml/config.h> but could also be overridable using OCAMLRUNPARAM as in #10955 if desired.
- When Gc.set is called to change the minor heap size S or max domain number D, a minor GC is performed to empty the minor heaps; the virtual memory space is freed, then reallocated with the new S and D parameters, and the addresses of the minor heaps are adjusted

Concerning Valgrind and AFL, my hope is that with the default S and D parameters I suggest, the product S * D is small enough that the virtual memory space can not only be reserved, but also fully preallocated, without running out of memory on a reasonable machine.  With S = 262144 words and D = 128, that's 256 Mbytes, and it should not be a problem.

**Comment by gasche** [comment]
If I understand correctly, you are looking for a low-invasiveness patch. But having a limit on the maximum number of domain (that is fairly low unless you remember to explicitly set it higher) sounds inconvenient/undesirable, so it would be nice to avoid it unless there are clear advantages. I'm not sure we can avoid having to handle unmapping/remapping with your restriction, so both implementation could be of equal size/difficulty.

**Comment by xavierleroy** [comment]
> having a limit on the maximum number of domain (that is fairly low unless you remember to explicitly set it higher) sounds inconvenient/undesirable

Not really.  Domains are for parallelism, and there's little point in having more domains than available cores.  (You're just wasting memory by having too many minor heaps.)  That's why we have / we will have fibers on top of domains, so that you can have a great many threads of control while using hardware resources efficiently.

**Comment by jhjourdan** [comment]
Then what about setting the default maximum number of domains to the number of available cores?

**Comment by xavierleroy** [comment]
The number of available cores is surprisingly difficult to determine at run-time.  AFAIK, there are no standard APIs to do that.

**Comment by gasche** [comment]
In any case there are desktop machines sold with 64 cores today, so I think that 16 (as was previously proposed) would be a surprisingly low default, especially when the consequence of going above the limit is a program crash. D=128 sounds more reasonable, but I don't know for how many years. From looking at the code it doesn't sound too hard to write code that does not assume a maximum number of domains; I may be wrong, and I'll try to send some PRs instead of just comments.

**Comment by dbuenzli** [comment]
> The number of available cores is surprisingly difficult to determine at run-time. AFAIK, there are no standard APIs to do that.

It would still be nice to have something that does an educated guess at that in the stdlib. Otherwise we are all going to write our semi-broken code to determine the number of domains we should use.

I believe [these](https://github.com/b0-system/b0/blob/master/src/b00/std/b00_stubs_cpu.c) system calls mostly do the job on Unices and Windows. Though I vaguely remember a discussion about `_SC_NPROCESSORS_CONF` to be maybe better than `_SC_NPROCESSORS_ONLN` on some platforms as the latter will not count processors that are put to sleep for power saving.

**Comment by abbysmal** [comment]
I did not go through in depth in the conversation yet, I will just mention that I think @gasche meant to link https://github.com/ocaml/ocaml/issues/10961 for `sampled_gc_stat` (which is an important step to reach if we are to change the minor heap allocation lifecycle).

Also to be mentioned, when thinking about how we allocate the minor heaps and what could be potential caveats, our report on moving to a [bump-pointer minor heap allocation schema](https://github.com/ocaml-multicore/ocaml-multicore/wiki/Domain-Local-Allocation-Buffers-Addendum). (Domain local allocation buffers)

I'm re-mentioning the later because some of our observations in the past showed that preallocating (vs reserving and then committing, or allocating on the spot for each domain) may have insidious effects performance wise.
Though, for the suggested schema in this thread, pre-allocation is merely a nice bonus, not a requirement.

**Comment by dbuenzli** [comment]
> Though I vaguely remember a discussion about _SC_NPROCESSORS_CONF to be maybe better than _SC_NPROCESSORS_ONLN

Found that again. It was in [firefox's implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1333059) of `navigator.hardwareConcurrency`, apparently on `ARM` and if the symbol is defined you should rather use `_SC_NPROCESSORS_CONF`.

**Comment by nojb** [comment]
> The number of available cores is surprisingly difficult to determine at run-time. AFAIK, there are no standard APIs to do that.

FYI this is how GHC does it https://github.com/ghc/ghc/blob/3531c4784c0a06063dcfc0f084943d5149e64035/rts/posix/OSThreads.c#L305-L366.

**Comment by damiendoligez** [comment]
@xavierleroy 
> Now, here is a very simple design that meets my requirements:
> 
> * When the run-time system starts, it reserves a virtual memory space of size S * D, where S is the default size for minor heaps and D the default max number of domains.  S and D default to the quantities in <caml/config.h> but could also be overridable using OCAMLRUNPARAM as in [Make Minor_heap_max and Max_domains OCAMLRUNPARAM options #10955](https://github.com/ocaml/ocaml/pull/10955) if desired.
> * When Gc.set is called to change the minor heap size S or max domain number D, a minor GC is performed to empty the minor heaps; the virtual memory space is freed, then reallocated with the new S and D parameters, and the addresses of the minor heaps are adjusted

I would go one step further and allocate only as much memory as needed: minor_heap_size * number_of_domains. Then you need to stop the world, empty the minor heap, and reallocate the minor heap whenever you want to change the minor heap size or spawn (or shutdown) a domain. These operations are expected to be infrequent and costly, so a stop-the-world pause is probably acceptable.

I'll try to open a PR of this soon.

**Comment by gasche** [comment]
In #10974 I propose to use a global atomic counter to derive domain unique identifiers, instead of using `+= Max_domains` in the computation. This is a non-critical change that should help any proposal to change `Max_domains` at runtime or get rid of it.

**Comment by kayceesrk** [comment]
@damiendoligez 

> and reallocate the minor heap whenever you want to change the minor heap size or spawn (or shutdown) a domain.

Are you thinking about having a minimum number of domains pre-allocated? I think it would be prudent performance-wise to do so. In the extreme case, if the minimum is 1, for every domain spawn and shutdown, we will have a stop-the-world section where we remap the minor heap areas. It is common in our [Sandmark benchmarks](https://github.com/ocaml-bench/sandmark/tree/master/benchmarks), to quickly spin up N domains at program startup (where N is up to 128 in our nightly benchmark runs). Currently, we don't have a stop-the-world section at domain creation. It may be useful to start with a minimum number of domains that covers the common case (8 or 16), and then double this number when we hit the limit. 

I am also not convinced that we need to reduce the minor heap areas on domain shutdown. We do have a stop-the-world minor collection at domain termination:

https://github.com/ocaml/ocaml/blob/6a7a7b36fa2b6f4c4f3d210c8ecaff6faa094adf/runtime/domain.c#L1354

That said, many of the parallel programs in Sandmark terminate all the domains just before program termination. Hence, reducing minor heap areas at domain termination will not buy much in those programs. 

> I'll try to open a PR of this soon.

Thanks for volunteering to do this work. We would be happy to benchmark this PR (and various options) on our [benchmarking servers]( https://sandmark.ocamllabs.io/#machines-used-for-generating-results).

**Comment by xavierleroy** [comment]
> you need to stop the world, empty the minor heap, and reallocate the minor heap whenever you want to change the minor heap size or spawn (or shutdown) a domain

Like @kayceesrk I'm worried this would make spawning domains quite costly.  Plus, it's cost that cannot be parallelized ("stop the world")...

Is someone planning to implement my trivial proposal first?

**Comment by sadiqj** [comment]
Coming in a bit late to this PR but I think @xavierleroy 's suggestion is probably the one that will most likely perform well. It also has the property that we can keep the default max domains reasonably high and but it's still flexible enough to have valgrind and AFL run with some OCAMLRUNPARAMs.

As kc said, I'd be concerned with allocating `number_of_domains * minor_heap_size` and resizing on domain spawn/terminate. It may perform poorly at high core counts without us resorting to heuristics.

**Comment by ctk21** [comment]
+1 for @xavierleroy's suggestion. 

If pursuing more radical changes, Sandmark has HPC style benchmarks based on domainslib (for example [these](https://github.com/ocaml-bench/sandmark/tree/master/benchmarks/multicore-numerical)). We have used these benchmarks in the past to explore changes to the minor heap allocation scheme and domain lifecycle. It has been our experience that seemingly simple changes to the way domains allocate minor heaps can lead to meaningful performance differences at higher core counts (e.g. 32-256cores).

**Comment by sabine** [comment]
I'm looking into the simple proposal and will report back.

**Comment by jmid** [comment]
A default D that satisfies both a 4-core Raspberry Pi 4 and high-performance machines with 32-256cores will be hard to find IMHO, so some users will have to 
- run with OCAMLRUNPARAMs or 
- pay a bit of performance for stop-the-world gc'ing, freeing, and reallocating (rereserving).

A compromise could be to adapt @xavierleroy's proposal to set D to the number of available cores by default (perhaps multiplied by a factor 2 to leave a bit of headroom):
- default virtual memory reservation would be smaller on, say a 4-core Raspberry Pi 4
- multicore performance should not be too affected by looking the number up once at startup
- it will be less inconvenient, as fewer users across the spectrum would have to set OCAMLRUNPARAMs
  (thus satisfying @gasche's concern)

I do understand getting the number of available cores is a hassle, however with the feedback and pointers from @dbuenzli and @nojb it seems possible to get a first version running for the currently supported platforms (I know: easier said than done! 😅)

**Comment by sadiqj** [comment]
> A default D that satisfies both a 4-core Raspberry Pi 4 and high-performance machines with 32-256cores will be hard to find IMHO.

I'm not sure I understand why this is the case? If kept at 128 or 256 the only users that might need OCAMLRUNPARAMs are those using AFL or Valgrind and I don't see that as an issue. These are specialist tools, one of which already requires compiling with different flags.

**Comment by kayceesrk** [comment]
I don't think AFL's default virtual memory limit of 50MB gives us a lot of room to play with. It has options for setting virtual memory limit and `-m none` would remove this limit. This is already mentioned in the manual now. 

https://github.com/ocaml/ocaml/blob/ef0e05f645f6413c7299b8b38f40d3242091cf34/manual/src/cmds/afl-fuzz.etex#L71

**Comment by avsm** [comment]
If anyone wants access to a high core count machine (64+) for development, please drop me a line with an SSH key and I'll add you an account.

**Comment by lpw25** [comment]
I'm not sure I understand the concerns about stopping the world when adding new domains. Firstly, you can increase the minor area as required by doubling it each time, which limits how many STWs you could need. Secondly, I would expect that by far the most common pattern was to create an appropriate number of domains all at once near the start of the program, at which time there is only a single domain and so "stopping the world" is free.

**Comment by gasche** [comment]
@xavierleroy has a proposal ( https://github.com/ocaml/ocaml/issues/10971 ) that allows changing S (the size of each minor heap) and D (the "maximum number of domains") at runtime: when the current reserved area is not big enough for the new S*D value, free it and allocate a new one.

We can easily adapt this design to avoid having a "maximum number of domain". D is just the "currently reserved number of domains", and if we reach this limit when creating a new domain, just set (D = 2*D) and resize as appropriate.

Then we can easily support everyone by starting with D=1.

(We could have an API on the OCaml side to reserve several domains at once, to avoid having to resize several times in a row when spawning several domains for the first time.)

**Comment by hannesm** [comment]
FWIW, finding out the number of available cores as done in opam https://github.com/ocaml/opam/blob/2.1.2/src/core/opamSystem.ml#L775-L787

**Comment by xavierleroy** [comment]
> A default D that satisfies both a 4-core Raspberry Pi 4 and high-performance machines with 32-256cores will be hard to find IMHO.

As I wrote above, with S = 262144 words and D = 128, we reserve 256 Mbytes or virtual memory, or just 128 Mbytes on a 32-bit machine, so even the RPi 4 can reserve this.  If you then run valgrind or some other tool, the 256 / 128 Mbytes may have to be allocated in full, but that's still within range of a RPi.

Also, we can have different D defaults on 32-bit platforms (if we support them at all) and on 64-bit platforms, e.g. D = 4 in 32 bits and D = 256 in 64 bits.   Virtual memory space is a premium on 32-bit machines, but not on 64-bit machines.

I would rather not determine D at run-time based on the number of cores detected.  It adds complexity and nondeterminism (think of a CI job running on various VMs, not all of them offering the same number of cores).

**Comment by damiendoligez** [comment]
@xavierleroy 
>I would rather not determine D at run-time based on the number of cores detected. It adds complexity and nondeterminism (think of a CI job running on various VMs, not all of them offering the same number of cores).

I think @gasche's proposal is to automatically increase D when needed. If we do that, we can start with a rather small value.

I just realized that currently each domain can change its minor heap size independently. With your proposal all minor heaps must be resized together. Not sure if this is a problem.

**Comment by sabine** [comment]
Status update: Working towards the proposal by Xavier Leroy, we're at a point where

1. global variables `caml_max_domains` (d) and `caml_minor_heap_max_wsz` (s) haven been introduced.
2. All the arrays that used to be of size `Max_domains` are now allocated based on `caml_max_domains`.
3. Since we do not reserve extra virtual memory for the minor heaps beyond s anymore, setting d sufficienly low enables to run AFL without extra options, and Valgrind runs out of the box.
4. The test suite passes locally.

The next step is to implement `Gc.set` in such a fashion that it resizes the minor heap area to size d * s, in case d or s are changed by `Gc.set` by the only domain that exists.

Follow up steps:

1. have the runtime automatically increase max_domains and  resize the minor heap area when it runs out of domains at domain creation
2. enable `Gc.set` to change d and s when more than one domain exists.

I meet on Friday with @gasche for pair programming on this.

**Comment by damiendoligez** [comment]
I discussed this with Pierre Chambart yesterday, and he suggested that `max_domains` should be settable from `OCAMLRUNPARAM`. I think that would give a good balance between usability and complexity of implementation: no need for a complex stop-the-world protocol to resize the heap, good user control of address space consumption, ease of use on machines with a lot of cores.
In this case, it would be good to add a primitive for OCaml programs to get the value of `max_domains`.
