### ISSUE TITLE
Bootstrap problem when moving Cont_tag to be after No_scan_tag

### ISSUE THREAD

**Issue by ctk21** [ocaml/ocaml#11182]
As things stand, we tag pointers to stacks in continuation objects to avoid them getting entangled with the GC; however if `Cont_tag` were after `No_scan_tag` then it looks like we could avoid this (making various bits of assembler and C code simpler).

However in my attempt to move the tags around, I could not bootstrap the compiler using the instructions in [BOOTSTRAP.adoc](https://github.com/ocaml/ocaml/blob/949fdacd5f48d7a29c049d7f01590a95b1c3e090/BOOTSTRAP.adoc). The commit I was attempting to bootstrap is [here](https://github.com/ctk21/ocaml/commit/60b1200db5e3537d3f5a1e0d74bc4c70efc6c3d0); this commit shuffles the tags such that `Cont_tag` is after `No_scan_tag`. I tried stepping through the `make bootstrap` commands and the problem arises at the `$(MAKE) library-cross` point with:
```
../runtime/ocamlrun ../ocamlc -strict-sequence -absname -w +a-4-9-41-42-44-45-48-70 -g -warn-error +A -bin-annot -nostdlib -principal -safe-string -strict-formats  -nopervasives -c camlinternalFormatBasics.mli
```
This command causes a segmentation fault in `intern_alloc_obj`. I believe the problem is that the new runtime (with new tag conventions) is attempting to read a binary file produced with the old runtime (with old tag conventions).

I'm not exactly sure how to proceed to make the bootstrap work and so any advice on how best to achieve this would be welcome.

**Comment by dra27** [comment]
I’m fairly sure you’ll need an interim runtime with some slightly different intern/extern rules - I’ll try to have a look later if noone else gets there first!

**Comment by dra27** [comment]
I have a branch which manages this bootstrap (well, it takes 5 bootstraps + magic number bump), though with slightly different tag numbers:

| Tag | trunk | ctk21 | dra27  |
|-----| ----- | ------ | -------| 
| Obj.last_non_constant_data_constructor_tag | 243 | 243 | 242
| Forcing_tag | 244 | 244 | 244
| Cont_tag | 245 | 250 | 250
| Lazy_tag | 246 |  245 | 246
| Closure_tag | 247 | 246 | 243
| Object_tag | 248 | 247 | 245
| Infix_tag |249 |  248 | 247
| Forward_tag | 250 | 249 | 248
| No_scan_tag | 251 | 250 | 249

I believe all these invariants still need to hold:
- `Infix_tag`, `Forward_tag` and `No_scan_tag` need to be contiguous
- `Infix_tag` needs to be odd

The rough-and-ready commits to do this (repeatably) are at https://github.com/dra27/ocaml/commits/tagging. The tricks needed are to ensure that values which will be extern'd can be intern'd by both old and new runtimes (that allows `Object_tag` to be moved by exploiting that `Cont_tag` and `Object_tag` aren't used in the running of the compiler) and a temporary disabling of Lazy forwarding, because I couldn't find a way to build an ocamlc that could successfully work with two values of `Forward_tag`!

Assuming we're happy with this tag scheme, I'd be happy to write it up properly and do a PR for it. It's a shame that we lose _another_ data constructor which might be worth looking at, but assuming that `Infix_tag` must remain odd and `oldify_one` still needs the contiguity of those three tags, clearly `No_scan_tag` must go down by 2.

**Comment by gasche** [comment]
Where do the invariants come from? Do you have a pointer for why Infix_tag needs to be odd?

In 4.14 we had oldify_one in minor_gc.c <https://github.com/ocaml/ocaml/blob/4.14/runtime/minor_gc.c#L205-L269> that would check for three intervals: `(tag < Infix_tag)`, `(tag >= No_scan_tag)` and "the rest" `(Infix_tag <= tag < No_scan_tag)`, and it's important that the rest contain exactly cases that need special oldification logic (Infix_tag, Forward_tag, that's it).

In trunk, oldify_one [https://github.com/ocaml/ocaml/blob/146766c352f02967cb98de6f57477618ff5f7c6f/runtime/minor_gc.c#L251-L364](https://github.com/ocaml/ocaml/blob/146766c352f02967cb98de6f57477618ff5f7c6f/runtime/minor_gc.c#L251-L364&) handles `(tag == Infix_tag)` first, then splits into ranges `(tag == Cont_tag)`, `(tag < Infix_tag)`, `(tag >= No_scan_tag)` and then "the rest", which is `(Infix_tag < tag < No_scan_tag)`, which must be exactly `(tag == Forward_tag)`. (Note: maybe we could go slightly faster if Cont_tag was in fact included in "the rest", which is possible with either the ctk21 or dra27 schemes, if we used the ranges `(tag < Infix_tag)`, `(tag > Cont_tag)` and "the rest: , assuming that `Cont_tag` remains the very first no-scan-tag.)

**Comment by gasche** [comment]
Note: several places test for `(tag == Lazy_tag) || (tag == Forcing_tag)`, it may be nice to have them consecutive. For example it is in the common block path of `major_gc.c:mark_slice_darken`.

**Comment by gasche** [comment]
> Do you have a pointer for why Infix_tag needs to be odd?

https://github.com/ocaml/ocaml/blob/146766c352f02967cb98de6f57477618ff5f7c6f/runtime/caml/mlvalues.h#L232-L235

Another last-minute wish: it would also be nice if `Infix_tag` and `Closure_tag` were consecutive, to be able to test quickly if a value is a function.

**Comment by gasche** [comment]
To summarize, I think that a good mapping would be as follows:

| Tag | trunk | ctk21 | dra27  | gas42
|-----| ----- | ------ | -------| ---|
| Obj.last_non_constant_data_constructor_tag | 243 | 243 | 242 | 243
| Forcing_tag | 244 | 244 | 244 | 244
| Cont_tag | 245 | 250 | 250 | 250
| Lazy_tag | 246 |  245 | 246 | 245
| Closure_tag | 247 | 246 | 243 | 247
| Object_tag | 248 | 247 | 245 | 246
| Infix_tag |249 |  248 | 247 | 249
| Forward_tag | 250 | 249 | 248 | 248
| No_scan_tag | 251 | 250 | 249 | 250

We don't have Infix_tag and Closure_tag consecutive, oh well. We could still get a fast test with `Closure_tag <= tag <= Infix_tag`, assuming we know that `Forward_tag` is not possible.

**Comment by lthls** [comment]
I seem to remember that we considered removing `Infix_tag`, and using a single a single tag for lazy blocks (with the forcing/lazy/forward status encoded in a field of the block). Shouldn't these possibilities be taken into account too ?

Oh, and I'm not sure we even need `Infix_tag` to be odd anymore. The whole closure block used to be scanned, with some special handling for code pointers, so the infix headers and arity/closure_info fields needed to be tagged; but now that we don't even scan the non-environment parts of the closures, I think we could handle an even `Infix_tag` (and untagged arity fields, if we wanted to).

**Comment by gasche** [comment]
Three remarks:
- Actually we have more freedom wrt. `Infix_tag` in trunk: the runtime code must start by ruling it out and all other tests are done with Infix_tag excluded, so we could in fact pick any odd value strictly above `last_non_constant_constructor` and it would work.
- I'm not sure that `Infix_tag` could be even, for example `mark_stack_push` seems to assume that infix headers in the middle of the closure can be scanned for marking. ( [code](https://github.com/ocaml/ocaml/blob/146766c352f02967cb98de6f57477618ff5f7c6f/runtime/major_gc.c#L575) )
- With the tests for `(tag == Infix_tag)` and `(tag == Cont_tag)` first, the trunk minor GC code is less optimized than the 4.14 code, which covers all "normal" cases and all No_scan cases in just two tests, and deals with Infix_tag and Forward_tag in a third "cold path". All three non-trunk proposals above have (Cont_tag, Forward_tag, Infix_tag) consecutive in a way that would allow to go back to the 4.14 design (with Cont_tag in the cold path as well). However, I suppose that branch prediction makes the extra Infix_tag, Cont_tag checks very cheap fast in practice, as otherwise we would probably observe the difference in microbenchmark results.

**Comment by lthls** [comment]
> * I'm not sure that `Infix_tag` could be even, for example `mark_stack_push` seems to assume that infix headers in the middle of the closure can be scanned for marking. ( [code](https://github.com/ocaml/ocaml/blob/146766c352f02967cb98de6f57477618ff5f7c6f/runtime/major_gc.c#L575) )

As far as I can tell, the code that you pointed to:
- Asserts that it's not called on a block with tag `Infix_tag`
- In the `Closure_tag` case, skips the code pointers and infix headers using `Start_env_closinfo`

So I don't think this particular piece of code relies on the parity of `Infix_tag`. If I remember correctly, the whole reason why we added the `Start_env_closinfo` stuff was because in no-naked-pointers mode, we must never scan the code pointers. I'm relatively confident that it means we never scan the Infix headers either.

**Comment by dra27** [comment]
Sorry, yes the pointers for the invariants were those listed in `mlvalues.h` - by "believe" I meant that I hadn't yet gone to the effort of refuting them!

For `Cont_tag`, the primary purpose here is to subsume all the tests on `Cont_tag` into the test on `No_scan_tag` - that's what @ctk21 plans to do next (and can start, even based on the temporary commits I've done already).

> Another last-minute wish: it would also be nice if `Infix_tag` and `Closure_tag` were consecutive, to be able to test quickly if a value is a function.

`Infix_tag` can only occur inside `Closure_tag` blocks (it's mostly guarded by the alloc functions - `caml_alloc_shr` and `Alloc_small` themselves don't, but `caml_alloc` and `caml_alloc_small` both do) - where does this help (trying to follow your train of thought, rather than refuting it!)

In terms of what we want to do now:
- It'd definitely be useful to completely convince ourselves that `Infix_tag` no longer needs to be odd (and remove the comment from `mlvalues.h`!) as we definitely get to keep a tag.
- Ceasing to scan `Cont_tag` blocks is definitely going to simplify some hairy code and possibly improve performance on some fiber workloads, but the former is compelling reason in its own right. 
- If `Obj.last_non_constant_data_constructor` _does_ have to be changed, then we should definitely make this change in 5.0 (as `Obj.last_non_constant_data_constructor` is already changing for 5.0). If it's not changing, then perhaps the `Cont_tag` shift is not critical for 5.0 (but we may change our minds on that when we see simpler code!)
- The optimisations for lazy I think are covered by having `Lazy_tag` and `Forcing_tag` first - in the event of unifying the three tags into one, `Forward_tag` would presumably take on that role, and the two lowest tags would be released for users.

**Comment by gasche** [comment]
(Note: I think that having `Cont_tag` above `No_scan_tag` will only simplify away *some* `Cont_tag` checks, for example we still need the `caml_darken_cont` logic in the major GC which is different from all other `No_scan_tag` objects.)

@dra27 I wonder if you have opinions on my proposed mapping in https://github.com/ocaml/ocaml/issues/11182#issuecomment-1096738903, which I think satisfies your constraints without lowering `last_non_constant_constructor_tag`. Basically the trick is to have Forward_tag *below* Infix_tag rather than above, which allows to keep Infix_tag at 249 and No_scan_tag at 250.

On lazy (getting rid of Forcing_tag): I don't know that @gadmm has been able to work further on that, and I think that we will not have visibility on how/whether that works by 5.0.

**Comment by gadmm** [comment]
> On lazy (getting rid of Forcing_tag): I don't know that @gadmm has been able to work further on that, and I think that we will not have visibility on how/whether that works by 5.0.

The branch https://github.com/gadmm/ocaml-multicore/tree/sync_lazy is supposed to implement the forward/forcing status as a separate field. This looks simple enough to do and I remember that @lthls was looking forward to the simplifications it would bring.

I say "supposed" because after merging Gabriel's contribution, the implementation was supposed to be complete but there were some bootstrap issues, and I did not have the time to go back to it. I just tried to compile it again now, and it looks like that the issues are similar to those discussed here.

Unfortunately, I cannot really justify at the moment, at a scientific level, spending more time on it, with the current unclear status of the discussion about Lazy. Let me know if someone could help me with finishing the sync_lazy branch including sorting out this bootstrapping issues.

The sync_lazy branch adds a field to lazy blocks and removes the tags Forcing and Forward. It prepares for the polymorphic custom synchronization scheme described at https://github.com/ocaml-multicore/ocaml-multicore/issues/750 but this final step is not included. The sync_lazy branch is the minimal change for what @lthls wants.

**Comment by dra27** [comment]
@gasche - oops, I wasn't explicit in my previous comment, but I was meaning your scheme! What I hadn't properly taken in as that we could potentially have _both_ `Infix_tag` needing to be odd _and_ not losing a tag value by tweaking the GC not to need to worry about the ordering any more.

**Comment by dra27** [comment]
@gadmm - for the bootstrapping, there are two underlying principles[^1] when changing either the bytecode instructions or the value representation:
1. The old runtime and new runtime need to be capable of intern-ing and interp-ing both
2. `ocamlc` must be able to build run correctly on both the old and new **stdlib**+runtime

These principles are relaxed slightly by some tricks for "normal" bootstrapping: they are trivially satisfied by only adding or removing primitives when they are themselves already unused and the second is faked around by the use of `-use-prims` in the build system, but this is the reason for the need for an interim C function when _renaming_ a primitive.

For your proposed branch, I expect an adapted form of https://github.com/dra27/ocaml/commit/efbdc2f2f1b2adeae30dbc8ae841e67f504c4d3e may help - i.e. bootstrap a runtime which doesn't use Forward_tag any more - this should allow you to have a runtime which interprets values with that tag in your new representation but still allowing the old Lazy_tag and Forcing_tag to have their original meanings. Then after bootstrapping you can remove the Lazy_tag and Forcing_tag code.

[^1]: Assuming I've got the details of this properly clear in my mind from the exercise of having done this, I do intend to write it up properly to the bootstrapping guide

**Comment by gasche** [comment]
> `Infix_tag` can only occur inside `Closure_tag` blocks (it's mostly guarded by the alloc functions - `caml_alloc_shr` and `Alloc_small` themselves don't, but `caml_alloc` and `caml_alloc_small` both do) - where does this help (trying to follow your train of thought, rather than refuting it!)

Having `Infix_tag` and `Closure_tag` close together is a "nice to have", not a notable requirement. I didn't want to add noise to the conversation, but let's go for it for the love of low-level details.

It would allow for efficient testing of whether a value is a function (that is, has tag either `Infix_tag` or `Closure_tag`), which would allow to efficiently implement a trick used in Coq's native_compute machinery which needs sum/variant types which also contain functions. (See more discussion at https://github.com/coq/coq/pull/12733#issuecomment-674741700 ). Basically it would be useful to have a `is_closure : Obj.t -> bool` function that works on either Closure or Infix objects.

Having `Forward_tag` in between makes it possible to implement `is_closure` with a single range check if we assume that the value cannot be a lazy thunk -- which is reasonable because if lazy values are allowed at the callsites, they can have basically any tag instead Double_tag so you cannot distinguish them from others at runtime. The current layout has `Object_tag` in between, which makes for a weirder check `is_closure_or_object` fast check, that could of course also do well for many use-case (including Coq's I believe).

**Comment by gadmm** [comment]
> For your proposed branch, I expect an adapted form of https://github.com/dra27/ocaml/commit/efbdc2f2f1b2adeae30dbc8ae841e67f504c4d3e may help - i.e. bootstrap a runtime which doesn't use Forward_tag any more - this should allow you to have a runtime which interprets values with that tag in your new representation but still allowing the old Lazy_tag and Forcing_tag to have their original meanings. Then after bootstrapping you can remove the Lazy_tag and Forcing_tag code.

Thanks, it looks like an intermediate step of this kind could help.

**Comment by xavierleroy** [comment]
This discussion seems to be stuck, and the proposed reallocation of tag numbers can be done at any later point, so I'm removing this PR from the 5.0 milestone.  If any one of you is still interested, try to get a proposal ready in time for 5.1.
