### ISSUE TITLE
Toplevel : spurious type printer after redefinition 

### ISSUE THREAD

**Issue by paulpatault** [ocaml/ocaml#11286]
After entering the following statements in the OCaml toplevel:
```
# type t = A;;
type t = A
# type t = B;;
type t = B
# type t = C;;
type t = C
```
The types of A and B are both represented as `t/2`:
```
# A;;
- : t/2 = A
# B;;
- : t/2 = B
```
But (as expected) these values are not treated as if they were of the same type:
```
# A = B ;;
Error: This variant expression is expected to have type t/2
       There is no constructor B within type t/2
```

**Comment by Octachron** [comment]
The printing that you are quoting corresponds to the current specification for toplevel printing:

* printing should be local: 
      it should not depend on which type has been previously printed
* correctly printed code fragment should be copy-pastable
 
In particular, this means that
```ocaml
# type t = A;;
type t = B
let x = A;;
```
should be printed as
```ocaml
type t = B
val x : t/2 = A
```
because the type `t` of the constructor `A` does not match the type `t` in the environment at this point and thus copy-pasting the code without the `/2` part would lead to an error:
```ocaml
let x : t = A
```

Similarly since printing is local, the type `t/2` is not an unique identifier for the whole toplevel session but merely a marker that the type of `A` is another type `t` that the one currently in scope at this point of the REPL session.

**Comment by gasche** [comment]
I must say that the reported user trace also looks fairly confusing to me. Could we afford to relax our "locality" criterion, or does unspeakable implementation complexity lie this way?

**Comment by Octachron** [comment]
It would be possible to keep some memory for naming decision during the toplevel session (ever for the whole session or maybe just for few sentences?). I would expect that the worse increase in complexity would be in the `Printtyp` API rather than in the implementation itself.

**Comment by garrigue** [comment]
If we do that, I suggest we add a directive to reset the printing counters.
Otherwise, since it is quite common to redefine things in the toplevel, one would soon end up with lots of types with numbered names.

**Comment by gasche** [comment]
Thinking out loud: if we used for `t/n` the "shadowing depth" of that occurrence of `t`, I think the behavior would be local and less surprising. It would have the impact that introducing a new `t` changes the numbering of previous `t`, but this already happens (at least the t that was previously 0-shadowed, that is not shadowed at all, is now a `t/n` instead of `t`). This "shadowing depth" behavior may be less surprising than the current behavior -- certainly in this example.

**Comment by garrigue** [comment]
That's an interesting concept, but then you need to track where shadowing occurs. The order of ident numbering seems OK, so extracting everything in scope would suffice?

**Comment by gasche** [comment]
Another weird behavior that seems non-local this time (maybe this issue is not the best place to record such examples; would someone create a dedicated issue?):

```
OCaml version 5.0.0+dev4-2022-06-14
Enter #help;; for help.

# type 'a t = int * 'a u and 'a u = bool * 'a t;;
Error: The definition of t contains a cycle:
       int * 'a u
# type 'a t = int * 'a u and 'a u = bool * 'a t;;
Error: The definition of t contains a cycle:
       int * 'a u/2
# type 'a t = int * 'a u and 'a u = bool * 'a t;;
Error: The definition of t contains a cycle:
       int * 'a u/3
```
