### ISSUE TITLE
There is no implementation `caml_alloc_shr_with_profinfo` with WITH_PROFINFO

### ISSUE THREAD

**Issue by FardaleM** [ocaml/ocaml#11287]
When using `WITH_PROFINFO` which is activated with the option `--enable-reserved-header-bits=26` of `configure`, the symbol `caml_alloc_shr_with_profinfo` is declare in [`runtime/caml/memory.h`](https://github.com/ocaml/ocaml/blob/09ed8dfa28fd1d4a6576aac0ada6d1e0fde7a0e7/runtime/caml/memory.h#L38) but there is no implementation for it in `runtime/memory.c`. This function was define in 4.14.0 but is no longer there in trunk.

This function is currently not used in trunk. But this function is used by the [fork](https://github.com/let-def/ocaml/tree/tagl-413) from @let-def and I am trying to port it to OCaml 5.0.

**Comment by gasche** [comment]
As far as I understand, the 5.0 runtime removed those remnants of Spacetime support, and non-trivial changes would be required to recover WITH_PROFINFO support. (cc randomly @let-def, @Engil, @stedolan who may know otherwise; I also discussed this with @francoisthire in the contest of memory profiling.) This means that unfortunately you won't be able to easily port the fork, if my understanding is correct.

**Comment by FardaleM** [comment]
That was my understanding after our discussion. But porting the patch seems to work. I manage to make it compile, just the linker complains about this function. So it seems that most of it is still there. I opened this issue, because I found it weird to expose a function that does not exist. If there is interest, it could be added back or maybe it should be remove from the header file.

**Comment by dra27** [comment]
I think the principle of reserved header bits is still there (with the caveat that the header must remain immutable), so this probably is just a tweak in the headers. @FardaleM - do you have anything upstreamable from your port?

**Comment by NickBarnes** [comment]
I'm going to have a go at this, as my first OCaml hack.

**Comment by NickBarnes** [comment]
Note that PR #11872 does _not_ really "fix" this bug. See [my comment there](https://github.com/ocaml/ocaml/pull/11872#issuecomment-1373717269) for more details. Basically I think porting this part of the let-def fork to 5.0 is going to be more complicated than just hooking up some internal APIs.

**Comment by NickBarnes** [comment]
Looking at [this let-def branch](https://github.com/let-def/ocaml/tree/tagl-413), `caml_alloc_shr_with_profinfo()` appears only to be meaningfully used in `caml_alloc_with_profinfo()` in `runtime/alloc.c`, and this latter function does not appear to be used anywhere.

**Comment by NickBarnes** [comment]
Ah, thanks to @dra27 I now see (I think) what is going on here. `Config.profinfo_width` is used in the let-def branch, in `asmcomp/cmm_helpers.ml`, to calculate and manipulate block headers. This could be readily rewritten to match PR #11872, using `Config.reserved_header_bits`.

**Comment by NickBarnes** [comment]
Also `lambda/taglib.ml`

**Comment by FardaleM** [comment]
The port on 4.14 can be found here https://github.com/fardaleM/ocaml/tree/tagl-414 and the work on 5.00 can be found here https://github.com/fardaleM/ocaml/tree/tagl-trunk. The state is that it seems to work for 4.14, but I am definitely playing at the sorcerer's apprentice with this. From what I know, for 4.14, the port still needs to be adapted for the TMC optimization. For now, the optimization just drops the reserved bits. For 5.00 it seems that only this function was missing, but I am not sure.

**Comment by NickBarnes** [comment]
I see that, yes, the bits are being thrown away. That at least is fixed in PR #11872. However, this `tagl-trunk` branch uses these reserved bits via functions `Obj.set_profinfo` and `Obj.get_profinfo`. Disregarding the trivial point that those should be renamed (as it's not profiling info, as far as I can tell, and so in #11872 the bits are now called "reserved header bits"), I'm concerned about how `Obj.set_profinfo` might work (or fail) in the 5.0 memory model. That's beyond my pay-grade at present (paging @stedolan). It's used by `transl_const` in `bytecomp/symtable.ml`.

**Comment by NickBarnes** [comment]
In short, I hope this PR #11872 is a step in the right direction, reinstating and regularising reserved header bits, but I think that even with that PR this `tagl-trunk` branch is going to need some careful thought regarding the memory model.

**Comment by gasche** [comment]
(I'm surprised to know that there are interactions with Tail-Modulo-Cons, but I could possibly help on that part if you have specific questions. Let me know.)

**Comment by FardaleM** [comment]
@NickBarnes If I remember correctly, the "reserved header bits" are never set after the creation of the value. I don't know the memory model of OCaml 5.0, but I guess have only read operation should be simpler than read and write.

@gasche Tagl add information in the reserve bit to be able to implement a polymorphic print that only use the information contained at runtime. To be able to print the correct name of the constructor, this information is somehow stored in the header. That's why there is an interaction with Tail-Modulo-Cons. It's maybe easy to fix, I just don't understand the work of @let-def to be able to fix it. I will try to look into this again using the PR #11872 in a couple of weeks.

**Comment by gasche** [comment]
I see your tmc-related commit https://github.com/FardaleM/ocaml/commit/4325bcea801c7e12ab3cb5b1c9cbf517ffbeef29 . The commit is incorrect: you ignore the extra information on line 829, and then you make up "default" information in other places. Transformating a Pmakeblock call into another should preserve this information. To do thisyou should extend the triple `(tag, flag, shape)` into a quadruple to also store the extra information, and also add it as a field of the to the record `Constr.t` as well, so that it is available whenever you generate a Pmakeblock call.
