### ISSUE TITLE
On Ubuntu, configure fails with "flexlink does not work"

### ISSUE THREAD

**Issue by mbouaziz** [ocaml/ocaml#11292]
On my Ubuntu machine (21.04 then upgraded to 22.04, same result), `configure` of OCaml 4.13+ fails with `flexlink does not work`.

I bisected and found that 474255bb0e1265067bdd81bbf107f0027295be04 (#10135) by @dra27 introduced the failure.

I tried `--without-flexdll` (same error) and `--with-flexdll` (fails with `checking for flexdll sources... requested but not supported`).

I then renamed my `/usr/bin/flexlink` and `configure` finished successfully, even though its log contains
```
checking for flexdll sources... checking for flexlink... no
checking flexdll.h usability... no
checking flexdll.h presence... no
checking for flexdll.h... no
```

IIUC flexlink is supposed to be for Windows/Cygwin so I have no idea why it was present on my machine. But if ignoring it fixes the problem then ignoring it when it does not work could be a good idea?

**Comment by nojb** [comment]
~~Do you have anything inside the `flexdll` subdirectory of your repository? You shouldn't. If you do, deactivating the submodule with `git submodule deinit --force --all` should get rid of it.~~ EDIT: OK, rereading your explanation I see that the problem is that you have an executable called `flexlink` in your `PATH`. As mentioned, if this is Flexdll's `flexlink`, then it was a botched installation because it is useless on Unix systems.

Flexdll is only used or useful under Windows and should not appear in any way when building on Unix.

**Comment by mbouaziz** [comment]
Yeah I have no idea how I ended in that situation but it took me a while to understand it was due to a `flexlink` that I should never have had and that it was safe to get rid of `flexlink`.
( If it helps: `/usr/bin/flexlink` is a symlink to `/usr/lib/flexdll/flexdll.exe`. All files are from Oct 28 2017, 2 years before my machine existed :thinking:  )

If we want to do something useful from my experience either:
- add a message close to the failure to tell Unix users to get rid of `flexlink`
- or avoid doing anythink with `flexlink` on Unix systems

**Comment by dra27** [comment]
Were you configuring with straight `./configure` or with any other arguments (apart from trying `--without-flexdll`, etc.)?
