### ISSUE TITLE
ocamlc overwrites /dev/null

### ISSUE THREAD

**Issue by thierry-martinez** [ocaml/ocaml#11302]
If *root* runs the following commands:
```
# echo 'print_endline "Hello, world!"' >hello.ml
# ocamlopt -o /dev/null hello.ml
```
if `/dev/null` was initially the null block device, the latter remains unchanged by these commands; whereas if root runs the following command instead:
```
# ocamlc -o /dev/null hello.ml
```
then `/dev/null` becomes a regular file (the outcome of the compilation).

@marc-chevalier initially reported this is https://github.com/thierry-martinez/stdcompat/issues/18: I can (and will) fix this by using a workaround in `stdcompat`'s `./configure`, but I didn't expect `ocamlc` to have this behavior.

**Comment by nojb** [comment]
Thanks for the report. The problem stems from this line
https://github.com/ocaml/ocaml/blob/cbfa40a606354aba9aa81aefb5938d5c4b3982fe/bytecomp/bytelink.ml#L317
which _deletes_ `/dev/null` (if you have sufficient permissions) before writing the output. This deletion was added in order to address #8354 (output file is left with existing permissions if it already exists on disk), so this needs to be looked at to figure out what's the best workaround.

**Comment by nojb** [comment]
For comparison `gcc` sets the executable bit of the output file if it is a regular file that already exists, but _not_ in the case of `/dev/null`, which it leaves untouched.

**Comment by xavierleroy** [comment]
> For comparison gcc sets the executable bit of the output file if it is a regular file that already exists

This is a reasonable strategy, but we cannot implement it in ocamlc (currently) because the `Sys` portable interface doesn't give direct access to `stat` and to `chmod`, and I'd rather keep it this way.  The question, then, is to find a minimal extension to `Sys` (or perhaps to `Out_channel`) that does what we want.

Let's not rush a fix.  The "problem" has been with us since 2003, and sane users don't run compilers with superuser privileges.

**Comment by dra27** [comment]
In passing, #9787 proposed `caml_sys_chmod` as a primitive only (i.e. an external ocamlc could declare and use).

`caml_sys_is_directory` already uses `stat` for `Sys.is_directory` - would adding `caml_sys_is_regular` be OK? `Sys.is_regular_file` seems OK to add, and we could then keep the existing "delete if exists strategy" (which would avoid adding `caml_sys_chmod` and then pretending that it's not there in the stdlib)

**Comment by marc-chevalier** [comment]
I'm not saying what I was doing is sane (pretty much the opposite: fighting with a very non OCaml-friendly environment and build system), but there is now a common situation where we can expect users to run about anything as root: docker. Not saying it's a good idea, but the simple normal and common setup is to be root inside the container, as far as I know.

**Comment by dra27** [comment]
> there is now a common situation where we can expect users to run about anything as root: docker. Not saying it's a good idea, but the simple normal and common setup is to be root inside the container, as far as I know.

It certainly doesn't _need_ to be that way - _deploying_ in Docker as root is one thing, but using it as a development environment, one should create a non-privileged user in the normal way. cf. the opam images at [ocaml/opam](https://hub.docker.com/r/ocaml/opam) on Docker hub which all have an `opam` normal user.

**Comment by xavierleroy** [comment]
> `Sys.is_regular_file` seems OK to add,

Agreed.  I had a more complicated fix in mind, but here is a fix based on `Sys.is_regular_file`: #11412.

**Comment by xavierleroy** [comment]
For the record, the alternate solution I had in mind is here: https://github.com/xavierleroy/ocaml/commit/d89892266aac92c6ef99ede3a11fd291a77162e6 .  The good thing about this alternate solution is that the bytecode file generated by ocamlc is not executable until it's complete and ready for execution.  The not so good thing is that the final permissions are harder to predict.
