### ISSUE TITLE
"str.[i] <- c" is desugared into "String.set str i c" which does not exist anymore

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#11342]
Using the `5.0` branch (https://github.com/ocaml/ocaml/commit/f5d778a335c653da33c1c021a445fd910198089c), the following can be seen in the REPL:
```
# "x".[0] <- 'y';;
Error: Unbound value String.set
Hint: Did you mean get?
# (Bytes.create 1).[0] <- 'y';;
Error: Unbound value String.set
Hint: Did you mean get?
```

The first expression `"x".[0] <- 'y'` is desugared into `String.set "x" 0 'y'`, however `String.set` does not exist anymore since #10867. To me, this expression should raise a type error on `"x"` being `string` instead of the expected `bytes`.

The second expression `(Bytes.create 1).[0] <- 'y'` is desugared into `String.set (Bytes.create 1) 0 'y'`, however, once again, `String.set` does not exist anymore. To me this should instead desugar to `Bytes.set (Bytes.create 1) 0 'y'` which would be correct.

**Comment by nojb** [comment]
Indeed `s.[i] <- c` has always been a synonym of `String.set s i c`. After the removal of `String.set` one natural course of action would have been to also remove `s.[i] <- c`, given that they are synonyms. However, a better alternative could be to do what you suggest which is to redefine `s.[i] <- c` to be `Bytes.set s i c`. Since `String.set` does not exist anymore, we are not causing any extra breakage by redefining the infix operator. I'm in favour.

**Comment by nojb** [comment]
> Indeed `s.[i] <- c` has always been a synonym of `String.set s i c`. After the removal of `String.set` one natural course of action would have been to also remove `s.[i] <- c`, given that they are synonyms. However, a better alternative could be to do what you suggest which is to redefine `s.[i] <- c` to be `Bytes.set s i c`. Since `String.set` does not exist anymore, we are not causing any extra breakage by redefining the infix operator. I'm in favour.

One issue with going in this direction is that `s.[i]` continues to be a synonym for `String.get`, and it may be strange to have `s.[i]` and `s.[i] <- c` refer to two different types.

**Comment by xavierleroy** [comment]
> One issue with going in this direction is that s.[i] continues to be a synonym for String.get, and it may be strange to have s.[i] and s.[i] <- c refer to two different types.

Yes, this feels strange to me as well.  Removing the `.[ ] <-` notation altogether could be better.

**Comment by lthls** [comment]
> One issue with going in this direction is that `s.[i]` continues to be a synonym for `String.get`, and it may be strange to have `s.[i]` and `s.[i] <- c` refer to two different types.

This has already been the case for a while (`String.set` takes a `bytes` argument), so I don't think we should worry about that for 5.0.
As a long term solution, I would be in favour of evaluating whether `.[]<-` is still used or not and remove it if we can. We could also provide custom operators to compensate (`.![]` and `.![]<-`, for instance, either in `Bytes` or directly in `Stdlib`).

**Comment by Octachron** [comment]
I tend to agree that it is probably better to remove the syntactic sugar `.[ ]<-` rather than remap it to `Bytes.set`.

First, this avoids  the precedent of re-enabling a deprecated function (`.[ ]<-` has been deprecated since 4.02.3). 
Second, this also avoids adding an assignment operator `.[ ]<-` for Bytes without a matching indexing operator (`.[ ]`).

**Comment by nojb** [comment]
See #11345
