### ISSUE TITLE
Warning 23 is invoked for mutable record functional updates, even though it's the only(?) way to obtain a copy.

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml#11413]
```ocaml
type x = { mutable a : int }

let r0 = { a = 0 }
let r1 = {r0 with a = r0.a}
(*
Warning 23 [useless-record-with]: all the fields are explicitly listed in this record:
the 'with' clause is useless.
*)
let w0 = { a = 0 }
let w1 = w0

let _ =
  r0.a <- 1;
  w0.a <- 1;
  assert ((r0.a, r1.a) = (1, 0));
  assert ((w0.a, w1.a) = (1, 1));
  assert (r0 != r1);
  assert (w0 == w1)
```

**Comment by Octachron** [comment]
The `with` clause is indeed useless, removing it,
```ocaml
let r1 = { a = r0.a }
```
is shorter and strictly equivalent.

**Comment by hyphenrf** [comment]
silly me, thanks!

**Comment by dbuenzli** [comment]
> silly me, thanks!

Not necessarily. I often have types which start with a single field and would like to use `{ r with f = e}` so that the code still works when new fields are added. 

Basically having warning 23 enabled by default is like having the `fragile-match` warning enabled by default, but the latter is not. 

From the default warning set perspective I always found the current state of affairs to be rather inconsistent (that is in my opinion both should be enabled or disabled by default).
