### ISSUE TITLE
Bootstrap is broken in OCaml 5

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#11435]
This can be reproduced by running `tools/ci/inria/bootstrap/script` :
```
make -C tools make_opcodes
make[2]: Entering directory '/home/barsac/ci/builds/workspace/bootstrap/tools'
../boot/ocamlrun ../boot/ocamllex -q make_opcodes.mll
../boot/ocamlrun ../boot/ocamlc -nostdlib -I ../boot -g -use-prims ../runtime/primitives -I .. make_opcodes.ml -o make_opcodes
make[2]: Leaving directory '/home/barsac/ci/builds/workspace/bootstrap/tools'
./runtime/ocamlrun tools/make_opcodes -opcodes < runtime/caml/instruct.h > bytecomp/opcodes.ml
the file 'tools/make_opcodes' has not the right magic number: expected CI-bootstrap, got Caml1999X032
Makefile:1348: recipe for target 'bytecomp/opcodes.ml' failed
```

The invocation of `../boot/ocamlrun ../boot/ocamlc -use-prims ../runtime/primitives` produces a bytecode executable that is unusable: it has the format and magic numbers appropriate for `../boot/ocamlrun`, but expects the same primitives as `../runtime/ocamlrun`.

This used to work in earlier versions of OCaml probably because `bytecode/opcodes.ml` was not re-generated at this point during bootstrap.  Looks like too much cleaning goes on during bootstrap.

Cc: @shindere @dra27

**Comment by dra27** [comment]
I was slightly startled by this, as @Octachron successfully bumped the magic numbers when branching 5.0. It turns out the script should have been updated in #11149, so since that was merged the test has only been updating `runtime/caml/execinfo.h` and not `utils/config.cmo`. Sorry for that - one day I'll find a way to see the wood for the trees where the Jenkins notifications are concerned 😣

Fixed in 606abe802ba367af7e6842bfa192c308ffd385bd on trunk (which has already passed) and 90b70460667852c343682eb9c12aa91459a490eb on 5.0 (which is currently running).
