### ISSUE TITLE
ocamltest: syntax error in header causes test to be disconsidered

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#11513]
To reproduce, create a directory `testsuite/tests/tmp` and create a file there with the following contents:
```ocaml
(* TEST

* bytecode
exit_status = 0
*)

let () = ()
```

Then from the `testsuite` directory run: `make one DIR=tests/tmp`:
```
make : on entre dans le répertoire « /home/olivier/compiler/tsan/testsuite »
make[1] : on entre dans le répertoire « /home/olivier/compiler/tsan/testsuite/lib »
make[1] : on quitte le répertoire « /home/olivier/compiler/tsan/testsuite/lib »
make[1] : on entre dans le répertoire « /home/olivier/compiler/tsan/testsuite/tools »
make[1] : on quitte le répertoire « /home/olivier/compiler/tsan/testsuite/tools »
make[1] : on entre dans le répertoire « /home/olivier/compiler/tsan/testsuite »
make[1] : on quitte le répertoire « /home/olivier/compiler/tsan/testsuite »
make[1] : on entre dans le répertoire « /home/olivier/compiler/tsan/testsuite »


Summary:
    0 tests passed
    0 tests skipped
    0 tests failed
    0 tests not started (parent test skipped or failed)
    0 unexpected errors
    0 tests considered
make[1] : on quitte le répertoire « /home/olivier/compiler/tsan/testsuite »
make : on quitte le répertoire « /home/olivier/compiler/tsan/testsuite »
```
Removing the `exit_status` line makes the test being considered again.

**Comment by OlivierNicole** [comment]
Actually, adding quotes around the value (`exit_status = "0"`) fixes the problem. However, I find the silent dropping of the `.ml` file due to one syntax error confusing.

**Comment by shindere** [comment]
Olivier Nicole (2022/08/26 06:14 -0700):
> Actually, adding quotes around the value (`exit_status = "0"`) fixes
> the problem. However, I find the silent dropping of the `.ml` file due
> to one syntax error confusing.

It's make which does that, not ocamltest. You can always find the output
in the `_log` file, after you have run make. But as I said, running
ocamltest directly is IMO a better way to test tests.

**Comment by shindere** [comment]
You may have missed the message but ocamltest says:

```
Could not read test block in test.ml
```

The reason for that is that, unfortunately, ocamltest variables are not
typed. All of them need to be strings. So ocamltest does not understand
your definition of `exit_status` because you assign a number, rather
than a string.

If you change you change the variable definition so that it reads:

```
exit_status = "0"
```

you get this behaviour:

```
$ ocamltest/ocamltest.opt test.ml
 ... testing 'test.ml' with 1 (bytecode) => passed
```

which is, I assume, what you were expecting.

Note how it is possible to invoke ocamltest directly rather than through
make. When you want to run it on just one test file this may be simpler
and you will see the output directly. You can even use `-e` to see the
complete log on stderr.

I am going to close this issue but if you feel the need to, please, do
not hesitate to re-open it.

**Comment by OlivierNicole** [comment]
Thank you for the explanation, it makes sense.
