### ISSUE TITLE
Does OCaml 4.12.1+ no longer support MinGW static linking?

### ISSUE THREAD

**Issue by phated** [ocaml/ocaml#11531]
Sorry if this is a vague report. I've tried searching for days upon end and even opened an [OCaml Discuss](https://discuss.ocaml.org/t/does-ocaml-4-12-1-no-longer-support-mingw-static-linking/10411) thread to no avail.

In our project, we have been building binaries for Mac, Linux, and Windows. To do this on Windows, we need to use this dune stanza (sorry that I don't have the direct ocamlopt command):

```
(executable
 (name grainc)
 (public_name grainc)
 (package grain)
 (modules grainc)
 (modes exe)
 (flags
  (:standard -ccopt -- -ccopt -static))
 (libraries grain grain_diagnostics binaryen dune-build-info))
```

The important part are the `-ccopt -- -ccopt -static` flags, which statically links in the libraries provided through MinGW (this avoids our users needing to know about MinGW at all).

This currently works great on OCaml 4.12.0; however, if I try to upgrade to OCaml 4.12.1 or 4.13 or 4.14, our builds begin to fail.

Is this no longer supported by OCaml? Are we doing something blatantly wrong and should change to something else?

**Comment by gasche** [comment]
The only change in 4.12.1 that is listed in the Changelog and sounds potentially related is #10351, but it's a bugfix and it is unclear how it could break your build.

I don't know anything about Windows, but I think the following information could help:
- what version of MinGW are you using?
- what version of binutils do you have?
- what is the build error message that you are seeing?

To have a smaller repro case, you can start by looking at the dune build log (in `_build/log`); the last line before the failure should be the failing step (you can check by going inside `_build` and then executing the line), and it may be possible to devise a much smaller reproduction case by trying to adapt this line to work on a toy OCaml program.

**Comment by xavierleroy** [comment]
Also: check the version of `flexlink` on your system, it may be too old and in need of an upgrade.

But it could also be that #10351 broke static linking.  @dra27 should know.

**Comment by dra27** [comment]
I expect this was "broken" by #10351 (static linking has never been a formal thing for Windows OCaml, although "one day, I'd like it...." - pre-3.11 the DLL was required for bytecode, IIRC). In particular, Windows OCaml doesn't support configuration with `--disable-shared`, and #10351 can't be reliably turned off unless you can build with that (it's all to do with ASLR in binutils 2.36+ as noted in the PR).

Please could you post a build log with the error? I expect that the issue is applying `-static` across the board - it ought to be possible to link the external libraries you're using with a more precise linking specification (i.e. specifying exactly what should be being linked statically), but I'm just guessing without seeing either the actual command line or the error!

**Comment by phated** [comment]
@dra27 I ran a variety of builds in our CI and here is the error from OCaml 4.13.1 (which is reflective of each error we see):

```
(cd _build/default && D:\a\libbinaryen\libbinaryen\_opam\bin\ocamlopt.opt.exe -w -40 -ccopt -- -ccopt -static -g -o test/test.exe libbinaryen_c.cmxa -I . test/binaryen.cmxa -I test test/.test.eobjs/native/dune__exe__Test.cmx)
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: test/libbinaryen_stubs.a(binaryen_stubs_types.o): in function `caml_binaryen_type_none':
/cygdrive/d/a/libbinaryen/libbinaryen/_build/default/test/binaryen_stubs_types.c:33: undefined reference to `__imp_Caml_state'
/usr/lib/gcc/x86_64-w64-mingw32/11/../../../../x86_64-w64-mingw32/bin/ld: test/libbinaryen_stubs.a(binaryen_stubs_types.o): in function `alloc_BinaryenType':
/cygdrive/d/a/libbinaryen/libbinaryen/_build/default/test/binaryen_stubs_types.c:26: undefined reference to `__imp_caml_alloc_custom'
```

**Comment by dra27** [comment]
A small update - mainly to note that I haven't forgotten this 🙂 I just opened https://github.com/ocaml/flexdll/pull/106, which is part of removing the runtime requirement on both `libwinpthread-1.dll` and also `libgcc_s_seh-1.dll` in 5.0 (the latter of which had cheekily slipped in under the radar while we were tolerating `-lpthread` pulling in a DLL).

I anticipate that using `-l:libfoo.a` instead of `-lfoo` is going to be more robust for what you need here than trying to use `-static` (it would be fully backwards compatible with OCaml 4.x - you just need to be using flexlink 0.42 once it's released).

I'm being lazy (as opposed to grumpy!), but do you have step-by-step instructions for what you're doing for your Windows builds at the moment, or is it all buried in CI scripts? I'd be interested to see if `-l:` is enough for what you need as well. It was looking like I would need to address `-Wl,--whole-archive` for doing this, but it doesn't look like 5.0 will need that in the end, but I'm interested to see if your use-case might actually need it.[^1]

[^1]: `--whole-archive` is the C linker's equivalent of `-linkall` and becomes a bit more relevant when statically linking objects vs DLLs. It's one of these back-burner issues that something will eventually make critical (it pops up with the native toplevel as well)

**Comment by phated** [comment]
Very cool and thanks for the update! We've been using dune to put everything together, but I think I can get the direct ocaml commands if I dig into logs. Do you need the dune files or those commands?

**Comment by phated** [comment]
Also, it's interesting that you mention pthreads because the underlying C library we use depends on pthreads too.

**Comment by dra27** [comment]
Dune commands are fine - something along the lines of `git clone ... ; opam install ; dune build ...` will be great, thanks 🙂

The pthreads part could be even more intriguing from a 5.0 perspective! Are you already 5.0-ready?

**Comment by phated** [comment]
Perfect, I can provide those 😄 

1. git clone --recursive git@github.com:grain-lang/libbinaryen.git
> We have a submodule on Binaryen
2. git checkout phated/windows-static
> I made a branch that has the flags hardcoded in dune instead of relying on dune-configurator
3. opam install . --deps-only --with-test
> There's a depext on cmake but I think opam 2.1 just handles that?
4. opam exec -- dune build
> I believe it fails here because of the `-static` flag
5. opam exec -- dune runtest


Regarding OCaml 5.0, I'm not sure what is required relating to the C FFI. I haven't had time to look since we've been struggling to get to 4.14.

**Comment by phated** [comment]
@dra27 does the work in https://github.com/ocaml/ocaml/pull/11586 help with the issues experienced here?

**Comment by phated** [comment]
@dra27 I hope you don't mind me pinging you again, but ubuntu 22.04 is starting to roll out everywhere (CI, our users) now and they updated GCC to a version that won't compile OCaml 4.12.0, so having Windows static linking in a newer version of OCaml has become a much higher priority.

Is the remaining work to backport #11586 to the 4.x branches or do other fixes need to happen?

**Comment by phated** [comment]
@dra27 Checking if there is any way I can help on this! We're getting ever more frequent reports from users because we can't upgrade from 4.12.0 and that doesn't work on newer GCCs which are rolling out to all Linux distros.

**Comment by dra27** [comment]
Sorry for the silence on this one, @phated. FlexDLL 0.42 understands `-l:`, which means that you should be able to specify the libraries _individually_ as being linked statically. Does that help for now (I'm afraid I haven't had a chance to pull the repo and try it myself). It's not immediately clear to me which libraries are being pulled in as DLLs, but I expect that you want at least `-l:libpthread.a` (which avoids the pthreads DLL) and possibly `-static-libstdc++` (that might need passing as `-link -static-libstdc++` so that flexlink just passes it directly on to the linker)

**Comment by phated** [comment]
Does ocaml always use the latest FlexDLL or does that need to be backported?

**Comment by phated** [comment]
It looks like flexdll is a submodule for the project. @dra27  Should I submit a PR that updates it from 0.41 to 0.42?

**Comment by xavierleroy** [comment]
The upgrade to FlexDLL is tracked at #11817, and should address this issue, so allow me to (optimistically!) close the issue as (in the process of being) fixed.
