### ISSUE TITLE
testsuite fails with XCode14 on MacOS

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#11554]
The compiler test suite currently fails when using XCode14 due to following new warning

> ld: warning: -undefined dynamic_lookup may not work with chained fixups

which is emitted by the new version of ld64 as soon as `-undefined dynamic_lookup` is used.
It is not clear to me what is the workaround for this when building OCaml cmxs files.

**Comment by frou** [comment]
Seems like @carlocab drove the `-undefined dynamic_lookup` change in PR #10723. @carlocab do you have an idea what the issue here is?

**Comment by xavierleroy** [comment]
We're not alone: https://issues.guix.gnu.org/issue/57849 .

Looks like the only "solution" is to suppress all linker warnings (hmph) using `-Wl,-w`...

"Trop de warnings tue le warning", to quote @maranget 's wisdom.

**Comment by carlocab** [comment]
Sorry, I meant to reply earlier but my GitHub notification are overflowing.

Yes, this is happening to everyone using `-undefined dynamic_lookup`. Apple had deprecated this for iOS, so I guess they might be looking into doing the same on macOS as well.

Possible solutions/workarounds:
1. Suppress linker warnings as suggested above.
2. Stop using `-undefined dynamic_lookup`. If there are symbols you expect to be undefined, use `-Wl,-U,<symbol_name>`. This doesn't scale well, sadly.
3. (Speculative) Setting `MACOSX_DEPLOYMENT_TARGET` to an earlier version of macOS. My theory is that this will prevent the linker from trying to use chained fixups, since this is a new-ish feature in `dyld`.

This is new in Xcode 14, so I don't know a lot about this yet, but I'm looking into it and will report back when I know more. Feel free to ping me again as needed if I'm unresponsive.

A bit more background on chained fixups: https://www.wwdcnotes.com/notes/wwdc22/110362/

**Comment by carlocab** [comment]
An alternative to silencing all warnings or removing usage of `-undefined dynamic_lookup` might be to pass `-no_fixup_chains` (e.g. `-Wl,-no_fixup_chains`) to the linker.

This has a runtime cost, but the benefit from fixup chains is new so should not introduce any performance regressions compared to builds with older versions of Xcode.

**Comment by carlocab** [comment]
Related: https://github.com/python/cpython/issues/97524
