### ISSUE TITLE
Add an the equality witness type to the standard library

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#11564]
GADTs have now been part of OCaml for more than 10 years, and are even used inside the type-checker itself, but they are yet to make their way to the standard library.

While many GADTs are application-specific, and would have no reason to be there, the standard equality witness is used may GADT examples, and having to redefine it every time is cumbersome, and creates risks of conflicts.

So I suggest adding this single line, either in `Stdlib` itself, or in a specific submodule (`Eq.t` ?)

```ocaml
type (_,_) eq = Refl : ('a,'a) eq
```

**Comment by garrigue** [comment]
This is loosely related to #11484.

**Comment by nojb** [comment]
I'm in favor.

Putting it into a module may be better if we are planning to add more functions that act on this type. For example, this is what we have at LexiFi:

```ocaml
module TypEq : sig
  type (_, _) t = Eq: ('a, 'a) t

  val refl: ('a, 'a) t
  val trans: ('a, 'b) t -> ('b, 'c) t -> ('a, 'c) t
  val sym: ('a, 'b) t -> ('b, 'a) t
  val app: ('a, 'b) t -> 'a -> 'b

  module Lift(T : sig type 'a c end) : sig
    val eq: ('a, 'b) t -> ('a T.c, 'b T.c) t
  end
end
```

**Comment by yallop** [comment]
I need this quite often, so I'm in favour.  The type definition itself is the most important thing for compatibility, but it'd be good to have both the type (perhaps in `Stdlib`) and a module along the lines @nojb describes.

**Comment by dbuenzli** [comment]
Can we maybe pack the whole thing so that we get type identifiers on the way ? 

Most of my programs end up using them at some point, either directly or indirectly through a library.

[That's](https://github.com/b0-system/b0/blob/061eb173bcdf7ad49753b5c0323f040d03989695/src/std/b0_std.mli#L18-L34) the minimal interface I settled on. It seems [`base`](https://github.com/janestreet/base/blob/master/src/type_equal.mli#L183-L229) also has something similar.

**Comment by nojb** [comment]
> I need this quite often, so I'm in favour. The type definition itself is the most important thing for compatibility, but it'd be good to have both the type (perhaps in `Stdlib`) and a module along the lines @nojb describes.

Is there a good argument for having the type defined in `Stdlib` instead of in its own module?

**Comment by yallop** [comment]
> Is there a good argument for having the type defined in Stdlib instead of in its own module?

Such decisions always involve a judgment call, but to me @damiendoligez's [comment](https://github.com/ocaml/ocaml/pull/147#issuecomment-77888247) from the `result` PR perfectly apply here:
> Why it should go into pervasives: I don't want to close the debate, but let me state (what I think is) the current consensus: it's such a fundamental type that it's worth the trouble of putting it in Pervasives to strongly encourage compatibility and discourage incompatible redefinitions

That was a while ago, and there may be less appetite for extending `Stdlib` nowadays.  But in my view the equality GADT is so fundamental that if we're still adding types to `Stdlib`, that'd be the natural place for it.

**Comment by dbuenzli** [comment]
To give a bit more weight to my objection [here](https://github.com/ocaml/ocaml/pull/11581#issuecomment-1261361306). I think a `Type` module could be added. We could have for a start

```ocaml 
module Type : sig 
  type ('a, 'b) equal = Equal : ('a, 'a) equal
end
```
But that would leave room to later define, for example, the following submodules :

```ocaml 
module Type : sig 
  module Equal : sig
    (* More things along what @nojb suggested above  *)
  end

  module Id : sig
    (* Type identifiers. *)
  end

  module Repr : sig 
    (* One can dream… *)
  end
end
```

**Comment by yminsky** [comment]
I generally like @dbuenzli's proposed structure.

I just wanted to mention that the [Type_equal module in Base](https://github.com/janestreet/base/blob/master/src/type_equal.mli) is another source for prior art, to see what utilities might be useful for such a shared type. The Lift modules in particular are quite nice!

Note that in Base, we have Type_equal.t and Type_equal.Id.t. I think Type.Equal.t and Type.Id.t seems like a nicer way of organizing it.

**Comment by nojb** [comment]
From reading the discussion so far most opinions seem to be for one of the possibilities below. The advantage of 1) is that one can use `Type.Equal` as constructor name instead of the long-winded `Type.Equal.Equal`.

Please speak up if you are for, or against either of these. 1) seems an OK compromise to me.

1)
```ocaml
module Type : sig 
  type (_, _) equal = Equal : ('a, 'a) equal
  (* Could be added later:
  module Equal : sig
    type ('a, 'b) t = ('a, 'b) equal = Equal : ('a, 'a) t
    ...
  end
  *)
end
```
2)
```ocaml
module Type : sig
  module Equal : sig
    type (_, _) t = Equal : ('a, 'a) t
  end
end
```

**Comment by garrigue** [comment]
I have a feeling we are getting away from my original request.
I do think adding just the equality witness is already a major improvement.
If it is added directly as `Stdlib.eq` then it is easy to define operations in another module, like is done for lists, arrays, etc...
I don't really see what advantage we would get in putting it in a submodule, particularly if we don't intend to add anything else to that submodule.
Also I don't really see such a big advantage in adding functions to the standard library: everything can already be done by matching on the constructor, and if you want them you can always define them in one line.

As for the `Eq` vs. `Refl`, I don't really care. As I wrote, I used `Eq` until I came to see that other languages had converged to `Refl`, but this would not be the first time OCaml does things differently.
The only impact it might have is for add-on libraries who already define such a type: if they already use the same constructor name, they can choose to reexport the standard library one, otherwise they need conversions.

**Comment by dbuenzli** [comment]
> if we don't intend to add anything else to that submodule.

As far as I'm concerned I'd like to follow up with adding `Type.Id`. It's a good tool that is not complicated to use but rather convoluted to come up with for the average programmer (in which I include myself).

I think @nojb's 1) is fine. One thing to consider is if you want to call the type `Type.equality` (following Haskell's module name) or `Type.equal`, since that would also define the name of a possible subsequent module.

**Comment by alainfrisch** [comment]
> I don't really see what advantage we would get in putting it in a submodule, particularly if we don't intend to add anything else to that submodule.

`Stdlib.eq` is not self-explanatory (reading this type in a function's signature does not immediately convey the idea that this is about *type* equality).  Moreover, `Stdlib` is already a bit overcrowded; there should be a strong argument to put new stuff there; here, I don't see any downside of putting the definition in a dedicated submodule.

**Comment by nojb** [comment]
Leaving aside the question of future additions and extensions, can we agree on the minimal addition of a submodule?

```ocaml
module Type : sig
  type (_, _) eq = Eq : ('a, 'a) eq
end
```

Regarding the name of the constructor there have been three suggestions: `Refl`, `Eq`, and `Equal`.

- @garrigue has a preference for `Refl` due to the use of this name in other programming languages, but is open to `Eq`.
- @xavierleroy prefers to _avoid_ `Refl` as it is jargon.
- @alainfrisch also suggested `Equal` instead of the abbreviation `Eq`.

I am OK with either of the three, with a slight preference for `Eq`.

**Comment by dbuenzli** [comment]
I'm ok with your proposal but personally I would go with:

```ocaml 
module Type : sig 
   type (_, _) equality = Equal : ('a, 'a) equality
end
```

**Comment by dbuenzli** [comment]
@nojb any progress on this ? I'm ~~writing~~ cut and pasting my `nth` version of type identifiers, I would like in a few years to be able to delete all that code.

**Comment by nojb** [comment]
I was letting it stew :) Current version is over at #11581: a submodule `Stdlib.Type` with contents
```ocaml
type (_, _) eq = Equal: ('a, 'a) eq
```
But the entire PR is about naming choices; unless by some serendipitous circumstance @garrigue @yallop @alainfrisch @dbuenzli @xavierleroy were to come to some kind or consensus, am not sure there's a lot more that can be done to bring it to conclusion.

**Comment by dbuenzli** [comment]
https://github.com/ocaml/ocaml/pull/11581 has been merged. This can be closed.
