### ISSUE TITLE
Equality of identical variables is not optimized (flambda)

### ISSUE THREAD

**Issue by smuenzel** [ocaml/ocaml#11599]
The following function
``
let ss_same s = if s == s then 1 else 0
``
Does not compile to a constant when compiled with flambda and `-O3`. Similar functions/code snippets can be the result of inlining (which is where I've found this).
Indeed, flambda tries to remove comparisons between the same left- and right-hand-side (https://github.com/ocaml/ocaml/blob/dd5e82d079a0fd8c79fcbd622e26c4a3417c9031/middle_end/flambda/simplify_primitives.ml#L136), but this optimization only works when the values are the same global symbol, not for variables.

The issue comes from the `phys_equal` function in `Simplify_primitives`, which does not handle variables, and explains it with the following comment:
```
    (* N.B. The following would be incorrect if the variables are not
       bound in the environment:
       match a1.var, a2.var with
       | Some v1, Some v2 when Variable.equal v1 v2 -> true
       | _ -> ...
    *)
```
However, it is not clear to me why two values which alias to the same variable can become unequal, and what that has to do with them being bound.
Is the limitation still current? If not, I can write a patch to add the variable equality check. Otherwise, maybe we can extend the comment with an example of when the check fails. @mshinwell, I think you're the original author of this section of code.

**Comment by lthls** [comment]
I believe that `a.var` only tracks the original variable that the value was bound to. You could have other variables that are aliases to the original one, but defined in contexts where they can be lifted and statically allocated instead.
Example:
```ocaml
let f x =
  let t = [x] in
  match x with
  | None -> let t' = t in t == t'
  | Some _ -> false
```
Here `t'` is an alias for `t`, so the approximations in the arguments for the physical equality will both have a `.var` field pointing to `t`. But because `t'` is in a branch where `x` has a known value, it can be statically allocated to the constant `[None]`. So it's possible for the function to return `false` here (although I think the semantics of physical equality might allow us to return `true` in this case even if they're not actual aliases).

I suspect that the comment refers to another kind of issue, I'll try to find out what it was (it might take a few weeks, feel free to ping again if I forget).

**Comment by smuenzel** [comment]
Thanks. I played around a little bit with your example, and I wasn't able to provoke the compiler into statically allocating a constant (even this code wont do it: ``match x with None -> [ x ] | Some _ -> ..``).

> I suspect that the comment refers to another kind of issue, I'll try to find out what it was (it might take a few weeks, feel free to ping again if I forget).

Yeah, it sounds like it, since the simplification to physical equality -> true is expected by the user and consistent with the semantics of physical equality in the cases we explored so far.

Regarding the approximation, the comment in simple_value_approx.mli says:
```
    If the variable (resp. symbol) is present then that variable (resp.
    symbol) may be used to obtain the value [v].
```
If we can always obtain the same `v`, then the semantics of physical equality are satisfied.

- In case of a mutable block, if it's the same `v`, mutations will be visible in all approximations.
- In case of a non-mutable block, optimizations may mean it is not exactly the same memory address (if the optimization you described happens), but we still meet the condition `e1 == e2` implies `compare e1 e2 = 0`, which is sufficient.

PS. It just occurred to me that the definition of `==` in the manual is written in a way to permit both the optimization proposed here, and the statically allocated constant optimization you are talking about. I imagine this was done on purpose?

**Comment by lthls** [comment]
So I've talked with @chambart about this issue, and it looks like one of the main reasons for disabling this optimisation is linked to records of floats. If we have the following code:
```ocaml
let v = Random.float 1. in
let p = { x = v; y = v; } in
p.x == p.y
```
In that case, flambda will transform the code into `v == v`, so it would be fine to optimise. But if `v` wasn't in scope then `p.x` and `p.y` would each allocate a different boxed float, so the equality wouldn't hold.
Building a case where `v` isn't in scope but the approximations still refer to it isn't trivial; in theory something like ` let v = let v0 = Random.float 1. in v0 in ...`would work, but in practice the simplification passes in flambda will translate this back to a linear form.
I'll try to look harder for a real counter-example when I have some more time.

Regarding the semantics of physical equality, I think the manual was written in a way to allow the compiler to share or not share immutable blocks as it wishes. I don't know if any other optimisations were considered (that was way before any work on Flambda).
But even though it looks like it would be ok to simplify `x == y` to `true` when we know that they are structurally equal and immutable, it is still problematic because it makes `(==)` look like a non-pure function.
For instance, building on my previous example (assuming `v` is not actually in scope):
```ocaml
let f x =
  let v = x +. 1. in
  let p = { x = v; y = v; } in
  let {x; y } = p in
  (x, y, x == y)
[@@inline never]

let g () =
  let x, y, b = f 0. in
  assert (b = (x == y));
```
If we did the simplification, then the assertion would fail. It could be argued that this is still allowed given the specification of `(==)`, but this might also break things somewhere (for example with hash tables on addresses, compared by physical equality).

There might be an argument for adding a flag, off by default, that would trigger the optimisation. But I'd be wary of turning it on by default.

**Comment by smuenzel** [comment]
That's a good point about floats, they do have a tendency to cause problems everywhere.

However, I think that for this particular optimization, we're simply preserving existing behaviour of `phys_equal`/`==` around floats.
In particular, because `==` can already observe the effects of float boxing decisions, we can provoke both `true` and `false` return values depending on optimizer decisions (this is with the current optimizer, without my proposed change).
For example (I'm using core and expect tests for simplicity here -- `phys_equal = (==)`):
```ocaml
open! Core

let[@inline never] twice_never x = 2.0 *. x
let[@inline always] twice_always x = 2.0 *. x

let%expect_test "twice" =
  let x = 1.0 in
  let y = 0.5 in
  print_s [%sexp (phys_equal x (2.0 *. y) : bool)];
  [%expect {|
    true |}];
  print_s [%sexp (phys_equal x (twice_never y) : bool)];
  [%expect {|
    false |}];
  print_s [%sexp (phys_equal x (twice_always y) : bool)];
  [%expect {|
    true |}]

```
In this code, an identical function produces a different result depending  on if it's inlined. I'm simulating the effect of different optimizations by manually annotating the function, but we can even do this without annotations by hiding the function from the optimizer:

```ocaml
let func = ref (fun _ -> assert false)

let init =
  if Sys.opaque_identity true
  then func := twice_always

let%expect_test "twice_always" =
  let x = 1.0 in
  let y = 0.5 in
  print_s [%sexp (phys_equal x (twice_always y) : bool)];
  [%expect {| true |}];
  print_s [%sexp (phys_equal x (!func y) : bool )];
  [%expect {| false |}]

```
We can probably also provoke this depending on other factors as well (varying inlining depth, cross-module inlining enabled, etc).


So maybe if only floats are causing the problem, then this optimization is still fine?

**Comment by smuenzel** [comment]
I've prepared a patch here:
https://github.com/ocaml/ocaml/compare/trunk...smuenzel:equality-of-identical-variables
I tried to document the consequences of the optimization in both the manual and the in the code.

Any objections to trying to get this merged?

**Comment by lthls** [comment]
My example was pointing out that if you allow the optimisation as it is, you can get cases where you have two values `x` and `y`, and at one point `x == y` evaluates to `true`, and at another point to `false`. This means that `==` is not a pure function anymore, and will mess with code that expects that purity, typically hash tables. You could end up in situations where `let () = Hashtbl.add tbl key v in Hashtbl.find tbl key` would throw an exception instead of returning `v`.
So I do object to this being on by default.

**Comment by smuenzel** [comment]
Yes, I understood. My point was that in the presence of float unboxing, `==` is not pure.

In the current version of ocaml (with flambda), you can recreate the problematic situation with the hashtbl you gave.
I made an example of an alist below.

```ocaml
open! Core

let (==) = Stdlib.(==)

(* Let's build an alist for floats, using a set of buckets for some specific floats *)
let alist_buckets = List.map ~f:(fun x -> x, ref []) [ 2.0; 1.0; 0.5 ]

(* We can add values to the alist *)
let add ~key ~data =
  List.iter
    ~f:(fun (v', bucket) -> if key == v' then bucket := data :: !bucket) alist_buckets

(* and find them again *)
let find v =
  List.find alist_buckets ~f:(fun (x, _) -> x == v)
  |> Option.map ~f:snd
  |> Option.map ~f:(fun x -> !x)

let print () =
  print_s [%sexp (alist_buckets : (float * string list ref) list)]

type store_for_later = { mutable key_to_store : float }

let%expect_test "alist" =
  (* Right now, we're empty *)
  print ();
  [%expect {|
    ((2 ()) (1 ()) (0.5 ())) |}];
  (* Let's add a value *)
  let my_key = 1.0 in
  add ~key:my_key ~data:"first add";
  print ();
  (* Our value got added! *)
  [%expect {|
    ((2 ()) (1 ("first add")) (0.5 ())) |}];
  (* and we can find it *)
  print_s [%sexp (find my_key : string list option)];
  [%expect {|
    (("first add")) |}];
  (* Let's store it for later *)
  let for_later = { key_to_store = my_key } in
  (* And let's use our stored value to find the data again *)
  print_s [%sexp (find for_later.key_to_store : string list option)];
  (* Our value is lost!! *)
  [%expect {|
    () |}];
  (* Our key is no longer equal to the original key *)
  print_s [%sexp (for_later.key_to_store == my_key : bool)];
  [%expect {|
    false |}];
  print_s [%message ""
      (Float.compare for_later.key_to_store my_key : int)
      (Int64.bits_of_float my_key : Int64.Hex.t)
      (Int64.bits_of_float for_later.key_to_store : Int64.Hex.t)
  ];
  (* But the bit pattern is the same, and compare = 0 *)
  [%expect {|
    (("Float.compare for_later.key_to_store my_key" 0)
     ("Int64.bits_of_float my_key" 0x3ff0000000000000)
     ("Int64.bits_of_float for_later.key_to_store" 0x3ff0000000000000)) |}];
  ()

```
