### ISSUE TITLE
Incorrect help message for --force-instrumented-runtime configure option

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#11655]
Running `./configure --help` says:
```
  --force-instrumented-runtime
                          force the usage of the instrumented runtime
```
but using the option errors with “unrecognized option”. The flag that actually works is `--enable-force-instrumented-runtime`, which is probably not what we want. I’m not sure how to modify `configure.ac` to fix this, but maybe @shindere will know.

**Comment by dra27** [comment]
This option came in as part of multicore with the aim that it causes the normal runtime to be the instrumented runtime. The option does have to be of the form `--enable-foo` (autoconf) so either we live with the strange name or possibly call it something which reflects that (e.g. `--enable-instrumented-runtime-as-default` or some such).

It's definitely a developer option, though - how useful is it still (@Engil, @sadiqj ?)

**Comment by shindere** [comment]
Out of curiosity, what exactly happens when this option is selected? Is
instrumentation added to the default runtime and so it becomes identical
to the instrumented runtime, or is the non-instrumentd runtime not even
build and the instrumented runtime is built and used as the default
runtime, or something different?

**Comment by abbysmal** [comment]
@dra27 This option is not required anymore (as of Eventring). It was used during Multicore's development to have a simple Sandmark workflow, since it required linking against the instrumented runtime.
I do not quite recall the details, it would still build all the runtimes, but swap the default runtime for the instrumented one when linking the programs.
My memory is hazy on the "how", but the why makes it clear we should remove it.
I will submit a PR soon.

**Comment by abbysmal** [comment]
(hopefully this answers your questions as well, @shindere)

**Comment by shindere** [comment]
Enguerrand (2022/10/24 05:43 -0700):
> (hopefully this answers your questions as well, @shindere)

It does yes. Thanks!

**Comment by Octachron** [comment]
I am closing the issue since the configuration has been removed for now.
