### ISSUE TITLE
Inconsistent treatment of partially applied functions in the recursive-value check

### ISSUE THREAD

**Issue by goldfirere** [ocaml/ocaml#11674]
This was discovered by reading the source code, not because I actually got caught in practice, so feel free to ignore.

I was surprised that the recursive-value check understands skipped arguments but not partial application. For example, the following program is accepted:

```ocaml
exception Undef

let f x ~y z = raise Undef

let rec x = f ~y:[x]
```

Despite the fact that the RHS of the recursive value is a function application, OCaml knows that the first argument to `f` was skipped and that therefore `x` will be a closure, easily allocated.

On the other hand, this is rejected:

```ocaml
let rec x = f [x]
```

The error is

```
Error: This kind of expression is not allowed as right-hand side of `let rec'
```

I would think these two cases would be handled identically.

**Comment by Octachron** [comment]
Skipping an argument with a labelled function is an explicit partial application whereas the second example is a regular function call which might be partial application or not.

I am not sure why an explicit partial application and a function call should be handled identically?

**Comment by gasche** [comment]
My own justification for the behavior is that when type-checking `f ~y:[x]`, the type of `f` suffices to determine, by the operational semantics of labelled argument, that this is actually a lambda-abstraction that will block reduction: if `f` has type `... -> y:'a -> 'b`, then we will abstract over everything non-labelled in the `...` before applying `y`.

On the other hand, to know whether `f x` may compute and dereference `x` or not you have to look not just at the type of `f`, but its body as well: a value of type `'a -> 'b -> 'c` may or may not start computing when passed its first argument. So the property of blocking computation is "local" or "known by typing" in the first case, and the rec-checker (that operates on the typed tree) has access to it, but non-local in the second case (it would require a static analysis).

Another way to think of it: if we had n-ary functions (as say F# under the hood), we would know for sure in some cases that we have a partial application. We don't, but we have labelled functions, and labelled work a bit like n-ary functions (... with everything more complex).

**Comment by yallop** [comment]
Related:
- [let-rec wellformedness check is more restrictive than expected (#7767)](https://github.com/ocaml/ocaml/issues/7767)
- [Fix Mantis PR#7767: interaction between labels and let rec check #1712 ](https://github.com/ocaml/ocaml/pull/1712)

**Comment by gasche** [comment]
According to the git history, this specific handling of partial applications introduced by labelled arguments was introduced fairly recently in 741ceef97c1978afb3427049f8d14ded464b47f2, to implement the user suggestion #7767.

The example proposed by the user in that issue is as follows:

```ocaml
type prog = Seq of prog list | Exp of string;;
let concat_map xs ~f = List.map f xs |> List.concat;;
let rec concat_prog = concat_map ~f:(function Seq xs -> concat_prog xs | x -> [x]);;
```

The user (Ivan Gotovchits develops [bap](https://github.com/BinaryAnalysisPlatform/bap)) suggests that the redesign of the value-let-rec check in #556 broke their existing code (in bap). Before #556, the value-rec-check was performed on the Lambda implementation, not on the typedtree. Desugaring of labelled applications into abstractions is performed when moving from typedtree to lambda, so on the lambda-abstraction it is obvious that this is safe. I suppose that accepting the program above was never an explicit design choice of the original value-let-rec, but a user-observable consequence of its implementation approach, that we had to replicate in the new check because users now rely on it.

**Comment by goldfirere** [comment]
Thanks for these responses. I'm completely persuaded by @gasche's https://github.com/ocaml/ocaml/issues/11674#issuecomment-1293645102. I will close.
