### ISSUE TITLE
[multicore] does Hashtbl respect separation?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11681]
I say that a data structure "is separated" or "respects separation" if operations on logically-disjoint parts of the structure are data-race free. (More formally, if the ownership of sub-parts of the structure obeys the expected separation-logic equation: `S[A \uplus B] = S[A] \star S[B]`.) For example, OCaml arrays are separated: two domains can read and write at different positions in the array without any need for synchronization. This justifies having, for example, a global array indexed by domain identifiers, or more generally by distinct domain-local indices.

Question 1: Is `Hashtbl.t` separated?

(For example, if each domain has a unique identifier, can we safely use a global hash table of values indexed over these unique identifiers, without locking?)

My intuition is that it is not: when you add a binding for a given key in a hash table, this may cause a global rebalancing of the data-structure that conflicts with other reads and writes, even at different keys.

Question 2: could we make `Hashtbl.t` separated, or would that have an important performance cost?
(Is this a sensibly simpler problem than having a "concurrent hashtable" that is well-behaved even on same-key operations?)

My intuition: ideally it would be enough to have a per-table lock and take it when resizing the bucket array. But I'm afraid that bucket mutations would also need to be made atomic, meaning some atomic access in the common case -- and I we don't have a compact implementation of arrays-of-atomics in the stdlib, as far as I know.

Question 3: should we document "separation"?

My understanding is that the in-progress PRs on documenting concurrency-safety document in #11193 that Hashtbl cannot be used concurrently, and in #11237 that Arrays can safely be used concurrently, which in particular implies that they are separated. (Hashtbl could be separated and yet be unsafe for concurrent usage due to same-key races, but currently I suspect it is neither so there is not much more to specify.)

**Comment by stedolan** [comment]
I like this idea in principle - from a memory-model point of view, you'd say that a `'a Hashtbl.t` is semantically a `'a ref` per key (well, a `'a list ref` because of the weird multiple-binding semantics of `Hashtbl`, but let's ignore that). This is a semantics that's weaker than a standard concurrent hashtable, because you're still allowing weak effects on individual entries, and not imposing particular ordering requirements between domains accessing distinct entries.

In practice, though, I can't see how to implement this any more efficiently than a full concurrent hashtable, at which point we may as well just provide that: weak semantics are only worthwhile if they're fast. In particular, do you have any ideas how we might solve these two problems in a way that profits from the "separation" property (and is therefore cheaper than full atomicity):

  1. When two domains race to add distinct keys (neither already present), there is a chance that they keys are hashed to the same bucket, and both domains attempt to insert the keys into the same place.
  2. When one domain tries to mutate an existing key while another domain is resizing the table, there is a chance that the mutation is lost because only the old version of the table is mutated, not the new resized version.

To me, issue (1) sounds like the array of buckets needs to be an atomic array so that we can CAS on allocating a new bucket, while (2) sounds like all mutations must synchronise somehow with whatever mechanism is used to synchronise resizes. At that point, we're not far off the overhead of a full concurrent hashtable. Do you have ideas for how some of the overhead could be less with the weaker semantics?

> we don't have a compact implementation of arrays-of-atomics in the stdlib, as far as I know.

This does seem like something we should fix!

**Comment by gasche** [comment]
Indeed, resizes are the problem because they affect all buckets at once, so they break separation. I don't know how to do this without reader-writer locks, but I thought I would ask anyway. It is infuriating because we expect resizes to be a very uncommon operation. Dynamic arrays have the same problem.

(Note: this "separation" property sounds very natural, but I don't know much about concurrent programming and haven't heard of it before. Do people know how it is usually called?)

**Comment by DemiMarie** [comment]
What about guaranteeing that replacing keys _already in the table_ respects separation, so long as there are no concurrent resizes?  The same would work for dynamic arrays: it is safe to operate on different elements of the array concurrently so long as nobody is changing the array size.

**Comment by gasche** [comment]
@DemiMarie makes a good point: if we can statically reason about the fact that mutators only act on keys that are already in the structure (no resize necessary) then we get separation for hashtables and dynamic arrays. This may actually be enough for some workflows.

Unfortunately, most potential use-cases I would have in mind involve adding new keys/indices from time to time, and I don't see a way to make this idea of "separation" work in practice in this context. I'm closing the issue.

**Comment by UnixJunkie** [comment]
@gasche having a hash table whose maximum expected size is known at creation time doesn't shock me.
This hash table implementation, not allowing resizing, could still be useful in many cases.

If we are looking at simplifying things even more for a memory-safe and thread-safe hash table, I have never been a fan of the remembering previous bindings "feature".

**Comment by gasche** [comment]
Well, if you are motivated to implement a non-resizing hashtable library, I think that could be a good idea.
There are design choices:
- you could fail with an error when reaching more elements than expected
- or you could just have longer collision buckets, degrading performance
- maybe you want balanced-tree maps instead of linear linked lists for the buckets to better accumulate this crowded scenario

One could implement a concurrent hashtable as a non-resizing hashtable with atomic balanced-tree maps for the buckets, and benchmark this against the obvious approach of a standard hashtable with a mutex. I would be curious to look at the performance comparison.

**Comment by kayceesrk** [comment]
An add-only non-resizing hash table is quite handy for parallel dynamic programming. See Section 3 of https://oa.upm.es/11119/1/HERME_A_2010-1.pdf.

**Comment by UnixJunkie** [comment]
- I would obviously choose the simplest scenario: if you try adding to an already full ht, you get an exception.
- Having worked on a distributed system in the past, I also think deleting something should not be allowed.
Since you don't know who and when something will try to access a binding that is supposed to be there.
