### ISSUE TITLE
module type syntax

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml#11690]
It seems like I can write a module type in lower cases, or in upper cases, and it works. It also seems like the manual shows an all uppercase syntax when using module types: https://v2.ocaml.org/manual/moduleexamples.html

should this be enforced by the compiler?

**Comment by dra27** [comment]
The syntax aims to be as liberal as possible, while remaining possible to parse (see the table in https://v2.ocaml.org/manual/names.html) - what do we gain constraining it more than it needs to be?

**Comment by mimoo** [comment]
Homogeneity. If every codebase looks different then it'll be hard to work with OCaml.

**Comment by Octachron** [comment]
Personally, I prefer lower-cased names for module types (`Monoid:monoid`) rather than the screaming-cased variant (`Monoid:MONOID`).

Anyway, as a general language evolution criterion, we don't break backward compatibility if we can avoid it.

Since this feature wish only proposes to break backward compatibility, it is in direct conflict with this policy.

If you have arguments, don't hesitate to expose them in this issue, I will re-open it if the proposal may cross the `wont-fix` threshold.

**Comment by mimoo** [comment]
I guess there really needs to be an official linter for ocaml (like clippy) that can do this work
