### ISSUE TITLE
Large amount of no-op spill-reload in some programs

### ISSUE THREAD

**Issue by Ekdohibs** [ocaml/ocaml#11695]
Consider the following program:
```ocaml
let test a b c d e f g h i j k l m =
  let cnt = ref 0 in
  let a = ref a in
  let b = ref b in
  let c = ref c in
  let d = ref d in
  let e = ref e in
  let f = ref f in
  let g = ref g in
  let h = ref h in
  let i = ref i in
  let j = ref j in
  let k = ref k in
  let l = ref l in
  let m = ref m in
  while !cnt <> 100 do
    cnt := !cnt + !a + !b + !c + !d + !e + !f + !g + !h + !i + !j + !k + !l + !m
  done;
  !a + !cnt
```
When compiled with `ocamlopt spill.ml -c -S` (tested with 4.12.0, 4.14.0 and 5.0.0~alpha1), we get assembly code containing the following large number of reloads immediately followed by a spill to the same location, where the reloaded variable is unused:
```
	movq	(%rsp), %rax
	movq	%rax, (%rsp)
	movq	8(%rsp), %rax
	movq	%rax, 8(%rsp)
	movq	16(%rsp), %rax
	movq	%rax, 16(%rsp)
	movq	24(%rsp), %rax
	movq	%rax, 24(%rsp)
	movq	32(%rsp), %rax
	movq	%rax, 32(%rsp)
	movq	40(%rsp), %rax
	movq	%rax, 40(%rsp)
	movq	48(%rsp), %rax
	movq	%rax, 48(%rsp)
	movq	56(%rsp), %rax
	movq	%rax, 56(%rsp)
	movq	64(%rsp), %rax
	movq	%rax, 64(%rsp)
	movq	72(%rsp), %rax
	movq	%rax, 72(%rsp)
	movq	80(%rsp), %rax
	movq	%rax, 80(%rsp)
	movq	88(%rsp), %rax
	movq	%rax, 88(%rsp)
```

Interestingly, removing the single variable `m` makes all these spill-reload pairs disappear, and almost no variable is spilled anymore, with each variable using a different register; whereas with it, almost all variables are spilled and loaded each loop iteration. This is probably unrelated to the unneeded spill-reload problem, but explains why there are as many variables in the above example.

The strange behaviour of the register allocator sub-optimally using the registers with a large number of variables is probably difficult to fix, but the useless spill-reloads look like a bug to me.

**Comment by nojb** [comment]
Just after insertion of reloading code, the generated code looks like:
```
  ...
  a/100[%rax] := spilled-a/99[s0] (reload)
  a/47[%rax] := a/100[%rax]
  spilled-a/85[s0] := a/47[%rax] (spill)
  b/101[%rax] := spilled-b/98[s1] (reload)
  b/48[%rax] := b/101[%rax]
  spilled-b/84[s1] := b/48[%rax] (spill)
  ...
```
which "makes sense" (eg the reloaded `a/100` is used in the assignment `a/47 := a/100`). But then the moves between identical registers are (correctly) removed, which leaves some useless reloads in place.

**Comment by lthls** [comment]
I observe that on this particular example, turning off the superpressure feature in `Spill` gives a much more reasonable output.

I wonder if we should completely remove it, or at least decrease the estimated pressure generated by move instructions (which are likely to reuse an existing register).

Independently, we could also try to remove redundant spills or reloads at some point, though I'm not sure when (I would do it in `Linearize`, but it may be better to introduce a separate pass).

**Comment by xavierleroy** [comment]
I still don't fully understand what's going on with this example.  However, excluding "move" instructions from the "superpressure" heuristic sounds like a good idea.  I still believe the heuristic is useful for "normal" instructions, i.e. those that need a fresh register to store their results.

**Comment by lthls** [comment]
I did a few small experiments this week-end. I tested the example from this PR and also checked the assembly code generated for `typecore.ml` to see the effect on normal OCaml programs (with a very small sample).

First, the trunk version. For `typecore.ml`, trunk is the reference so there isn't anything to say. For the example here though, `Selection` generates code containing a number of "rotating" moves: sequences where all live registers are moved to a new register. This includes the initial copy from argument registers to local registers, but there are also other occurrences later. And so on each move the pressure forces us to spill the earliest live register, and with so many moves all registers end up spilled, so the result is not great.

My next experiment was to disable the superpressure feature and let the register allocation deal with it. This is what gave me the best result on the example from the PR, with only a few registers spilled, but on `typecore.ml` I get strictly worse results (not that much, as in regular code the superpressure feature isn't used very often anyway, but there's definitely no improvement).

Then I tried to disable superpressure around moves (setting `Proc.safe_register_pressure` to `max_int` for moves). This felt a bit too ad-hoc, and indeed it didn't help that much on the example from the PR as the additions still forced many different registers to be spilled, but curiously it did remove two move instructions in `typecore.ml`.

Finally, I tried a clever trick where I remember not only which registers were spilled, but also which were live during a superpressure spilling but not spilled, and used that information to prefer registers that were not in this set. Although it is the most heavy change in terms of code as I need to change the result type of `Spill.reload`, in terms of algorithm all it changes is which register is spilled first during superpressure. It does give a nice improvement in the example from this PR, though still a bit worse than the version with superpressure disabled. And it gives exactly the same result as trunk on `typecore.ml`.

Since there isn't any obvious solution and this issue is not critical, I'll let it rest for now. I can make my code available if someone wants to look at it.

**Comment by gasche** [comment]
> Since there isn't any obvious solution and this issue is not critical, I'll let it rest for now. I can make my code available if someone wants to look at it.

The issue is about to be forgotten for eternity, and I think that making the code available would be a prudent step before that.

**Comment by lthls** [comment]
I'm not sure I still have it. If I can find it again I'll push it to a branch on my fork and post a link.
