### ISSUE TITLE
let exception with <handler> in <body>

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11720]
### Context

A recommended approach to emulate `break` or `continue` in a loop is to use exceptions for local control flow:

```ocaml
let exception Break in
try while <cond> do
  ... raise Break ...
done with Break -> ()

while <cond> do
  let exception Continue in
  try
    ... raise Continue ...
  with Continue -> ()
done
```

Here we use not only exceptions but locally-declared exceptions. This makes sense given that (1) the local-exception syntax was introduced with optimizations-into-local-control-flow analyses in mind, and (2) declaring custom exceptions instead of reusing `Exit` is more readable and extends gracefully to the case where we want to return values when breaking.

```ocaml
let exception Found of int in
try
  while <cond> do
    ... raise (Found i) ...
  done; None
with Found i -> Some i
```

### Proposal

We could make this pattern lighter by merging the local-exception declaration and the single handler:

```ocaml
let exception <decl>
with <handler>
in <body>
````

as syntactic sugar for

```ocaml
let exception <decl> in
try <body>
with <handler>
```

Full examples:

```ocaml
let exception Break
with Break -> () in
while <cond> do
  ... raise Break ...
done

while <cond> do
  let exception Continue
  with Continue -> () in
  ... raise Continue ...
done

let exception Found of int
with Found i -> Some i in
while <cond> do
  ... raise (Found i) ...
done; None
```

**Comment by jhjourdan** [comment]
I'm not a fan. The syntax is not shorter than the current alternative, but the order of subexpressions is not the right one: we expect the handler to be after the code that raises the exception.

**Comment by glondu** [comment]
I agree with @jhjourdan about the order of subexpressions.

**Comment by gasche** [comment]
Actually I like the new order in these examples, because it gives the semantics for the exception right away -- by the point you see `raise Found` you already know what its seemantics is. (In fact I believe that having such an order for effect handlers would also be nice.) If people prefer the "regular" order, they can of course use the existing `try .. with ..` construct.

**Comment by dbuenzli** [comment]
The discussion about order looks a bit like a discussion between proponents and opponents of (Haskell) `where` clauses. 

As a matter of personal preference I prefer when identifiers are defined before they are used and thus find myself rather against them. But here it is about control flow order and I think I would tend to find it more natural and easier to grasp to have all possible outcomes packed at the end of the loop.

More pragmatically, from a reading point of view, adding this would mean that as the reader of a `raise` in a loop, I now have to check two different possible locations to understand what happens, depending on the *preference* of the writer. Is that a language improvement ?

**Comment by gasche** [comment]
We already have this order-inversion phenomenon with `Fun.protect`, where you define the "final logic" before the computation that will be finalized, and in that case people generally agree that it actually improves clarity and readability, because it lets you define the initialization and finalization logic (or acquisition and release) for a given resource close together. My intuition is similar here, we introduce a local name for control-flow and explain away its behavior at the same place.

A concrete example of using this feature to collect "unit clauses" in a toy implementation of a SAT solver. (Clauses are arrays of literals understood disjunctively, `L1 \/ L2 \/ ... \/ Ln`, and a literal `Li` is "unit" if it is the only "not yet decided" (unset) literal in the clause, and all set literals are False -- if one is True, then the clause is True and not undecided.)

```ocaml
let unit_clauses (cnf : cnf) v : lit list =
  Array.fold_right (fun clause units ->
    let nb_unset = ref 0 in
    let unset = ref (Lit 0) in
    let exception NoUnit
    with NoUnit -> units in
      for i = 0 to Array.length clauses - 1 do
        let lit = clause.(!i) in
        match Valuation.get v lit with
        | False -> ()
        | True -> raise NoUnit
        | Unset ->
          incr nb_unset;
          if !nb_unset >= 2 then raise NoUnit;
          unset := lit;
      done;
      !unset :: units
  ) cnf.clauses []
```

**Comment by lthls** [comment]
I find it disappointing that the proposal is only for syntactic sugar. I would have preferred if this introduced more constraints (like enforcing that the handler matches the exception being defined), and ideally come with an optimisation that transforms this into a static exception when possible (and a warning when it can't), in the spirit of #260 and #638.

If you don't have any additional optimisations, then I don't see what's the benefit of this proposal compared to these versions:
```ocaml
(* Regular syntax *)
let exception Break in
let break () = () in
try while <cond> do
  ... raise Break ...
done
with Break -> break ()

(* Or with a hypothetical ppx,
   expanding to the code above *)
let%local_exception break () = () in
while <cond> do
  ... raise Break ...
done
```

**Comment by dbuenzli** [comment]
> We already have this order-inversion phenomenon with `Fun.protect`, where you define the "final logic" before the computation that will be finalized,

I'm not disputing this. You also have it with `let*` operators in general. 

However your answer doesn't address the language usability point I mention. My feeling is that the (learning and reading) costs of the new syntax you propose on users  largely trumps its benefit.

**Comment by gasche** [comment]
(@lthls I'm interested in working on optimizations of exceptions for local control flow eventually, but I think that those do not need to be coupled to the specific syntax used, so they can be discussed separately. I actually like this separation of concerns.)

**Comment by lthls** [comment]
> I actually like this separation of concerns.

I don't mind separating the discussion, but I'm opposed to implementing them separately. The optimisation will need at least attributes to control activation and warnings anyway, so I don't think we can avoid syntax issues in the optimisation work.
Even for discussing the syntax only, I think you would find people more open-minded if you sell this as a new feature rather than syntactic sugar.

Anyway, on the choice between putting the handler before or after the body, we already have examples for both.
The `try ... with` syntax put the handler after, and the `[@local]` transformation puts the handler before. So my opinion is that if we want to advertise the feature as a regular try-with that happens to be optimised, I would prefer keeping the order consistent with `try ... with`, but if we want to advertise it as a more general version of the `[@local]` optimisation then putting the handler before, as you propose, is coherent.

On the actual syntax itself, as I mentioned I don't like the duplication between the exception declaration and the handler definition, but I accept that it's hard to work around that if you want to allow the code to be compiled using regular exceptions.
Here are two variants of your original proposal:
```ocaml
(* Function syntax *)
let fun exception break () = () in
while <cond> do
  ... break () ...
done

let fun exception found i = Some i in
while <cond> do
  ... found i ...
done; None

(* Exception syntax *)
let fun exception Break = () in
while <cond> do
  ... raise Break ...
done

let fun exception Found of int = fun i -> Some i in
while <cond> do
  ... raise (Found i) ...
done; None
```
Apart from the debatable choice of keywords, the function version allows us to infer the types of the parameters but makes it hard to distinguish regular functions from static exceptions in the rest of the code. The exception version is clearer, and makes it possible to compile the code using regular exceptions as a fallback. This could be particularly important for code where the optimisation is only possible after inlining.
Example:
```ocaml
let array_find (type a) (p : a -> bool) (arr : a Array.t) : (int * a) option =
  let fun exception Found of int * a =
    (* Note: the tuple below doesn't correspond to a real tuple,
       but to the arguments of the constructor.
       Adopting a curried-style syntax might be better to avoid confusion.
       The original approach of duplicating the constructor name also
       resolves the ambiguity. *)
    fun (idx, v) = Some (idx, v)
  in
  (Array.iteri[@inlined])
    ((fun idx v -> if p v then raise (Found (idx, v)))[@inline])
    arr;
  None
```
This example cannot be compiled to a static exception in bytecode, but if we have a fallback then one could use different flags between `ocamlc` and `ocamlopt` so that only `ocamlopt` would warn (or error) if the fallback was used.

**Comment by alan-j-hu** [comment]
> The discussion about order looks a bit like a discussion between proponents and opponents of (Haskell) `where` clauses.

In his essay [Learnable Programming](http://worrydream.com/LearnableProgramming/), Bret Victor criticizes the C-style for loop syntax for being unintuitive for beginners because the order of expressions in the syntax does not reflect their order of evaluation:

> This is a particularly difficult example for a beginner to follow. The "for" construct, with its three statements on a single line, makes the control flow jump around bizarrely, and is an unnecessarily steep introduction to the concept of looping.

I think the same guideline applies here. Haskell is a non-strict and purely functional language, so its syntax can afford a more declarative style and still be intuitive. For example, all Haskell bindings are implicitly in a let rec, so you can write the definitions that give the high-level operations of the program at the top and write the helper definitions used by the high-level definitions lower down in the file. This is also why `where` clauses look nice in Haskell. In contrast, OCaml is a strict and imperative language, so if binding Y uses binding X, the definition of X must be evaluated before the definition of Y. Because of side effects, it is more intuitive to require X to be defined before Y syntactically, as you can easily tell the order of side effects by reading the source code from top to bottom. Because hypothetical `where` clauses in OCaml would evaluate the definitions at the bottom before evaluating the definition at the top, I don't think `where` clauses would be intuitive in OCaml. For the same reason, I don't think the exception handler clause should go at the top.

> We already have this order-inversion phenomenon with `Fun.protect`, where you define the "final logic" before the computation that will be finalized, and in that case people generally agree that it actually improves clarity and readability, because it lets you define the initialization and finalization logic (or acquisition and release) for a given resource close together. My intuition is similar here, we introduce a local name for control-flow and explain away its behavior at the same place.

For what it's worth, when I use `Fun.protect`, I use labeled arguments to put the cleanup callback after the body, a la Java's `finally`.

Knuth's essay [Structured Programming with `go to` Statements](https://pic.plover.com/knuth-GOTO.pdf) mentions a control structure proposed by a C. T. Zahn similar to what is proposed here, and in Knuth's essay, the handler comes at the end. Maybe Knuth's essay could provide some inspiration.

**Comment by gasche** [comment]
Okay, okay, closing :-)
