### ISSUE TITLE
Complete file paths is lost in errors when building `otherlibs/unix`

### ISSUE THREAD

**Issue by MisterDA** [ocaml/ocaml#11747]
I've noticed that when the C compilers errors while building a file in `otherlibs/unix`, it errors without printing the whole path relative to OCaml source root, but relatively to `otherlibs/unix`. That can be confusing, it makes it more difficult to locate the file (although it is one call to `find` away). I suspect this might have happen during the merge of unix and win32unix if that wasn't the historical behaviour. We're likely chdir'ing into `otherlibs/unix`. Could it be possible to build everything relatively to the source root?

This is an example of an error message:

```
fork.c: In function 'caml_atfork_child':
fork.c:31:6: error: old-style function definition [-Werror=old-style-definition]
   31 | void caml_atfork_child() {
      |      ^~~~~~~~~~~~~~~~~
```

**Comment by MisterDA** [comment]
pfff this is too much nitpicking it's clear from the previous commands where we're located.
cc-ing @shindere just in case

**Comment by shindere** [comment]
I don't think it's nitpicking -- many thanks for the report!

I think what you report is independent of the `unix/win32unix` merge and
things worked in a similar way before. The cause is rather, as you
explain, the fact that during the build we constantly change directory
to the directory where the file we are compiling lives. I think one
consequence of merging the makefiles will be that we will stop changing
directories and, indeed, build everything from the toplevel of the
source directory.

One other thing is that there may be a gcc option to request that
absolute paths are printed, no matter which was the current directory
from which gcc was called. It may make sense to use such an option since
it is what the OCaml compiler does already. We could even imagne a way
to have these options synchronized, i.e. a configure option that
controls whether paths should be printed in a absolute way or not, both
by the C and OCaml compilers.
