### ISSUE TITLE
List.max and List.sum

### ISSUE THREAD

**Issue by glsscnnn** [ocaml/ocaml#11785]
why these not exist they seem pretty obvious to have, but don't exist in ocaml for some reason and would be p trivial to add is there any reason why not exist?

**Comment by nojb** [comment]
For `sum` it is a one-liner: `let sum l = List.fold_left (+) 0 l`, so am not sure it is worth it. `max` may be more interesting (which signature?).

In general, if your favourite function is not in the standard library, it is due to no one having done a concrete proposal and pushed the contribution through. PRs in this direction are always welcome (but they may not always end up getting merged if no consensus can be reached).

**Comment by nojb** [comment]
See https://github.com/ocaml/ocaml/blob/trunk/stdlib/CONTRIBUTING.md for more information on the process of contributing to the standard library.

**Comment by Octachron** [comment]
The max function is a sum in disguise as soon as the type of interest has a minimal element:
```ocaml
let max = List.fold_left max Int.min_int
```

Moreover, any version of `sum` that works with any monoid will require the users to define the neutral element and the addition function
```ocaml
val sum: ('a -> 'a -> 'a) -> 'a -> 'a list -> 'a
```
which is mostly equivalent in term of complexity to a `fold`.

Contrarily, it might make sense to have a `List.max` function which is directly defined from the `compare` function
```ocaml
val max: ('a -> 'a -> int) -> 'a list -> 'a option
```
A quick look shows that both `base` and `batteries` have a similar function.

**Comment by xavierleroy** [comment]
There are 5 types of numbers in the standard library (int, float, int32, int64, nativeint) and more in external libraries (big integers, big rationals, ...).  There's no reason to have a `List.sum` function that is specific to one of these types and doesn't apply to others.

Likewise, beyond lists, there's arrays, sets, ..., that could all benefit from a `sum` function.

The OCaml solution is that each container defines a "fold" operation, each numerical type defines a "plus" and a "zero", and the "sum" operation you're after is "fold plus zero".

For min and max, as @Octachron notes, folds also work, but you have to decide what happens when the list or the collection is empty.  One more reason for not defining this in the standard library.

I move to close this feature wish.

**Comment by glsscnnn** [comment]
Sure I understand why may not be able to have `sum` function

But for min / max functions not sure I understand, the `max` and `min` function already exist just not on containers, can not decide what happens when the list is empty there's many options for what to do? Does ocaml not have standard why of handling something like this? if other functions exist in stdlib what happens when they receive input like this, does it throw error return none return 0 what do other functions in stdlib I don't see why couldn't decide how to handle empty list.

**Comment by kayceesrk** [comment]
@glsscnnn I suggest that this discussion be moved to [discuss.ocaml.org](https://discuss.ocaml.org).
