### ISSUE TITLE
Data race in codefrag.c when marshalling closures in parallel

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#11791]
Running the test [`lib-marshal/intext_par.ml`](https://github.com/ocaml/ocaml/blob/944baa06e3d24056e0c536e8594246407ed9679d/testsuite/tests/lib-marshal/intext_par.ml) with ThreadSanitizer warns of several data races in the code handling code fragments, which seem triggered by the parallel marshalling of closures. For example, the function `caml_digest_of_code_fragment` seems to be called concurrently on the same fragment.
[Full ThreadSanitizer report](https://gist.github.com/OlivierNicole/811c97712db9d66a7cf5bc62602364df)

**Comment by gasche** [comment]
I looked at this out of curiosity (but this is something that @xavierleroy knows well and can probably fix easily). Below is an explanation of what is going on and some potential approaches to fix the race.

- Code fragments have a digest (a hash of the code) that is used for marshalling code pointers within this fragment (unmarshalling a code pointer works by finding a code fragment of the same digest already in memory, and pointing to the same offset in this pre-existing fragment).
- When registering a new code fragment, it is possible to compute its digest right away or to ask that the digest be computed "later", that is when marshalling one of its code pointers or when unmarshalling any code pointer. (In debug mode, marshalling a code pointer also forces the digest computation for all fragments.)
- In fact this DIGEST_LATER mode is the default; it is used by (nat)dynlink and by the native compiler; in contrast, (only) the bytecode compiler eagerly computes the digest of it main bytecode segment.
- If two domains try to get the digest of a code fragment that is in DIGEST_LATER mode, we may have a write/read or write/write race (to the fields `status` or `digest`).

Potential fixes:
1. Drop the DIGEST_LATER mode and always compute code fragment digests eagerly. This is the simplest approach but it may cause a performance regression on all programs. My expectation would be that this is very fast on today's machines, and will remain super fast if we move to a better digst algorithm.
2. Use a mutex per code fragment, to be taken whenever reading or updating the digest of the fragment.
3. Use a global mutex to protect all the digests of all the code fragments. This is slightly less code, it adds more contention, but it may in fact be faster when unmarshalling a code pointer forces the computation of all code fragments (we can take the lock only once).
4. Make the fields `cf->digest` and `cf->status` atomic. In some rare scenarios, the digest of a code fragment may be computed several times by domain forcing it in parallel.
5. Make the field `cf->status` atomic, but still use a per-fragment mutex to guarantee that force-force races only compute the fragment digest once.

I would try solution (2) which is simple and probably performs very well in practice. But an expert may know whether the even-simpler (1) is also a sensible choice.

**Comment by gasche** [comment]
I proposed two PRs to implement approaches (1) and (2):

- #11795
- #11796

**Comment by xavierleroy** [comment]
This is the prototypical benign race: two threads can race but will produce the exact same result in the end.  

There was a similar issue with file descriptors in the Win32 Unix library that was nicely fixed recently.  Let me find the PR...

**Comment by xavierleroy** [comment]
Here is the PR in question: #11304

**Comment by xavierleroy** [comment]
Hashing twice should occur pretty rarely, so the overhead of hashing twice can be tolerated, I think.  In which case approach (4) might work just fine.

**Comment by gasche** [comment]
@xavierleroy writing the code of #11796 let me confirm to myself that the mutex (in solution 2) is limited strictly to the find-the-digest function, no other codefrag operation is affected. (Allocation and deallocation get slightly more work to do.) The version of (4) you propose would thus, at best, make this function slightly faster, at the code of arguably more complexity (atomics accesses instead of the good old mutex, and possibly a SPIN_WAIT loop with a new "waiting" status for mutual exclusion). Are you reasonably sure that this is a good tradeoff? If "yes", I don't mind writing a third PR going that way.

**Comment by gasche** [comment]
In a new branch [codefrag-mutex-atomic-status](https://github.com/gasche/ocaml/tree/codefrag-mutex-atomic-status) ([compare/diff](https://github.com/ocaml/ocaml/compare/trunk...gasche:ocaml:codefrag-mutex-atomic-status)), I use a hybrid solution with an atomic `digest_status` field, and a mutex to guarantee (I think?) that threads block each other instead of duplicating the hashing computation (without busy spinning, say no to busy spinning!).

Compared to #11796, I suppose that finding a code fragment becomes slightly faster in the common case because we perform an atomic read-acquire instead of taking a mutex, but the code is substantially more complex. In my opinion, #11796 is better.

I am unsure about the proposal to just use two atomics and let threads race to compute the digest. (Also, the digest is currently an array inline in the structure, I'm not sure how to make that atomic.) In theory racing on digest computation is rare because it can only happens once per fragment. But some fragments may be very large (typically the initial native code fragment), so the repeated computation could be important. (For example, a large actor-based program that would immediately start message-passing across domains in parallel, marshalling closures along the way.)

**Comment by xavierleroy** [comment]
I'm OK with the approach in #11796 (basic locking), as I don't expect the code to be performance-critical, nor the mutexes to be heavily contended.

The variant in https://github.com/gasche/ocaml/tree/codefrag-mutex-atomic-status is a case of [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking), which made me suspicious at first, but should be OK because you're using SC atomic variables.  (If you're tempted to relax the atomics, the Wikipedia page above outlines a correct implementation with release and aquire.)  Performance should be excellent.

> Also, the digest is currently an array inline in the structure, I'm not sure how to make that atomic.

Not quite sure either.  There's a high risk that the compiler reintroduces a lock around the array, which would be silly.

**Comment by gasche** [comment]
> The variant in https://github.com/gasche/ocaml/tree/codefrag-mutex-atomic-status is a case of [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking), which made me suspicious at first, but should be OK because you're using SC atomic variables. (If you're tempted to relax the atomics, the Wikipedia page above outlines a correct implementation with release and aquire.)

Actually the codefrag-mutex-atomic-status uses acquire/release (I only used SC for the initializing write where we don't care about performance at all), in a way that turns out to be slightly stronger than what Wikipedia uses (I used a load-acquire twice, once before and once after the load, where Wikipedia does a relaxed load once holding the mutex), so it might be correct, phew!

I would still be rather in favor of the "basic locking" approach of #11796 unless we believe the performance is problematic (the cost is to lock the mutex on each read), I think that we can spend our complexity budget somewhere else.
