### ISSUE TITLE
Give access to fdset (or there simulation on windows)

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#11807]
Building and reading the list of sockets is time and code consuming. It would be simpler in many cases if
unix module exposed the fdset data type.

**Comment by dra27** [comment]
I started off thinking you meant being able to cache the fdset between calls to `Unix.select` i.e. we'd add `val fdset_of_fds : file_descr list -> fdset` and a variant of `select` which takes `fdset` instead of `file_descr list`. However, re-reading it, are you meaning that we effectively expose `FD_ZERO`, `FD_SET` and `FD_ISSET` in the Unix module i.e. we'd add `type fdset` and operations like `val add_to_fdset : fdset -> file_descr -> unit`?

The former seems possible, but sounds like a micro-optimisation, and the latter sounds incredibly hairy to get right on the Windows side - how much simpler do you feel the code would look?

**Comment by nojb** [comment]
The API underlying `Unix.select` is inherently inefficient; even if we tried, we would not be able to gain a lot. The solution is to switch to more performant APIs such as `poll`, `epoll`, `kqueue`, `iocp`, `liburing`, etc. Unfortunately, these APIs are system-dependendent, so a priori they cannot be included in `Unix`.

**Comment by craff** [comment]
I wanted to avoid use hashtbl with sockets as keys... Another solution would be to make file_descr a private int, so I could have an array indexed file_descr. 
This is actually a simple change?

Ideally, it would nice to have things like the pool library available in the standard Library. I currently have trouble with poll, an issue is probably coming, and I also reported a bug for cohttp-eio.A well tested alternatives to select available in most platforms would be really nice in standard lib.  

Le 12 décembre 2022 02:01:47 GMT-10:00, David Allsopp ***@***.***> a écrit :

**Comment by dra27** [comment]
`file_descr` isn’t (portably) an `int`, though (and there is very strong resistance to exposing file_descr’s internals to OCaml)

**Comment by craff** [comment]
Yes I knew that file_descr where not int in windows... May be expose an efficient O(1) data structure indexed by file_descr? Could be of general use beyond select?  

Le 12 décembre 2022 07:01:42 GMT-10:00, David Allsopp ***@***.***> a écrit :

**Comment by xavierleroy** [comment]
We could reimplement `Unix.select` using `poll`, which is POSIX.1-2001.  This would support file descriptors above `FD_SETSIZE`, fixing an annoying limitation of the `select`-based implementation of `Unix.select`.

But `poll` has no notion of "set of file descriptors" with O(1) operations.  Even if we were to represent sets of file descriptors using balanced search trees on the OCaml side, enabling O(log n) operations, there would still be an O(n) cost when converting to/from the arrays of descriptors that `poll` is using.

In the end, I agree with @nojb that high-performance code will want to use nonportable system calls like kqeueue or epoll, and that's best done in separate libraries.

Closing this feature wish...
