### ISSUE TITLE
manual: the API module index is not sorted since 4.13

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11857]
This is a repost of https://github.com/ocaml/ocaml.org/issues/740 reported by @talex5 on the ocaml.org repository.

Rerpot by @talex5:

> At the moment, https://v2.ocaml.org/releases/5.0/api/index.html seems to be in a random order. It starts:
> 
>     * `Ocaml_operators`
> 
>     * `Format_tutorial`
> 
>     * `CamlinternalFormatBasics`
> 
>     * `Stdlib`
> 
>     * `Either`
> 
>     * `Sys`
> 
>     * `Obj`
> 
>     * `Atomic`
> 
>     * ...
> 
> 
> (@gasche reminded me of the importance of sorting in documentation in https://discuss.ocaml.org/t/dune-wish-list-for-2023/11083/26)

Triaging by myself:

> This list was sorted in the past, it looks like this is a regression that occurred for 4.13:
> 
>     * https://v2.ocaml.org/releases/4.12/api/index.html : sorted
> 
>     * https://v2.ocaml.org/releases/4.13/api/index.html: not sorted

> @Octachron I can observe this issue in ocaml/ocaml upstream by:
> 
> ```
> make -C api_docgen clean
> make html_doc -j
> less ./api_docgen/ocamldoc/build/html/libref/index.html 
> ```
> 
> The following patch appears to fix the issue (at least in part):
> 
> ```diff
> diff --git a/api_docgen/Makefile.docfiles b/api_docgen/Makefile.docfiles
> index 2d77fe6984..487bf304c7 100644
> --- a/api_docgen/Makefile.docfiles
> +++ b/api_docgen/Makefile.docfiles
> @@ -76,8 +76,13 @@ compilerlibref=$(compilerlibref_MLIS:%.mli=%)
>  compilerlibref_TEXT=Compiler_libs
>  compilerlibref_C=$(call capitalize,$(compilerlibref))
>  
> -ALL_LIBREF= $(libref_TEXT:%=libref/%) $(libref:%=libref/%)
> +ALL_LIBREF= $(call sort,$(libref_TEXT:%=libref/%) $(libref:%=libref/%))
>  ALL_COMPILERLIBREF= \
>    $(compilerlibref_TEXT:%=compilerlibref/%) \
>    $(compilerlibref:%=compilerlibref/%)
>  ALL_DOC= $(ALL_LIBREF) $(ALL_COMPILERLIBREF)
> ```
> 
> (I don't understand why this patch works, because `sort` is defined as `ocamldep -sort` which itself is documented as sorting by dependencies, while in practice it appears to sort alphabetically.)
> 
> (The patch keeps capitalized modules, namely Format_tutorial and OCaml_operators, at the front -- other modules come from uncapitalized module names so they get sorted after. I think this is an okay result, in any case we would rather have users read https://v2.ocaml.org/releases/5.0/manual/stdlib.html than the auto-generated https://v2.ocaml.org/releases/5.0/api/index.html.)
> 
> If you ( @Octachron ) can confirm that this is an upstream issue, we can move the discussion there.

**Comment by gasche** [comment]
The automatically-generated [OCaml API](https://v2.ocaml.org/releases/5.0/manual/index.html#), which is the focus of this issue, is rather bad anyway. There is a manually-written page with better content, [The standard library](https://v2.ocaml.org/releases/5.0/manual/stdlib.html).

Could we emphasize that page in the menu instead of the auto-generated page? (The "OCaml API" page also includes otherlibs, but we could have a forward reference in the "The standardl ibrary" page that points to the otherlibs chapter or something.)

Note: the "standard library" page is itself a bit weird in that the LaTeX version uses a nice categorization of modules in topic areas, while the HTML version just list all modules in alphabetic order. I wonder which presentation is best and why we don't use it consistently.

Note: there is no sorting/ordering issue for the auto-generated compilerlibs page <https://v2.ocaml.org/releases/5.0/api/compilerlibref/index.html>, except that Pparse is weirdly at the very end.

**Comment by dra27** [comment]
`$(call sort` is equivalent to `$(sort` - i.e. the call to `ocamldep` is never made. The compiler-libs docs order is because they are sorted in three separate batches:

```Makefile
compilerlibref_MLIS= \
  $(PARSING_MLIS) \
  $(UTILS_MLIS) \
  $(DRIVER_MLIS)
```
which is why `Pparse` is at the end (it's the sole member of `$(DRIVER_MLIS)`) but also why the order suddenly jumps back to `Arg_helper` (the first entry in `$(UTILS_MLIS)`) after `Syntaxerr` (the last entry in `$(PARSING_MLIS)`.

`$(sort ...)` is available in GNU make 3.81 (i.e. on macOS), so I think it's OK to use that instead? I don't think calling `ocamldep` can ever have been going to work, because it, gets passed a list of filenames which don't exist?

**Comment by dra27** [comment]
Ah - PR opened as I commented 🙂

**Comment by Octachron** [comment]
Even in the cases were `ocamldep` was given a list of existing files, since the include paths did not include the path to the files, the output of `ocamldep -sort` would have been empty. 

I have thus switched to `$(sort ...)` in the concurrent PR when it made sense to `sort`. After all, this was the solution that we were already using, just in a quite obfuscated way.
