### ISSUE TITLE
"M.t would escape its scope" when it actually wouldn't

### ISSUE THREAD

**Issue by goldfirere** [ocaml/ocaml#11925]
Consider

```ocaml
module M = struct
  type t = T
  let cell = ref None
  let t = T
end

let () = M.cell := Some M.t
```

This produces

```
File "bug2.ml", line 7, characters 24-27:
7 | let () = M.cell := Some M.t
                            ^^^
Error: This expression has type M.t but an expression was expected of type 'a
       The type constructor M.t would escape its scope
```

but the type `M.t` is still in scope outside the module, so I think this should be OK. Is there something I'm missing here?

(The following is a guess as to a solution. But I'm on uncertain ground here.) When we leave type-checking a module, can we adjust the scopes of types that are still exported? That would seem to fix this.

**Comment by Octachron** [comment]
> but the type M.t is still in scope outside the module,

The scope mentioned in the error message is not the environment but the scope of the type definition and the issue is that the scope of the weak type variable for `cell` is older than the scope of `M`. In other words, this is issue an instance of
```ocaml
let cell = ref None
type t = A
let () = cell := Some A
```
with the nuance that the reference in your example can be annotated to avoid the error:
```ocaml
module M = struct
  type t = T
  let cell : t option ref = ref None
  let t = T
end

let () = M.cell := Some M.t
```

**Comment by goldfirere** [comment]
It may be that the weak variable precedes `M`, but it does not precede the type `t`. Also, the reported behavior exists even when the weak variable does not precede the scope of `M`:

```ocaml
module rec M : sig
  type t
  val cell : t option ref
  val t : t
end = struct
  type t = T
  let cell = ref None
  let t = T
end

let () = M.cell := Some M.t
```

That's a bit more contrived, and actually I would still want the original program to work.

Forgetting about scopes for a sec: There's a perfectly good type one can assign to `cell` -- why can't we infer it? Note that this is not the case for @Octachron's first example, where `cell` has no good type at its definition site.

**Comment by gasche** [comment]
My understanding of what is going on would be:
- type-checking `M` is done within its own inference level (not the global level 0), say 1
- `t` has scope 1 (I'm simplifying a bit, I think that scopes are shifted by one on the declaration of `t`, but anyway)
- the type of `let cell = ...` cannot be generalized due the value restriction, so it remains a "weak" inference variable at level 1 within the body of the module
- when we are done checking the module, all its remaining non-generalized variables are decreased by one, so the weak reference ends up at level 0, as if it had been introduced "before" `t`

If a type annotation is given on `let cell : ...`, then there is no weak inference variable remaining. If a signature is given on `M`, then this weak inference variable gets defined as something concrete before exiting `M` -- it's not possible to write a weak inference variable in the signature, so we know that modules with signatures never leak weak reference variables to their external scope.

The suggestion of @goldfirere to also "leak" `t` by decreasing its scope from 1 to 0 does make sense to me, and it could work. It is also a bit scary, I don't think that we ever decrease scopes currently (scopes increase and levels decrease). This is because we use scopes for "local" things that must not exit their, ahem, scope, but in this case it does.

I would expect @garrigue to have thought about this before, because it looks like a not-uncommon pattern to have.

**Comment by gasche** [comment]
I also wonder whether there is a connection between a scope decrease for `t` in this case and the placement of "abstract type names" in the enriched signatures of @diremy  and @clementblaudeau.

**Comment by remy** [comment]
wrong remy…

**Comment by garrigue** [comment]
@goldfirere For the first problem (i.e. That one cannot instantiate a weak type variable from a module with a type defined by this module after leaving it), the rationale is that, we don't want to allow instantiating with a type defined later (in case we need to generate code for the type for instance), and at this point, there is no way to know the order of introduction of the variable and the type.
At some point this was allowed, but caused problems for @alainfrisch.

For your second example, of needing to instantiate before checking inclusion, that is something I wanted to do, but it somehow requires to do extra work to propagate the expected type first. Never went around to do it. I remember people hurt by that, so it would be worth doing.

**Comment by lpw25** [comment]
I've said this to Richard elsewhere, but I think that the current behaviour is correct and that doing anything else is at least somewhat dubious. The `struct ... end` construct is essentially the `pack` construct from a standard treatment of existentials, and you need to know about all the occurrences of `x` in `P(x)` before you finish closing `∃x.P(x)` since those are the ones that must be freshened at each `open` construct that uses the existential. It's extremely similar to trying to infer additional uses of `'a` inside `'b` in:
```ocaml
let rec foo : 'a. 'a -> 'b = fun x -> ...
```
once you've already closed that polymorphic type and used it as the type of `foo`.

**Comment by goldfirere** [comment]
I don't quite buy the existentials argument. While I agree that `struct ... end` is like `pack`, what is like `open`? That is, where does the freshening operation you're worried about happen? As observed elsewhere, this problem can only occur in modules without signatures (otherwise the signature pins everything down), so we can't reasonably expect this action to happen through a functor application.

By analogy to universals, I agree that we can't infer occurrences of `'a` in `'b` because we need to know about these before we ever instantiate the type of `foo`. But I lose the thread of the analogy at that point: how does this map back to modules and existentials?

By the way, maybe in the end this whole subject is moot, because signature-less modules are rare. That's fine. It also might be that implementing this idea is too hard. But I'm not yet convinced that what I'm asking for is broken.

**Comment by lpw25** [comment]
Traditionally, the point at which you name a module is considered the point you open it. See for example [this paper](http://gallium.inria.fr/~remy/modules/Montagu-Remy@popl09:fzip.pdf) for a description of modules in that style. Although for this discussion I suspect that it is projection that behaves like open.

Mechanically, the underlying operation that is broken for an incomplete signature is substitution, since substitution needs to replace the occurrences of `t` that do not yet exist. Projection includes such a substitution of `M.t` for `t`. Worse this substitution must be done lazily for performance. Such substitutions necessarily duplicate the type that has the substitution applied to them, so at the very least you'd need to create two unification variables linked by a substitution -- then unifying with either of the variables would require running the substitution (or its inverse) on the unified type and then unifying the other variable with the result.

I'm not saying this idea is impossible to implement, I'm just saying that it runs counter to what type theory naturally says should happen and so would require an ad-hoc implementation. I would not be confident that such an implementation played nicely with every corner of the language or future language feature.

**Comment by goldfirere** [comment]
Thanks, @lpw25. That's considerably more convincing. For my money, "runs counter" starts when we allow a weakly polymorphic variable to escape a module at all (it's not really a package when some of its interface is left unspecified), although what I propose definitely continues to run counter. I'm content to give up here, but someone else can reopen if you are moved to do so.

**Comment by goldfirere** [comment]
Interestingly, **since closing this ticket** (within that 20 minute span!), a colleague called me over because he had induced the scenario above, because his module in an ml file had a weak polymorphic variable that needed to unify with a type declared earlier in the module. When the compiler matched the type of the module against the declaration in the mli file, the type in the module would escape its scope, leading to a very confusing error message.

**Comment by gasche** [comment]
We should probably have a warning, maybe an error, when a module is introduced in the environment with a weak inference variable in its signature. The same situation is rejected at the toplevel of a compilation unit (as it then becomes unsound):

```
$ echo "let x = ref []" > test.ml
$ ocamlc -c test.ml
File "test.ml", line 1, characters 4-5:
1 | let x = ref []
        ^
Error: The type of this expression, '_weak1 list ref,
       contains type variables that cannot be generalized
```
