### ISSUE TITLE
Large slowdown of Coq with OCaml 5.0

### ISSUE THREAD

**Issue by silene** [ocaml/ocaml#11926]
We have not yet investigated where the time is spent, but @jhjourdan suggested I report the issue already. Things will become easier to reproduce once Coq 8.17.0 is released, which should be soon.

Below is a comparison of the time needed to compile various Coq-related Opam packages. NEW is OCaml 5.0 while OLD is OCaml 4.14. Package `coq-core` builds the Coq binaries, so Coq itself is not run. Other packages do run Coq to compile `.v` files, starting with `coq-stdlib` for Coq's standard library. As can be seen, Coq runs from 10% to 50% slower when compiled with OCaml 5.

The table below contains only a small selection of what I consider to be representative of Coq user developments. See https://github.com/coq/coq/pull/15494 for the complete tables.

```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │
│                             │                         │                                       │                                       │                          │
│        package_name         │   NEW      OLD    PDIFF │      NEW             OLD        PDIFF │      NEW             OLD        PDIFF │   NEW      OLD    PDIFF  │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┤
│                    coq-core │  108.77   115.56  -5.88 │   448176242336    475316383968  -5.71 │   514833338600    484621682946   6.23 │  349008   348540    0.13 │
│      coq-mathcomp-odd-order │  460.19   420.33   9.48 │  2105740732942   1925971651287   9.33 │  3636963772697   3240724888710  12.23 │ 1660816  1548300    7.27 │
│                 coq-unimath │ 1413.84  1286.34   9.91 │  6449325705965   5870103915729   9.87 │ 12337978851391  10949635771154  12.68 │ 2610752  1595128   63.67 │
│                coq-bedrock2 │  424.71   384.84  10.36 │  1939859579088   1759094439924  10.28 │  3939338066859   3438424521822  14.57 │ 1637572   960636   70.47 │
│          coq-mathcomp-field │  102.61    92.87  10.49 │   469145106933    425015888266  10.38 │   800728664311    708580479443  13.00 │ 1207896   991884   21.78 │
│        coq-mathcomp-algebra │   67.13    60.61  10.76 │   306004188492    276943140328  10.49 │   445538650133    389421431816  14.41 │  778480   592284   31.44 │
│                    coq-corn │  884.20   787.11  12.33 │  4027754587020   3592264603042  12.12 │  6564781087980   5685800395118  15.46 │ 1227808   953876   28.72 │
│         coq-category-theory │  876.81   780.11  12.40 │  4005299774130   3564940614845  12.35 │  6882470483447   5999346368760  14.72 │ 1691800   950456   78.00 │
│                  coq-geocoq │  754.20   664.75  13.46 │  3435148027480   3032125535685  13.29 │  5768255706915   4962353357381  16.24 │ 1386692  1044540   32.76 │
│              coq-coquelicot │   40.32    35.09  14.90 │   181669608454    156892061130  15.79 │   259364772318    216191351923  19.97 │ 1029252   795264   29.42 │
│                   coq-verdi │   55.87    46.44  20.31 │   253830568044    210894419676  20.36 │   401185193644    324441924701  23.65 │  761628   542540   40.38 │
│            coq-math-classes │  108.57    89.00  21.99 │   491023018742    404117277870  21.51 │   738331588513    580845820789  27.11 │  609912   503888   21.04 │
│                    coq-hott │  204.14   160.98  26.81 │   924133893279    729612021105  26.66 │  1481436404912   1160692706313  27.63 │  740224   590128   25.43 │
│                   coq-color │  285.95   219.88  30.05 │  1292347301747    996517976184  29.69 │  1963372763085   1467553366877  33.79 │ 1664020  1208376   37.71 │
│                  coq-stdlib │  601.49   406.86  47.84 │  2507810116636   1738015228647  44.29 │  1973667764774   1429571108104  38.06 │  996288   718004   38.76 │
│               coq-fiat-core │   91.89    56.42  62.87 │   401157873653    243392412738  64.82 │   609702670266    357553599029  70.52 │  625444   481032   30.02 │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┘
```

**Comment by kayceesrk** [comment]
Thanks for the report @silene. IIUC, there were no crashes when running the Coq benchmarks using OCaml 5 (which is great to see). 

In order to investigate the regressions, I would like to see instructions for reproducing the results for a single benchmark listed here. Say, the slowest one `coq-fiat-core`. Is this easy to do? This would help us run tools like `perf`, `olly` and collect other metrics such as GC stats.

**Comment by silene** [comment]
Until Coq 8.17 is released, thing like Fiat Crypto are moving targets, so it is better to stick to Coq itself.
```
opam switch create foo
opam repository add coq https://coq.inria.fr/opam/core-dev
opam install coq-core=8.17+rc1
perf stat opam install -j1 coq-stdlib=8.17+rc1
```

Results for 4.14.1:
```
        268 873,63 msec task-clock                #    1,015 CPUs utilized          
            14 140      context-switches          #   52,590 /sec                   
               452      cpu-migrations            #    1,681 /sec                   
        38 929 587      page-faults               #  144,788 K/sec                  
 1 223 229 572 714      cycles                    #    4,549 GHz                    
 1 696 376 553 043      instructions              #    1,39  insn per cycle         
   350 716 407 442      branches                  #    1,304 G/sec                  
     9 059 482 937      branch-misses             #    2,58% of all branches        

     264,861861341 seconds time elapsed

     233,274208000 seconds user
      35,701257000 seconds sys
```

Results for 5.0.0:
```
        340 474,57 msec task-clock                #    1,012 CPUs utilized          
            16 242      context-switches          #   47,704 /sec                   
               790      cpu-migrations            #    2,320 /sec                   
        44 394 798      page-faults               #  130,391 K/sec                  
 1 549 148 888 877      cycles                    #    4,550 GHz                    
 2 200 455 861 475      instructions              #    1,42  insn per cycle         
   459 666 250 802      branches                  #    1,350 G/sec                  
    12 022 250 800      branch-misses             #    2,62% of all branches        

     336,313511053 seconds time elapsed

     300,767060000 seconds user
      39,820431000 seconds sys
```

So, not as dramatic as the 45% of the original bench, but still a solid 30% slowdown.

**Comment by silene** [comment]
In case it helps, note that more than 10% of the time is spent on rebuilding the hashtable in `build_frame_descriptors` for OCaml 5. The corresponding code for OCaml 4 `fill_hashtable` amounts to less than 0.2%.

If I understand correctly, the old code was incrementally storing new entries into the table. The new code, however, restarts from scratch every time new entries are added.

**Comment by gasche** [comment]
This sounds related to https://github.com/ocaml/ocaml/pull/11673#issuecomment-1297384255. But that issue is related to heavy use of Dynlink, and I hadn't realized that "standard Coq" used Dynlink a bit. Do you have the call trace that leads to `build_frame_descriptors` being called?

**Comment by silene** [comment]
Most users will use between 7 and 10 plugins for tactics and syntax extensions. But since the relevant metric seems to be the number of modules according to the comment you pointed at, this amounts to about 140 modules.

As for the call trace, I don't see anything suspicious:
- `caml_c_call`
- `caml_natdynlink_run`
- `caml_register_frametable`
- `build_frame_descriptors`

**Comment by gasche** [comment]
I believe that this is the same issue as https://github.com/ocaml/ocaml/pull/11673#issuecomment-1297384255 indeed. It's a bit of work but not too hard either, we will have a look. ( @silene would you be interested in hacking on it yourself? )

**Comment by gadmm** [comment]
The current implementation uses a read-copy-update strategy by creating a new version every time `caml_register_frametable` is called; the main problem is that the rate at which new versions are created defeats the scaling strategy of the hash table.

I think that you can avoid a full-blown concurrent hash table by keeping the same read-copy-update strategy, but by adding to the current table in a way that is lock-free for readers, and creating a new version only when the previous table is too full.

Concretely, since you have a hash table with linear probing, I think adding a new element to the current version only needs a CAS loop on the writer's side. Synchronization is avoided for readers because each version is monotonous and each intermediate state of the table is a valid hash table. (This still needs an acquire fence once an entry is located, or to rely on dependency ordering if acquire proves too costly, in which case generated code is basically the same as the single-threaded version.)

To synchronize between multiple writers you can use a mutex, but it is not clear to me yet that this is necessary (it might make things easier though). So another way of seeing this is as an optimization of a naive mutex strategy which tries to be lock-free for readers.

**Comment by gadmm** [comment]
(cc @stedolan)

**Comment by stedolan** [comment]
@gadmm 

> Concretely, since you have a hash table with linear probing, I think adding a new element to the current version only needs a CAS loop on the writer's side. Synchronization is avoided for readers because each version is monotonous and each intermediate state of the table is a valid hash table. (This still needs an acquire fence once an entry is located, or to rely on dependency ordering if acquire proves too costly, in which case generated code is basically the same as the single-threaded version.)
>
> To synchronize between multiple writers you can use a mutex, but it is not clear to me yet that this is necessary (it might make things easier though). So another way of seeing this is as an optimization of a naive mutex strategy which tries to be lock-free for readers.

This is a nice idea! I think the big lock on the writer side would be fine, and easier to get right than fine-grained CAS, but this sounds great.

Independently of improving the data structure here, I've opened #11935 to reduce the number of times we rebuild the frametable. (In the `impact` example of #11662, 12 `cmxs` are opened containing in total 216 modules. We currently rebuild the frametable 216 times, but it should be 12 with after 11935)

**Comment by gasche** [comment]
Now that #11980 is merged, the quadratic behavior due to plugin loading (so only a fixed cost at startup, but non-neglectible) should be gone. Updated results on Coq build are available at https://github.com/ocaml/ocaml/pull/11980#issuecomment-1422432303 . If I read correctly, trunk is correctly 2.6% slower than 4.14.1 at building Coq itself, whereas 5.0 was 26.7% slower.

It is unclear if the current performance difference is due to performance regressions in OCaml 5, or just due behavior difference in the runtime that require a different tuning. (If I remember correctly, Coq was delicately tuned for the OCaml 4 GC, so a different GC behavior may fall differently on the memory/time trade-off and require re-tuning.)

There is nothing actionable from the information left in the present issue: going further would require a more in-depth analysis of Coq performance and a comparison against the 4.14 profile. @silene, do you agree that the current issue can be closed?

**Comment by silene** [comment]
Yes. I will reopen one (if needed) when both Coq 8.17 and OCaml 5.1 have been released.
