### ISSUE TITLE
Object initializers keep memory from their environment alive

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml#11938]
The memory is effectively "leaked" as long as the object itself is alive.
This can be reproduced like so:
```ocaml
let o a = object
  initializer ignore a
end

let _ = assert Obj.(
  let m1 = reachable_words (repr (o (Array.make 1000 0))) in
  let m2 = reachable_words (repr object end) in
  m1 = m2
)
```

As far as I understand, an initializer is a private method which runs _exactly once_ after object creation or inheritance, and cannot possibly run again (can't be referenced from outside or within the object).
If my understanding is correct, and that sort of linearity is guaranteed, the initializer shouldn't hold references to values from its environment through the lifetime of the object. Instead, anything it references should be released as soon as the initializer itself is done and "dead".

PS: If this is the intended behavior (why?), I don't think it's specified or warned against in the manual.

**Comment by lthls** [comment]
The parameter `a` does end up reachable from the object.

I'll spare you the details, but roughly speaking an initializer is a function that takes an object as input, runs some code that can access the object, and exits. In theory, like all OCaml functions, it could refer to variables outside its scope through its closure, but this doesn't work here because the compiler for objects tries to optimise the creation of the class corresponding to the object (yes, even immediate objects are compiled using classes), in particular so that successive calls to `o` do not create a new class, only a new object. So the class itself cannot refer to any particular value of `a`. Instead, the class will contain a function that takes as parameter the values of the free variables of the object (including its initializers), creates an object containing these values in a special environment field, and then calls the generic initializers, which will go through the object's environment to access `a`. But the result is that after the initializers have run, `a` is still stored in the object's environment.

> PS: If this is the intended behavior (why?), I don't think it's specified or warned against in the manual.

I don't think anybody ever wrote what the intended behaviour is for objects (beyond the basic denotational semantics). The implementation details are explicitly kept opaque in the chapter on interacting with C.

**Comment by OlivierNicole** [comment]
Maybe this issue should be closed, unless an example of a legitimate use case is found where this behaviour causes a memory leak?

**Comment by hyphenrf** [comment]
I personally have no legitimate case where this causes a pathological leak. It was just a surprising finding is all.
I don't mind it closed with the given explanation.
