### ISSUE TITLE
Finaliser called before value is unreachable

### ISSUE THREAD

**Issue by Gbury** [ocaml/ocaml#11995]
Finalisers registered using `Gc.finalise_last` are sometimes called before the value is unreachable. This seems to affect only ocaml 5.0 (and trunk), and only finalisers registered using `GC.finalise_last` (i.e. finalisers registered using `Gc.finalise` behave as expected).

# Steps to reproduce

Consider the following program:

```ocaml
let[@inline never][@local never] bar s =
  let foo () = print_endline ("hello: " ^ s) in
  Gc.finalise_last (fun () -> print_endline "bye bye !") foo;
  Gc.minor ();
  foo

let () =
  let foo = bar "chameau" in
  foo ()
```

Compiling and running it using ocaml 5.0 yield the followng output:

```
bye bye !
hello: chameau
```

Which show that the finaliser registered for the function `foo` was called **before** we call `foo`, and thus before `foo` becomes unreachable.

**Comment by lthls** [comment]
From a bit of debugging that we did before submitting the issue, we found that the value is added to the set of values to be finalised during `generic_final_minor_update`, at the end of a minor collection. Apparently the value registered in the finaliser still points to the minor gc area, although the value itself has been promoted.
Hopefully this will be helpful to anyone trying to fix this.

**Comment by abbysmal** [comment]
Hello,

Thank you for your report!

I am not extremely familiar with finalisers.

What I can see though is that `caml_final_update_last_minor` is called _before_ promotion happens during the minor GC.

https://github.com/ocaml/ocaml/blob/trunk/runtime/minor_gc.c#L602

Is it the right behaviour?

Maybe @gadmm or @sadiqj can provide some insight.

**Comment by Gbury** [comment]
I'm not familiar at all with the runtime code for finalisers, I only know what the [documentation ](https://v2.ocaml.org/api/Gc.html#VALfinalise_last) says. In this case I'd expect that you at least need to know which values will be promoted before running finalisers (since promoted values are still alive, and thus their finalisers should not be run).

**Comment by kayceesrk** [comment]
@sadiqj the comment, interpreted in one way, does not match the code that follows:

https://github.com/ocaml/ocaml/blob/a606e92d8672b1f6d0fcc71c956dde23d8c3c7c0/runtime/minor_gc.c#L588-L590

If the intention is to not have a barrier at the end of the minor GC and unconditionally promote the finalisers, you'll need to promote both the finalisers and the values on which the finalisers are installed on. The last argument is `0` in the above and doesn't promote the finalise last values. 

Is this the intended design? You can unconditionally promote the finalise last values along with the finalisers, by changing `0` to `1`. (Really, you don't need this argument at all since this is the only place where this function seems to be called in the runtime). If we do this, then `caml_final_update_last_minor` and hence, `generic_final_minor_update` is unnecessary and can be removed. I confirmed that this fixes the bug.

**Comment by kayceesrk** [comment]
Taking a step back, is unconditionally promoting the finalise last values and only handling them in the major collection a reasonable approach? Do users expect that finalise last finalisers on values in the minor heap to be run as soon as the values become dead in the minor heap?

Implementing prompt handling of finalise last finalisers during a minor collection shouldn't be too difficult. We already have a barrier at the end of the minor GC

https://github.com/ocaml/ocaml/blob/a606e92d8672b1f6d0fcc71c956dde23d8c3c7c0/runtime/minor_gc.c#L710-L725

For handling finalise last finalisers will need no extra barrier IIUC -- a domain will only process its own finalise last finalisers, which are in its own minor heap. So after the barrier above, each domain can go through its list of finalise last finaliser values, check if they're dead and arrange for the finaliser to be called (which is done in `caml_final_update_last_minor`). 

Either way, it would be useful to fix the bug first and come back to improvements in a separate PR.

**Comment by abbysmal** [comment]
> Do users expect that finalise last finalisers on values in the minor heap to be run as soon as the values become dead in the minor heap?

At least in 4.14 the behaviour is such that the last finaliser is not run as soon as the value in the minor heap is dead.

The fix you suggest aligns with the `4.x` behaviour.

I am opening a PR with it.

**Comment by lpw25** [comment]
I found this discussion a little confusing, so just for clarity: I think it is fine, and somewhat unavoidable, to always promote the *finaliser* from a `finalise_last` call. I think it would not be fine to always promote the *value* from a `finalise_last` call -- it is important that those are still collected in the minor GC and that their finaliser be called sooner than the end of the next major cycle.

**Comment by abbysmal** [comment]
@lpw25 If my understanding is right, with the proposed fix, we do run the finaliser earlier than the next major cycle if the associated value is collected during said minor cycle. (I actually just checked by moving the call to `Gc.minor` at the end of the program, rather than after `finalise_last`, this way it is not promoted to the shared heap.)

The suggested fix merely make sure we do not wrongly run a finaliser for a value that has been promoted, and as a result is still live. (in the shared heap, that is.)

I am not extremely knowledgeable about finalisers, but I think the fix is correct (having spent time reading finalise code in the process).
