### ISSUE TITLE
GC alarm leads to non-termination if the callback causes a major GC

### ISSUE THREAD

**Issue by samwgoldman** [ocaml/ocaml#12002]
If you compile and run the following program, it will not terminate:

```
let () =
  ignore (Gc.create_alarm Gc.full_major);
  Gc.full_major ()
```

We ran into this problem at Meta when updating some code to OCaml 5.0. In this case, the callback ran `Gc.stat ()`. Before OCaml 5, `caml_gc_stat` was a separate heap walk which did not trigger a major GC, but the new implementation does. While we only noticed this issue when updating to OCaml 5, the code above also reproduces on 4.x.

**Comment by fabbing** [comment]
A very simple change to `call_alarm` avoids the problem:
```diff
diff --git a/stdlib/gc.ml b/stdlib/gc.ml
index 832cfedb4..adc2c624a 100644
--- a/stdlib/gc.ml
+++ b/stdlib/gc.ml
@@ -108,8 +108,8 @@ type alarm_rec = {active : alarm; f : unit -> unit}
 
 let rec call_alarm arec =
   if Atomic.get arec.active then begin
-    finalise call_alarm arec;
     arec.f ();
+    finalise call_alarm arec;
   end
```
The finaliser is not re-registered until the user thunk of `create_alarm` is called. This prevents getting into an infinite loop where the user thunk always causes a major GC.
This has the drawback of changing the semantics of `create_alarm`, which is no longer called after every major GC cycle, but only after those not caused by the alarm itself.
It seems reasonable to me, but I would be interested to hear other opinions.

**Comment by jberdine** [comment]
This change of semantics would not be a problem for the uses of GC alarms I have seen.

**Comment by gasche** [comment]
You propose to not run alarms callbacks for GC events  that are themselves caused by an alarm callback. From a distance (I don't understand the details), this sounds like a desirable change, in particular it avoids non-termination that is easy to get.

I believe that @gadmm may have good advice to give on this topic.

Note that this is not a reentrancy issue: there are no re-entrancy questions if major GC events are 'masked' during the alarm callback, that is, if we wait until the alarm callback is done to call itself again on GC events that it has caused. That behavior (which is possibly the one currently implemented?) avoids re-entrancy problems but does not avoid non-termination.

**Comment by fabbing** [comment]
Many thanks for your input, I've created #12017 to propose this fix.
