### ISSUE TITLE
Add -Werror -Wall flags (or equivalent) to ocamlopt

### ISSUE THREAD

**Issue by dannywillems** [ocaml/ocaml#12050]
For the moment,
```
$ ocamlopt -config 
version: 4.13.1
[...]
ocamlopt_cflags: -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -g -O2 -ffile-prefix-map=/build/ocaml-SC7b9w/ocaml-4.13.1=. -fstack-protector-strong -Wformat -Werror=format-security
[...]
```
Is there any reason `-Wall -Wextra` is not added by default (or any "stronger" or equivalent flags/build warnings/errors)?
Discussions with other members of the OCaml community "offline" seems to give a compatibility reason with the different C compilers.

IMHO, it would increase the code quality and (sometimes) security, and avoid bug reports like [2].
On another side, it might list warnings as errors in projects which do not include these flags by default. However, I think it is positive.

I am opening this issue for discussions.

[1] gcc options: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
[2] https://github.com/yallop/ocaml-ctypes/issues/248

**Comment by gasche** [comment]
The problem with `-Werror -Wall` is that whenever you switch to a more recent C compiler, your code breaks. This is okay for development builds, but a terrible choice for release builds -- because it means that your *users* will see the breakage whenever they build from source. We cannot enable this by default for this reason.

If you use `ocamlc` or `ocamlopt` as a C compiler, you can pass `-ccopt "-Werror -Wall"` explicitly to turn warnigns into errors. (You should not use this when compiling OCaml modules as well, because then the flags would be stored in the resulting .cma library if any, which is not what you want.)

Enabling `-ccopt "-Werror -Wall"` when using ocamlc/ocamlopt to build C files is a choice of the build system, not something to be decided by the compiler itself.
