### ISSUE TITLE
Runtime events: Allow specifying events dir via OCaml API

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml#12173]
I'm using the `Runtime_events` module for basic monitoring of GC performance within a process (with the pure OCaml API). I'd like to change the change the directory where the .event file is written, since the working directory is sometimes not writable. 

This is currently possible via the `OCAML_RUNTIME_EVENTS_DIR`, but not via the OCaml API. `OCAML_RUNTIME_EVENTS_DIR` is read during startup, so setting it using `Unix.putenv` before calling `Runtime_events.start` has no effect.

Alternatively (or additionally), the API could be enhanced to allow monitoring within a process without creating a backing file.

I'd be willing to submit a PR if there's agreement that this change is desirable and how to implement it (e.g., reading the environment variable when `Runtime_events.start` is called, or adding a new parameter to  `Runtime_events.start`).

**Comment by sadiqj** [comment]
Thanks for creating an issue for this @copy .

So there's some tension in the API and design for `Runtime_events` at the moment in that it was designed both for programs that know about it and can interact with it but also for those that are completely unaware of it's existence. We should be able to monitor any OCaml program's Gc behaviour. That's why the environment variables exist for controlling it's behaviour.

I think deferring reading the `OCAML_RUNTIME_EVENTS_DIR` environment variable until `Runtime_events.start` is a good idea and a PR would be welcome. My only question is what to do if we've already started it from an `OCAML_RUNTIME_EVENTS_START` environment variable?

**Comment by copy** [comment]
> My only question is what to do if we've already started it from an OCAML_RUNTIME_EVENTS_START environment variable?

If `OCAML_RUNTIME_EVENTS_START` is set, `Runtime_events.start` already doesn't do anything in the current implementation. I don't think changing the events directory at that time is a useful behavior.

**Comment by dbuenzli** [comment]
> I think deferring reading the `OCAML_RUNTIME_EVENTS_DIR` environment variable until `Runtime_events.start` is a good idea and a PR would be welcome.

This looks rather obscure and brittle to me. What's wrong with specifying the file on `Runtime_events.start` with an optional argument ? Or even have a separate fun call to get and set the value and simply default it to `OCAML_RUNTIME_EVENTS_DIR` at startup ?

**Comment by gasche** [comment]
I tend to agree with Daniel: I prefer a world where environment variables used to determine the behavior of an OCaml program are read at an unspecified time during the execution of the program, and we assume that they will not change during the program execution.

Behaving more or less when when the external environment changes them is one thing, but here you are organizing things so that your program can changes them itself as an API to configure its own behavior, and that sounds fragile to me.

I would rather have a cascading behavior where the environment variables do not change, and/but it is also possible to specify this configuration state programmatically from the program itself (not by mutating the environment), and this explicit configuration takes precedence over the environment variable.

**Comment by sadiqj** [comment]
> This looks rather obscure and brittle to me. What's wrong with specifying the file on `Runtime_events.start` with an optional argument ? Or even have a separate fun call to get and set the value and simply default it to `OCAML_RUNTIME_EVENTS_DIR` at startup ?

The reason I lean towards the environment variable is that the program specifying these values fundamentally breaks the property that you can take any OCaml program and monitor it externally without any coordination. 
The current pattern for monitoring a process (which works for GC and custom events too) is to set the environment variables, start the process and then consume events the known location (https://github.com/tarides/runtime_events_tools/blob/main/bin/olly.ml#L82-L109). Having it on `start` makes it far more likely for users to do this. It is also not a good public API because we ignore the parameter (if runtime events is already started) which could be pretty surprising for the user if they expected things to be in a certain location.

**Comment by dbuenzli** [comment]
Then why provide `Runtime_events.start` at all ? Why agreeing that it's good to consult the environment variable at this point so that the instrumented program can still change it in an obscure way ? 

At a certain point you have to choose a design and deal with its consequences. Errors maybe ?

**Comment by dbuenzli** [comment]
I mean it doesn't sound complicated to have a design that allows for both internal and external monitoring with the external taking over if present in a non-silent way for the internal user. 

Or am I missing something ?

**Comment by sadiqj** [comment]
> Then why provide `Runtime_events.start` at all?

Because we still want to support the usecase of programs monitoring themselves.

> I mean it doesn't sound complicated to have a design that allows for both internal and external monitoring with the external taking over if present in a non-silent way for the internal user.

Open to suggestions that could work for both.

**Comment by dbuenzli** [comment]
So *you* want to support both uses cases but you want *me* to do the design ? I'm happy to provide feedback on your design but please don't ask me to do the work for you.

**Comment by gasche** [comment]
My understanding is that there is a tension between:
- being able to uniformly monitor arbitrary OCaml programs
- giving OCaml programs control over how they want to monitor themselves

I see two approaches:
1. The OCAML_RUNTIME_EVENTS_DIR setting is enforced. This means that if the program wants to monitor itself, it should either (1) use another approach in addition, for example by asking for a shared-memory buffer into the file wherever it is (this corresponds to @copy's "Additionally" suggestion above), or (2) be able to specify *additional* locations (with a hard link between the different locations in the filesystem) instead of replacing the default choice.
2. The OCAML_RUNTIME_EVENTS_DIR setting is not enforced, but the caller of the program has a feedback mechanism to learn at which location the program placed its monitoring data in the end. This sounds more difficult.

From a distance it sounds like it would be reasonable for a program to ask to monitor itself without creating an external file -- more precisely, in a way that is independent from the availability of the same data as an external file if requested by the caller.

In any case, if @sadiqj is correct that we want to be able to uniformly monitor arbitrary OCaml programs, then the feature proposal of behaving "correct" if the environment variable is mutated by the program in-flight should be rejected, #12176 is not the right approach.

**Comment by dbuenzli** [comment]
The question is what can an external monitor infer if you let the program control itself when it wants to pause and resume event collection. 

1. Does it make any sense ? I doubt.
2. Do the program initiated pauses at least appear as events to the monitor ?
3. How can the external monitor enforce what it wants to see by overriding what the program is doing ? 

It seems to me that without a mecanism for 3. you have already given up on the "we want to be able to uniformly monitor arbitrary OCaml programs".

In any case for the particular problem of specifying an event dir from OCaml then you could have a simple scheme where specifying one from OCaml is merely a hint and the value set at init time via an environment variable always takes over what the program tries to set (rather than specifying a default). Of course you want an API entry point to actually access the concrete value since your `set` may have not succeeded. Regarding having additional locations, hard links and what not seems like adding useless complexity to me.

**Comment by hannesm** [comment]
I've not used "runtime events" at all, only observed from a distance that this feature has been merged in 5.0. I wonder why the API is so different from the well-established pretty `Gc.Memprof` (https://v2.ocaml.org/api/Gc.Memprof.html) -- which has the additional benefit to not depend on "file" and other system resources, that allowed me to use that very API to profile MirageOS unikernels (https://github.com/roburio/memtrace-mirage).

Now, since there are some issues with the existing "runtime events" (as discussed above here), what about taking a step back and not use any "environment variables" or writing to arbitrary files/directories, but provide an API in the same spirit as Gc.Memprof?

Is the requirement "being able to uniformly monitor arbitrary OCaml programs" really given and realistic? According to the documentation, you need the runtime_events library or "olly".

**Comment by sadiqj** [comment]
> I've not used "runtime events" at all, only observed from a distance that this feature has been merged in 5.0. I wonder why the API is so different from the well-established pretty `Gc.Memprof` (https://v2.ocaml.org/api/Gc.Memprof.html) -- which has the additional benefit to not depend on "file" and other system resources, that allowed me to use that very API to profile MirageOS unikernels (https://github.com/roburio/memtrace-mirage).

Hi @hannesm . The PR for eventring has some justification for the current design so I won't go through it all here: https://github.com/ocaml/ocaml/pull/10964 but essentially Runtime_events isn't meant to replace Memprof but Eventlog. The latter used a file that was appended to with new events and could be consumed by external programs. Runtime_events replaces that with a ring buffer and enables programs to monitor themselves (which wasn't really possible with eventlog, not for anything other than very short running programs).

There is a bit of a tension in the API as others have pointed out. You can already currently do things that break consuming the events from an external monitor.

> Is the requirement "being able to uniformly monitor arbitrary OCaml programs" really given and realistic?

This comes from runtime_events being a replacement for eventlog, which was designed for this very usecase.

Is the only gap with the `Gc.Memprof` API that there's no backing file for the buffers? It's worth pointing out that the `Runtime_events` library is shipped with the compiler in otherlibs.

**Comment by hannesm** [comment]
Thanks for your reply @sadiqj. I started reading #10964 but couldn't find a rationale for the current API (apart from "replaces eventlog"). But it is likely that's an issue on my side (the PR you linked is just too big, searching for "memprof" didn't lead to much insight about the API design / comparison). I wrote my comment since I had the impression the event API is getting more intricate and more knobs to turn (which, from an outside, makes it harder to use). But please move along with however it should look like. It'll likely be several years before I use OCaml 5.

**Comment by copy** [comment]
I suggest the following way forward then:

- If  `OCAML_RUNTIME_EVENTS_START` is not set, calling `Runtime_events.start` doesn't create an events file. Any cursors for the event ring of the current program work on the ring buffer in memory. This should make the `Runtime_events` library compatible with MirageOS. The only potential downside is that child processes won't be able to observe their parent any more, at least with the current API
- If  `OCAML_RUNTIME_EVENTS_START` is set, everything keeps behaving as it does now. Since `Runtime_events.start` doesn't use a file, there's no conflict over the file location

And leave the following for later discussions:

- Should `Runtime_events.pause` become a no-op if `OCAML_RUNTIME_EVENTS_START` is set?
- Provide a new function in `Runtime_events` that maps the ring buffer of the current program into a specified file, for an external process (that didn't specify `OCAML_RUNTIME_EVENTS_START`) to observe the current program
