### ISSUE TITLE
Add Profile-Guided Optimization (PGO) support to the compiler

### ISSUE THREAD

**Issue by zamazan4ik** [ocaml/ocaml#12200]
Hi.

I have read multiple articles about attempts to add PGO (or FDO) support to Ocaml. But as far as I see, right now there is no support for PGO in AoT mode in Ocaml compiler. Do you have plans to support so? If I am wrong and PGO is already supported - could you please point me out to the documentation?

Thanks!

**Comment by xavierleroy** [comment]
I guess those articles were from Jane Street's blog?  My understanding is that Jane Street has experimental support for some profile-guided link-time optimizations in their internal fork of OCaml, but this support has not been upstreamed yet.

As far as I know, the only part that is already in the OCaml core distribution is the `-function-sections`  option to the `ocamlopt` compiler, which puts each function in a separate section, so that a linker script can group "hot" functions together.

**Comment by zamazan4ik** [comment]
> I guess those articles were from Jane Street's blog?

Yeah, you are right: the [link](http://www.cs.cmu.edu/afs/cs/academic/class/15411-f20/www/lec/19-yorsh.pdf)

**Comment by xavierleroy** [comment]
Right.  Maybe @gretay-js can tell you more.  At the moment, as far as I know, some of the basic mechanisms mentioned in her talk were integrated in the core OCaml distribution, but not the tools that actually perform link-time optimizations, and I don't know whether these tools are publicly available.

**Comment by gretay-js** [comment]
A very much out-of-date version of profile-guided layout optimization tool is available [here](https://github.com/gretay-js/ocamlfdo), if you want to have a look at how it was implemented. Function reordering is implemented simply with a linker script. Basic block reordering is implemented by converting Linear IR to a CFG and then back to Linear using a different layout.

The version we use internally at Jane Street is slightly different, because we use an [experimental](https://github.com/ocaml-flambda/flambda-backend) compiler with several changes on top of OCaml 4.14 that haven't been upstreamed yet. If you want to try ocamlfdo with this experimental compiler, please let me know. Note that this version of ocamlfdo is only tested/supported on Linux/x86_64 targets.
