### ISSUE TITLE
Problem compiling 5.0.0 on raspberry pi 4

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#12226]
opam init && opam switch create 5.0.0 give the error below.

```
# runtime/arm64.S:913: Erreur: registre ARM attendu -- `add x8,x8,#:lo12:caml_array_bound_error_asm'
# runtime/arm64.S:927: Erreur: type erroné de correctif de réadressage (1)
# runtime/arm64.S:931: Erreur: type erroné de correctif de réadressage (1)
# If your assembler produced syntax errors, it is probably
# unhappy with the preprocessor. Check your assembler, or
# try producing arm64.o by hand.
# make[2]: *** [Makefile:953 : runtime/arm64.o] Erreur 2
# make[2]: *** Attente des tâches non terminées....
# make[2] : on quitte le répertoire « /home/pi/.opam/5.0.0/.opam-switch/build/ocaml-base-compiler.5.0.0 »---------------------------------------------------------------------
# make[1]: *** [Makefile:265 : opt.opt] Erreur 2
# make[1] : on quitte le répertoire « /home/pi/.opam/5.0.0/.opam-switch/build/ocaml-base-compiler.5.0.0 »
# make: *** [Makefile:340 : world.opt] Erreur 2
```

OS is up to date latest raspbian:

```
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by craff** [comment]
I will try 5.1 alpha shortly

**Comment by xavierleroy** [comment]
Assuming these are the last 3 lines of errors (and that there are many other before), this could have the same cause as #12215: you're using an ARM 32-bit assembler, which chokes on ARM 64-bit code (unsurprisingly), yet OCaml autodetected an ARM 64-bit platform because you're using a 64-bit kernel.

To run OCaml 5 you MUST have a full 64-bit ARM installation, including a 64-bit toolchain.  This could mean ditching Raspbian and using e.g. Ubuntu 22.04, which works fine in 64-bit mode on the rPi 4.

**Comment by Lupus** [comment]
TWIMC: changing the image to Raspberry Pi OS 64 bit solves the issue, OCaml compiles just fine.
![image](https://github.com/ocaml/ocaml/assets/105348/a07e515a-d439-4d4e-8dd6-876792535a8b)
