### ISSUE TITLE
"Unbound value" error message can hide relevant module type mismatches with interface file

### ISSUE THREAD

**Issue by gullcomb** [ocaml/ocaml#12272]
Consider `issue.mli`:

```ocaml
module type T = sig
  val x : unit
end
```

and `issue.ml`:

```ocaml
module type T = sig end

module F (M : T) = struct
  let () = M.x
end
```

which is an extremely reduced version of a mistake I made: add a component to a module type in an `.mli` and forget to update the same module type in the `.ml` but immediately use that component from a functor argument and only then trigger a rebuild.

In that case, the compiler's output is short:

```
File "issue.ml", line 4, characters 11-14:
4 |   let () = M.x
               ^^^
Error: Unbound value M.x
```

and gives no hint to the user that at the point the compiler issued the error message it considered `M` to have the `.ml`'s module type and did not look at all at the `.mli`/`.cmi` yet so could not know whether there was a mismatch of module types.

Just adding that `M` has type `T` and pointing to the relevant part of the functor's header and the definition of `T` in the `.ml` file would probably have been enough to immediately remind me that I forgot to update `T`'s definition in the `.ml` instead of spending several minutes puzzling out the error.

Obviously, triggering a rebuild between the `.mli` addition and the `.ml` use does trigger the `The implementation […] does not match the interface […]` error message. Less obviously, trying to put the two files together in a single module declaration with an explicit signature also triggers that message instead of reproducing the issue.

 * * *
<sup>In a related note, I've always found the duplication of public type definitions (be they value types or module types) in interfaces and implementations to be an annoying design flaw of OCaml. But I don't have the slightest hint of a beginning of a solution so I won't expand on that topic.</sup>

**Comment by Octachron** [comment]
First, a major issue is that interface files and implementations don't need to define items in the same order. Consequently, comparing an implementation that fails to typecheck to an interface file is not possible in general, because we might be missing important type equalities that are only introduced after the error.
 
Overall, one should keep in mind that only well-typed implementation are compared to their interface.

> Just adding that M has type T and pointing to the relevant part of the functor's header and the definition of T in the .ml file 

Pointing to the module type of `M` is an interesting suggestion for unbound error on qualified paths, especially if we can recover the location of the definitions of the module type since this would avoid the need to balance the usefulness of printing the module type with the noise induced by printing a lengthy module type.

**Comment by Octachron** [comment]
The idea of possibly reusing module type location is still on my investigation list, but this seems fair to close the original feature request which was not that closely related.
