### ISSUE TITLE
Change in behaviour with ocamlmktop, 5.0.0 to 5.1.0 beta 1

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#12356]
When running "make top" to build the Camlpdf top level with 5.1.0 beta 1 I get:

```
ocamlmktop <lots of .o files> -custom -g -o camlpdf.top <lots of .cmo files>
ld: warning: directory not found for option '-L/Users/john/.opam/5.1.0~beta1/lib/ocaml/ocamlmktop'
```

With 5.0.0 the warning does not appear.

This warning does not appear to prevent the resultant top level working.

Steps to reproduce:

Get trunk from https://github.com/johnwhitington/camlpdf.git , install `ocamlfind`, and type `make top`.

Is this an intentional change? If so, perhaps I just need to fix my build system. But I thought it worth flagging up.

**Comment by Octachron** [comment]
Thanks for the report : this was a missing cleaning step in #11745 : when we removed the need to link an initialization module (`ocamlmktop_init`) when using `ocamlmktop` ( in order to be able to register toplevel printers), we forgot to also remove the directory that contained this initialization module from the `ocamlmktop` include path.
