### ISSUE TITLE
Unix.create_process_env might not be multi-thread safe

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#12395]
The `Unix.execv*` functions allocate memory. This can lead to deadlocks in multi-threaded programs when calling `exec` following `fork` (see eg https://www.evanjones.ca/fork-is-dangerous.html). Apparently this issue is triggered in `Lwt_process`: https://github.com/ocsigen/lwt/blob/f83bcf3a9fba2217bf478e65fd7b02be2599b691/src/unix/lwt_process.cppo.ml#L142.

It seems to me that documenting this behaviour could be a good first step.

(Issue was riginally reported in Discuss: see thread starting at https://discuss.ocaml.org/t/help-review-the-new-file-manipulation-tutorial-on-ocaml-org/12638/10.)

**Comment by ChrisVine** [comment]
It's a small point but although `Unix.create_process` is now thread safe, `Unix.create_process_env` is not unless the underlying OS provides either `execvpe` or `posix_spawn`.  As and when the behaviour of `Unix.execv*` under threads is documented, there may possibly be a case for documenting `Unix.create_process_env` also.

The problem with Lwt_process has been noted in the Lwt repository at https://github.com/ocsigen/lwt/issues/959#issuecomment-1314353644

**Comment by gadmm** [comment]
As explained in the discuss thread where this was first brought up, many other bad things could happen between fork and execve in OCaml. There is now the following documentation for `Unix.fork`:

> It fails if the OCaml process is multi-core (any domain has been spawned). In addition, if any thread from the Thread module has been spawned, then the child process might be in a corrupted state.

This should strongly discourage the use of OCaml's fork with multithreaded programs (except rare cases). This includes execve as there is nothing that can be really done to make OCaml code async-signal-safe in the C sense (cf. polling). Does this help?

In OCaml 5, the runtime no longer relies on pthread_atfork and therefore it no longer interferes with forking from C. Therefore, an alternative is to perform fork+execve from C where usual async-signal-safety rules apply.

**Comment by gadmm** [comment]
`Unix.create_process_env` not being thread-safe on the other hand sounds like a serious bug!

**Comment by ChrisVine** [comment]
@gadmm On `Unix.create_process_env`, I think it's pretty much unavoidable.  And I wonder what supported systems don't provide `posix_spawn` or `execvpe`?  Presumably a small number might not or the emulation fallback would not have been provided, but I suspect that documenting the position would be enough.

**Comment by xavierleroy** [comment]
I changed the title of this issue to better reflect its actual content.  It's fine if `Unix.execv*` functions allocate memory using `malloc`, because, as documented already, `Unix.fork` is unreliable and should not be used at all if other threads or domains were spawned, from OCaml or from C.

Concerning `Unix.create_process_env`, there may be a simple way to implement `execvpe` semantics without dynamic memory allocation in the child.  However, I'm not sure your typical C library implements `execvp` without dynamic memory allocation, so there may be a problem with the emulated implementation of `Unix.create_process` as well.  At some point, OCaml cannot do better than the C standard library it builds upon...

**Comment by xavierleroy** [comment]
Note to self: this may be a legitimate case for using C99 stack-allocated, variable-length arrays (a.k.a. `alloca`) in the OCaml runtime system, even though I've refused to use this mechanism until now.

**Comment by ChrisVine** [comment]
~You know more about this than me, but my reading is that even if `execvp` has to be implemented using some kind of dynamic allocation, the implementation still has to find a way to do so successfully so as to start the new process image.  From the Open Group Base Specifications Issue 7, 2018 edition (the only version I have ready access to): "A call to any exec function from a process with more than one thread shall result in all threads being terminated and the new executable image being loaded and executed."~

~This seems to include all of `execl`, `execle`, `execlp`, `execv`, `execve` and `execvp`.~

**Update:**  Actually that's not relevant because in the child process there is only one thread running anyway.  But surely it "still has to work".

**Update 2** No it doesn't, and you are right.  execvp is not on the list of async-signal-safe functions, unlike `execl`, `execle`, `execv` and `execve`.  You live and you learn.

**Comment by xavierleroy** [comment]
> execvp is not on the list of async-signal-safe functions, unlike execl, execle, execv and execve

Interesting twist...  I looked at the OpenBSD implementation of `execvp` and it is careful not to use `malloc`; instead, it allocates working memory directly with `mmap`.  I'll look at the glibc implementation next.

**Comment by xavierleroy** [comment]
At any rate: it seems that `posix_spawn` is provided by the main platforms: Linux, macOS, and the BSDs, at least with sufficiently recent versions.  So, the  fork+exec emulation in OCaml's Unix library is rarely, if ever, used.  Moreover, there's a trivial fix to avoid using the `execvpe` emulation that allocates, which I'll submit shortly.  So, I don't think we need to add the mark of infamy ("not thread-safe") to the  documentation of `Unix.create_process_env`.

**Comment by xavierleroy** [comment]
In Glibc, `execvp` uses stack-allocated temporary space (via C99 variable-length arrays).

**Comment by avsm** [comment]
[FreeBSD's execvp](https://github.com/freebsd/freebsd-src/blob/main/lib/libc/gen/exec.c) uses `alloca`, and [musl libc's execvp](https://git.musl-libc.org/cgit/musl/tree/src/process/execvp.c#n30) (as seen in Alpine Linux most commonly) uses C99 variable-length arrays too.

**Comment by xavierleroy** [comment]
Thanks for having checked.  It looks like everyone did a good job implementing `execvp` without `malloc`, so we can use it in our backup implementation of `posix_spawn`.  See my proposal at #12404.

**Comment by ChrisVine** [comment]
@gadmm

> As explained in the discuss thread where this was first brought up, many other bad things could happen between fork and execve in OCaml. There is now the following documentation for `Unix.fork`:
> 
> > It fails if the OCaml process is multi-core (any domain has been spawned). In addition, if any thread from the Thread module has been spawned, then the child process might be in a corrupted state.

This text is not in the documentation for Unix.fork in ocaml-5.1

**Comment by xavierleroy** [comment]
> This text is not in the documentation for Unix.fork in ocaml-5.1

No, and neither is #12404, but both will be released in 5.2.
