### ISSUE TITLE
FreeBSD pthread_getaffinity_np not detected

### ISSUE THREAD

**Issue by VoxSciurorum** [ocaml/ocaml#12411]
On FreeBSD 13.2, 64 bit x86 or 64 bit ARM, s.h does not define `HAS_BSD_GETAFFINITY_NP` as expected.  The function `pthread_getaffinity_np` is not found because command line to compile the test program needs -pthread or -lpthreads.

```
configure:18103: cc -o conftest    conftest.c -lm  >&5
ld: error: undefined symbol: pthread_getaffinity_np
>>> referenced by conftest.c
>>>               /tmp/conftest-2a7a19.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gasche** [comment]
cc @shindere: this sounds like a configure issue

**Comment by shindere** [comment]
Do you have the possibility to try the
`fix-pthread-affinity-np-detection` branch of `shindere/ocaml` to see
whether it fixes the problem, please?

AIUI, the test involving `pthread`getaffinity_np` occurs in `configure`
before the detection of pthread libraries so it can not really work and
that's what this branch changes and hopefully fixes.

**Comment by VoxSciurorum** [comment]
The patch did not work because `$LIBS` did not contain -lpthread even when the test was moved later.

With the following patch the function is detected.  I am not familiar with autoconf so I can't say if this is the "right" way to do it.

[affinity.diff.txt](https://github.com/ocaml/ocaml/files/12148120/affinity.diff.txt)

**Comment by shindere** [comment]
John F. Carr (2023/07/24 09:46 -0700):
> The patch did not work because `$LIBS` did not contain -lpthread even
> when the test was moved later.

Could you please run configure with the branch I provided and share the
`config.log` you get by doing so?

Re:your patch is it on top of trunk or on the branch I provided?

**Comment by VoxSciurorum** [comment]
My patch was relative to the fix-pthread-affinity-np-detection branch.

I attached a config.log from an ARM system.  X86 has the same behavior.

[config.log.txt](https://github.com/ocaml/ocaml/files/12174882/config.log.txt)

**Comment by shindere** [comment]
John F. Carr (2023/07/26 09:17 -0700):
> My patch was relative to the fix-pthread-affinity-np-detection branch.

OK thanks, and thanks for your config.log too, which helped.

Could you please give the `fix-pthread-affinity-np-detection` branch
another go?

I think there was another problem, which was that the flags and
libraries detected to be necessary for pthread to work were not kept in
the CFLAGS and LIBS variable, whichthe branch now should fix. I'm a bit
surprised that things worked until now and that nobody complained so if
you can confirm that the branch now fixes the problem I'll submit a PR.

**Comment by VoxSciurorum** [comment]
With the new branch `pthread_getaffinity_np` is detected but arguably it works for the wrong reason.

On FreeBSD 12, which is nearing end of life, the patch works as intended.  The GNU version does not compile and the BSD version does.  `HAS_BSD_GETAFFINITY_NP` is defined.

On FreeBSD 13 and 14 configure incorrectly detects the GNU flavor of `pthread_getaffinity_np`.  The FreeBSD implementation has become sufficiently compatible that the runtime compiles without warning.   If there is a test that depends on `pthread_getaffinity_np` working in the runtime I can run it.

A missing function declaration is a warning rather than an error.
```
configure:19281: checking arguments for pthread_getaffinity_np
configure:19299: cc -o conftest  -pthread   conftest.c -lm  -lpthread >&5
conftest.c:145:7: warning: call to undeclared function 'pthread_getaffinity_np'; ISO C99
and later do not support implicit function declarations [-Wimplicit-function-declaration]
      pthread_getaffinity_np(pthread_self(), sizeof(cs), &cs);
      ^
1 warning generated.
configure:19299: $? = 0
configure:19301: result: gnu
```
This warning does not appear compiling the runtime because domain.c includes the right set of header files.

I don't have any other BSD flavors to test on.

**Comment by shindere** [comment]
Many thanks for for your detailed feedback.

John F. Carr (2023/07/27 13:11 -0700):
> On FreeBSD 13 and 14 configure incorrectly detects the GNU flavor of
> `pthread_getaffinity_np`.  The FreeBSD implementation has become
> sufficiently compatible that the runtime compiles without warning.
> If there is a test that depends on `pthread_getaffinity_np` working in
> the runtime I can run it.

This function is called by the runtime primitive
`caml_recommended_domain_count`, which is itself called by the
`Domain.Raw.get_recommended_domain_count` function from the standard
library, in turn called by `Domain.recommended_domain_count`.

I think the test in
`testsuite/tests/parallel/recommended_domain_count.ml` exercises this.
You can run it directly e.g. by doing, from the toplevel of the source tree:

./ocamltest/ocamltest.opt testsuite/tests/parallel/recommended_domain_count.ml

> A missing function declaration is a warning rather than an error.
> ```
> configure:19281: checking arguments for pthread_getaffinity_np
> configure:19299: cc -o conftest  -pthread   conftest.c -lm  -lpthread >&5
> conftest.c:145:7: warning: call to undeclared function 'pthread_getaffinity_np'; ISO C99
> and later do not support implicit function declarations [-Wimplicit-function-declaration]
>       pthread_getaffinity_np(pthread_self(), sizeof(cs), &cs);
>       ^
> 1 warning generated.
> configure:19299: $? = 0
> configure:19301: result: gnu
> ```
> This warning does not appear compiling the runtime because domain.c
> includes the right set of header files.

OK, is that to say that the configure test is also missing the right set
of headers and that the warning we currently see can not be used because
it's there just because we fail to include the right headers?

I'm wondering, thus, how the BSD implementation is supossed to be
distinguished for the GNU one or even whether it should be
distinguished, if efforts have been made to makeit compatible enough,
perhaps we can just make this work? Perhaps it does actually already
work and the only fix is to add the right headers to the configure test?

Let's see whether the test mentionned above passes?

**Comment by VoxSciurorum** [comment]
The recommended_domain_count.ml test passes on FreeBSD systems with 4, 32, and 48 cores or threads.

According to the git log FreeBSD has been trying to provide a more Linux-like cpuset interface.  That's why the function was detected as GNU flavor.  The GNU flavor code in domain.c should work unless you define one of the strict standards macros `_ANSI_SOURCE`, `_C99_SOURCE`, or `_C11_SOURCE`.

I think the test will be more robust if the configuration test program includes `<pthread_np.h>`, which is where the function should be declared.  See diff relative to your branch:
[affinity-check.diff.txt](https://github.com/ocaml/ocaml/files/12197985/affinity-check.diff.txt)

**Comment by shindere** [comment]
Thanks a lot for this!

I just submitted #12443 (beware, the name of the branch is slightly
different).

It'd be nice if you could re-test it (for the last time hopefully),
making sure the configure test now does not produce any warning and then
that the involved test passes.

**Comment by omasanori** [comment]
I have triggered CI servers using <https://github.com/ocaml/ocaml/pull/12416>. The BSD variant is detected on [FreeBSD 12](https://builds.sr.ht/~omasanori/job/1031775#task-configure-234), the GNU variant is detected on [FreeBSD 13](https://builds.sr.ht/~omasanori/job/1031768#task-configure-234), and neither is detected on [NetBSD 9.2](https://builds.sr.ht/~omasanori/job/1031769#task-configure-231) and [OpenBSD 7.2](https://builds.sr.ht/~omasanori/job/1031770#task-configure-232). NetBSD looks misbehaving but it may be out-of-scope.

**Comment by VoxSciurorum** [comment]
On FreeBSD 12.4, 13.2, and 14 configure completes without any warnings related to getaffinity and the recommended_domain_count.ml test passes.   I also observe that the BSD variant is selected on 12.4.  The Linux compatibility changes were introduced in 13.1 or 13.2.

**Comment by shindere** [comment]
Masanori Ogino (2023/07/29 02:47 -0700):
> I have triggered CI servers using
r> <https://github.com/ocaml/ocaml/pull/12416>. The BSD variant is
> detected on [FreeBSD
> 12](https://builds.sr.ht/~omasanori/job/1031775#task-configure-234),
> the GNU variant is detected on [FreeBSD
> 13](https://builds.sr.ht/~omasanori/job/1031768#task-configure-234)

That looks conform to what's expected.

> and neither is detected on [NetBSD
> 9.2](https://builds.sr.ht/~omasanori/job/1031769#task-configure-231)

I had a hard time readingthepage because its accessibility (in terms of
WCAG) isreally poor. Would you mind copyingthe relevant lines of output
of configure here and perhaps even those of config.log?

WhatI oculd see was that one test failed in both bytecode and native
mode but that these failures seemed unrelated (I assume they occur in
the similar way on nust trunk).

> and [OpenBSD
> 7.2](https://builds.sr.ht/~omasanori/job/1031770#task-configure-232).

Here I didn't see the problem because allthe tests seemed to pass but
then I am guessing that the problm is in the output of configure and so,
if you similarly could copy/pase therelevantlines here that would be
especially helpful.

**Comment by omasanori** [comment]
> I had a hard time reading the page because its accessibility (in terms of
WCAG) is really poor. Would you mind copying the relevant lines of output
of configure here and perhaps even those of config.log?

Of course, no problem, though I have no access to `config.log`.
```
checking arguments for pthread_getaffinity_np... pthread_getaffinity_np not found
```
After searching the NetBSD source code by myself, it seems that NetBSD requires `_NETBSD_SOURCE` for non-portable definitions and it has no `pthread_np.h`. For brevity, I think it would be fine to finish this issue with sorely FreeBSD fix.

> Here I didn't see the problem because all the tests seemed to pass but
then I am guessing that the problem is in the output of configure and so,
if you similarly could copy/paste the relevant lines here that would be
especially helpful.

Sorry for my confusing message. OpenBSD is completely fine since it has no `pthread_getaffinity_np`.
