### ISSUE TITLE
Stubs DLLs are often optimized out with MSVC link.exe, limiting use of toplevel

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/ocaml#12412]
### Context

Windows 11
OCaml: 4.14.0 with Visual Studio 2019
Distribution: DkML 2.0.1 (unreleased installer snapshot: https://gitlab.com/diskuv-ocaml/distributions/dkml/-/package_files/86309425/download)

### Symptoms

In a top-level I can successfully load packages with stubs ... but only if they have at least one explicit symbol reference to their stub.

Example: `graphics` has at least one symbol reference at https://github.com/ocaml/graphics/blob/77572a472ab76a44270b4b2e6dcd9acc01905ec9/src/graphics.ml#L23:

```ocaml
external raw_open_graph : string -> unit = "caml_gr_open_graph"
```

However, most packages that bind to C use `ctypes`. Those packages (ex. `sqlite3`, `tsdl`) do not have an explicit symbol reference ... instead those packages use `libffi` to query C functions from the *DLLs available at load-time*.

Here is an example (I use `utop` but `ocaml` has the same issue) of the problem:

```
utop # #require "sqlite3";;
Cannot load required shared library dllsqlite3_stubs.
Reason: dllsqlite3_stubs.dll: The specified module could not be found.
utop # #require "graphics";;
utop #
```

even when all the stubs are present:

```
    Directory: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\DiskuvOCaml\desktop\bc\lib\stublibs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-ar---         7/22/2023  12:58 PM          13312 dllbase_internalhash_types_stubs.dll
-ar---         7/22/2023  12:58 PM          15360 dllbase_stubs.dll
-ar---         7/22/2023  12:58 PM          31744 dllgraphics_stubs.dll
-ar---         7/22/2023  12:58 PM          20480 dlllambda_term_stubs.dll
-ar---         7/22/2023  12:58 PM          49152 dlllwt_unix_stubs.dll
-ar---         7/22/2023  12:58 PM          56832 dllsqlite3_stubs.dll
-ar---         7/22/2023  12:58 PM          10752 dllstdcompat_stubs.dll
-ar---         7/22/2023  12:58 PM          34816 dllxdg_stubs.dll
```

### Problem

The stub import libraries are making it to MSVC's `link.exe` linker. But MSVC will, as an optimization, remove any shared libraries from the `link.exe` invocation that don't have at least one symbol reference. So, the stub DLL will not be implicitly linked (https://learn.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=msvc-170#implicit-linking) on Windows. 

It sounds like the problem is with ctypes but if we want libraries referenced in `.cma` files to be handled the same way on Unix and on Windows then DLLs should be attached to the `ocamlc` compiled executable at load-time (ie. implicit load-time linking).

@dra27 mentioned having `link.exe` use [`/INCLUDE`](https://learn.microsoft.com/en-us/cpp/build/reference/include-force-symbol-references?view=msvc-170) to force the DLL to be loaded. That sounds look it should work.

### Mitigations

Package maintainers can hack their OCaml code to explicitly have one reference to the C code, like was done in https://erratique.ch/repos/tsdl/commit/?id=9a5f889025305b7b028e72a7467adda162cf0d88

### Other Notes

I don't know which issue queue this belongs (here or flexdll).

**Comment by jonahbeckford** [comment]
Closing. Will re-open and edit when I have the correct test case. The one above (`sqlite3`) was just a missing dependent DLL and not a good example for what I debugged earlier.

**Comment by dra27** [comment]
Looking at the referenced commit in Tsdl, I think it's worth conceptually separating out libraries which use hand-rolled stubs (like graphics above, and sqlite3) and ctypes-based ones, like Tsdl. For the hand-rolled stubs libraries, the references to the stubs library  (`dllgraphics_stubs.dll`, `dllsqlite3_stubs.dll`, etc.) shouldn't ever pose a problem because the stubs should be being referenced by `external` statements in the library's OCaml modules (I can imagine being able to contrive a series of modules where this doesn't work, but you'd have to work really hard to hit this issue with hand-rolled C stubs, I think, and it could _always_ be solved with `-linkall` on the resulting .cma/.cmxa).

For the ctypes case, it looks like this should be fixed on the application-side as a Windows-specific (or possibly even MSVC-specific) quirk. The `/INCLUDE` mechanism looks like it'd fix MSVC - I'm guessing that binutils either doesn't do this kind of "optimisation", or that ld will have some equivalent magic switch somewhere. Rather than Windows-specific C no-op stub used in Tsdl, I'm wondering whether a Windows-specific call to `Dl.dlopen` is sufficient to allow the subsequent calls to resolve the symbols (even without having to put `~from` on all the foreign declarations) - i.e. whether just doing `ignore (Dl.dlopen "sdl2.dll")` or whatever it exactly is is sufficient to load the library and allow all the subsequent ctypes magic to work).

**Comment by jonahbeckford** [comment]
Re-opening. When you say "application-side" do you mean fix within ctypes? Or individually in each of the [126+ packages which use ctypes](https://v3.ocaml.org/p/ctypes/latest#used-by)?

Aside: I've had a years long issue with ctypes to accept my MSVC patch, so I have forked ctypes at an old version for DkML/MSVC users ... and I won't be following up with ctypes. However, I'm not convinced this is a ctypes issue, even if completely agree that ctypes packages should be the only ones affected by the issue.

**Comment by dra27** [comment]
I'm not sure (without digging into it further than I have time to at the moment) whether the fix would be in ctypes or in the libraries themselves - but it does look at the moment as though the fix isn't in OCaml itself, inasmuch as OCaml's C FFI I think is working correctly (don't mind at all the issue staying open to track this, though). As far as I can tell here, the compiler drivers (`ocamlc`/`ocamlopt`) are passing on link flags specified by the library/application (i.e. ctypes, or the library using ctypes), but it's that additional flags may be needed for MSVC which ocamlc/ocamlopt nor flexlink are in a position to infer (I guess flexlink is _possibly_ in a position to have a feature added to do force-linking by inspecting the symbols available in a DLL and working out an appropriate `/INCLUDE` flag).
