### ISSUE TITLE
GADT exhaustiveness check fails with structurally equal records/variants

### ISSUE THREAD

**Issue by slamko** [ocaml/ocaml#12472]
The following code snippet:
```ocaml
module Wrapper = struct
  type x = { a : int; } 
  (* structurally identical records *)
  type y = { a : int; }
end

open Wrapper

type _ witness =
  | X : x witness
  | Y : y witness

let not_exhaustive_match_records: type a. a witness -> a witness -> unit =
  fun w1 w2 ->
  match w1, w2 with
  | X, X -> () 
  | Y, Y -> ()
```
when compiled with ```ocamlopt``` or ```ocamlc``` version 5.0.0 produces the warning 8 [partial-match] : 

```sh
15 | ..match w1, w2 with
16 |   | X, X -> () 
17 |   | Y, Y -> ()
Warning 8 [partial-match]: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(X, Y)
```

The same applies for the following code:
```ocaml
module Wrapper = struct
  type x = A

  type y = A
end

open Wrapper

type _ witness =
  | X : x witness
  | Y : y witness

let not_exhaustive_match_variants: type a. a witness -> a witness -> unit =
  fun w1 w2 ->
  match w1, w2 with
  | X, X -> () 
  | Y, Y -> ()

```
notice structurally equal variants ```Wrapper.x``` and ```Wrapper.y``` and **the presence of the module ```Wrapper``` itself, which is crucial in both cases.**  
  

Nevertheless, an attempt to provide the last function with ```witness```es of different types results in an error:
```ocaml
let _ = not_exhaustive_match_variants X Y
```
```sh
| let _ = not_exhaustive_match_variants X Y
                                          ^
Error: This expression has type Wrapper.y witness
       but an expression was expected of type Wrapper.x witness
       Type Wrapper.y is not compatible with type Wrapper.x
```
Same for:
```ocaml
let _ = not_exhaustive_match_records X Y
```

I'm using "The OCaml compiler, version 5.0.0" on x86_64 Void Linux.

**Comment by gasche** [comment]
In OCaml, where you see two type definitions

```ocaml
  type x = { a : int }
  type y = { a : int }
```

exported in a module interface, this *may* come from two declarations looking exactly similar:


```ocaml
  type x = { a : int }
  type y = { a : int }
```

*or* (among other things) from the re-export of a previous definition, looking as follows:

```
  type x = { a : int }
  type y = x = { a : int }
```

The declaration `type y = x = { a : int }` can be exported with the precise signature `type y = x = { a : int }`, or with the less precise signature `type y = { a : int }`, which is the same signature you get if `y` is declared separately. There is no way in the interface / typing environment to distinguish between "`y` was declared as a new record" or "`y` is secretly a re-export of an existing record"; this matters for compatibility purposes (you can move a declaration to a different place, changing the previous declaration site into a re-export, and nothing breaks).

In consequence, the type-checker can neither assume that `x` and `y` are definitely equal, nor that they are definitely inequal. Using them with GADTs gets somewhat awkward, but this is an inevitable outcome from a design choice, rather than a bug in itself.

If the two definitions are part of the *current* module, they is no abstraction boundary between their declaration and the current program point, the type-checker uses stronger rules -- it knows more about which types are the same or not. People have criticized this aspect (the type-checker knows more about local declarations) as creating surprises / usability cliffs, and it is proposed to remove it ( #8900 ). (See also #9042 and https://github.com/ocaml/RFCs/pull/4 ).
