### ISSUE TITLE
Map.fold_back or Set.fold_back

### ISSUE THREAD

**Issue by hummy123** [ocaml/ocaml#12476]
Hi there,

The [map.ml](https://github.com/ocaml/ocaml/blob/96d1702bd287f94a0e76013820e07e3466c32d66/stdlib/map.ml#L325 file has a fold function coded as:
```
    let rec fold f m accu =
      match m with
        Empty -> accu
      | Node {l; v; d; r} ->
          fold f r (f v d (fold f l accu))
```

And there is an equivalent fold function in set.ml.

I think it could be helpful in some cases to have a fold_back function which would just switch around the 'l` and `r` parameters around in the above implementation. If I wanted to consΩ a list out of the set/map for example, it would usually make more sense to fold from the other side because then the list would be in order.

I wouldn't have minded opening a pull request for this alternative function myself (it just involves copy-pasting the function while swapping two variables around), but I wasn't sure what an appropriate name would be. The `Array` module has `fold_left` and `fold_right`, but I think adopting that naming scheme for maps/sets would require changing the name of the `fold` function which would break user code.

F# has `fold` and `foldBack` (which are like `fold_left` and `fold_right` respectively) which wouldn't break user code but then there's incnsistency with the names of the fold functions here and in the Array module.

I think it's a helpful little function for many scenarios but not 100% sure if it's worth breaking the naming consistency/user code for.

**Comment by gmevel** [comment]
I think the best option is to add `fold_left` as a new name for `fold`, and add your new function under the name `fold_right`.

BTW: the existing `fold` function has its arguments in a confusing order: what it does is technically a `fold_left` but its arguments follow the convention of `fold_right`. I think the new name `Set.fold_left` should swap the arguments, instead of being a mere alias.

**Comment by nojb** [comment]
From a distance it makes sense to have a fold that goes over the elements of the map or set in decreasing order instead of increasing order, but I don't remember missing this function often so I don't have a strong opinion about it. Let's wait to see if other devs chime in.

For the naming, calling this function `fold_right` (and aliasing the existing `fold` to `fold_left`) may make sense.
