### ISSUE TITLE
Lower the precedence of the `assert` keyword

### ISSUE THREAD

**Issue by ddickstein** [ocaml/ocaml#12506]
Right now the `assert` keyword requires parentheses around boolean expressions that are passed to it, e.g.,
```
assert (not false);
```
It would be nice not to have to write these parentheses.

**Comment by nojb** [comment]
> Right now the `assert` keyword requires parentheses around boolean expressions that are passed to it, e.g.,

This is not quite true. For example, `assert false` does not require any parentheses. In general, `assert` requires parentheses in exactly the same way as any other function application.

> It would be nice not to have to write these parentheses.

While `assert` is a reserved keyword, it behaves in most respects like a regular function application. It is hard to imagine any upside in breaking this uniformity. On that basis alone, I don't think such a change should be entretained.

**Comment by hyphenrf** [comment]
> I don't think such a change should be entretained.

nevertheless, allow me to entertain the idea because I wasn't convinced that "behaves like function application" is enough of a reason (considering for example that `assert` can't be passed around like the regular keywordish function `raise` would, among other features that make it special and not first-class).

If precedence was to be altered, when does the assertion stop? one is inclined to say at the `;` following the assertion expression, but today `assert true |> print_newline` is acceptable code.
It really seems unlikely this change will be as nice as it sounds at first..

At least that's how it appears to me

**Comment by Octachron** [comment]
I also believe that precedence uniformity is better in this case. Let's close the issue in the absence of explicit support for the feature.
