### ISSUE TITLE
incorrect Makefile dependencies

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#12521]
I just did the following on a `trunk` repository at commit 76c4617b90934c418fdd21b9af42bb52590754e8 :

```
./configure
make -j
# this works: I can run the testsuite, etc.
<change something in typing/typecore.ml
 that affects generated code without breaking the compiler>
make -j
```

On the second (incremental) build, I get the following errors:

```
File "_none_", line 1:
Error: Files otherlibs/dynlink/dynlink.cmxa and ./stdlib/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__Uchar
make[2]: *** [Makefile:164: ocamlnat] Error 2
make[2]: *** Waiting for unfinished jobs....
[...]
File "_none_", line 1:
Error: Files ../otherlibs/unix/unix.cmxa and ../stdlib/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__Printf
make[3]: *** [Makefile:170: ../ocamldoc/ocamldoc.opt] Error 2
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/gasche/Prog/ocaml/github-matching/ocamldoc'
make[2]: *** [Makefile:1245: ocamldoc.opt] Error 2
make[2]: Leaving directory '/home/gasche/Prog/ocaml/github-matching'
make[1]: *** [Makefile:311: opt.opt] Error 2
make[1]: Leaving directory '/home/gasche/Prog/ocaml/github-matching'
make: *** [Makefile:381: world.opt] Error 2
```

My understanding is that redoing `make -j` after changing something in the compiler should work correctly -- it should incrementally rebuild a working compiler, unless the change is broken, and that the failures I observe are the sign of incorrect dependencies.

I have the vague impression that this used to work correctly in the past, and that this may be a regression due to recent-ish changes to the build system.

Note: the reason I am doing `make -j` and not `make -j core` is that I need to run the testsuite. If it was possible to request a bytecode-only testsuite run without configuring with `--no-native-compiler`, I would not run into these issues of dependencies with non-core tools. (We discussed this in https://github.com/ocaml/ocaml/pull/12339#issuecomment-1638317342 already.)

**Comment by gasche** [comment]
Note: I managed to fix my build by running `make -C otherlibs clean`, then `make -C ocamldoc clean`, and then `rm ocamltest/*.cm*`. I would usually run `make -C ocamltest clean`, but this is not possible anymore now that `ocamltest/Makefile` is merged in `Makefile` (for good reasons). It would be convenient to still have access to a target `ocamltest-clean` or something to deal with this situation.

**Comment by lthls** [comment]
I think this is a case where the dependency on the standard library is not properly recorded, so some files that should have been recompiled are not and they conflict with files that do get recompiled.
I don't think we've ever had a solution for that.

**Comment by dra27** [comment]
Indeed, it's a "missing" dependency on stdlib.cmxa. The problem is that if we add the dependency, virtually any change requires the whole of opt (and opt.opt) to rebuild, which I think is why it's not done at the moment. It can be easily repro'd by making any trivial change to a standard library implementation.

We should definitely do something to make the rebuild in this situation easier (i.e. some kind of rebuild or `clean-for-native-rebuild` target). A possibility might be to develop with `-opaque` used more, which I think will reduce the number of cases where recompilation is necessary (that's basically what Dune does to get around this). The perfect compromise is to have a trick similar to `runtime/primitives` but using the interface implementations, but this can't be done in the same way as for runtime/primitives (because we can't "statically" determine the checksums). Doing it for cmxa would require staging the build. I'll muse over this with @shindere - there may be a neat enough way to enable this when working on the compiler, without making the build too ridiculously meta-programmed.

As a small tip which works now, you can always edit `ocamltest/ocamltest_config.ml` and change `native_compiler` to `false` and you'll have an ocamltest in a tree configured _without_ `--disable-native-compiler` which doesn't test native code. It's a hack, obviously, but it does work _right now_ 🙂

**Comment by gasche** [comment]
My take-away is:

1. my vague intuition is probably wrong and no recent change touched this
2. there is no hope for a short-term fix
3. so we may as well close this issue

Some things mentioned so far still deserve remembering or further discussion.

A. It would be nice to keep `clean` targets for subdirectories when we need this. (Or @dra27's proposal of a `nativeclean` target?)
B. We should use `-opaque`. I thought that we used `-opaque` already, but I just checked and indeed we don't. (But then, systematic use of -opaque means that we don't dogfeed our cross-module optimizations, which is probably not such a great idea.)
C. There are ways to configure ocamltest to do byte-only tests. I should find the time to make them controllable through an environment variable and my life would magically improve.

**Comment by lthls** [comment]
> As a small tip which works now, you can always edit `ocamltest/ocamltest_config.ml` and change `native_compiler` to `false` and you'll have an ocamltest in a tree configured _without_ `--disable-native-compiler` which doesn't test native code. It's a hack, obviously, but it does work _right now_ 🙂

If you happen to also have a hack that allows ocamltest to test the native compilers without using the native binaries, I'm interested. Ideally something that can be run after `make opt`.

> B. We should use `-opaque`. I thought that we used `-opaque` already, but I just checked and indeed we don't. (But then, systematic use of -opaque means that we don't dogfeed our cross-module optimizations, which is probably not such a great idea.)

I'm not really fond of this suggestion. I'm fine with a special configuration flag that enables a fast-compile mode (using opaque if it helps), but to get actual benefits from it we need to update the dependency files, so more work on the build system side.
Besides, while bytecode compilation is done using the bootstrap compiler, which doesn't change when you change the sources, native compilation uses the compiler generated from the sources, so any trivial change may require you to redo the whole native compilation, opaque or not. This dependency isn't tracked either, of course.
