### ISSUE TITLE
Allow or pattern to be used with GADT

### ISSUE THREAD

**Issue by glyh** [ocaml/ocaml#12529]
I'm trying to implement a series of ASTs that looks similar with GADT(ref: this [paper](https://icfp23.sigplan.org/details/ocaml-2023-papers/4/Modern-DSL-compiler-architecture-in-OCaml-our-experience-with-Catala)), but running in to problems. 
Here's an example:
```ocaml
type yes = Y
type no = N
type u = U
type v = V

type ('a, 'b) e = 
   | B1: string -> (v, 'b) e
   | B2: string -> (v, 'b) e
   | Seq: (u, 'b) e list -> (u, 'b) e
   | If: (u, 'b) e * (u, 'b) e * (u, 'b) e -> (u, 'b) e
   | IfSeq: (u, 'b) e * (u, 'b) e list * (u, 'b) e list -> (u, <seq: yes; ..> as 'b) e

type top = <seq: yes;>
type deseqed = <seq: no;>

let rec deseq: type a. (a, top) e -> (a, deseqed) e = function
   | IfSeq(test, _then, _else) -> If(deseq test, Seq(List.map deseq _then), Seq(List.map deseq _else))
   | B1(_) as e -> e
   | B2(_) as e  -> e
   | B1(_) | B2(_) as e -> e(* what the paper wrote, but still error *)
   | e -> e (* what I expect, but ocaml's type system doesn't seem to be able to handle this *)
   | _ -> raise Unimplemented
```

so the main concern is that, ocaml should know the pattern of type `a b` is compatible with type `a' b`, where b is a GADT, but it didn't. 

This is useful for avoiding redundant code. In my case, ` B1(_) | B2(_) as e -> ...` actually invokes another function which I can't even abstract out of it because otherwise ocaml can't deduce the type of it.

**Comment by gasche** [comment]
It is a well-known limitation that we don't handle GADTs under or-patterns well, and I am not aware of any plans to do the considerable implementation to try to lift it. I don't think that this feature wish will be granted soon. 

Have you tried working with polymorphic variants instead of GADTs? They are designed to work well for ASTs sharing constructor, and pattern-matching handles them well. You have to remember to annotate your code to avoid unclear error messages, but GADTs also impose an annotation burden anyway. I think you should give variants a try.

(I considered closing the issue as "not planned", not sure if this is the right move triaging-wise.)

**Comment by glyh** [comment]
Thanks, I may take a look on that.
