### ISSUE TITLE
why does building the toplevel (eg. `make runtop`) also builds flambda?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#12569]
The `make runtop` target, which I use on a very regular basis, seems to spend some time in the `middle_end` repository building the Flambda sources. Do we know why, and is it reasonably easy not to do this? (I haven't quantified the time spent there, and I am not claiming that it is large; we should do measurements before spending any non-trivial time on this question.)

**Comment by dra27** [comment]
This is something which, in various combinations, @shindere, @stedolan and I have discussed, indeed. It's something of a "build smell" how much of the middle end is compiled during `make world` and even more so in `opt.opt` where compiling  `ocamlmiddleend.cmxa` with flambda's modules when you're not actually building the flambda compiler is a significant amount of time.

A spattering of numbers, based on timings for my machine. Building the toplevel minimally - which is `make -j coldstart ; make -j ocamlc ; make -j ocaml` doesn't compile flambda's modules, but it does require some of the .cmi files from the middle end (I didn't check, but I would expect the compilation time of those to be insignificant). That's roughly 18.4s for me.

`make runtop`, on the other hand also builds `otherlibraries` and that pulls in `ocamltools` (for `ocamlmklib`). `ocamlobjinfo` needs `ocamlmiddleend`, which is why one sees flambda being compiled in `runtop` (and it would also be seen when building the toplevel "normally", via `coreall`). That's roughly 38.7s for me.

Temporarily removing ocamlobjinfo from the list of tools to build saves just over 1s.

Various observations:
- The need to compile the whole of `ocamltools` in order to do `runtop` I would expect ultimately to disappear as part of @shindere's `Makefile` merging, because rather than the opaque `otherlibraries: ocamltools` we can move towards more precise dependencies - i.e. building otherlibraries would only build the _required_ `ocamlmklib`.
- @shindere's and @stedolan's work on getting rid of `dynlink_compilerlibs` is much more impactful - just under 4s removed from `make runtop` from cold.
- At present, there's still a big build performance regression since the reserved keywords PR was merged for which I have a tentative workaround which I will try to get actually opened this week. This effect of this dwarfs everything else being discussed: it adds 13.5 seconds to `make runtop` from cold for me. Note that the build performance regression is not the reserved keywords change itself, but rather the change in dependency graph (which is really very surprising...!).

**Comment by gasche** [comment]
Thanks for the details and numbers. Why does `runtop` need `otherlibraries`? I think that you suggest  that `ocamlmklib` is used, but I don't see what requires it in the `runtop` target.

**Comment by gasche** [comment]
Answering to myself: I guess that `otherlibraries` is built for people who would want to use Unix or ... (what?) from the toplevel. Maybe we could just remove it as a dependency and let the people who want to use otherlibs from the toplevel build it separately?

(On my machine, a cold run `runtop` takes 1m20s, removing otherlibraries makes it 40s, so roughly twice as fast.)

**Comment by gasche** [comment]
Thanks to @shindere I just merged #12573 that makes `runtop` not depend on otherlibs -- an alternative new target `runtop-with-otherlibs` is available for that use-case. This halves the cold build time, and the saving is probably larger than anything flambda-related. I feel happy about this and I propose to close the present issue -- even if the dependency on some parts of the middle-end is probably still there and could be investigated. Thanks both!
