### ISSUE TITLE
misuse of #ifdef DEBUG

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#12621]
In `runtime/caml/misc.h`:

```
#ifdef DEBUG
#ifdef UNICODE
... some stuff ...
#else
... some other stuff...
#endif

#define CAMLassert(x) ... definition ...
CAMLnoreturn_start
CAMLextern void caml_failed_assert (char *, char_os *, int)
CAMLnoreturn_end;
#else
#define CAMLassert(x) ((void) 0)
#endif
```

I think this should be restructured:
```
#ifdef DEBUG
... debug stuff only
#endif
#ifdef NDEBUG
#define CAMLassert(x) ((void) 0)
#else
... 
#endif
```

The problem is that -DDEBUG forces `-runtime-variant=d`, and those are separate concerns. This causes a problem with the standard Bazel cc toolchain, which unfortunately passes `-DDEBUG` when compilation mode is `fastbuild` (which is the default). It can be worked around, but the root cause is that OCaml is conflating DEBUG and NDEBUG.

**Comment by gasche** [comment]
I'm no C expert, and I don't understand your issue. I looked at the doc, it looks like `assert.h` from the C standard library is defined to be active not when DEBUG is defined, but when NDEBUG is not defined. Okay.

1. What does it have to do with the OCaml build?
2. What would you expect a build with -DDEBUG to have as "debug stuff"?

My reading of the situation is that `CAMLassert` in the runtime code should be thought of as a "debug assert" rather than an "enabled-all-the-time assert", so it is different from C's `assert`.

If bazel passes -DDEBUG and not -DNDEBUG, my understanding would be that it is asking to get both the debug and non-debug assertions. OCaml does this correctly -- it enables debug assertions, which is all it has. What is the issue?

**Comment by mobileink** [comment]
It leaks an internal build detail to users of the C API.  Use of DEBUG in user code should not force use of an ocaml debug build - I might want to DEBUG my, code, not the OCaml runtime. I suppose the easy fix would be to rename DEBUG to OCAML_DEBUG (or RUNTIME_VARIANT_DEBUG or something), or just to remove DEBUG from the public API.  Or you could use DEBUG and NDEBUG as I suggested, and then to build ocaml pass -DDEBUG (and implicitly -UNDEBUG) for a debug build and -DNDEBUG (and implicitly -UDEBUG) for a non-debug build.

"If bazel passes -DDEBUG and not -DNDEBUG, my understanding would be that it is asking to get both the debug and non-debug assertions."

-DDEBUG has nothing to do with assertions.

**Comment by gasche** [comment]
I don't understand. You can compile the OCaml runtime with or without DEBUG, and link it with user code compiled with or without DEBUG, right? (Of course if you want to call runtime functions that are only defined when DEBUG is set, you have to link with a DEBUG runtime.) Are you trying to reuse `CAMLassert` in your own code rather than just `assert`?

**Comment by stedolan** [comment]
> Use of DEBUG in user code should not force use of an ocaml debug build - I might want to DEBUG my, code, not the OCaml runtime.

Use of DEBUG when compiling user code causes:

  - `CAMLassert(foo)` in user code to not be a noop
  - Some OCaml debugging definitions (`Debug_tag` and friends) to become available in user code

I don't think it has much other effect? It certainly doesn't force use of a debug build of the ocaml runtime, at least not unless you compile the whole runtime with `-DDEBUG` (in which case, presumably that's what you want?)

**Comment by gasche** [comment]
I propose to close for now, and I promise to reopen if/when I understand what the issue is.
