### ISSUE TITLE
Warning 5 starts appearing in 5.1

### ISSUE THREAD

**Issue by jchavarri** [ocaml/ocaml#12627]
The following code used to compile without warnings in 5.0 and earlier versions:

```ocaml
let all = (Hashtbl.create 10 : (string, int -> string) Hashtbl.t)

let register name table =
  match Hashtbl.find all name with
  | _ -> failwith "handler exists"
  | exception _ -> Hashtbl.replace all name table
EOF
```

In 5.1 the compiler starts showing warning 5 [ignored-partial-application], as shown next:

```bash
$ cat > main.ml <<EOF
let all = (Hashtbl.create 10 : (string, int -> string) Hashtbl.t)

let register name table =
  match Hashtbl.find all name with
  | _ -> failwith "handler exists"
  | exception _ -> Hashtbl.replace all name table
EOF
$ ocamlopt -o program main.ml
File "main.ml", line 4, characters 8-29:
4 |   match Hashtbl.find all name with
            ^^^^^^^^^^^^^^^^^^^^^
Warning 5 [ignored-partial-application]: this function application is partial,
maybe some arguments are missing.
```

Interestingly, if the wildcard in the `match` pattern is changed to something else, the warning disappears:

```bash
$ cat > main.ml <<EOF
let all = (Hashtbl.create 10 : (string, int -> string) Hashtbl.t)

let register name table =
  match Hashtbl.find all name with
  | handler -> failwith "handler exists"
  | exception _ -> Hashtbl.replace all name table
EOF
$ ocamlopt -o program main.ml
```

**Comment by nojb** [comment]
This is #12094; the behaviour is expected...

- You can disable the warning by annotating the `match` scrutinee with `(Hashtbl.find all name : _ -> _)` or the wildcard case `(_ : _ -> _)` (which acts as a kind of documentation) or by using `find_opt` instead of `find`. Or use `if Hashtbl.mem all name then ... else ...`.

An unrelated remark:

- Never use `exception _` if you can help it, it catches more exceptions than the ones you want. In this case you should use `exception Not_found` or, even better, `Hashtbl.find_opt` instead of `Hashtbl.find`.

**Comment by jchavarri** [comment]
Thanks for the explanation @nojb, will keep the advice in mind.
