### ISSUE TITLE
(or) operator for 'a option

### ISSUE THREAD

**Issue by ksromanov** [ocaml/ocaml#12682]
@rizo proposed to use currently-not-defined `(or)` operator as an alternative to `Option.value`

https://discuss.ocaml.org/t/does-the-or-keyword-have-meaning-in-ocaml/13276/5

The original definition

```ocaml
let (or) opt default =
  match opt with
  | None -> default
  | Some x -> x
```

or, in other words

```ocaml
let (or) o default = Option.value o ~default
```

The usage is

```ocaml
None or 42 (* 42 *)
Some 1 or 0 (* 1 *)
List.nth_opt [1; 2; 3] 5 or 0 (* 0 *)
```

Does it make sense to add this operator to `Option` module? Btw, the similar operator can be added to `Result` module:

```
let (or) r default = value r ~default
```

**Comment by benjamin-thomas** [comment]
I would like to piggy back on this feature request by asking the question if removing `or` from the list of reserved keywords would be more appropriate?

On the forum post, I mention that such an operator could become confused with a function parameter. If an `or` operator were to become a standard tool in the OCaml toolbelt, then I suppose such confusion would not happen.

**Comment by rizo** [comment]
For what it's worth, even though I define and use this operator occasionally, I do not think that it should be added to the stdlib with the described implementation. Here's why:

1. The precedence of the `or` operator is historically low (which makes sense given it's original usage for boolean values). It's usage with options might cause confusion and might introduce subtle bugs. Given `Some 2 or 3 + 1`, would programmers expect this to result in `2` or `3`?
2. The second argument in `or`, i.e., the default value is not lazy, which might again be confusing to some people because in boolean expressions the part after `||` is lazy.
3. Sometimes I also define `val or_else : (unit -> 'a) -> 'a option -> 'a` to be able to write something like `num_opt |> Option.or_else (fun () -> expensive ...)`. I think this would be a more useful and general addition.
4. Finally, if `or` is removed from reserved keywords, it would be more idiomatic, in my opinion, to define it as a function similar to `or_else` so that one can write pipelines `Some 1 |> Option.or 0 |> process_number`.

Having said this, reserving `or` as a keyword for any future language additions is also a reasonable position.

P.S. I think my original inspiration for using `or` and `or_else` this way came from Rust: https://doc.rust-lang.org/std/option/enum.Option.html#method.or

**Comment by gasche** [comment]
I agree that a non-lazy `or` operator is a footgun that we probably should not encourage.

**Comment by ksromanov** [comment]
@benjamin-thomas , @rizo , @gasche 

Thank you very much for the discussion! Our group was fascinated by the idiom, so I wanted to raise the question here. Of course, `Stdlib` has its own requirements, so it was obvious that even wonderful in-house idiom may not fit. Nevertheless, it would be very sad if no-one discussed its inclusion in `Stdlib` here.

Thanks again!
