### ISSUE TITLE
Package compilation error due to `_Bool` type in domain_state.tbl

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/ocaml#12772]
On trunk, installing the package `optiml-transport` leads to the following failure:

```bash
$ opam install optiml-transport
The following actions will be performed:
  ∗ install optiml-transport 0.0.1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved optiml-transport.0.0.1  (cached)
[ERROR] The compilation of optiml-transport.0.0.1 failed at "dune build -p optiml-transport -j 30 @install".

#=== ERROR while compiling optiml-transport.0.0.1 =============================#
# context     2.1.2 | linux/x86_64 |  | https://opam.ocaml.org/#94fc188d
# path        ~/repos/ocaml/_opam/.opam-switch/build/optiml-transport.0.0.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p optiml-transport -j 30 @install
# exit-code   1
# env-file    ~/.opam/log/optiml-transport-162927-7c8c82.env
# output-file ~/.opam/log/optiml-transport-162927-7c8c82.out
### output ###
# [...]
# File "lib/dune", line 4, characters 39-50:
# 4 |   (foreign_stubs (language cxx) (names EMD_wrapper))
#                                            ^^^^^^^^^^^
# (cd _build/default/lib && /usr/bin/gcc -x c++ -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -pthread -g -I /home/kc/repos/ocaml/_opam/lib/ocaml -o EMD_wrapper.o -c EMD_wrapper.cpp)
# In file included from /home/kc/repos/ocaml/_opam/lib/ocaml/caml/mlvalues.h:70,
#                  from EMD_wrapper.cpp:42:
# /home/kc/repos/ocaml/_opam/lib/ocaml/caml/domain_state.tbl:45:14: error: ‘_Bool’ does not name a type
#    45 | DOMAIN_STATE(_Bool, action_pending)
#       |              ^~~~~
# /home/kc/repos/ocaml/_opam/lib/ocaml/caml/domain_state.h:31:47: note: in definition of macro ‘DOMAIN_STATE’
#    31 | #define DOMAIN_STATE(type, name) CAMLalign(8) type name;
#       |                                               ^~~~



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build optiml-transport 0.0.1
└─ 
╶─ No changes have been performed
```

I'm able to install `optiml-transport` on 5.1.0 successfully. Git blame points to the commit https://github.com/ocaml/ocaml/commit/3f9b1225eda0f21f5c63bd68c6700137be4ce888. @gadmm would you know if a required header file is not included?

## Steps to reproduce

```bash
$ git clone https://github.com/ocaml/ocaml
$ cd ocaml
$ opam switch create . --empty
$ opam install . --inplace-build
$ opam install optiml-transport
```

**Comment by gadmm** [comment]
The point of using bool instead of int was that the `RET_FROM_C_CALL` assembly macro was slightly better on one platform (s390x I think).

We need `caml/domain_state.h` to be includable from C++. Possible solutions:

- Use `int` or `intnat` instead of bool
  - Caution: requires to change the RET_FROM_C_CODE macros in `runtime/*.S`.
- Make `bool`/`_Bool` usable in OCaml headers in the future
  - Include `<stdbool.h>` (compatibility risks)
  - Test for `__cplusplus` and define `_Bool` as `bool`

**Comment by kayceesrk** [comment]
I'm not knowledgeable in this area. Perhaps @dra27 or other maintainers will know what the best course of action is here.

**Comment by MisterDA** [comment]
I reported this issue here https://github.com/ocaml/ocaml/issues/11332#issuecomment-1777187003, but my comment might have been lost in the overall discussion.

> We need `caml/domain_state.h` to be includable from C++. Possible solutions:
> 
> * Use `int` or `intnat` instead of bool
>   * Caution: requires to change the RET_FROM_C_CODE macros in `runtime/*.S`.

That's an easy option.

> * Make `bool`/`_Bool` usable in OCaml headers in the future
>   * Include `<stdbool.h>` (compatibility risks)

For reference, the compatibility risks are that people might define their own `bool` typedef, conflicting with the definition from `<stdbool.h>`. See #12196 and https://github.com/ocaml/ocaml/pull/11990#issuecomment-1513719434 for discussion.

Note that unconditionally defining `bool` will eventually break when compilers default to C23, so authors doing this already have foreseen problems and we might actually do them a favor breaking their code _now_.

> * Test for `__cplusplus` and define `_Bool` as `bool`

The only risk is ABI incompatibility. In C pre 23, `bool` should be wide enough to hold `0` and `1`, in C23, wide enough to hold `true` and `false` (Language > Concept > Types). In C++, `sizeof(bool)` is implementation-defined, and not required to be `1` ([expr.sizeof](https://eel.is/c++draft/expr.sizeof)). I have read somewhere that if the same vendor is used for the C and C++ compiler there are good chances that the ABI for C and C++ bool is the same.

I could find mentions of cases where compilers vendors broke ABI by changing the size of bool.

---

I suggest using `<stdbool.h>` and `bool`.

Besides, `_Bool` is removed from C23 and `<stdbool.h>` is a no-op in C23 and C++.

We can also check at configure-time `sizeof(bool)` easily with [`AC_CHECK_SIZEOF[bool]`](https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Generic-Compiler-Characteristics.html#index-AC_005fCHECK_005fSIZEOF-1), embed the value in a config header with a define, and add a static assert comparing the define with `sizeof(bool)`.

I can think of two possible problems: one may simply link with OCaml and never check whether the bool ABI is compatible, and the static assert should live in a header file, where we open the door to the same compatibility problems if someone has redefined `static_assert`.

**Comment by kayceesrk** [comment]
Given the myriad of current and future compatibility issues, is it not better to go for the easier option of changing the type to `intnat`?

**Comment by MisterDA** [comment]
> Given the myriad of current and future compatibility issues, is it not better to go for the easier option of changing the type to `intnat`?

True, and we won't even waste space as each field is aligned to an 8 byte boundary.

IMO it's a bit sad not to be able to use nice things, though.

**Comment by gadmm** [comment]
+1 for intnat.

The assembly code for bool is still better though, negligibly so but it is a waste of effort to make the change. I believe that the only thing that could go wrong is if someone tried to use something like 256 as a truth value. So I propose to keep the asm code as it is, but simply document the valid values for action_pending (`0`,`1`).

**Comment by xavierleroy** [comment]
> The assembly code for bool is still better though, negligibly so but it is a waste of effort to make the change. 

I bite!  What is the asm code that is better if the field is declared as `_Bool` rather than as a full-width integer?  Just curious :-)

**Comment by xavierleroy** [comment]
At any rate, `intnat` feels like a good choice, if only because we're expecting all fields of the domain_state structure to be evenly spaced (every 8 bytes on a 64-bit architecture).  This could be invalidated if we have two consecutive fields of smaller types like `int` or `_Bool`.

**Comment by gadmm** [comment]
Re. the latter, this is ensured with `CAMLalign(8)` anyway.

Re. asm, on amd64 the `cmp` has a shorter encoding for `byte ptr` than for `qword ptr`, and for s390x there is a separate load instruction.

However, one reason for which I want to make the change to asm after all is that I just learnt that power64 is back in big-endian as well, and I don't want to risk fighting it.

**Comment by xavierleroy** [comment]
> However, one reason for which I want to make the change to asm after all is that I just learnt that power64 is back in big-endian as well, and I don't want to risk fighting it.

Can you elaborate?  For a 64-bit big-endian architecture like system Z or (sometimes) Power, if you have a 64-bit integer at address "p" equal to 0 or 1, loading one byte at address "p" doesn't give you 0 or 1, it always gives you 0.  So, something needs to be done for these architectures.  For Power, just load a full 64-bit word.  For System Z, either use 64-bit wide operations or load a byte at "p + 7".

**Comment by gadmm** [comment]
Yes, I see now that my suggestion to keep the asm unchanged is indeed incorrect due to big endian platforms (which also include s390x).

I want to keep RET_FROM_C_CODE generated rather than hand-crafted. The simplest solution is to operate on 64-bit words on all platforms. This means updating the [godbolt snippet](https://github.com/ocaml/ocaml/blob/426f1ea33375bab44dd9ddd2f5acbfac99820723/runtime/amd64.S#L688-L705) to use int64_t, and apply the change to *.S files. This is what I mean with making the change to the asm after all.

Edit: I initially misunderstood the remark.

**Comment by xavierleroy** [comment]
> This is what I mean with making the change to the asm after all.

OK, thanks for the clarification.

Since system Z has been big-endian since 1964 and will remain so forever, you're welcome to use a byte load at `Caml_state(action_pending) + 7`.  I don't mind if it's not the code that a C compiler would generate.

For Power, a 64-bit word load is as efficient as a byte load, so there's no reason to complicate the code.

**Comment by kayceesrk** [comment]
@gadmm would you be able to make the PR for this since this is a change that you understand well? I'm happy to review this quickly.

**Comment by gadmm** [comment]
@kayceesrk Done
