### ISSUE TITLE
TSan-reported race between GC marking and sweeping

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#12916]
TSan recently reported a race between `large_alloc_sweep` and `do_some_marking` while running the test `gc-roots/globroots_parallel.ml` on revision b3b892e1733864d75361a2e11cf8174bedf13d34: https://gist.github.com/OlivierNicole/f7f920dae55e06af665b0029bb3671d1.

Either the race is very rare, or it was triggered/uncovered by a recent change on trunk. I cannot reproduce it locally.

**Comment by stedolan** [comment]
This race is by design, although TSan is correct to report it as a data race. (It should really be using relaxed atomics to access the header here rather than unannotated pointers).

Marking happens in parallel with sweeping. Marking finds blocks that are UNMARKED and makes them MARKED, while sweeping finds blocks that are GARBAGE and adds them to the free list / frees them.

Reads by the sweeper can race with writes by the marker. However, this does not cause a problem: the sweeper treats MARKED and UNMARKED identically (both indicate an object not subject to sweeping), so it doesn't matter which value it sees.

(Reads by the marker do not race with writes by the sweeper: the marker reads only reachable objects, and the sweeper writes only to GARBAGE objects, which are not reachable).

**Comment by OlivierNicole** [comment]
Thank you for the explanation! I will make a PR to perform relaxed atomic reads on the header.
