### ISSUE TITLE
Annoying message

### ISSUE THREAD

**Issue by skaller** [ocaml/ocaml#12940]
This message
```
File "_none_", line 1:
Alert ocaml_deprecated_auto_include:
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
```
Is annoying . There is no need to add those switches to a pure link.
You do, however, have to add the `cmxa` files or the link fails.

It's also annoying the message mentions unsupported third party build systems (dune, ocamlbuild, ocamlfind) which i do not use anyhow.

**Comment by lthls** [comment]
You should only have seen this message if you were passing `unix.cmxa` on the command line without `-I +unix`. Since OCaml 5.0, this only works because of some special code we added for backwards compatibility, and you get this message when this special code is actually used to encourage you to not rely on it.
Note that adding `-I +unix` works fine on older OCaml releases too, so whatever build system you use I suggest to tweak it to add `-I +unix` either when appropriate or all the time.
If you still think that the message should not apply in your case, please provide the actual command you used so that we can understand what changes we may need to make.

**Comment by skaller** [comment]
I've added `-I +unix -I +str` to every invocation of ocamlopt which indeed gets rid of the message.

The problem is, there was previously no need to know what modules were used by a module.
Ocamlopt finds them automatically. You just need the search paths.

Now I have to specify `+unix` and `+str` with a search path flag, for both compiles and links
which presumably means "whatever directory contains `unix` and `str`. But the compiler already
know these are needed on compilation so why do i need a flag?

On linkage, it would make sense to specify "+unix" and "+str" but then i shouldn't need to specify "unix.cmxa" and "str.cmxa". I have to put both. It doesn't make sense.

Anyhow this is a minor quibble. But it took me 3 hours to sort out.
My product is a compiler, and the system is bootstrapped with Python build code,
then my own language tools rebuild the whole system.  So changing a couple of lines
in the build code takes about 40 minutes.
