### ISSUE TITLE
Typing does not respect the order of labeled arguments

### ISSUE THREAD

**Issue by yzyzsun** [ocaml/ocaml#12960]
The following code will throw an error if we don't `open Hashtbl`:

```ocaml
let stats = [Hashtbl.stats (Hashtbl.create 0)];;
List.map (fun x -> x.num_bindings) stats;;
(* Error: Unbound record field num_bindings *)
```

In fact, the type of `x` in the first argument can be inferred from the second argument `stats`. If we know in advance `x` has type `Hashtbl.statistics`, the type error can be avoided. We can verify this idea by swapping the order of the two arguments:

```ocaml
let flip f x y = f y x;;
(flip List.map) stats (fun x -> x.num_bindings);;
(* - : int list = [0] *)
```

Based on the same principle, I expect the following code type checks too:

```ocaml
ListLabels.map stats ~f:(fun x -> x.num_bindings);;
(* Error: Unbound record field num_bindings *)
```

However, it seems that the OCaml type checker does not respect the order of labeled arguments. The order of typing arguments does not matter in most cases of `List.map`, but it matters in this case.

According to the paper *Labeled and optional arguments for Objective Caml* by @garrigue, I guess this is because the labeled arguments are desugared before typing. Is it correct? Is there any chance to change it to respect the order of labeled arguments?

**Comment by Octachron** [comment]
This is the expected behavior: the order in which the typechecker checks function arguments is not specified, and is an implementation detail of the typechecker.

You can enable the `-principal` option to get a warning whenever you accidentally rely on the typechecking order:
```ocaml
(flip List.map) stats (fun x -> x.num_bindings);;
```
>Warning 18 [not-principal]: this type-based field disambiguation is not principal.

In the current implementation, labelled argument are always typed in the order of definition of labels, since labelled arguments are reordered at function call to fits this order. But once again, this is not a detail that you should rely upon.
