### ISSUE TITLE
Regression around warning 53 (misplaced-attribute) and [@@ocaml.inline always].

### ISSUE THREAD

**Issue by rlepigre** [ocaml/ocaml#12972]
Impacted version: 5.02.0~alpha1

To reproduce:
```bash
echo "val f : int -> int [@@ocaml.inline always]" > bug.mli && ocamlc bug.mli
```
This gives:
```
File "bug.mli", line 1, characters 22-34:
1 | val f : int -> int [@@ocaml.inline always]
                          ^^^^^^^^^^^^
Warning 53 [misplaced-attribute]: the "ocaml.inline" attribute cannot appear in this context
```

There is no such warning on 5.01.1 or earlier versions as far as I can tell. I first encountered this problem trying to compile [coq](https://github.com/coq/coq), due to, e.g., [this line](https://github.com/coq/coq/blob/3b9e094e270353afeb4635117fb4f4980b2069b3/kernel/float64.mli#L60).

**Comment by Octachron** [comment]
This is a bugfix and not a regression: the `inline` attribute has no effects on a signature since it is a property of function implementation and not a part of their type. 

You can check this behavior with

```ocaml
module M: sig
  val x: ('a -> 'b) -> 'a -> 'b [@@inline always]
end = struct
  let x f y = f y [@@inline never]
end

let test = M.x (fun x -> x) 1
```
which produces the inlining report:
```
* Application of x/9{i.ml:7,11-29}
  
  This function was not specialised because it is not recursive.
  
  This function was not inlined because of an annotation.
```

**Comment by rlepigre** [comment]
Ah! I suspected this could be the case, but could not find the relevant item in the changelog. Do you know in what PR this was fixed?

**Comment by lthls** [comment]
> Do you know in what PR this was fixed?

Probably #12451.

**Comment by rlepigre** [comment]
Actually, let me ask a question: is there any way to inline functions from a module which has an `.mli` file?

I'm always confused by this, and cannot find anything about that in the documentation. What are the limitations? What if your function uses abstract types?

**Comment by lthls** [comment]
Inlining occurs after the types have been compiled away, so `.mli` files do not impact inlining and neither does the use of abstract types.
The main limitations of inlining are:
- The compiler must resolve the left-hand side of an application (the function) to a single function definition. So for example `let f = if cond then foo else bar in f ()` will never see `f` inlined unless the compiler can statically resolve the condition to a single value. For cross-module inlining, the cmx files contain information about the shape of the module block so that dependencies can resolve module paths into actual functions.
- If Flambda is not enabled, functions containing other function definitions cannot be inlined. The most common occurrences are functors, and functions calling higher-order functions with anonymous or locally-defined functions as parameters (this includes many uses of monadic operators).
- Recursive functions cannot be inlined, although Flambda has a bit of support for unrolling.
