### ISSUE TITLE
Abnormal exit after upgrading to OCaml 5

### ISSUE THREAD

**Issue by cometkim** [ocaml/ocaml#13141]
I was trying to build [Odiff](https://github.com/dmtrKovalenko/odiff) with OCaml 5.

https://github.com/cometkim/odiff/commit/e9b5c365094647b3328c84be0375bad322373a99

The program builds successfully and appears to work well.

But something strange happened when I tried to migrate its test codes. The project uses [Rely](https://reason-native.com/docs/rely/), and the Rely framework doesn't allow OCaml 5, so I patched that together.

https://github.com/cometkim/reason-native/commit/de7ae18d6ae1e5b9aa165bcd12964b0c3ca723e4

Then I run `esy test` from Odiff, it exits prematurely with exit code 246. Since esy appears to swallow the error, I ran the binary directly with gdb.

```
❯ gdb -ex run ./_esy/default/build/default/test/RunTests.exe
GNU gdb (Ubuntu 14.0.50.20230907-0ubuntu1) 14.0.50.20230907-git
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./_esy/default/build/default/test/RunTests.exe...
Starting program: /home/comet/Workspace/src/github.com/dmtrKovalenko/odiff/_esy/default/store/b/odiff-1a3feb5e/default/test/RunTests.exe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running 9 test suites
 RUNS  IO: TIFF
Program received signal SIGSEGV, Segmentation fault.
do_some_marking (stk=0x55555590c230, budget=-32, budget@entry=16384) at runtime/major_gc.c:871
871           header_t hd = Hd_val(block);
```

I thought this was an issue in OCaml 5 because this has not happened in OCaml 4.14. There is some C code in Odiff, but I'm not sure if it is related to the issue here.

**Comment by gasche** [comment]
This is very likely to be an issue to fix in the program/library, rather than an issue to fix in the OCaml distribution. Please open an issue there.

It looks like the GC is encountered a value that is malformed -- it should be a block but accessing its header segfaults. 

There are several ways this could happen, but one possibility would be that some FFI code uses "naked pointers" (OCaml values that are raw pointers to non-OCaml values outside the OCaml heap), which used to accepted for OCaml 4, were deprecated in OCaml 4.11 (2020), and are now illegal in OCaml 5. One would need to look at the FFI code to tell if it is using naked pointers to rule this possibility out. See [the reference manual](https://ocaml.org/manual/5.1/intfc.html#ss:c-outside-head) on this topic.

**Comment by Octachron** [comment]
Here is an example of naked pointer in the odiff code for reading `tiff` files: https://github.com/dmtrKovalenko/odiff/blob/c79541749f0debaf34b698e592dce6da9fb87e9d/io/tiff/ReadTiff.c#L52 . This is most likely the source of the illegal naked pointer in the test.

**Comment by gasche** [comment]
There you go:

https://github.com/dmtrKovalenko/odiff/blob/c79541749f0debaf34b698e592dce6da9fb87e9d/io/jpg/ReadJpg.c#L75

I think that you could change the code (also in ReadPng) to use a "managed" bigarray where the memory is malloced by the OCaml runtime when creating the bigarray, and deallocated when it gets collected. Alternatively, you can just set the last bit of the pointer when storing it as an OCaml value, this is the "valid representation as an OCaml tagged integer" approach mentioned last in the reference manual.

**Comment by cometkim** [comment]
Oh I see, thank for explanation :)

**Comment by dmtrKovalenko** [comment]
Unfortunately we can't do that because the memory is allocated by the codec library. (That is one of the main reason odiff exists as a project)

I don't really understand one thing: bigarray must always return int32 which is a type totally matching C layout, why specifically in v5 we need to mark a bit for GC?
