### ISSUE TITLE
Library archive name change in OCaml 5 (e.g libunix.a -> libunixbyt.a & libunixnat.a)

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#13183]
Today I noticed that the compiler changed how the it names its library archive files. For example, previously with OCaml 4 we got:
- `libunix.a`

Now with OCaml 5, this file is gone but instead we have:
- `libunixbyt.a`
- `libunixnat.a`

A similar changed happened to `libcamlstr.a` (now `libcamlstrbyt.a` and `libcamlstrnat.a`).
One exception is libthreads which had both `libthreads.a` and `libthreadsnat.a` and didn't change them in OCaml 5. Is `libthreads.a` the equivalent of what would be `libthreadsbyt.a` if it followed the same convention?

I looked around but i couldn't find the reasoning behind this change/convention, is there a piece of documentation somewhere about that particular point by any chance?

**Comment by shindere** [comment]
Kate (2024/05/21 05:47 -0700):
> One exception is libthreads which had both `libthreads.a` and
> `libthreadsnat.a` and didn't change them in OCaml 5. Is `libthreads.a`
> the equivalent of what would be `libthreadsbyt.a` if it followed the
> same convention?

I think so, yes.

Did the inconsistency bite you inany way?

Just curious on how you discovered the change.

> I looked around but i couldn't find the reasoning behind this
> change/convention, is there a piece of documentation somewhere about
> that particular point by any chance?

This happened as part of the work on TSan, I think.

Before this work, there was a tendency to compile the C stubs only once
and to reuse the same object files for both bytecode and native
libraries.

With TSan it became obvious that this does not really make sense,
becuase it forces you to use an instrumented version of the stubs even
in the context of bytecode, whereas one  does not want to instrument it,
because it makes it way too slow.

So we now compile C stubs twice, once to link the bytecode library and
once to link the native one.

Does all this make sense?

**Comment by kit-ty-kate** [comment]
> Does all this make sense?

yes, thanks!

> Did the inconsistency bite you inany way?

No not this inconsistency. I've only noticed the change because we use `-noautolink -cclib -lunix -cclib -Wl,-static` in opam to produce statically linked executables on Windows/MinGW and Linux/musl. `-lunix` worked fine with OCaml 4 but now triggers an error if OCaml 5 is used, which we have to replace with `-lunixnat` and I was curious why this change happened.

Just in case anyone out-there is making an OCaml 4 to OCaml 5 transition guide anywhere, i feel like it could have a paragraph explaining this change for people who are in the same situation as us.

I'll close this as there is nothing to fix. Thanks again.

**Comment by shindere** [comment]
Kate (2024/05/22 02:40 -0700):
> > Does all this make sense?
>
> yes, thanks!

My pleasure!

> > Did the inconsistency bite you inany way?
>
> No not this inconsistency. I've only noticed the change because we use
> `-noautolink -cclib -lunix -cclib -Wl,-static` in opam to produce
> statically linked executables on Windows/MinGW and Linux/musl.
> `-lunix` worked fine with OCaml 4 but now triggers an error if OCaml 5
> is used, which we have to replace with `-lunixnat` and I was curious
> why this change happened.

Okay I got it. Many thanks for the context.
