### ISSUE TITLE
Stdlib: `Dynarray.insert` procedure

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml#13196]
For context, I needed `insert` and `binary_search` while trying out `Dynarray` as a candidate structure that may be most suitable for backing an `OrderedSequence` abstract collection. The latter was easy and efficient enough to implement, but I had to unsafely inspect the structure's internals for the former, which made me quickly elect to just patch `stdlib/dynarray.ml[i]` to make good use of the proper and safe mechanisms provided internally.

I imagine `insert` should involve at most 1 resize and 1 blit. In other words, two copies delimited by the split point.
Alternative approaches involve more copies and/or a write loop. Not ideal...

Here are some alternatives I tried:
```ocaml
let insert_loop a i x =
  Dynarray.add_last a (Dynarray.get_last a);
  for i = Dynarray.length a - 2 downto i + 1 do
    Dynarray.set a i (Dynarray.get a (i-1))
  done;
  Dynarray.set a i x

let insert_seq a i x =
  let sub = Dynarray.to_seq a |> Seq.drop i |> Seq.cons x |> Array.of_seq in
  Dynarray.truncate a i; Dynarray.append_array a sub

let insert_subarray _ _ _ =
  (* would be a really bad implementation via to_array,
   * a [Dynarray.sub/sub_array] would be great to have here *) ()
```

I tried a conventional implementation of `insert` for the patch. Here are two worst-case microbenchmarks
First, _one insertion_ at the front of an array of length and capacity n:
| n = | insert_seq | insert_loop | insert_patch |
|----|----|----|----|
|10² |16us|5us|3us|
|10³ |147us|35us|24us|
|10⁴ |1ms|0.53ms|0.14ms|
|10⁵ |17.5ms|3.2ms|1.8ms|
|10⁶ |145.8ms|38.9ms|20.6ms|

And then, _n insertions_ at the front of an array of length and capacity 1:
| n = | insert_seq | insert_loop | insert_patch |
|----|----|----|----|
|10 |38us|24us|15us|
|10² |3.32ms|0.68ms|0.04ms|
|10³ |46.6ms|13.1ms|6.2ms|
|10⁴ |4.17s|0.97s|0.43s|
|10⁵|10m|1.5m|40s|

I'm willing to submit my patch as a PR if the addition is deemed worthwhile.

**Comment by gasche** [comment]
The underlying primitive that cannot be easily implemented outside Dynarray is basically a `blit` operation with two requirements:
- interface/expressivity: it should allow to extend the destination dynarray -- the destination index for the start of the blit can be up to the length of the destination dynarray
- implementation detail: it should be optimized to an Array.blit when the dummy values of the source and destination arrays are the same

With this it is easy to implement `insert`, by self-blitting to shift one half of the array by one position, and then writing the element to insert.

I don't know what other people think of `insert` (personally I find these linear-traversal primitives a bit dubious for arrays, but oh well), but I am interested in providing `blit` in any case to unlock this use-case and others. (This would also optimize the code of `Dynarray.append` slightly, as it does not currently use the same-dummy optimization.)

**Comment by hyphenrf** [comment]
Personally I'm happy with a `blit` for this use-case. Indeed that was the core internal operation (as well as `Dummy.of_val`) that I needed to get a good `insert` implementation.

FWIW if you look at other languages stdlibs, `insert` is a common operation if they offer a dynamic array API, even the performance-oriented languages of the bunch. I'd argue it's expected even.

**Comment by gasche** [comment]
I'm working on an implementation of `blit` because it is a bit delicate, I will try to send a PR. You will then be free to send an easier/smaller/simpler PR for `insert` and make your case.

**Comment by gasche** [comment]
See a PR for `blit` in #13197.

**Comment by nojb** [comment]
> I don't know what other people think of `insert` (personally I find these linear-traversal primitives a bit dubious for arrays, but oh well), but I am interested in providing `blit` in any case to unlock this use-case and others. (This would also optimize the code of `Dynarray.append` slightly, as it does not currently use the same-dummy optimization.)

> FWIW if you look at other languages stdlibs, `insert` is a common operation if they offer a dynamic array API, even the performance-oriented languages of the bunch.

Indeed `insert` is a common operation exposed on vector data structures, however it is also inefficient. Doing several insertions in sequence is particularly inefficient, and it is much better to first do a blit to open a "gap" in the target vector and then do a sequence of `set`s to fill the gap. From this point of view, it seems `blit` is the more useful primitive and not so much `insert`.

The `insert` operation is similar to `List.nth` in that it is a linear-complexity primitive which can be misued to write inefficient code. Since supposedly someone thought that `List.nth` had its uses, we could also envisage adding `insert`, but my feeling is that the number of genuine use-cases for `insert` is rather low.

**Comment by hyphenrf** [comment]
As a bit of a tangent but related to your comment about "several insertions in a sequence", I was curious to see how bad it was in other camps, so I went on and tested a bunch of analogous dynarray implementations in other languages. It was so strange seeing how my implementation, nothing inconspicuous, was the slowest among contemporaries, double the second-slowest. I wonder what makes it especially pathological for us...

insert 100k elements to the beginning of an empty dynarray:
|lang|real|user|sys|
|----|----|----|----|
|C++|1.081|1.066|0.006|
|F#|2.353|2.353|0.017|
|Go|13.140|11.271|6.615|
|Haskell|11.458|11.077|0.181|
|Kotlin|0.635|0.560|0.052|
|OCaml|20.032|19.902|0.003|
|Rust|1.059|1.047|0.005|
|Swift|1.027|1.007|0.006|

I did not expect so much slowdown (vs for example go or haskell (also wow kotlin timings are surprising!)). If someone wants to investigate, I created a [gist](https://gist.github.com/hyphenrf/dbdacc2e9244cd0b9178b0608e70539d) which also has my implementation of `insert` for reference.

**Comment by gasche** [comment]
My guess would be that `Array.blit` is fairly expensive in OCaml 5, at least on systems with a weak memory model (eg. arm rather than x86_64), because each element write involves some atomic synchronization in addition to the usual write barrier of the GC. In contrast, Vec::insert in Rust [just calls](https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#1558) ptr::copy, which I suppose boils down to just a `memmove`, which has much smaller constant factors.

(What machine are you using for your benchmarks?)

We could test this theory by just microbenchmarking `Array.blit` on an array of integers on OCaml 4 and OCaml 5: if this guess is somewhat right, there should be a measurable slowdown.

I wonder if we could offer a simpler implementation of `caml_modify` for sequential programs. (Ideally there would be a `caml_modify_alone` variant that could be called in bulk-modify operations, instead of checking within modify each time.) This sounds obvious, so I suspect that someone tried and found out it is not worth it, but I don't know.

**Comment by gasche** [comment]
I tried writing a dumb microbenchmark for Array.blit, but on my (amd64) machine I get the opposite result, which is that 5.1 is 20% faster than 4.14.

```ocaml
let n = int_of_string Sys.argv.(1)

let arr = Array.init n (fun i -> i)

let () =
  for i = 1 to n do
    Array.blit arr 0 arr 1 (n - 1)
  done
```

**Comment by hyphenrf** [comment]
I'm actually running my benches on a good old x86_64 intel machine. Here are the cpu specs:
```
$ ddcpuid
Name:        GenuineIntel Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
Identifier:  Family 0x6 Model 0x8e Stepping 0x9
Cores:       2 cores, 4 threads
Max. Memory: 512 GiB physical, 256 TiB virtual
Platform:    x86-64
Baseline:    x86-64-v3
Features:    eist turboboost intel-txt/smx sgx htt
Extensions:  x87/fpu +f16c mmx intel64/x86-64 +lahf64 vt-x/vmx aes-ni adx bmi1 bmi2
SSE:         sse sse2 sse3 ssse3 sse4.1 sse4.2 fma
AVX:         avx avx2
AMX:        
Mitigations: ibrs stibp ssbd l1d_flush md_clear
Cache L1-D:    2x   32 KiB,   64 KiB total, si
Cache L1-I:    2x   32 KiB,   64 KiB total, si
Cache L2-U:    2x  256 KiB,  512 KiB total, si
Cache L3-U:    1x    4 MiB,    4 MiB total, si ci cci
```
Kernel is vanilla `Linux 6.6.32 #1-NixOS SMP PREEMPT_DYNAMIC`

(I had a gut feeling it had something to do with the write barrier too... not so sure now)

**Comment by gasche** [comment]
I tried to find the source of `insert` in Kotlin out of curiosity, and I ended up on the `system.arraycopy` method from the JVM which seems to benefit from, uh, shocking amounts of optimization (see here for something that might be [the openjdk implementation](https://github.com/openjdk/jdk/blob/7564949a56b533b9d955ff5feee75afd18e51f74/src/hotspot/share/opto/arraycopynode.cpp)).

**Comment by gasche** [comment]
I tweaked my microbenchmark above to use an array of floats instead of an array of integers -- just replace `Array.init n (fun i -> i)` with `Array.init n float`. Array of floats are optimized to a different primitive shape (to allow unboxing) and the runtime knows to use a simple `memmove` for blitting.

I observe that this version is 19x faster than the integer version my machine. This precisely corresponds to the 20x slowdown observed between OCaml and the rest of the pack in your microbenchmark, confirming that we are paying barrier-related costs. (Obviously the JVM has a trick to avoid paying these costs, but I don't know what it is and the implementation is too obscure for me to venture there.)

**Comment by hyphenrf** [comment]
Sure enough. I tried with a different approach during your attempt with floatarrays, running `perf` on this, and:
```perf
+   70.24%  bench-ml  bench-ml              [.] caml_modify                                                 
+   29.61%  bench-ml  bench-ml              [.] caml_array_blit                                             
     0.04%  bench-ml  bench-ml              [.] caml_check_urgent_gc  
```
70% of the execution time is spent on `caml_modify`
is it not possible to, for example, tell the gc to batch a bunch of writes? so that blits don't suffer so much..

**Comment by gasche** [comment]
This is not a shocking result as `caml_modify` is known to make certain imperative programming patterns more costly, nudging us towards immutable structures that don't pay these costs. The microbenchmark results show a very large slowdown, but this is typical of microbenchmarks and it is not at all representative of costs of real programs. (Well, I could see a programmer mistakenly using `Dynarray.insert` with quadratic complexity, resulting in a real program bottlenecked on the `insert` performance.)

(In other words: I think the best is to accept to look bad on this particular microbenchmark, because there is no obvious low-hanging win to be found here, it is just a corner consequence of design decisions. If users hit this on real programs, it should be possible to write their code differently to avoid it.)

**Comment by hyphenrf** [comment]
if anything, it looks like I made myself another argument against including `insert` hahaha
not just that it's algorithmically bad, but also that it has the write barrier overhead stuck to it
the batching can be done from algorithmic pov and at user-level as nojb suggested by creating an n blit then a bunch of sets, rather than n * 1-blits aka insert.
well, it doesn't address the runtime limitations, just the algorithm in this one instance which was meant to be pathological anyway, but not having `insert` can act as sort-of deterrance against that type of O(n) writes being done too frequently on such granular level... I won't push for it. I can see it being a footgun.

**Comment by bluddy** [comment]
Is the problem that currently, blitting the rest of the Dynarray is hitting the barrier on every single value it's shifting over?

**Comment by hyphenrf** [comment]
Seems not, rather on every blit. I checked by overriding `caml_modify` in a stub:
```c
#include <caml/mlvalues.h>

static unsigned long count;

CAMLprim value getcount(value unit) {
  (void)unit;
  return Val_long(count);
}

extern CAMLexport CAMLweakdef void caml_modify_override(volatile value*, value);

CAMLexport CAMLweakdef void caml_modify(volatile value *fp, value val) {
  count++;
  caml_modify_override(fp, val);
}
```
`$ objcopy --redefine-sym caml_modify=caml_modify_override ...` then linking that using `-without-runtime` and supplying the modified runtime here.

I also adjusted my benchmark program to print out the call count by calling `getcount`. It shows `100_028` calls for `100_000` insertions.

**Comment by hyphenrf** [comment]
(the extra 28 calls appear to be related to the dynarray resizing. there are 20 resizes, not sure what the remaining 8 are, I give up hahaha)

update: I didn't give up and actually looked a bit more into it using godbolt and reading stdlib source code. I realized that **my overriding was flawed** because it also renamed the symbol at call sites in the runtime lib, thus eliding any calls that happen in prims (`Array.blit` uses a prim) from my counting.
The two instances of invoking `caml_modify` outside of stdlib code and in my function, [noting that blitting can invoke additional `caml_modify` for every element](https://github.com/ocaml/ocaml/blob/272cf5da6715f6a90cb46526ac429aa4e7c1b272/runtime/array.c#L413-L435), are:
- when we resize the dynarray as noted above, what invokes the barrier is assigning the freshly allocated array to the `arr` field of the dynarray.
- when we set the new element on insert, [the very last line in my `insert` function](https://gist.github.com/hyphenrf/dbdacc2e9244cd0b9178b0608e70539d#file-insert-ml-L51). I think the compiler can't tell it's an array of immediates (in my benchmark) because of the `dummy` conversion..?

if the speculation in this last point is true, that means a `Dynarray.blit` is expected to always invoke the write barrier, regardless of whether the elements are immediate or not. I'll also look for another way to count the calls to `caml_modify` and confirm.

**Comment by hyphenrf** [comment]
so I used `gdb`'s `breakpoint`+`command` to count the calls (which was horribly slow), and indeed for a thousand insertions, `caml_modify` was called more than 460 thousand times.
Interestingly, for lower numbers of insertions, the number of calls doesn't match what I expected. In retrospect, this is probably because smaller dynarrays live on the minor heap where they don't need a write barrier to begin with. This is a note I'll keep in mind when using them :)
|insertions|calls|resizes|
|----|----|---|
|10 | 22|2|
|100 | 115 | 5|
|200| 216 | 6|
|300| 12527 | 7|
|500| 92627 | 7 |
|1000| 467878 | 8 |

**Comment by bluddy** [comment]
OK so this should be fixable, right @gasche ?

**Comment by hyphenrf** [comment]
If you mean whether or not `dummy` has something to do with it, I tried with a plain array blitting in a loop,
```ocaml
let _ =
  let a = Array.make n 0 in
  for _ = 1 to n do
    Array.blit a 0 a 1 (n-1);
  done
```
it still ran the barrier for every element resulting in quadratic number of calls. I think I just had a misconception about the barrier not being invoked when the array holds immediates...?

edit: `caml_modify` itself does an `is_block` check which means it does nothing on immediates. and since `dummy` conversion is just a type-system trick that doesn't box the underlying immediates, it should retain that behaviour. It's probably only the case for actual dummies that they'd hit a write barrier. Instead of tracking `caml_modify` I should've tracked `caml_darken` to check, which does show this distinction. and the number of calls to that grows a lot slower.

**Comment by gasche** [comment]
Dynarray uses a non-immediate dummy and I don't think we can change this, as we need to ensure that the value is distinct from anything the user could put themselves.

Even without dummies, the C runtime cannot tell that an array may only contain immediates (the only thing it tracks is `Double_array_tag`, which says that there are only doubles); in OCaml many types contain both immediates and non-immediate values. (The compiler can know that an array may only hold immediates when it generates code, so direct writes in only-immediate arrays can avoid using `caml_modify`)

We could have a different C primitive for blitting between immediate arrays, but (1) we cannot use it for dynarrays and (2) this would not improve the performance of blit on non-immediate data.

**Comment by hyphenrf** [comment]
This issue has been very informative to me on the runtime, thanks all.
I'm not gonna push for `Dynarray.insert`, feel free to close if it was hanging on me to do so.

**Comment by gasche** [comment]
I'm going to close because I share your hesitation regarding introducing performance footguns in the stdlib. (I had asked @nojb for a second opinion and [his assessment](https://github.com/ocaml/ocaml/issues/13196#issuecomment-2137789819) (thanks!) was also lukewarm.)

On the other hand, this issue convinced me to propose `Dynarray.blit` in #13197 , and I hope we do manage to get around to review and integrate this, because it would make it easier for users to implement `insert` if they really want, and also other operations -- for example the "batched insert" form we discussed. I must say that I was impressed with the care&sophistication of your own implementation of `insert`, but it's not reasonable to expect users in general to pour this amount of effort.

Thanks for the nerd-sniping benchmarks and the discussion.
