### ISSUE TITLE
Buggy exhaustiveness check when defining types inside a module

### ISSUE THREAD

**Issue by mlemerre** [ocaml/ocaml#13208]
Hello,

This compiler behavior seems buggy to me. The following program is fine:

```ocaml
type boolean = |
type integer = |

type 'a value = 
  | Boolval: bool -> boolean value
  | Intval: int -> integer value

let not_ (Boolval b) = Boolval(not b);;
```
But the following one reports exhaustive check errors:

```ocaml
module A = struct
  type boolean = |
  type integer = |
end

include A

type 'a value = 
  | Boolval: bool -> boolean value
  | Intval: int -> integer value

let not_ (Boolval b) = Boolval(not b);;
```
reports the error

```Warning 8 [partial-match]: this pattern-matching is not exhaustive.```

I can't remove the latter error no matter how hard I try:

```ocaml
let not_: boolean value -> boolean value = fun (x:boolean value) -> match x with
  | (Boolval b) -> Boolval(not b)
  |  Intval _ -> .
```
returns

```Error: This match case could not be refuted.```

Am I doing something wrong or is there an error? It appears in both 5.2.0 and 4.14.0

**Comment by gasche** [comment]
I don't think that this is a bug, but an unfortunate property of our language of signature that certain disjointness properties cannot be expressed. If two types share the same constructor names, they may be distinct or they may be alias of each other, and there is no way to say for sure that they are distinct in the interface. This is what is going on here, but `type integer = Foo` and `type boolean = Foo` would get you the same result. This is because the following implementation has the same interface:

```ocaml
module A = struct
  type integer = |  (* or:  = Foo *)
  type boolean = integer
end
```

You can get disjointness by using different constructor names for the two types, for example:

```ocaml
type integer = [ `Integer ]
type boolean = [ `Boolean ]
```

**Comment by mlemerre** [comment]
What I infer from your (otherwise very clear) explanation is that modules without signature are automatically assigned a transparent signature which, as you said, cannot describe the disjointedness property, which is why the program fails even if my module was not given a signature. Thanks! I now understand the problem and know how to fix my program.
