### ISSUE TITLE
Unreachable case in pattern matching fails because unreachable

### ISSUE THREAD

**Issue by samsa1** [ocaml/ocaml#13231]
Currently the type checker checks if a case is possible before using the information that a case is unreachable.

Thus the following example fails with an error.
```ocaml
type _ t =
  | A : int t

let f (v : float t) =
  match v with
  | A -> .
```

```ocaml
File "test.ml", line 23, characters 4-5:
23 |   | A -> .
         ^
Error: This pattern matches values of type int t
       but a pattern was expected which matches values of type float t
       Type int is not compatible with type float
```

However, this case is marked as unreachable, thus it was expected that typing should fail.

Versions tested : 4.08, 5.1.1 and trunk for last week

I'll try to fix this bug but help/hints is always welcomed

**Comment by gasche** [comment]
I think you should write `_ -> .` here, and I don't think that your example is a bug.

**Comment by gasche** [comment]
Longer version: the OCaml compiler does not let you write patterns that it knows are ill-typed, but can check that a well-typed pattern that you wrote actually does not match any value (it tries to prove it by expanding wildcards into a disjunction of possible head constructors).

**Comment by Gbury** [comment]
Small note: If we consider a slight variation of the example where we add a constructor that has the correct type:
```ocaml
type _ t =
  | A : int t
  | B : float t

let f (v : float t) =
  match v with
  | B -> 0.
  | _ -> .
```
Forcing the use of a wildcard pattern is slightly annoying since it triggers the `fragile-match` warning, which `dune` treats as an error by default. Though in that case, maybe it's the fragile warning which is wrong, since in the case of additional constructors, either they are refutable, and the match stays exhaustive, or they are not refutable, and the wildcard case will not be refutable anymore.

**Comment by gasche** [comment]
Indeed, this new example looks like an issue with the fragile-match warning.

But: I don't think it is the case that Dune treats fragile-match as an error by default, this would break too much code. Where can we find documentation on the set of warnings enabled by dune by default?

**Comment by Gbury** [comment]
Ah, you're right, `dune` probably doesn't treat `fragile-match` as an error by default, I guess I have become too accustomed to the special configuration that we use for `flambda2`, ^^. And I now realize that I don't know where the set of warnings enabled by default in `dune` is documented.
