### ISSUE TITLE
caml.inria.fr is not accessible anymore

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#13237]
I was trying to download the archive for OCaml 4.14.2 and got hit by a "Couldn't connect to server".
Going to the website in HTTPS indeed results in a timeout, and trying the HTTP version nets me this page instead:
![scrn-2024-06-14-13-47-58](https://github.com/ocaml/ocaml/assets/2611789/32bfb50e-2c13-45fc-8ed7-0da0802613dd)

**Comment by shindere** [comment]
This may have to do with Inria's move?

Maybe somebody from Inria like @xavierleroy or @gasche can tell more?

**Comment by xavierleroy** [comment]
Yep, the servers are moving, and as it says on the error page, "the websites are scheduled to go back online on June 19 or 20, 2024".  I was hoping no one relies on caml.inria.fr any longer...

**Comment by kit-ty-kate** [comment]
> I was hoping no one relies on caml.inria.fr any longer...

if this is the case, i think it would be nice for the archives created by hand for each releases to be added to the GitHub release page (cc @Octachron), this way we have a set of immutable archives. I believe this is the only reason people still use caml.inria.fr

PS: sorry @shindere i should've thought of adding an alt-text for the image, i'll try to remember for next time

**Comment by Octachron** [comment]
It is a good idea to add the archive to the GitHub release page anyway.

**Comment by shindere** [comment]
Kate (2024/06/17 03:45 -0700):
> > I was hoping no one relies on caml.inria.fr any longer...
>
> if this is the case, i think it would be nice for the archives created
> by hand for each releases to be added to the GitHub release page (cc
> @Octachron), this way we have a set of immutable archives. I believe
> this is the only reason people still use caml.inria.fr

And maybe we shold properly retire caml.inria.fr, possibly with
redirections to GitHub?

> PS: sorry @shindere i should've thought of adding an alt-text for the
> image, i'll try to remember for next time

Thanks, and no worries. It's also my fault as I have been lazy and did
not follow the linkyou mentionned to "see" by myself.

**Comment by avsm** [comment]
It looks like some package managers still have the caml.inria.fr server baked in; e.g. NixOS' nixpkgs:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ocaml/generic.nix#L27

So uploading the caml.inria.fr archives with the same SHA256 hash to the corresponding GitHub release would be indeed a very useful way to make the fix for Nix is a one line change instead of updating all the checksums as well.

**Comment by mtelvers** [comment]
caml.inra.fr is also embedded into the opam build process for 2.0 and 2.1, preventing us from building new Docker base images for the CI system.  https://github.com/ocurrent/docker-base-images/issues/283

As the `opam` files for the compiler in the opam-repository have recently been touched via various PRs, the CI system is rebuilding the compiler even though it already exists in the current switch.  This is slowing the CI system and causing the workers to repeatedly hit the websites, which host the dependencies needed to compiler OCaml.  This is resulting in `curl` failures due to rate limits on those sites.  See https://github.com/ocaml/infrastructure/issues/128.

Opam 2.0 needs a lot of effort to get it to pass CI, but 2.1 could easily be patched to remove the dependency on caml.inria.fr.  OCaml-CI uses opam 2.1, Opam-repo-ci uses opam-dev.  Does anyone still use opam 2.0?

**Comment by mtelvers** [comment]
Further to my last comment, the patch to opam is more straightforward than I thought. It is the bootstrap compiler that is failing, so one patch on master will resolve the issue. See ocaml/opam#6032.

**Comment by shonfeder** [comment]
Would it be possible for inria to redirect requests for these archives (and for opam) to the source on github for the duration of their outage? If so, is that lift light enough that we could expedite to address the immediate impact of these disruptions?

**Comment by shindere** [comment]
I fear (1) it's not something we have control over and (2) can't happen
before the beginning of July. @Octachron maybe able to contact the
engineers in charge to see with them what they could do?

**Comment by gasche** [comment]
Note: caml.inria.fr is back online (probably has been since yesterday).

**Comment by shindere** [comment]
Gabriel Scherer (2024/06/21 03:20 -0700):
> Note: caml.inria.fr is back online (probably has been since
> yesterday).

Okay thanks for this update!

In this context, I will close this issue (but anybody should feel free
to re-open it if deemed appropriate). I think we can open more specific
issues to change the URLs in the various places so that they do no
longer refer to caml.inria.fr, and likewise for uploading the releases
to GitHub.
