### ISSUE TITLE
Raise the maximum number of domains

### ISSUE THREAD

**Issue by zyedidia** [ocaml/ocaml#13256]
It seems like currently OCaml cannot create more than 128 domains (creating more fails with `Fatal error: exception Failure("failed to allocate domain")`). I am trying to run a parallel OCaml program on a Google Cloud VM with 180 cores and 360 vCPUs (AMD Genoa C3D). Is it possible to raise this limit, ideally to at least 360? Thanks!

**Comment by kayceesrk** [comment]
HI @zyedidia, do you see good scalability up to 128 that warrants an increase beyond this limit? Machines with a large number of cores typically have multiple sockets and exhibit NUMA behaviour. The OCaml runtime is not optimised for NUMA and you may see degrading performance with cores.

**Comment by zyedidia** [comment]
I am running a task that is embarrassingly parallel -- it is essentially running a for loop with 4 billion iterations, where each iteration is completely independent. I haven't tested the scaling in depth, but I would expect it to be quite scalable because there is no communication across threads. I could use multiprocessing to solve this, but the program requires around 10GB of memory, so starting a process for each core would waste a lot of memory. Currently I am running multiple processes, each with roughly 128 threads, but it would be simpler and easier to just run all the threads within a single process.

**Comment by shindere** [comment]
Completely naïve question from somebody knowing _nothing_ about these things.

I understand that it's best if the max number of domains for one run is
known in advance so that the domain talbe can be allocated once and for
all, which makes things mroe efficient than a more dynamic data
structure.

My question, though, is why this constant couldn't be made overridable
by, say, a runtime parameter so that users can adjust it to their own
needs?

**Comment by kayceesrk** [comment]
@zyedidia would be useful to see some scaling data, if possible. 

Even though the threads do not have any contention in the source program, there can still be contention in the runtime due to memory allocation. The runtime structures are designed so that most data structures, such as per-domain minor heap arena, major heap allocation pools, etc, are domain local. That said, we do expect some overheads due to synchronization for minor collections, the performance of system allocators, finding free pools for major heap, etc. In addition, there may be NUMA effects due to say, a global array allocated in one memory domain, where most accesses may incur the latency of a remote memory access.

**Comment by kayceesrk** [comment]
@zyedidia #13272 adds support for specifying maximum number of domains at startup. You can now do

```bash
$ OCAMLRUNPARAM="d=360" ./my_very_parallel_program.exe
```

to have 360 domains max. 

As as aside, I would be curious to learn what workloads you are using where you need more than 128 cores. Is this publicly available somewhere? Are you seeing reasonable speedup? (How) are you performance profiling the program?

If you have other issues, please report them here.
