### ISSUE TITLE
Add Atomics.swap

### ISSUE THREAD

**Issue by NoahTheDuke** [ocaml/ocaml#13387]
In #7043, a number of Atomics functions were recommended to be brought into Stdlib. The closing PR #9570 implemented `compare_and_swap` as `compare_and_set`.

I'd like to add a function like `swap` that atomically calls a function on the contents of the atomic: `Atomic.swap r (( * ) 2)` will multiply the contents of the atomic by 2, retrying if the value of the atomic has changed while performing the update.

The implementation would look something like:

```ocaml
let rec swap r f =
  let old = Atomic.get r in
  let new' = f old in
  if Atomic.compare_and_set r old new' then new' else swap r f
```

**Comment by OlivierNicole** [comment]
What is the motivation for this addition? Is it a usual function in other languages?

From my—arguably limited—experience, parallel programmers tend to avoid functions that implicitly perform busy-waiting, because busy-waiting is costly and so is usually very explicit and clearly delimited.

**Comment by NoahTheDuke** [comment]
It's the single most used "thread-safe update" function in Clojure ([clojure.core/swap! documentation](https://clojuredocs.org/clojure.core/swap!), [grep.app `swap!`](https://grep.app/search?q=swap%21&filter[lang][0]=Clojure), [grep.app `compare-and-set!`](https://grep.app/search?q=compare-and-set%21&filter[lang][0]=Clojure)). It's useful when the goal is to accrue non-integer data across threads, such as gathering a list of objects. Because you don't have to know the value ahead of time, you can "fire and forget", trusting that regardless of execution order, the change will occur and nothing will be dropped.

**Comment by gasche** [comment]
Unless I am missing something, Clojure's `swap!` is not in fact what people usually call compare-and-swap, given that it returns the new value of the reference, rather than the old value before modification. (And also it takes a function and applies it instead of taking a value.) In #10798 I proposed implementations of `Atomic.modify`, `Atomic.modify_get`, which I think correspond to what you are proposing here.

One design issue that we had in #10798, that explains why it remains un-merged, is that we don't really know what should be a good implementation in the standard library in contended scenarios. We probably want to implement some backoff policy, but which one? Deciding how to backoff may be better left as a responsibility of the caller, but the stdlib does not have an abstraction to express this.

**Comment by NoahTheDuke** [comment]
Ah yes, your `Atomic.modify` looks like Clojure's `swap!` but with different return semantics. I'll close this and comment further on that PR.
