### ISSUE TITLE
[5.3] Was the renaming of OCAMLC_CFLAGS in Makefile.config intended?

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#13503]
Reading the discussion that happened after the merge of https://github.com/ocaml/ocaml/pull/13201, it looks like the renaming of `ocamlc_cflags` etc. weren't intended.

My question is: is the renaming also not intended in `Makefile.config` ?

The reason i ask is that this file is also installed publicly as part of the OCaml distribution and some projects do use it and do use this variable. I noticed it while debugging a compilation error in `labltk` with OCaml 5.3 (see https://github.com/garrigue/labltk/pull/26)

**Comment by gasche** [comment]
I would say that the renaming was intended (the new names are arguably nicer) but we forgot to preserve backwards-compatibility by keeping the old names around. Would you want to submit a PR that includes both names in Makefile.config, to be consistent with #13244?

**Comment by shindere** [comment]
Kate (2024/09/30 08:50 -0700):
> Reading the discussion that happened after the merge of https://github.com/ocaml/ocaml/pull/13201, it looks like the renaming of `ocamlc_cflags` etc. weren't intended.
>
> My question is: is the renaming also not intended in `Makefile.config` ?
>
> The reason i ask is that this file is also installed publicly as part
> of the OCaml distribution and some projects do use it and do use this
> variables. I noticed it while debugging a compilation error in
> `labltk` with OCaml 5.3 (see
> https://github.com/garrigue/labltk/pull/26)

Good question, thanks. I think I didn't implement the backward
compatibility in `Makefile.config` because I kind of hope that people
will progressively stop using this interface in favour of `ocamlc
-config` so I humbly confess I have been reluctant to do anything that
could encourage people to continue using `Makefile.config`.

Is it reasonable to consider starting to patch the projects that still
use it to start using `ocamlc -config`?

**Comment by gasche** [comment]
My opinion: not adding support for new stuff in Makefile.config is fine, but breaking stuff that worked in the past should be avoided unless we have a good justification (when it's hard to maintain compatibility). Here it's a few-lines fix on our side and the issue goes away for all downstream projects, it's a good deal.

**Comment by shindere** [comment]
@kit-ty-kate the renaming you mention was intentional, apologies for not
having been explicit about it as well as for having broken the
backward compatibility.

The rationale behind the renaming is to use variable names that rely
on backends rather than the names of the compilers used to produce
the corresponding code, as this is believed to be more future-proof
(there is still the hope / possibility that we will one day have one single
instance of ocamlc that will be able to produce both bytecode
and (several types of) native code).

I have just submitted #13519 as aproposed fix for the present issue.
