### ISSUE TITLE
Possible regression of ambiguity checks in non-principal mode

### ISSUE THREAD

**Issue by voodoos** [ocaml/ocaml#13531]
I noticed something strange while doing some refactoring: PR #10277 introduced a test that should "fail in both cases" (with and without the `-principal` option, and that seems reasonable:

[tests/typing-gadt/ambivalent_apply.ml](https://github.com/ocaml/ocaml/pull/10277/files#diff-6236131cc368abeff97b503eaaa3ac2f68034b4447aaa907ef529c8976cdfa06)
```ocaml
type (_,_) eq = Refl : ('a,'a) eq;;

(* Both should fail *)
let f (type a b) (w1 : (a, b -> b) eq) (w2 : (a, int -> int) eq) (g : a) =
   let Refl = w1 in let Refl = w2 in g 3;;
[%%expect{|
Line 2, characters 37-40:
2 |    let Refl = w1 in let Refl = w2 in g 3;;
                                         ^^^
Error: This expression has type b = int
       but an expression was expected of type 'a
       This instance of int is ambiguous:
       it would escape the scope of its equation
|}]
```

But changes introduced in PR  #10364 appear to break this test:
[tests/typing-gadt/ambivalent_apply.ml](https://github.com/ocaml/ocaml/pull/10364/files#diff-6236131cc368abeff97b503eaaa3ac2f68034b4447aaa907ef529c8976cdfa06)
```diff
let f (type a b) (w1 : (a, b -> b) eq) (w2 : (a, int -> int) eq) (g : a) =
   let Refl = w1 in let Refl = w2 in g 3;;
[%%expect{|
+val f : ('a, 'b -> 'b) eq -> ('a, int -> int) eq -> 'a -> 'b = <fun>
+|}, Principal{|
Line 2, characters 37-40:
2 |    let Refl = w1 in let Refl = w2 in g 3;;
                                         ^^^
```

@garrigue is this behavior expected or is it a regression ?

**Comment by garrigue** [comment]
This is the expected behavior. More precisely, the `both should fail` is not about the normal mode, but about the two examples, where `w1` and `w2` have inverted orders.
#10277 is about a weakness in ambivalence detection discovered recently. Namely, ambivalence was tracked only on the node expanded by an equation, but not on its descendants, resulting in non-principal behavior. However, this does not seem to have an impact on soundness (the descendants are fresh copied nodes, so no sharing involved), so we do not need this refined treatment in normal mode.

**Comment by voodoos** [comment]
I see, thank you for the explanation. I'm closing the issue.
