### ISSUE TITLE
New syntax error in string literals in comments in 5.3

### ISSUE THREAD

**Issue by Julow** [ocaml/ocaml#13626]
This comment no longer parses with OCaml 5.3 but parsed with 5.2:

```ocaml
(** [x < min({x'|x'∊l})] *)
```

The error is:
```
File "./local/test.ml", line 1, characters 0-3:
1 | (** [x < min({x'|x'∊l})] *)
    ^^^
Error: This comment contains an unterminated string literal
File "./local/test.ml", line 1, characters 13-17:
1 | (** [x < min({x'|x'∊l})] *)
                 ^^^^
  String literal begins here
```

This might come from https://github.com/ocaml/ocaml/pull/12664 that slightly changed the lexing rules of string literals in comments for the purpose of checking the validity of them and accidentally allowing all `identchar` in them.

**Comment by gasche** [comment]
cc @Octachron . I'm not sure how intentional the change is (I have not looked closely at #12664); if it isn't, then presumably we should revert it to avoid the breakage, but maybe it *is* intentional and then I think that it's okay to ask people to change their comments slightly -- this happened in the past when lexing rules change a bit, and it can be automated as a `sed` rule if the need arises. The point is any change/fix there is backward-compatible, so it's arguably okay.

**Comment by Octachron** [comment]
The change was only partially intentional: supporting `{é|…|é}` was intended, but not necessarily supporting 
`{x12|…|x12}`.

**Comment by Julow** [comment]
Not related to the bug but I feel like the author of the comment intended to be able to type anything in an ocamldoc code span (`[ ... ]`).
Perhaps the lexer should understand ocamldoc code spans and code blocks just like it understands string literals ?

**Comment by Octachron** [comment]
I agree that it might make sense to escape the content of ocamldoc code span, but that's a quite larger change.
