### ISSUE TITLE
[github patch] warn user when a type variable in a type constraint has been instantiated

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6313]
**Original bug ID:** 6313
**Reporter:** @gasche
**Status:** acknowledged (set by @damiendoligez on 2014-07-16T13:08:38Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.0+dev
**Category:** typing
**Tags:** patch

## Bug description

Reported by Grégoire Henry:
  https://github.com/ocaml/ocaml/pull/6
Patch is available at:
  https://github.com/ocaml/ocaml/pull/6.patch

> It seems to be a common misunderstanding amongst beginners that type
> variables in type constraint are unification variables and that they
> should be explicitly quantified when desired.
> 
> This small patch adds a warning when such non-quantified variable has
> been instantiated by the type checker. The verification is made /a
> posteriori/ by looking for type constraints in the typed tree.
> 
> I'm not sure this warning is really a desired feature, but it is
> probably worth discussion. For instance, ocamlyacc-generated files use
> such variables on purpose.

**Comment by gasche** [comment]
This still sounds like an excellent idea to me. Would people that know about the type-check be able to tell whether the patch was correct and still makes sense? (cc @garrigue @lpw25 @trefis @let-def).

I think that if we wanted to gather consensus on this, we would need to ensure that people that use the feature for something else than instantiation have a way to avoid the warning. I believe that `... as 'a` should obviously not warn, so `_ as 'a` is a correct but devious way to disable the warning, but I would rather ensure that `'_a` is supported by the parser, because it is obviously the right notation for not-necessarily-generalized unification variables.

**Comment by garrigue** [comment]
Using `'_a` is rejected by the parse, as denoting a non-generalisable variable.
You suggest allowing that?
Note that since weak variables all start with `'_weak` it could make sense to remove this error (or restrict it to variable starting with `'_weak`).

**Comment by gasche** [comment]
We need a syntax for (1) a variable that may or may not be instantiated and generalizable (this is what people typically use `'a`-as-sharing for), and a syntax for (2) a variable that may not be instantiated and is generalizable. I think the most natural is to use `'a` for (2) and `'_a` for (1), so yes, this suggests allowing them in the parser, and also changing the semantics slightly (in general `'_a` would not mean "cannot be generalized" but "may not generalize"; of course when inference uses one, we know it actually could not generalized). But other syntaxes might be possible (eg. `a` for (2) ?).
