### ISSUE TITLE
type Unix.sockaddr does not express IPv6 addresses with zone info

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6479]
**Original bug ID:** 6479
**Reporter:** vbmithr
**Status:** acknowledged (set by @damiendoligez on 2014-07-16T14:11:45Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.0+beta1 / +rc1
**Category:** otherlibs
**Monitored by:** @hcarty

## Bug description

Currently, it is not possible to connect to link-local IPv6 address using the Unix module. This should be possible.

**Comment by cfcs** [comment]
should this be reopened or has it been fixed?

**Comment by gasche** [comment]
To my knowledge the feature was never implemented.

If no one reacted when the annoying bot sent a ping, we can assume that none of the people reading the bugtracker at the time were motivated enough to implement this feature request. There is little value in keeping the feature request open for years if no one is planning to work on it, so leaving it close is reasonable. Anyone is of course welcome to jump in and contribute the feature if they wish to, or to at least express interest and restart the discussion in the present issue.

It should have been closed as a "won't fix" issue rather than a "solved" issue, but the bot apparently was written before Github introduced this distinction and uses the wrong category when closing.
