### ISSUE TITLE
Consider supporting GNU-style error messages

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6518]
**Original bug ID:** 6518
**Reporter:** @gasche
**Status:** acknowledged (set by @gasche on 2014-08-21T05:47:51Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** compiler driver
**Duplicate of:** #5070
**Related to:** #6087
**Monitored by:** @Yakobowski

## Bug description

In PR #6087 Daniel Bünzli requested the use of the more standard GNU-style error messages, which have the advantage of being recognized by tools without specific configuration -- while the error-message-regexp that Emacs uses to match OCaml error messages recently changed and could require upstream change as well.

## Additional information

(Note that even if a compiler-wide switch happens, ocamlbuild will need to be changed separately as it embeds its own error-location printing routines in ocamlbuild/loc.ml)

**Comment by mshinwell** [comment]
In the face of #8541 I don't think this needs to remain open.

**Comment by mshinwell** [comment]
@gasche I didn't see any reason for this to remain open having looked at the discussion in #8541.  What value do you see in reopening it?

**Comment by gasche** [comment]
The two issues/PRs are discussing fairly different things. This one suggests using the standard gnu-style locations that are a cryptic `foo.ml:23-25:13-68` or something like that, and that (apparently?) many tools support out of the box. #8541 is about changing slightly the custom format we used for OCaml (because it was broken in the multiline case), but in fact the discussion there shows that most editors had to change their custom-made regex for OCaml error messages -- whereas presumably using the "standard" mode would have been supported out of the box, witho requiring having or modifying OCaml-specific logic.
