### ISSUE TITLE
Test OCaml's PRNG against the new TestU01 testsuite

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7073]
**Original bug ID:** 7073
**Reporter:** @gasche
**Status:** acknowledged (set by @damiendoligez on 2016-02-10T16:53:25Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Target version:** later
**Category:** standard library
**Tags:** testsuite

## Bug description

In the previous weeks many of the Pseudo-Random Number Generators (PRNG) in Javascript implementation were found to be much weaker than they should -- even at non-security, non-crypto applications, I am not talking about crypto-randomness here. See the following article on LWN.net for a summary of the issues found in Chrome, Firefox and Safari:

  http://lwn.net/SubscriberLink/666407/44be03d386807580/

(This link is made available from my LWN subscription. Consider subscribing to support this excellent source of technical journalism!)

The PRNG of web browsers were all found insufficient by Pierre L'Ecuyer's TestU01 set of statistical tests, which seems to be the modern version of the venerable Diehard PRNG testsuite.

  http://simul.iro.umontreal.ca/testu01/tu01.html

It could be interesting to test OCaml's random generator against this new testsuite. Our implementation is non-standard, partly because of OCaml's integger tagging which makes the output domain of our PRNGs non-standard.

Note: the web browsers decided to move to a PRNG named xorshift128+, found at 

  http://xorshift.di.unimi.it/

**Comment by vicuna** [comment]
**Comment author:** vigna

Erlang had a similar problem. I designed for them a variant of xorshift128+ based on 58-bits integers:

http://xorshift.di.unimi.it/xorshift116plus.c

If you're interested in a better/faster PRNG, and you use a different number of tagging bits, I can put up together a similar generator with a different bit size.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

As a first step, I'm happy to report that OCaml's PRNG (version 4.02.3) passes all the SmallCrush tests.

**Comment by xavierleroy** [comment]
I tested with [dieharder](https://webhome.phy.duke.edu/~rgb/General/dieharder.php) and the `Random` PRNG passes with flying colors:
- byte per byte: 110 tests passed, 4 tests weak, 0 tests failed
- 32 bit words: 112 tests passed, 2 tests weak, 0 tests failed
- 64-bit words: 114 tests passed, 0 tests weak, 0 tests failed.

Anyone is welcome to test with their statistical test of choice and report the results.  I'll stick with dieharder, because I find it to be quite complete.

The conclusion is that the `Random` PRNG is solid, statistically speaking.  Its only issue is that the API is missing a few operations, first and foremost splitting.  

On this note I'll close this report.
