### ISSUE TITLE
non informative link time error when the c compiler couldn't run

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7141]
**Original bug ID:** 7141
**Reporter:** @sliquister
**Status:** acknowledged (set by @damiendoligez on 2016-02-25T13:24:13Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** compiler driver
**Tags:** junior_job
**Monitored by:** @diml @hcarty

## Bug description

When failing to run the c compiler at link time (in my case because
the command line is too big), ocamlopt just fails with this error:

$ /tmp/script.sh 
File "caml_startup", line 1:
Error: Error during linking

which is not super helpful. Even after adding -verbose, we still
didn't know what was failing and strac'ing was necessary.

This is because ocamlopt runs [Sys.command .. = 0], presumably relying
on the command to report an error. I think it would be preferable if
the Linking_error exception thrown in the false case could contain the
exit code, and perhaps the program name, so the error could look like:

$ /tmp/script.sh 
File "caml_startup", line 1:
Error: Error during linking (exit code 127 from running g++)

## Steps to reproduce

cd /tmp
rm -f a.cmx* b.cmx*
touch a.ml b.ml
ocamlopt -c a.ml
ocamlopt -ccopt "$(printf "%70000s")" -a a.cmx -o a.cmxa
ocamlopt -c b.ml
ocamlopt -ccopt "$(printf "%70000s")" -a b.cmx -o b.cmxa
ocamlopt a.cmxa b.cmxa -o out

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

We should special-case 127, which is the return value of Sys.command when it fails to execute the shell (in fact the return value of system() when exec() fails). In all other cases, we rely on the shell or the command to output an error message.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

In many cases, the shell that is run by Sys.command produces useful diagnostics already:

$ ocamlopt -cc zorglub foo.ml
sh: 1: zorglub: not found
File "caml_startup", line 1:
Error: Error during linking

Indeed, there is a problem if the shell cannot be started, e.g. if the argument list is too long.

**Comment by Anukriti12** [comment]
Hi, I am an outreachy applicant. Can i work on this issue?

**Comment by gasche** [comment]
@Anukriti12 yes please feel free to work on this issue.

You can use `git grep` to locate the place in the codebase that raises the "Error during linking" message, and figure out where in that module the related error arises. 

Then it's probably a good idea to propose an approach to fix the issue in this thread, and try building a PR from that.

**Comment by Anukriti12** [comment]
I found inside `optmain.ml` file there are two condition in while linking is handled `else if !shared then begin` which calls `Asmlink.link_shared` which is the one responsible here other condition `else if not !stop_early && !objfiles <> [] then begin` calls `Asmlink.link`.

As Vicuna suggested to special-case 127 since return value of Sys.command when it fails to execute the shell one possible solution is to display `Error: Error during linking (exit code 127 from running g++)` as message for that condition.

**Comment by gasche** [comment]
I think that you correctly found the places in the "main" logic that result in the linker being called. (The flags that are checked in these conditions are set from the command-line options.) Note that the error-processing logic is not to be found in `optmain`, but in the function `report_error` of `asmcomp/asmlink.ml`; I think that it is probably in this file that some code should be edited to pass more information in this error case -- but the command execution happens in yet another file, `utils/ccomp.ml`.

If you have an idea of a change you want to make to get the error code and executable name (or the whole command?) reported in the error, feel free to open a PR. Otherwise we can discuss more here.
