### ISSUE TITLE
asmcomp "compile-time constants" do not work on cross-compilers

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7250]
**Original bug ID:** 7250
**Reporter:** @whitequark
**Status:** confirmed (set by @gasche on 2016-05-10T10:54:17Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** later
**Category:** platform support (windows, cross-compilation, etc)
**Tags:** cross-compilation
**Monitored by:** @hcarty @dbuenzli

## Bug description

Please see https://github.com/whitequark/opam-cross-windows/issues/4.

**Comment by vicuna** [comment]
**Comment author:** @gasche

The PR you link to discusses a patch ( https://github.com/whitequark/opam-cross-windows/pull/5 ), but this patch is specific to cross-compiler targeting Windows.

What we would like to have upstream is a more general support of a host/target distinction, with those values specialized according to the target rather than the host. But those patches will come from people working on cross-compilation already.

Do you know if anyone is working on this more general approach? Could your Windows work then be rebased on top of that?

I'm tempted to "suspend" the PR as a way to mark that maintainers are unlikely to work on that in the short term, and that external contributions, in particular from people already working on cross-compilation, woud be warmly welcome.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

Yes. The patch is a hack. It is a hack and not a proper patch because I have no earthly clue as to how to do it decently.

I am unaware of anyone else working in that direction or even being aware of the problem.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

@gasche Huh? Why did you mark this as "resolved"? This is absolutely not resolved in any way, what you did was just made sure that the issue will be promptly forgotten.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I believe that "suspended" is the right status for this PR, and this is accessible under the "resolved" parent status. The status name is indeed misleading (the issue is not resolved), but it has the intended consequence that maintainers will not come back to the issue on each new release, but rather wait for someone (maintainer or not) to make progress and reopen the case.

In my mind "resolved > suspended" should be interpreted as "this issue is not going to move by itself, if you care about it you should probably work on it yourself".

**Comment by vicuna** [comment]
**Comment author:** @whitequark

Well, that's a probably the second most hostile and unproductive way to regard an issue like this after closing it with a comment saying "we don't give a damn". In fact, you've just guaranteed that if I ever fix this myself, I won't bother upstreaming it.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Gabriel, this way of proceeding makes little sense to the end-users of the OCaml system, unless, in that particular case, the dev team doesn't give a shit about cross-compilation which AFAIK is not the case given the recent improvements that were merged. 

The BT is already hard to search for issues so if we start marking as resolved, issues that are not we are not going anywhere. If this is a BT usability issue for release managers please find another way to resolve it (e.g. by tagging it with 'needs help' so that these bugs can be easily ignored by them). 

This feels like sweeping issues under the carpet.

**Comment by vicuna** [comment]
**Comment author:** @gasche

whitequark, I'm not sure why you are reacting this strongly. I moved the issue back to "confirmed" land, with apologies for making unpleasing triaging choices.

I guess you and Daniel are right that this resolution makes little sense. In fact I just found out that moving a "resolved > suspended" issue back into non-resolved land keeps the "suspended" bit, which is... interesting and could be of use in the future.

I think the important bit here is the "cross-compilation" tag which I added, which guarantees that as soon as someone starts working more thoroughly on cross-compilation they will be able to find the issues that would need fixing. If you see a cross-compilation issue that lacks the tag, please add it or ping me to do so, it's helpful.

(Indeed, the dev team is interested in improving cross-compilation in general.)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

@gasche:

1. the Status and Resolution fields are completely orthogonal, I don't know why you think something has to be "resolved" to make "suspended" available.
2. For this kind of PR, I set the Target Version to "later", which means "we are not working on this in the short term but contributions are still welcome". This takes the PR out of the release workflow.

**Comment by whitequark** [comment]
I think there was an effort to fix this systematically, but I don't know if this issue is fully fixed, and I couldn't quickly determine if it is.

**Comment by whitequark** [comment]
Stop with the stale labels already.

**Comment by XVilka** [comment]
Agree with @whitequark. In Rizin project we also initially enabled the stalebot but after year of use it was considered an annoyance and harmful since not all old issues are irrelevant even after many years of existence. Closing all bugs will not happen anyway, thus the number of opened issues should not be gamified, in my opinion, and issues treated as a kind of knowledge base, sometimes actionable and useful, even with workaround information.

Drew DeVault wrote a good article about it: https://drewdevault.com/2021/10/26/stalebot.html

**Comment by whitequark** [comment]
It is plainly disrespectful to anyone who spends their time investigating and filing bugs. Especially considering that *this specific* issue has a long history of maintainers being disrespectful!

Anyway, I am going to harass people here about the stalebot until they fix it or ban me.

**Comment by gasche** [comment]
I agree that the stale bot is bad and I would rather have it go away -- I agree with the post by Drew. There is obviously disagreement about this among compiler maintainers; some maintainers want to close PRs/issues that are going nowhere, and the stale bot helps with that.

I am pretty sure that "harass[ing] people here" is not going to improve the situation in any way; please don't do that.

The bug still exists today, and it is still the case that it is waiting for someone working on cross-compilation to be solved properly.

To my knowledge the best documentation of cross-compilation today is [in the Diskuv documentation by Jonah Beckford](https://diskuv-ocaml.gitlab.io/distributions/dkml/doc/CompilingInDepth.html#changing-ocaml-to-do-cross-compilation). It documents several limitations, including the one in the present issue report.

I am closing this issue because it will make the stale bot go away, which is fine, and not prevent discussion in any way. If someone actually starts working on cross-compilation for OCaml, they should feel free to reopen.

**Comment by xavierleroy** [comment]
https://github.com/ocaml/code-of-conduct/blob/main/CODE_OF_CONDUCT.md

**Comment by whitequark** [comment]
> Closed [#7250](https://github.com/ocaml/ocaml/issues/7250) as completed.

The "completed" here perfectly complements the attitude that brought the stalebot online.

I'll make sure to close all of the other issues I've opened, since it's clear that no one cares about them and there is no point in doing anything else.

**Comment by whitequark** [comment]
Thank you, @gasche.

**Comment by gasche** [comment]
Two comments:

- A repeating pattern in this discussion is maintainers using imperfect (or downright bad) tools, and infrequent contributors being offended by the messages generated by those tools. As a maintainer, I find it harsh to blame me because the default way to do something sends a "resolved" message that in fact does not work in this particular situation. (This happened with both Mantis, our previous bugtracker, and now Github.) I think that you do have a point that triaging tools embody attitudes towards contribution, but I would prefer to be given the benefit of the doubt that most of it is unintentional -- it is not like there is a perfect, convenient bugtracker that never sucks and that we can easily adopt. Some aspects could be improved with people working on that (for example the stale bot itself clearly should not mark issues as "resolved"), but maintenance resources are scarce (see [this discuss post](https://discuss.ocaml.org/t/maintenance-bottlenecks-in-the-compiler-distribution/11045)) and no one volunteered to spend time on the bugtracker.

- You @whitequark have made impressive experiments of bringing the compiler well outside the comfort zone, and generated bug reports out of that. I am very glad for this work, but it is also true that most frequent contributors have other priorities and no one has volunteered to specifically work to fix those issues. There is progress from time to time (for example, at least the cross-compilation situation is better documented now; on the Unicode front @xavierleroy made nice progress with #11717 and #11736 ; but #11736 is blocked on a filepath issue with no volunteer to do the work). I wouldn't say that "no one cares about your issues", but I personally care about more things that I can work on by myself, so either people volunteer to help or many things stay in limbo for years.

**Comment by whitequark** [comment]
> * but I would prefer to be given the benefit of the doubt that most of it is unintentional -- it is not like there is a perfect, convenient bugtracker that never sucks and that we can easily adopt.

I apologize for my earlier remarks (both the recent one and the one made many years before), I agree that I was out of line in both cases, and I'll make sure to approach the project in a different manner from now on.

That being said, I must mention that I only do so because you are someone I have a lot of respect personally as a result of many interactions over the years (on here, on #ocaml IRC, on StackOverflow and probably elsewhere).
