### ISSUE TITLE
Relaxing the value restriction some more

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7320]
**Original bug ID:** 7320
**Reporter:** @sliquister
**Status:** acknowledged (set by @damiendoligez on 2017-04-14T14:46:53Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Monitored by:** @gasche @yallop

## Bug description

Relaxing the value restriction some more

If I write this:
```
# let f =
  let now = ref 0 in
  fun () -> now, ref []
  ;;
val f : unit -> int ref * '_a list ref = <fun>
```
the type f is not generalized. But I don't name the intermediate value:
```
# let f =
  ref 0;
  fun () -> ref 0, ref []
  ;;
val f : unit -> int ref * 'a list ref = <fun>
```

or I name it at toplevel:
```
# let now = ref 0
  let f = fun () -> now, ref []
  ;;
val f : unit -> int ref * 'a list ref = <fun>
```

then the type is generalized.

It would be nice if, when I want to write something like the first snippet, I didn't have to write something like the third snippet instead, to work around the value restriction.

I think [`let x = e1 in e2`] should be generalized by saying:
- if `e1` is non-expansive, then generalize the type of the whole expression
- otherwise, go down recursively in `e2` to try to generalize it (the level mechanism would prevent generalization of the variables shared with the type of `e1`)

ie when an expression is not non-expansive, instead of giving up on generalizing it, try to generalize the non-expansive parts of it instead.

This would make all 3 examples behave the same.

**Comment by gasche** [comment]
@garrigue @lpw25 this sounds like a proposal you would have opinions about. Did you review this issue during its stale period?

(I think that the level mechanism suggested doesn't really work as an implementation approach because levels are only bumped in this example at `let f`, not after the `let ... in`. But the example seems interesting and the general idea of relaxing notions of syntactic values may be fruitful.)

**Comment by garrigue** [comment]
I'm aware of this idea. @fpottier and @diremy repeatedly suggested doing that. This is not so easy to do it with the current implementation, so I didn't revive it, but we will certainly consider it if we change the inference algorithm.

**Comment by diremy** [comment]
Indeed, we discussed this with @garrigue and also @xavierleroy a long time ago, and yes, we only need to disallow generalization of type variables that contribute to the type of an exposed expansive expression where application of contructors are non-expansive and expressions under abstractions are not exposed. This is known to be sound. 

I am not sure that this alone cannot be fixed in the current implementation, but there are other more interesting and more useful examples that we would like to allow which we have also been considering with @garrigue which would imply deeper changes and require more discussions.
