### ISSUE TITLE
In or-patterns, propagate path disambiguation from one prefixed constructor to other constructors

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7386]
**Original bug ID:** 7386
**Reporter:** @gasche
**Status:** acknowledged (set by @xavierleroy on 2017-02-23T16:06:20Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0
**Category:** typing
**Related to:** #5759 #5980 #7443
**Child of:** #6951 #7409
**Monitored by:** @ygrek @jmeber @yallop @hcarty

## Bug description

If we write a record pattern or expression with fields { a; M.b; c }, it is understood as equivalent to { M.a; M.b; M.c }. I would like this property to also hold of variant constructors appear in an or-pattern (or at the head of a list of clauses): (A | M.B | C) should be equivalent to (M.A | M.B | M.C), and

```ocaml
  | A -> ...
  | M.B -> ...
  | C -> ...
```

equivalent to

```ocaml
  | M.A -> ...
  | M.B -> ...
  | M.C -> ...
```

## Additional information

Here is a concrete example I just had of a situation where this feature would be useful to me:

```ocaml
  let fill_cache article_map =
    let open Canopy_content in
    let fold_fn key value acc =
      value () >>= fun content ->
      date_updated_created key >>= fun (updated, created) ->
      let uri = String.concat "/" key in
      match of_string ~uri ~content ~created ~updated with
      | Ok article ->
        article_map := KeyMap.add key article !article_map;
        Lwt.return acc
      | Error error ->
        let error_msg = Printf.sprintf "Error while parsing %s: %s" uri error in
        Lwt.return (error_msg::acc)
      | Unknown ->
        let error_msg = Printf.sprintf "%s : Unknown content type" uri in
        Lwt.return (error_msg::acc)
    in
    new_task () >>= fun t ->
    fold (t "Folding through values") fold_fn []
```

This is code is from <https://github.com/Engil/Canopy> . When compiled from 4.03, it raises the following warnings:

```
  File "canopy_store.ml", line 78, characters 4-716:
  Warning 45: this open statement shadows the constructor Ok (which is later used)
  File "canopy_store.ml", line 78, characters 4-716:
  Warning 45: this open statement shadows the constructor Error (which is later used)
```

The best way I see to silence the warning is to write

```ocaml
      match of_string ~uri ~content ~created ~updated with
      | Canopy_content.Ok article ->
        article_map := KeyMap.add key article !article_map;
        Lwt.return acc
      | Canopy_content.Error error ->
        let error_msg = Printf.sprintf "Error while parsing %s: %s" uri error in
        Lwt.return (error_msg::acc)
      | Unknown ->
        let error_msg = Printf.sprintf "%s : Unknown content type" uri in
        Lwt.return (error_msg::acc)
```

but I would find it natural if it was possible to prefix only the first constructor.

We previously discussed this feature during the type-based-constructor/field-disambiguation debate, but the applicability scope I had in mind was too broad and with an unclear specification. I believe that "are in a single or-pattern" (or, as a generalization, at the head of the clauses of a matching) is a clear, simple and useful specification.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I realize now that another way to avoid this warning would be to not warn when type-directed disambiguation in fact selects a non-ambiguous candidate: this means that the syntactic ambiguity is in fact benign, as the types determine the only possible choice. That's a feature request for the ambiguity warning.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

1) Another direction which would address this specific case is to disambiguate using all constructors "at the same position" (in your example, lookup a type containing the three constructors Ok/Error/Unknown), as we do for records.  The definition of "at the same position" could be the same as the one used to propagate paths.

2) Do you think that extending the notion of "at the same position" to traverse tuples would add too much complexity to this proposal?  (i.e. support function (M.A, _) -> ... | (B, _) -> ...).

**Comment by gasche** [comment]
I still believe that "at the head of the same or-pattern" or "at the head of clauses" is a good criterion to propagate qualifying modules or do multi-label disambiguation, because it is simple, predictable, useful in several situations and consistent with what we do for record fields. I am putting "implementing this" on my medium-term TODO-list, please complain if you don't like the idea!

**Comment by jberdine** [comment]
I think this would be valuable. This is something to which I've seen newcomers have a sort of "silly type-checker is just being intentionally obtuse" reaction. It seems to be run into reasonably frequently, though we tend to react by putting a type annotation on `e` in `match e with` rather than prefixing some of the constructors in the pattern.

**Comment by lpw25** [comment]
I'm a little worried about it because I assume that:
```ocaml
match e1, e2 with
| A, C -> ...
| M.B, D -> ...
```
will work, but:
```ocaml
match e2, e1 with
| C, A -> ...
| D, M.B -> ...
```
won't

**Comment by gasche** [comment]
With the simple criterion I proposed, neither would work, because they are not at the "head" of the pattern. Any extension that goes under constructor may run into trouble (in theory "at the same position under the same constructors" should work, but in fact because of GADTs it would only be correct in general to take the first argument of the constructor, giving the feeling of arbitrariness that Leo demonstrates in his example).
