### ISSUE TITLE
minimal documentation on injectivity

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7550]
**Original bug ID:** 7550
**Reporter:** @Octachron
**Status:** acknowledged (set by @Octachron on 2017-07-11T19:44:17Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** documentation
**Tags:** manual, junior_job
**Monitored by:** @gasche

## Bug description

Injectivity is never mentioned in the manual. Consequently, there are no explanation on why the "B" case cannot be refuted in

```ocaml
module M: sig type 'a t end = struct type 'a t = private T end
open M
type 'a s = A: int t s | B: float t s
let f:int t s -> int = function A -> 0 | _ -> .
```

whereas the apparently similar refutation case works fine:

```ocaml
module M: sig type 'a t = private T end = struct type 'a t = private T end
open M
type 'a s = A: int t s | B: float t s
let f:int t s -> int = function A -> 0
```

Adding a short example and explanation in the GADTs section of the language extension chapter would make the previous example less mysterious.

**Comment by isaacv-pl** [comment]
Hi, I'm an Outreachy applicant. Could this be my first contribution?

**Comment by gasche** [comment]
Hi @nobrowser: yes it could, but I think that writing documentation on this point requires a good familiarity with the OCaml type system (it's a newcomer job because it does not require familiarity with the compiler implementation). If you are not familiar with GADTs or the behavior of the example given above, I would maybe recommend picking an easier task.

**Comment by ghost** [comment]
Hmm.  Has someone uttered my name?  That is not an action one should take lightly!  AAAARRRRGGHHHHH!

**Comment by gasche** [comment]
Indeed, I meant @notemaster; sorry @nobrowser :-)

**Comment by isaacv-pl** [comment]
Okay, I did spend a bit of time familiarizing myself with certain examples of GADT's and I have some background in Type theory but I'm not super solid on everything thats going here. I'll look at another job then but keep this one on the backburner. Thanks @gasche!

**Comment by Octachron** [comment]
I have moved the issue to the advanced section of `newcomer-jobs` because it is the true that it requires a very specific skill set for a newcomer.

**Comment by anmolsahoo25** [comment]
If I understand this correctly, this behavior is because in the first case the type is assumed to be non-injective, thus it unifies `int t s` and `float t s` whereas in the second case, the type is injective, thus `int t s` and `float t s` are now distinct and can be refuted. (Apologies for the imprecise wording, I guess, not too well-versed with OCaml's type theory)

**Comment by gasche** [comment]
Note: there is now a proposed PR, #9500, that introduces explicit annotations for injective type parameters (`type !'a t= ...`). It comes with minimal changes to the manual (see [the current diff](https://github.com/ocaml/ocaml/pull/9500/files#diff-4a80c4268ca2f3ab338a46689949a2f0)) that may interact with the request in this issue. Note that the new documentation is in the "type declaration" part of the reference manual, there would probably remain to mention injectivity explicitly in the GADT chapter.
