### ISSUE TITLE
Dummy location reported for type error in toplevel declaration involving private

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7819]
**Original bug ID:** 7819
**Reporter:** @Armael
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.0
**Category:** toplevel

## Bug description

The following toplevel phrase produces a type error with a dummy location:

```
$ TERM=dumb ocaml

# type 'a t = private < x : int; .. > as 'a;;
Characters -1--1:
  type 'a t = private < x : int; .. > as 'a;;
  
Error: Type declarations do not match:
         type 'a t = private < x : int; .. > constraint 'a = 'a t
       is not included in
         type 'a t
       Their constraints differ.
```

**Comment by mrmr1993** [comment]
This appears to be fixed in trunk:

```
$ TERM=dumb make runtop

        OCaml version 4.11.0+dev0-2019-10-18

# type 'a t = private < x : int; .. > as 'a;;
Line 1:
Error: Type declarations do not match:
         type 'a t = private < x : int; .. > constraint 'a = 'a t
       is not included in
         type 'a t
       Their constraints differ.
```

**Comment by gasche** [comment]
I don't know what the issue was and whether it really was fixed. Even on 4.07, calling `ocaml /tmp/foo.ml` would print correct locations for this sentence. Interactive use with TERM=dumb does indeed show nonsensical locations, and later versions of the toplevel stop doing this, but I don't know if there ever was a nonsensical location parsed for the sentence (maybe the dummy-loc came from some other place) and if this location actually changed, or we just got better at not printing the location when we don't know.

In any case, indeed the user-facing issue (-1 in a location) is gone in 4.08 and later (note: 4.08 still prints the file as `_none_` which is a bit confusing, but then 4.09 and later don't do this either), so I will close the issue as not-an-issue-anymore.

Thanks for the reporting work.
