### ISSUE TITLE
patch of byterun/unix.c to bring native runtime inline with bytecode in regards to plugin reloading

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7893]
**Original bug ID:** 7893
**Reporter:** progman
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** rpi3
**OS:** raspbian
**OS Version:** debian 18
**Version:** 4.07.1
**Category:** dynlink and natdynlink
**Monitored by:** @nojb @hcarty

## Bug description

```diff
*** unix.c.dlltest	2019-01-05 07:26:44.459916955 +0000
--- unix.c	2019-01-05 08:22:05.729915688 +0000
***************
*** 273,278 ****
--- 273,282 ----
  
  void * caml_dlopen(char * libname, int for_execution, int global)
  {
+   //check whether already loaded
+   void* handle= dlopen(libname, RTLD_NOW | RTLD_NOLOAD);
+   if(handle)//it is so unload first as code is not otherwise actually loaded again
+     if(dlclose(handle) || dlclose(handle)) return NULL;
    return dlopen(libname, RTLD_NOW | (global ? RTLD_GLOBAL : RTLD_LOCAL));
    /* Could use RTLD_LAZY if for_execution == 0, but needs testing */
  }
```

**Comment by vicuna** [comment]
**Comment author:** progman

bytecode plugins can be edited, re-compiled and re-loaded into a running program.
with native the operation appears successful but does not in fact reload the
code.
the patch checks for presence of said plugin and unloads it to ensure 
a code refresh.
two dlclose()'s are required (docs say 1 close each open, and RTLD_NOLOAD still
(in practice) increments the plugin reference count, hence two)

**Comment by houndofsound** [comment]
Makefile:
go: dmods
	ocamlc -c dyn.ml
	ocamlc -o main dyn.cmo dynlink.cma main.ml
	(sleep 1 ;mv dmod2.cmo dmod.cmo; echo new dmod...)&
	./main

dmods:	dmod.ml dmod2.ml
	ocamlc -c dmod.ml
	ocamlc -c dmod2.ml

#doesn't work! dynlink successful but code not changed.
#patched byterun/unix.c:caml_dlopen to unload previous load
opt:
	ocamlopt -c dyn.ml
	ocamlopt -o dmod.cmxs -shared dmod.ml
	ocamlopt -o dmod2.cmxs -shared dmod2.ml
	ocamlopt -o main dyn.cmx dynlink.cmxa main.ml
	(sleep 1 ;mv dmod2.cmx dmod.cmx; mv dmod2.cmxs dmod.cmxs; mv dmod2.o dmod.o; echo new dmod...)&
	./main

dyn.ml:
open Printf
type dynfuns={
  mutable f1:unit->unit
}

let deffun()=
  printf "default dyn function\n"

let dynfuns={f1=deffun}

main.ml:
(*
load a unit, invoke one of it's function, wait for keypress,....
then go and change the unit ...
press key, and reload unit, invoke same function
*)

open Printf
open Dyn

open Dynlink

let prompt()=
  printf "press enter...";
  let _=read_line() in
  ()

let go()=
  let file= adapt_filename "dmod.cmo" in
  dynfuns.f1();
  loadfile file; (*it registers in the above record *)
  dynfuns.f1();
  prompt();
  loadfile file;
  dynfuns.f1();
  printf "done\n"

let _=go()

dmod.ml:
open Dyn
open Printf
let myfun()=
  printf "dynamically loaded fun...\n"

let _=
  dynfuns.f1<-myfun

dmod2.ml:
open Dyn
open Printf

type t=INT of int
let i=INT 99

let myfun()=
  printf "dynamically loaded fun 2nd!!!!...\n"

let _=
  dynfuns.f1<-myfun

**Comment by progman1** [comment]
still reproducible.

**Comment by lthls** [comment]
Unloading of modules in native dynlink is not supposed to work, and your example doesn't need to be modified much to show why.
If you replace the contents of the `go` function in `main.ml` by:
```ocaml
let file= adapt_filename "dmod.cmo" in
let f_before = dynfuns.f1 in
loadfile file; (*it registers in the above record *)
let f_between = dynfuns.f1 in
prompt();
loadfile file;
let f_after = dynfuns.f1 in
f_before ();
f_between ();
f_after ();
printf "done\n"
```

You should get an error in the call to `f_between` (with your patch) as its code has been unloaded. I'm not quite sure why it is fine to allow it in bytecode (I hope that at least there's a check that they share the same interface), but in native mode due to symbol conflicts you can't allow two compilation units with the same name to be loaded together (I wonder why the compiler is silently ignoring the second load instead of complaining, though). And since you can't unload code because you may still have closures around that point to it, that means you're stuck with only one dynamic load for each name.
For cases like yours where the modules are only loaded for their side effects, there's no reason why you could not just keep distinct file names. If you're actually depending on overriding the same module name (for instance if you are loading another module that depends on `Dmod`), then even in bytecode I don't think it was supposed to work.
