### ISSUE TITLE
test failures for alternative implementation of Float.round

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7917]
**Original bug ID:** 7917
**Reporter:** aha
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** standard library
**Monitored by:** @nojb

## Bug description

First failing test is
https://github.com/ocaml/ocaml/blob/4.08.0%2Bbeta1/testsuite/tests/lib-float/test.ml#L27

## Steps to reproduce

I can only reproduce it with gcc version 7.x (and newer) and 32-bit targets, e.g. mingw:

i686-w64-mingw32-gcc --version # i686-w64-mingw32-gcc (GCC) 7.4.0
./configure --build=x86_64-unknown-cygwin --host=i686-w64-mingw32
make world.opt
cd testsuite
make one DIR=tests/lib-float

(The Appveyor CI still uses gcc 6.4.0-1 ( https://ci.appveyor.com/project/avsm/ocaml/builds/22228711/job/v4rdbiu16yiwk2i6?fullLog=true#L26 ) instead of the current 7.4.0-1.)

It's not windows specific. The same happens under 32-bit linux, if the alternative implementation is chosen manually:

gcc --version # gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
./configure
sed -i 's|#define HAS_C99_FLOAT_OPS 1||g' runtime/caml/s.h
make world.opt
cd testsuite
make one DIR=tests/lib-float

**Comment by xavierleroy** [comment]
Sorry if this bug was ignored for so long.  I was able to reproduce it with x86 in 32-bit mode under Linux, as described.

This is an "excess precision" issue with GCC, similar to the infamous [GCC bug 323](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=323).  Consider https://github.com/ocaml/ocaml/blob/1d76e2ca91633ac63759c4672e9a8dddabac8a31/runtime/floats.c#L496
Recent enough versions of GCC implement `floor` with nice inline x87 code.  Hence, `f + pred_one_half.d` is computed on the x87 stack in extended precision, not rounded to double precision (that's the bug), then passed to `floor`.  The lack of rounding the sum to double precision causes the wrong result for `caml_round(0.5)`.  The same lack of rounding is a GCC bug w.r.t. the ISO C standard, of the bug 323 kind.

Passing `-fexcess-precision=standard` to GCC makes the bug go away.  Now I need to check with other developers if it's the best workaround and how to implement it cleanly.

**Comment by rwmjones** [comment]
This breaks compiling C++ files, eg if they use `:standard` flags in the dune file.  The reason is that although GCC supports `-fexcess-precision=standard` for C files, it doesn't support it for C++ files.

See:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/M2VM5DNB7HSAJIFDGT4WAIZDA5JPE5KM/

**Comment by fweimer** [comment]
And the flag isn't need on modern distributions which build there x86 (32-bit) variants with `-msse2 -mfpmath=sse` (no excess precision there due to SSE2).

**Comment by xavierleroy** [comment]
Thanks for the report.  I didn't know that some people would compile C++ files with ocamlc -c or ocamlopt -c.  See #9496 for a proposed fix.
