### ISSUE TITLE
It's difficult to make use of -runtime-variants

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7926]
**Original bug ID:** 7926
**Reporter:** lortex
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** platform support (windows, cross-compilation, etc)
**Monitored by:** @nojb @gasche

## Bug description

Currently, it's not possible to choose a custom variant unless libasmrun<name>.a is installed in the ocaml library directory. 
In most situations it's not a problem as any opam package could go and install its runtime variant in '<prefix>/lib/ocaml'.
However it's not possible to do that if ocaml is a system compiler (installed in '/usr/lib/ocaml' for example) because of permissions issues.

Is there a workaround ?
Is it possible to add an option to specify the runtime variant location ?

**Comment by dbuenzli** [comment]
See @TheLortex's PR https://github.com/ocaml/ocaml/pull/2309 (whose name should be changed to reflect what it does).

**Comment by gasche** [comment]
I'll note that @TheLortex discovered (in the process of implementing the PR above) that `-I <path>` actually works to indicate alternate directories for runtime variant, solving the immediate issue describing in this ticket (so I'm closing this). But we are discussed better / more discoverable ways to do these things.

**Comment by dbuenzli** [comment]
Note that `-I path` is in general unfriendly for incremental build systems. That said I'm not sure why you closed the issue while the corresponding PR to solve this problem has not been merged.

**Comment by gasche** [comment]
If I understand correctly, the issue as described is "I can't build my own runtime variants unless I install the `.a` in `ocamlc -where`"; this issue is entirely solved by using the `-I` flag -- although I believe we still have an ergonomics/usability problem with this workaround. The PR solves a more general problem that you helped identify, so I think the two are not directly related anymore.

Also, apparently it's PR-closing time after the migration, I didn't want to be left behind!
