### ISSUE TITLE
ocamlopt lets the compiler/linker silently fail if too many -ccopt or -cclib arguments are passed in

### ISSUE THREAD

**Issue by 2BitSalute** [ocaml/ocaml#8549]
Here's the StackOverflow post about this: https://stackoverflow.com/questions/55252132/ocamlopt-doesn-t-produce-any-output-only-an-error-code/55367803

The workaround is to pass `-ccopt @<compiler_args.file>` or `-cclib @<linker_args.file>`, but the only clue as to what was happening was `strace ld` or `strace gcc` showing that the tools exited with the message:

```
write(2, "ld", 2ld)                       = 2
write(2, ": no input files\n", 17: no input files
```

**Comment by nojb** [comment]
This seems to be a bug with the system compiler/linker. Not sure what we should do (if anything) on our side.

**Comment by xavierleroy** [comment]
`ocamlopt` doesn't call `ld` directly, but through the C compiler driver, so we don't have the full story.  Could you post a repro case?  Or a full trace ?  (e.g. `strace -f ocamlopt ...`)

**Comment by 2BitSalute** [comment]
The repro is a little entangled with our build system and the particular dependency I was including. The resulting command line is something like, `ocamlopt -cc <gcc> ` +  a sequence of thousands of -ccopt arguments or -cclib arguments (depending on whether a .c file was included in the ocaml binary or just a reference to the .o that included it instead).

I see the same error from gcc in the compilation phase.

```
write(2, "gcc: fatal error: no input files"..., 33gcc: fatal error: no input files
) = 33
write(2, "compilation terminated.\n", 24compilation terminated.
) = 24
```

strace of ocamlopt - I don't know what's important there, but I don't see an obvious error:
```
...
brk(0xdad000)                           = 0xdad000
lseek(1, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
lseek(2, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
getrusage(RUSAGE_SELF, {ru_utime={0, 2491}, ru_stime={0, 2491}, ...}) = 0
getrusage(RUSAGE_CHILDREN, {ru_utime={0, 0}, ru_stime={0, 0}, ...}) = 0
stat("<some_path>/ocaml/ocaml_compiler_internal_params", 0x7ffeefb01a00) = -1 ENOENT (No such file or directory)
stat("<some_path>/ocaml/ocaml_compiler_internal_params", 0x7ffeefb01a00) = -1 ENOENT (No such file or directory)
getrusage(RUSAGE_SELF, {ru_utime={0, 2672}, ru_stime={0, 2672}, ...}) = 0
getrusage(RUSAGE_CHILDREN, {ru_utime={0, 0}, ru_stime={0, 0}, ...}) = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

Is ocamlopt expecting/handling error code 2 or 4 from the C compiler that indicates an internal error?

**Comment by xavierleroy** [comment]
This is not really helping.  If the problem is caused by an excessively-long command line, as you assume, I'd like to see exactly which call to `exec*` runs into this error (`E2BIG` error code), which program performs this `exec*` (ocamlopt when invoking gcc? gcc when invoking ld?), and how the error code is handled or not.  To analyze this, I need either a repro case or a full strace.

**Comment by cyberhuman** [comment]
We have a similar issue, but with archiver (`ar`).
I first noticed that the command line was very long, bigger than 128 Kbytes, and then by strategically attaching strace to a running dune process, I managed to catch E2BIG (filenames are obfuscated):
```
[pid 16104] 07:13:33.149155 execve("/bin/sh", ["sh", "-c", "ar rc 'api/src/apicore.a' 'api/src/.apicore.objs/native/apicore.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzzzzzzzzzzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzzzz.o' 'api/src/.apicore.objs/native/apicore__zzzzz.o' 'api/src/.apicore.objs/native/apicore_"...], [/* 105 vars */]) = -1 E2BIG (Argument list too long) <0.000084>
```
And the command line and the error message can be found in [the attached log file](https://github.com/ocaml/ocaml/files/3582936/ocaml.log).

I guess the fix would be do create a temp file and supply to `ar` here https://github.com/ocaml/ocaml/blob/trunk/utils/ccomp.ml#L151, instead of passing the list of files directly. If we prepare the corresponding patch, is there a chance it will be accepted?

**Comment by nojb** [comment]
> I guess the fix would be do create a temp file and supply to `ar` here https://github.com/ocaml/ocaml/blob/trunk/utils/ccomp.ml#L151, instead of passing the list of files directly. If we prepare the corresponding patch, is there a chance it will be accepted?

If it is a problem in the `ar` invocation from `ocamlopt`, as you seem to indicate, then any patch fixing this would be considered for inclusion.

**Comment by gasche** [comment]
If I understand correctly, you are suggesting to use the responsefile mechanism `ar @file`? It would indeed be a reasonable fix (the relevant code to chave is `create_archive` in `utils/ccomp.ml`); but how do we know which `ar` support this option?

Quick browsing seems to suggest that:
- both GNU ar and Windows's `link` command (used by the msvc build) support responsefiles (`@file`)
- all UNIX `ar` utilies can be called several times to add new files to an archive (but presumably this is rarely used and may not work as well as advertised)
- both GNU ar and BSD ar support a `-M` option to pass commands to the standard input instead of the command-line
- the POSIX/OpenGroup standard descriptions of `ar` do not mention either responsefiles or the `-M` option

I guess that this patch would require testing the presence of whatever mechanism you use at configure-time, and that might be the less pleasant part of the patch.

**Comment by cyberhuman** [comment]
I wanted to do a quick hack to not be blocked on it and figured out the actual responsefile mechanism is already implemented for Windows. So indeed the "testing the presence of whatever mechanism you use at configure-time" is the less pleasant part of the patch, and is 99% of the whole patch.

**Comment by gasche** [comment]
(I'm not sure whether you have a complete patch already and have not submitted it yet, or if I missed it, or if it doesn't really exist for now. In any case, if/when you do have a patch submitted as a PR, please cross-link it with this issue to make it easy to find.)

**Comment by cyberhuman** [comment]
I don't have the proper patch yet, sorry. Will cross-link the PR if I submit it.
