### ISSUE TITLE
Warning number 8 affect generated code

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#8623]
See this https://github.com/BuckleScript/bucklescript/issues/3209 for more details.
In general people would expect warning numbers only emit warnings without other side effect, what do you think about this issue?

**Comment by dra27** [comment]
Could the issue be made a little more self-contained, please? The original Bucklescript issue could at least display the relevant diff and it’d be nice if the OCaml which generates that output didn’t have to be found from a larger test not included in the issue itself...

**Comment by bobzhang** [comment]
below is a self contained example, `+8` will have an effect on generated lambda code
```
[@@@ocaml.warning "a+8"]
type t6 = 
  | T60  
  | T61
  | T62
  | T63
  | T64 of int 
  | T65 of int 
  | T66 of int 
  | T68 of int


  let f9 = function 
  | T60
  | T61
  | T62 -> 1 
  | T64 _ 
  | T65 _ -> 2
  | _ -> 3   
```

**Comment by trefis** [comment]
Can you confirm which version of ocaml you are trying with? And whether you can still observe this behavior on trunk?

**Comment by garrigue** [comment]
My understanding is that indeed the generated code for some non-trivial exhaustive pattern-matches could be different according to the setting of warning 8 until version 4.05. Since 4.06, this is no longer supposed to happen (i.e. the only occurrences of `Warnings.Partial_match` are in the reporting code, see `Parmatch.do_check_partial` for the only place it is used). So knowing the version matters much here.

**Comment by garrigue** [comment]
See commit d91ea93596 of August 2017, by @trefis

**Comment by bobzhang** [comment]
@garrigue that's good news. The version I found is 4.02.3, we already supported 4.06.1, thanks for the info.
