### ISSUE TITLE
feature wish: some reasonable way to disable taill-call optimization to get better backtraces

### ISSUE THREAD

**Issue by bandersongit** [ocaml/ocaml#8643]
(Edit: this issue was originally written as a bug report, see the discussion below.)

Details can be found in depth in the README/code of [this repo](https://github.com/bandersongit/ocaml-stacktrace-issue) I created to reproduce the issue. 

Essentially if I have the following code (pardon the syntax/formatting, I wrote this example in Reason and then outputted it as ocaml. this is all in the example repo in both ocaml and reason because I thought that might be a complicating factor, but it was not)

ExampleFramework.ml
```ocaml
;;Printexc.record_backtrace true
let numSlots = 100
let printBacktraceOnCall () =
  (Printexc.get_callstack numSlots) |> (Printexc.print_raw_backtrace stdout)
let run fn =
  match fn printBacktraceOnCall with
  | exception _ -> Printexc.print_backtrace stdout
  | _ -> ()
```
Examples.ml
```ocaml
let exceptionCase _ = raise Not_found
let callbackLastLineCase callback = (); callback ()
let unitLastLineCase callback = callback (); ()
```
ReproOcamlBugApp.ml
```ocaml
;;print_endline "\nexception behavior:\n"
;;ExampleFramework.run Examples.exceptionCase
;;print_endline "\nworks as expected:\n"
;;ExampleFramework.run Examples.unitLastLineCase
;;print_endline "\ndoes not have the Examples file in the stack trace:\n"
;;ExampleFramework.run Examples.callbackLastLineCase
```

I get the following output:
```sh
exception behavior:

Raised at file "ocaml-src/Examples.ml", line 1, characters 22-37
Called from file "ocaml-src/ExampleFramework.ml", line 6, characters 8-31

works as expected:

Raised by primitive operation at file "ocaml-src/ExampleFramework.ml", line 4, characters 2-35
Called from file "ocaml-src/Examples.ml", line 3, characters 32-43
Called from file "ocaml-src/ExampleFramework.ml", line 6, characters 8-31
Called from file "ocaml-src/ReproOcamlBugApp.ml", line 4, characters 2-48

does not have the Examples file in the stack trace:

Raised by primitive operation at file "ocaml-src/ExampleFramework.ml", line 4, characters 2-35
Called from file "ocaml-src/ExampleFramework.ml", line 6, characters 8-31
Called from file "ocaml-src/ReproOcamlBugApp.ml", line 6, characters 2-52
```

Essentially in the exception case and in the case with Printexc.get_callstack and a unit after the line that calls the callback I correctly get Examples.ml in the callstack, but without the unit Examples.ml is not in the callstack with Printexc.get_callstack and I expect it to be there (both logically and based on the exception behavior).

**Comment by gasche** [comment]
This is a natural consequence of the tail-call optimization: tail calls do not grow the call stack. `callback ()` is a tail call in `(); callback ()` and it is not in `callback (); ()`, so the two usage contexts result in different stack traces.

It is not unreasonable to expect better from stack traces (there is old research by John Clements on how to present more complete call stacks to the user, even in presence of tail-call optimization), but this is a known behavior of the current implementation that is part of its accepted specification, rather than a bug.

**Comment by jberdine** [comment]
As someone who has to sprinkle `|> (fun x -> x)` through code in order to manually disable TCO, I have a lot of sympathy for the original report. While not a bug in the sense of a divergence between the implementation and accepted specification, this is a reasonable feature request. Is there a way to tag it is as such in the post-Mantis world?

Also, are there any pointers about how feasible it might be to reuse the machinery for reporting inlined function calls in stack traces.

Or even the seemingly simplistic approach of just disabling TCO for calls to non-recursive functions when compiling with `-g`? Is there any previous discussion which would indicate the reception such a PR would receive?

**Comment by bandersongit** [comment]
Something like what @jberdine described would awesome. This came up for me as I was debugging the stack trace output by the [Rely](https://github.com/facebookexperimental/reason-native/tree/master/src/rely) test runner. 

"Accurate" stack traces make debugging broken tests a lot easier for users and allow for us to display accurate file context so users can quickly jump to the relevant lines of code. Even just the ability to disable tail recursion for a function via something like Sys.opaque_identity would be nice for us as tests are described as callbacks in Rely.

**Comment by gasche** [comment]
I reopened this issue and tagged it as a feature request, "long-term" because it has been known for a long time and nobody has worked on it much yet.

A more general but related problem is the fact that system call stacks are generally useless when debugging continuation/monad-heavy programs such as Lwt, where a user-definable or at least library-definable notion of stack would be more useful. This calls for a more abstract treatment of control traces.

**Comment by gasche** [comment]
I have been willing to work on a `[@tailcall false]` extension of the `[@tailcall]` attribute, that would result in the compiler not using a tailcall for a specific call-site. I'm not sure this solves the original issue of globally improving backtraces/callstacks (it is more about certain call points where we explicitly disable tailcalls), but it can be used explicitly to preserve calls in the trace in certain situations, or temporarily during debugging.

**Comment by jberdine** [comment]
Having `[@tailcall false]` would be good to have. Currently the code added to confuse the compiler enough to prevent it generating a tail call cal also be confusing to human readers. And it would be good to have a mechanism that is not fragile with respect to compiler upgrades.

For the original use case, it is not really a solution though. A large part of the potential value of having a flag to disable (non-recursive) tailcalls is to make the initial debugging investigations easier and faster. Going through the loop of adding annotations to some suspect code and rerunning the failing command is sometimes fine, but if the failing command is long-running, or non-deterministic, etc. it would be much better to have as informative backtraces as possible in one round.

**Comment by stedolan** [comment]
This has also been an issue when trying to use statmemprof for profiling, where backtraces are the main source of information.

One possible heuristic that came to mind is to disable backtraces for direct tail calls to a different module. In practice, this would have caught most of the cases that confused me, and I doubt there are many tail-recursive loops that cross modules in such a way. (It's certainly possible to construct one, though)

**Comment by xavierleroy** [comment]
This discussion makes me sad.  Tail calls are something I and many others have been fighting for for several decades, against all odds: stupid calling conventions, stupid virtual machines (JVM I'm looking at you), stupid C compilers, etc.  So, turning tailcalls off "because it would be convenient" doesn't go down well.

**Comment by medovina** [comment]
I've created a pull request that adds a flag for disabling tail call optimization in calls between distinct functions.  My primary motivation is to improve stack traces that are reported by a sampling profiler.

In experimenting with this flag, I've found that it does improve stack traces, though they are still not as clean as I'd like because other optimizations (e.g. inlining) may still affect them a bit.
