### ISSUE TITLE
Error message on preprocessor failure

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#8700]
the compiler always accompanies a syntax error from a preprocessor with this:

File "file.ml", line 1:
Error: Error while running external preprocessor
Command line: ./parser 'file.ml' > /tmp/ocamlppd4a5a9

the line number is always 1 and the rest got old, fast!
if the preprocessor is actually outputting good messages already it would be 
desirable to suppress this compiler message.
is there already a way to do that?

thanks.

**Comment by mshinwell** [comment]
I am afraid there is not.

**Comment by gasche** [comment]
Moderate grumble: this issue is not a bug report, but it sounds like we could extract a "user interface feature request" from it with a small effort, and I think we should thank the reporter for the effort of giving us feedback. I think that closing with a harsh message is too harsh; there is a risk of antagonizing potential contributors and giving a bad image of the project.

On the issue itself: I don't remember what is the current protocol between the compiler and external preprocessors. I vaguely remember that ppx preprocessors take and return "cookies" that contain information, including on errors. When those are provided, we should be able to produce a nicer error message. For non-ppx preprocessors, it may be that no such protocol exists and that the compiler currently has no way to know that errors are handled by the preprocessor already. If this was important for good reasons (what non-ppx preprocessors generate those messages nowadays?), we could think of agreeing on an error/return code to signal this for example.
