### ISSUE TITLE
Nonsense error messages when mixing universal variables and polymorphic variants

### ISSUE THREAD

**Issue by lpw25** [ocaml/ocaml#8702]
```ocaml
# let foo : 'a . [`Foo] list -> ([> `Foo] as 'a) list =
    fun x -> x;;
  Line 2, characters 13-14:
2 |     fun x -> x;;
                 ^
Error: This expression has type [ `Foo ] list
       but an expression was expected of type [> `Foo ] list
       The second variant type does not allow tag(s) 
```

There are two ways in which this message is nonsense.

The first is the "The second variant type does not allow tag(s)" part, which is a regression in 4.08 caused by the changes to error reporting. The `Unify [Variant (No_tags(pos,rest))]` error is raised by `unify_row` when one of two conditions holds, however the message makes no sense for one of those conditions.

The second is that the type ``[> `Foo]`` should obviously unify with ``[ `Foo ]``. This comes from `row_fixed` being set by `instance_poly` even though the row of the variant is not fixed after instantiation. `row_fixed` causes unification to fail but is not visible in the printed type leading to a confusing message.

Setting `row_fixed` seems to be deliberate and has always been this way. However, as far as I can tell from a brief look, its only consequence is to produce worse error messages. Either I'm missing something or the `fixed` parameter of `instance_poly` should be removed (and possibly the `row_fixed` field as well). @garrigue  is probably the only person who knows which of those is the case.

**Comment by gasche** [comment]
(cc @Octachron for the error-message part)

**Comment by garrigue** [comment]
Setting `row_fixed` here is intended to get error messages earlier, i.e. as soon as you try to instantiate `'a`, rather than when checking the polymorphism after typing the expression.
It is in theory possible to remove it, but I would have to check that the algorithm works without it, and I believe there are some cases where setting it allows to give better error messages.
In this precise case, I suppose that one should look at the list of absent tags, and provide a different message when it is empty and `row_fixed` is set; this said, polymorphism error are always hard to report.

**Comment by Octachron** [comment]
Concerning the error message, maybe we could just add a small line of explanation:

```OCaml
| let f: 'a. ([> `A ] as 'a) -> [ `A ] = fun x -> x
                                                                         ^
Error: This expression has type [> `A ]
       but an expression was expected of type [ `A ]
       The first variant type is universally quantified
```
