### ISSUE TITLE
Wrong error location when using -absname flag

### ISSUE THREAD

**Issue by sbriais** [ocaml/ocaml#8724]
Assume two modules `A` and `B` located in subdirectories `foo` and `bar`. 
```
$ cat foo/a.ml
module type ARG = sig
  type t
  val f: t -> t -> t
end

module type RESULT = sig
  type t
  val f: t -> t -> t
end

module Make(X:ARG) : RESULT = struct
  type t = X.t
  let f = X.f
end
```
```
$ cat bar/b.ml
module X = struct
  type t = int
  let f x = x
end

module Y = A.Make(X)
```
Let's compile them

```
$ cd foo; ocamlc -absname -c a.ml; cd ..
$ cd bar; ocamlc -absname -I ../foo -c b.ml; cd ..
File "/bar/b.ml", line 6, characters 18-19:
Error: Signature mismatch:
       Modules do not match:
         sig type t = int val f : 'a -> 'a end
       is not included in
         A.ARG
       Values do not match:
         val f : 'a -> 'a
       is not included in
         val f : t -> t -> t
       File "/bar/a.ml", line 3, characters 2-20:
         Expected declaration
       File "/bar/b.ml", line 3, characters 6-7:
         Actual declaration
```

The error message is incorrect as it indicates that file `a.ml` is in subdirectory `bar` whereas it is actually into subdirectory `foo`.

**Comment by nojb** [comment]
The issue here is that the absolute path is not actually recorded in compiled interface `a.cmi` of `a.ml` but rather generated by the compiler when the error message is printed. The path recorded in the `.cmi` is the path passed on the command line to the compiler. When generating the absolute path, the compiler just concatenates this (if it is relative) with the current working directory.

To fix this, the locations recorded in the `.cmi` should be absolute from the get-go. It would mean that errors involving a `.cmi` compiled with `-absname` would always use absolute paths, even if `-absname` is not being passed in the current compiler invocation.

**Comment by gasche** [comment]
Here is an explanation for the current behavior: at the time of the error, when we want to indicate the location of the expected declaration, we look for the locations stored in `a.cmi` (in `../foo`), and those have relative filenames (relative to `foo/`, because `a.cmi` was produced from there). In particular the locations stored keep the filename-information `a.ml`. Then we print that path to the user in the error message, and the `-absname` logic says: if a path is relative, stick `Sys.getcwd ()` in front of it. So we get `bar/a.ml`, which is wrong.

I see two potential approaches to solve the problem, and none of them look very good to me:

1. keeping absolute filenames in locations when `-absname` is passed (see very simple diff below). This solves the problem but it changes the semantics of `-absname` which claims to be about error-message behaviors only. This also creates potential relocation issues, given that different people building the same source with `-absname` will end up with different `.cmi` files -- but they can use `BUILD_PATH_PREFIX_MAP` to hide that. That also doesn't solve the problem of other people's libraries, which are built without `-absname` (of course, otherwise their temporary-build-directory would show up in error messages, which would be terrible; or we would need to support DESTDIR stuff for users, which would be painful).

2. When we manipulate a location value, keeping in the context the relative path from where we are to that location. When we lookup a `.cmi` file, we know where it is on the disk, we can keep that contextual information around -- and stitch them back together when producing a path from a location. But that would be very painful to implement, I think, a fairly invasive change. (In particular the simple idea of rewriting all locations at loading time would be very inefficient in practice, so we don't want that.)

I'm not fond of either ideas. Maybe just saying "-absname only works reliably for files compiled from the same place" would be a decent choice, although that seems fairly unrealistic now that we have locations in `.cmi` files. The second idea is the most reasonable I think, but it's a lot of work for a relatively minor feature.

Here is a one-line patch implementing the first idea -- it solves the problem on the given repro case:

```diff
diff --git a/driver/pparse.ml b/driver/pparse.ml
index a5e98c0a4a..16ae076655 100644
--- a/driver/pparse.ml
+++ b/driver/pparse.ml
@@ -183,7 +183,7 @@ let file_aux ~tool_name inputfile (type a) parse_fun invariant_fun
       end else begin
         seek_in ic 0;
         let lexbuf = Lexing.from_channel ic in
-        Location.init lexbuf inputfile;
+        Location.init lexbuf (Location.show_filename inputfile);
         Location.input_lexbuf := Some lexbuf;
         Profile.record_call "parser" (fun () -> parse_fun lexbuf)
       end
```

**Comment by alainfrisch** [comment]
I don't think 2 can work, because (i) it would allow pointing to the directory containing the loaded .cmi file, which has no reason to be where the source file is (esp. when using installed libraries), and (ii) one .cmi file can contain locations pointing to multiple source files, possibly in different directories (this can happen for instance when using preprocessors that implement some "include"-like feature).

I think the absname feature is mostly useful in mono-repo contexts, or when you entire universe of OCaml code is compiled from the same tree (e.g. with dune).  So I think 1 might be a reasonnable direction, perhaps improving support for building outside the real source directories.

**Comment by sbriais** [comment]
Should we close this issue?

**Comment by nojb** [comment]
Sure. There doesn't seem to be much demand for changes in this direction.
