### ISSUE TITLE
Compiler libs's library structure

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#8728]
It seems that some of the elements (e.g. `bytecomp/meta.ml`) of `ocamlcommon.cma` are using the *interface* of elements whose implementation is in `ocamlbytecomp.cma` (e.g. `bytecomp/instruct.ml`). 

This of course remains sounds from a linking perspective, but I'm wondering if this is done on purpose or if it is an oversight; it is the first time I hit such an install structure.

**Comment by nojb** [comment]
I think it is just an oversight; since all the `.cmi`'s are visible when compiling the source distribution, this is easy to miss.

**Comment by dbuenzli** [comment]
@nojb I was wondering if you current delve into https://github.com/ocaml/ocaml/pull/9694 might lead to a fix for that one.

**Comment by nojb** [comment]
In a word, no.

To fix this problem, we need to "hide" the `.cmi`s from "later" libraries when compiling "earlier" libraries. The easiest way to do this is to put them into different directories and only pass the necessary `-I` flags when compiling.

For example, the compilation artifacts of `ocamlcommon` would go into `compilerlibs/ocamlcommon`, those of `bytecomp` into `compilerlibs/ocamlbytecomp`, etc. When compiling modules for `ocamlcommon` we would pass `-I compilerlibs/ocamlcommon` only so that the modules from `bytecomp` and later libraries would not be visible.

From my experience, this would be tricky to achieve with the current `Makefile` build system.

On the other hand, the `-inc` flag from #9056 could offer an alternative approach (to be investigated), avoiding the need to change the directory structure of the build.

**Comment by nojb** [comment]
> In a word, no.

More precisely, my understanding is that this issue is somewhat orthogonal to what is being done in #9694.
