### ISSUE TITLE
4.08 subtly breaks some functor-heavy code of mine

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#8762]
I'm afraid I don't have a small repro for now.

On my wip project [sidekick](https://github.com/c-cube/sidekick) at commit 33a784316276c0d81ec08c4ce583e86893fc690b (master as of 2019-06-21), the whole thing compiles properly on 4.06.1 but fails on 4.08.0 with:

```
ile "src/th-bool-static/Sidekick_th_bool_static.ml", line 53, characters 23-42:
53 | module Make(A : ARG) : S with module A = A = struct
                            ^^^^^^^^^^^^^^^^^^^
Error: In this `with' constraint, the new definition of A
       does not match its original definition in the constrained signature:
       ...
       In module S.Solver_internal.CC.A:
       Modules do not match:
         (module S.Solver_internal.CC.A)
       is not included in
         (module CC_A.A)
```

in code where there's literally `module A=A` in the body of the functor on the next line. It looks like some module alias (there are long chains of these) is lost somewhere.

**Comment by lpw25** [comment]
This will be caused by #2051. The module type `ARG` must include some internal module aliases in it, something like:

```ocaml
module type ARG = sig module M : S module N = M end
```

Types like that are not allowed as the type for a functor parameter because you cannot (currently) have a module alias to a functor parameter. So what #2051 does is it weakens the specified parameter type to something like:

```ocaml
module type ARG = sig module M : S module N : module type of struct include M end end
```

This means that, even though you wrote `A : ARG`, `A` does not actually have type `ARG`. That will be why your `with module` is failing. To fix it you should weaken your `ARG` module type to remove the module alias.
