### ISSUE TITLE
caml_stash_backtrace called by code compiled without -g

### ISSUE THREAD

**Issue by jberdine** [ocaml/ocaml#8780]
It used to be that unless source code was compiled with `-g`, the code generated for raising an exception would not call `caml_raise_exn` and then `caml_stash_backtrace`. Now, it appears that whether or not `-g` was passed to `ocamlopt`, calling `Printexc.record_backtrace true` results in `caml_stash_backtrace` being called at every raise (except `raise_notrace`). Is this intended? This behavior is surprising to me based on my interpretation of the documentation of `ocamlopt -g`:
> -g
Add debugging information while compiling and linking. This option is required in order to produce stack backtraces when the program terminates on an uncaught exception (see section 11.2).

While trying to hunt down how it was possible that I was seeing `caml_stash_backtrace` in perf profiles, I tracked this change to 7be0a81e9c605e73b04a31b400a6ab85e322a544, first included in 4.04.

**Comment by gasche** [comment]
This issue lacks an easy way to "reproduce" it to check whether it still occurs on recent OCaml versions. @jberdine, would you by chance be brave enough to provide one?

If I understand correctly, the logic in 7be0a81e9c605e73b04a31b400a6ab85e322a544 was that:
- `Lraise_regular` always stores the backtrace (`Lraise_notrace` does not)
  (indeed the emit.mlp stop checking Clflags.debug there)
- when `Clflags.debug` is set, `raise` gets compiled to `Lraise_regular`, otherwise to `Lraise_notrace` 
  (see cmmgen.ml:transl_prim_1)

Naively I would expect this to work as before, so users of `raise` should not observe stashing when `Clflags.debug` is not set. I may be reading the patch wrong, or maybe @jberdine only looked at the emit.mlp change and didn't try actually running a before-after check, or maybe there is a bug in the patch or that was introduced later. It is also possible that @jberdine is using a form of "raising an exception" that is not just using `raise foo` but some other lower-level mechanism that does not perform the `Clflags.debug` check.

**Comment by gasche** [comment]
(I don't know if this issue is "Stale" or not because I was too lazy to try to reproduce it.)

**Comment by jberdine** [comment]
I have still not managed to make time to create a reproduction case for this, so in the interest of tidiness I'll close this currently-unactionable issue.
