### ISSUE TITLE
Sequencing toplevel phrases in `ocaml`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#8813]
It seems that `ocaml`'s readline does not allow to sequence toplevel phrases on the same input interaction. Basically the first `;;` seems to act as an "end of line" comment. 

Is there any rationale about this or does it qualify as a bug ? 

More specifically I find the following discrepancy suprising:
```ocaml
> echo 'print_endline "bla";; print_endline "bli";;' > /tmp/bla.ml
> ocaml -noinit
        OCaml version 4.08.0

# #use "/tmp/bla.ml";;
bla
- : unit = ()
bli
- : unit = ()
# print_endline "bla";; print_endline "bli";;
bla
- : unit = ()
# 
```
Also it seems syntax errors are allowed after the first `;;`:
```ocaml
# print_endline "bla";; lat x = 3;;
bla
- : unit = ()
```

**Comment by nojb** [comment]
Indeed, the toplevel resets the input buffer after each phrase ending in ;; is read from the user, which results in the behaviour you have observed: https://github.com/ocaml/ocaml/blob/ddb4cd93cbab788a38cbc44ea7e624a6320970a3/toplevel/toploop.ml#L553

You can stop blindly resetting the input buffer after each phrase is read, but that results in strange interactions like:
```
# 1;; ignore
- : int = 1
# 2;;
- : unit = ()
```
To improve on this it would be necessary to read several phrases at once and evaluate them all at once. The problem is knowing when to stop waiting for input. Basically, you need to stop reading after seeing ;; **if** this would cause the lexer to block waiting for input. As far as I know this is not easily done with the current `Lexing` API.

**Comment by gasche** [comment]
@nojb: would it be possible to repeat the not-yet-interpreted portion of the buffer after the prompt, to avoid the "strange interaction" you mention?

**Comment by nojb** [comment]
> @nojb: would it be possible to repeat the not-yet-interpreted portion of the buffer after the prompt, to avoid the "strange interaction" you mention?

My feeling is that this is probably doable, but I haven't gone through the details.

**Comment by dbuenzli** [comment]
Just for context I noticed this while testing [down](https://erratique.ch/software/down)'s toplevel session support: you can record your phrases to store in a file to easily `#use` back later ([details](https://erratique.ch/software/down/doc/manual.html#sessions)). And I noticed a particular recorded sequence of phrases didn't have the same effect when loaded back.

**Comment by Armael** [comment]
Would it be hard to define a parser entry for "a list of toplevel phrases, where the last one is possibly terminated by EOF instead of ;;"?
Then we could use it to parse a toplevel input, and execute the resulting sequence of phrases.

**Comment by nojb** [comment]
> Would it be hard to define a parser entry for "a list of toplevel phrases, where the last one is possibly terminated by EOF instead of ;;"?
> Then we could use it to parse a toplevel input, and execute the resulting sequence of phrases.

I'm not sure that I follow: EOF is typically only sent to finish the session, right?

**Comment by damiendoligez** [comment]
Another possibility would be to have the toplevel wait for a double-semicolon **at end of line** before it stops reading and starts executing the input.

**Comment by pw374** [comment]
> Another possibility would be to have the toplevel wait for a double-semicolon **at end of line** before it stops reading and starts executing the input.

I like this option, provided the trailing spaces are ignored of course. Otherwise `";;      "`  wouldn't qualify.

**Comment by johnwhitington** [comment]
> > Another possibility would be to have the toplevel wait for a double-semicolon **at end of line** before it stops reading and starts executing the input.
> 
> I like this option, provided the trailing spaces are ignored of course. Otherwise `";; "` wouldn't qualify.

I second this qualification -- if not, copy and paste into a top level will get tiresome.

**Comment by wikku** [comment]
Would it make sense to change the grammar `toplevel_phrase` to that of `use_file` (OCaml scripts), but terminated with `SEMISEMI EOL`? The grammar needs to be similar to that of scripts if we want to maximize compatibility with pasting them to the toplevel. (Full compatibility isn't possible, because an executed phrase may read from stdin, so some remaining part of the script would be fed there). But I don't know if introducing `EOL` to the token stream would work.

**Comment by dbuenzli** [comment]
Mr bot, I don't think this should be closed.

**Comment by aqjune** [comment]
For anyone who doesn't want this problem to block your work, using `rlwrap ocaml` will partially resolve this error.
This does not resolve the case when one line contains multiple phrases however.
