### ISSUE TITLE
ocamlopt on powerpc

### ISSUE THREAD

**Issue by glondu** [ocaml/ocaml#8846]
Hello,

In Debian, the test suite for OCaml 4.08.0 [fails on powerpc](https://buildd.debian.org/status/fetch.php?pkg=ocaml&arch=powerpc&ver=4.08.0-2&stamp=1563965174&raw=0) because of some spurious messages, for example:

    /usr/bin/ld: bss-plt forced due to /tmp/camlstartup800a0a.o

Is powerpc still supported upstream?

**Comment by xavierleroy** [comment]
Is powerpc (not ppc64el) still supported in Debian?  https://www.debian.org/ports/powerpc/ indicates otherwise.

At any rate: our ppc32 / ppc64be test machine died, and the only Power hardware we have access to is ppc64le.  So I'm not surprised the ppc32 and ppc64be configurations are bit-rotting.  If someone cares about them, send patches or provide hardware for CI.

**Comment by glondu** [comment]
> Is powerpc (not ppc64el) still supported in Debian?

It is a "port", i.e. supported by those who care and not by Debian as a whole.

I've disabled the native compiler on powerpc, and all tests pass. This is better than nothing.

I am not going to spend more time on this, feel free to close.

**Comment by xavierleroy** [comment]
OK, thanks for the info.
