### ISSUE TITLE
ocamlopt -nodynlink does not work on armhf

### ISSUE THREAD

**Issue by glondu** [ocaml/ocaml#8867]
Hello,

As instructed in https://github.com/ocaml/dune/issues/2527, I open an issue here.

When I compile a simple hello.ml file (Debian unstable armhf):

    print_endline "Hello world!"

with `ocamlopt -nodynlink hello.ml`, I get relocation errors that go away when I remove `-nodynlink`.

Please have look at @nojb's insights in https://github.com/ocaml/dune/issues/2527

**Comment by nojb** [comment]
It seems (https://sourceware.org/ml/binutils/2009-04/msg00395.html) we should not be using `MOVW/MOVT` to load addresses of symbols coming from PIC libraries : https://github.com/ocaml/ocaml/blob/0557f07e70c9ab8c91f07df770ffc51c5d4b624c/asmcomp/arm/emit.mlp#L389-L392

**Comment by xavierleroy** [comment]
A friendly bot brought this issue to my attention, one year later.

Generally speaking, `ocamlopt -c -nodynlink` produces code appropriate for statically-linked executables.  However, OS distributions are increasingly using position-independent executables (PIE), which are not statically linked and undergo dynamic relocation at every execution.  

Here I can reproduce the problem on my Raspbian rPi by using `ocamlopt -ccopt -pie -nodynlink`.  I guess Raspbian doesn't use PIE by default yet.  Likewise, I guess @glondu can make the problem go away by using `ocamlopt -ccopt -no-pie -nodynlink`.

We need to discuss the future of the `-nodynlink` option.  Should  it go away?  Should it turn PIE off at link-time?  Should it be restricted so that the generated code is still compatible with PIE even though it may not be PIC?

For ARM, not using `MOVW/MOVT` as suggested in https://github.com/ocaml/ocaml/issues/8867#issuecomment-519861139 would implement the third approach above, and would not have much performance impact, I guess.  However, I need to check what happens with other non-x86 platforms.

**Comment by shindere** [comment]
@Armael may be interested in following this

**Comment by xavierleroy** [comment]
Results of a quick experiment: `-nodynlink` is incompatible with PIE on AMD64 (x86 64 bits) and ARM (32 bits).  In both cases, an error is reported at link-time.

For AMD64, PIC code is generated by default, which trumps `-nodynlink`, so one needs to do `ocamlopt -nodynlink -fno-PIC` to run into the issue. 

ARM64, Power, and I386 (x86 32 bits) seem OK.  s390x (Z systems) doesn't support PIE at all.  RISC-V could not be tested.

The appropriate action, I think, is to document that `-nodynlink` is incompatible with PIE and requires `-ccopt -no-pie` on systems that create PIEs by default.
