### ISSUE TITLE
Coq < 8.10 does not compile with ocaml 4.08.0, probably due to change in dynlink

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#8868]
Coq 8.9.1, and apparently previous versions too, do not compile with ocaml 4.08.0.
They fail with errors of the form:
```
- CAMLP5O   plugins/ssrmatching/g_ssrmatching.ml4
- Error while loading “/Users/garrigue/.opam/4.08.0/lib/camlp5/pr_dump.cmo”: The module `Pr_dump’ is already loaded (either by the main program or a previously-dynlinked library).
```
Apparently, the coq `Makefile.build` wrongly asks camlp5o to load `pr_dump.cmo`, while it is already included.
However, until 4.07.1 this worked, so I suppose the behavior was more laxist.
I proposed PRs for Coq (https://github.com/coq/coq/pull/10650) and opam (https://github.com/ocaml/opam-repository/pull/14668), but the problem is extensive, so a fix in ocaml might be simpler.
The problem was only discovered late because coq was waiting for the porting of camlp5, which happened just before 4.08.1.

**Comment by nojb** [comment]
This is probably due to #1063

**Comment by garrigue** [comment]
Indeed, it looks like the coq team didn't follow this discussion...

**Comment by ejgallego** [comment]
> Indeed, it looks like the coq team didn't follow this discussion...

Yes we did [as you can see in the thread], however we removed the dependency on camlp5 before testing that version of OCaml so we never found that issue.

**Comment by gasche** [comment]
I'm not convinced that we need a "fix" in the compiler.

This is a build-system bug and [your fix](https://github.com/ocaml/opam-repository/pull/14668/files#diff-b39117a9a703d731c9c736feaaba0c37) is quite simple -- a one-liner.

The Coq development team is free to decide whether this is a big deal for them, and release new patch-level releases of their older Coq versions, or just to backport your fix in their older release branches (so that enthusiasts can build from the release branch if they want to try an older Coq version with a newer OCaml version). Or maybe this can be just a patch in the opam-repository as you suggest, but my understanding is that opam-repo people are trying to shift away from patches and prompt new upstream releases in these situations.

**Comment by gasche** [comment]
To expand on Emilio's comment: in https://github.com/ocaml/ocaml/pull/1063#issuecomment-297278827 it is clear that Maxime found this exact issue (double module loading in camlp5) in April 2017, and decided that it was fine to fix it on the Coq side.

**Comment by ejgallego** [comment]
Indeed I don't think this is a bug in OCaml at all, IMHO camlp5 should be patched so it retains cmdline compatibility. No point on patching old Coq versions IMO.
