### ISSUE TITLE
-output-complete-obj is not documented in the manual

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#8882]

**Comment by Octachron** [comment]
There is  PR fixing this issue, #1351, but it ended up being stuck partially due to a non-intuitive behaviour of `-output-complete-ojb` ( which is linking less that `-output-obj` , see also the companion PR #1664). Maybe we should go ahead and merge the existing documentation, and worry about this behaviour later.

**Comment by Octachron** [comment]
There is still a documentation issue.
