### ISSUE TITLE
Source highlighting for contextual errors broken by line directives

### ISSUE THREAD

**Issue by trefis** [ocaml/ocaml#8889]
You can reproduce by applying this patch to trunk:
```diff
diff --git a/ocamldoc/odoc_gen.ml b/ocamldoc/odoc_gen.ml
index 8ea2c9477..eb43a9e86 100644
--- a/ocamldoc/odoc_gen.ml
+++ b/ocamldoc/odoc_gen.ml
@@ -26,7 +26,7 @@ module Base_generator : Base = struct
   class generator : doc_generator = object method generate _ = () end
   end;;
 
-module type Base_functor = functor (G: Base) -> Base
+module type Base_functor = functor (G: Base) -> Base with type t = int
 module type Html_functor = functor (G: Odoc_html.Html_generator) -> Odoc_html.Html_generator
 module type Latex_functor = functor (G: Odoc_latex.Latex_generator) -> Odoc_latex.Latex_generator
 module type Texi_functor = functor (G: Odoc_texi.Texi_generator) -> Odoc_texi.Texi_generator
```
And then running `make ocamldoc` produces:
```
../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -pp 'sh ./remove_DEBUG' -I ../utils -I ../parsing -I ../typing -I ../driver -I ../bytecomp -I ../toplevel -I ../stdlib -I ../compilerlibs -I ../otherlibs/str -I ../otherlibs/dynlink -I ../otherlibs/dynlink/native -I ../otherlibs/unix -absname -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -bin-annot -c odoc_gen.ml
File ".../ocamldoc/odoc_gen.ml", line 29, characters 48-70:
29 | ................................................ int
29 | module type Html_...........................................................................
Error: The signature constrained by `with' has no component named t
make[1]: *** [odoc_gen.cmo] Error 2
```

**Comment by Armael** [comment]
I investigated this a bit. The issue comes from the fact that, in presence of line directives, locations that are emitted have 1) line numbers that correspond to the file without the line directives (obviously), and 2) column and beginning of line numbers that correspond to the file *with* the line directives (`pos_bol` and `pos_cnum` fields).
That means that in the case of a preprocessor that inserts line directives, the locations that are emitted have line numbers that correspond to the original source file, but beginning of line/end of line numbers that correspond to the file after preprocessing.

I believe this was not an issue in most cases because printing code usually computes `pos_cnum - pos_bol` for positions in the same line. In that case, the offset that might have been introduced by line directives is cancelled out.
In the new printing code that quotes part of the file, we use `pos_bol` as an offset in the file from which to start reading the line. Therefore we have an issue if it doesn't correspond to a correct offset in the source file.

**Comment by Armael** [comment]
Most likely, the correct fix is to modify the lexer so as to correctly update the `pos_bol` field after reading a line directive.

**Comment by damiendoligez** [comment]
Note: if you update `pos_bol` you will also have to update `pos_cnum`.

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant. Can i work on this issue?

**Comment by gasche** [comment]
You are welcome, thanks for contributing!

The fields `pos_bol`, `pos_cnum` that are being discussed are declared and documented in `stdlib/lexing.mli`. The place where they should be modified is somewhere in `parsing/lexer.mll` where line directives are handled; I think this is the `directive` rule of the lexer.

It may be helpful to start by producing a small reproduction case that shows the bad behavior. Once you have this, we can explain how to add it to the testsuite.

(Various tutorials online have some documentation of ocamllex, if you want to understand the structure of `.mll` file; for example [Real World OCaml](https://dev.realworldocaml.org/parsing-with-ocamllex-and-menhir.html) has a chapter on using ocamllex (for a lexer) and menhir (for a parser); the parser part, which is the more advianced, is not relevant here.)

**Comment by Anukriti12** [comment]
I am trying to figure out this issue, I am an Outreachy applicant aswell.
As Armael suggested I can see in lexer.mll file inside directive 'update_loc' is called which updates pos_bol at line 59.

Maybe we can use this for testing
```ml
open Odoc_module

class type gen =
  object method generate : Odoc_module.t_module list -> unit end;;

module type S = sig
    class generator : gen
  end;;

module type Foo = functor (G: S) -> S with type t = int
```

**Comment by gasche** [comment]
Note: this issue is not stale, but the reproduction example (which requires modifying a file of the compiler codebase) is a bit painful. It would be nice to have a simple OCaml program to reproduce.

**Comment by damiendoligez** [comment]
>Most likely, the correct fix is to modify the lexer so as to correctly update the pos_bol field after reading a line directive.

I don't think this is the right idea, because the "line" directive actually gives you a *file name* and a *line number*. So in order to update `pos_bol`, you will have to open that other file and read it line by line to get the correct value for `pos_bol`.

A better idea is to fix the error-printing code to do the same thing: open the target file and read it line by line to get to the correct offset. There is no other way because the line directive gives you no information beyond file name and line number.

There is a way to shortcut this painful waste of CPU and I/O: by checking the `pos_fname` field, you can tell whether a line directive redirected you to another file. If that is not the case, the `pos_bol` field should be correct and you don't need to read the source line by line.
