### ISSUE TITLE
Is_young references a hidden type

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#8892]
The definition of `Is_young` uses the type `addr`:
https://github.com/ocaml/ocaml/blob/d233009cc900cd17436abab0e746c9dea7851522/runtime/caml/address_class.h#L28-L30

which is defined in `misc.h`, but it is guarded by `CAML_INTERNALS`:
https://github.com/ocaml/ocaml/blob/d233009cc900cd17436abab0e746c9dea7851522/runtime/caml/misc.h#L41-L43

 where the definition of `Is_young` is not. So at the moment `Is_young` produces an error if `CAML_INTERNALS` isn't defined in user code. There are three trivial fixes, the non-trivial part is which it should be:

1. Remove the guard around the `typedef` in `misc.h`
2. Add a guard around the definitions in `address_class.h`
3. Add the `typedef` in `address_class.h` guarded with `#ifndef CAML_INTERNALS` (yuck...)

**Comment by xavierleroy** [comment]
Let me add a fourth fix: use `char *` instead of `addr` in `Is_young` (like `Is_in_code_area` does, a few lines below `Is_young`).

Going further, I would suggest to remove the type name `addr`.  Many variables and macro parameters are named `addr` in the runtime code base, so it's not a great idea to use `addr` as a type name.  Plus, there are only 8 uses or so of the `addr` type name in our code base.

If we have cold feet and suspect 3rd-party sources to `#define CAML_INTERNALS`, we could keep the `typedef char * addr;` protected by `#ifdef CAML_INTERNALS`, perhaps with a deprecation warning attached, but still stop using it in `Is_young` and the rest of the code base.
