### ISSUE TITLE
toplevel: `#show Some;;` should show documentation on the option type

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#8945]
I'm teaching OCaml this week and I mentioned the command `#show` to get help on names of the language. This works for values and types, but not for constructors.

```
# #show option;;
type nonrec 'a option = None | Some of 'a
# #show Some;;
Unknown element.
```

I would like to see for example:

```
# #show Some;;
type nonrec 'a option = None | Some of 'a
```

**Comment by wyn** [comment]
I'm happy to have a go at this - is it OK to push up work-in-progress code (to my forked branch)?

Reason being that I've got it to half work:
<pre>
# #show Some;;
type nonrec 'a <b>Some</b> = None | Some of 'a
</pre>

I think this is because I am passing the Ident of "Some" rather than the "option" into Sig_type - basically I'm not sure how to get from the ident of the value ctor to the ident of the type ctor?

**Comment by wyn** [comment]
ah, ive just seen work-in-progress PRs so I'll just do that.

**Comment by alainfrisch** [comment]
`#show_constructor Some` should show the definition of the constructor, perhaps using a pseudo-value syntax:
````ocaml
val (Some): 'a -> 'a option
````

This would work for extension constructors (`exn` and more) as well.
````ocaml
val (Failure): string -> exn
````

So e.g. defining:
````ocaml
type t =A : int * int -> t
````
would allow showing `A` obviously as:
````ocaml
val (A): int * int -> t
````

😄

**Comment by gasche** [comment]
I would rather see the destriction in the style of a valid constructor definition

```
constructor at type 'a option:
| Some of 'a
```

or 

```
constructor at type 'a option:
| Some : 'a -> 'a option
```

for GADT constructors.

Personally I think that recalling the whole type definition would also be fine.

It would be nice if `#show (Foo : t)` was also supported in the disambiguation case (when different types export the same constructor), or if `#show Foo` could list all declarations that export `Foo` in scope, but those are nice-to-have features for a second iteration.

**Comment by yallop** [comment]
@alainfrisch:
> #show_constructor Some should show the definition of the constructor, perhaps using a pseudo-value syntax:

@gasche:
> I would rather see the destriction in the style of a valid constructor definition
> […]
> Personally I think that recalling the whole type definition would also be fine.

`ghci` provides both of these, as separate operations.  The `:type` directive prints out the type of a constructor (or other expression):

```haskell
Prelude> :type Just
Just :: a -> Maybe a
```

and  `:info` prints out information about the declaration:
```haskell
Prelude> :info Just
data Maybe a = ... | Just a 	-- Defined in ‘GHC.Base’
```

OCaml's `#show` is currently somewhere in between: it works for several different classes of identifier (like `:info`) but only prints out signatures (like `:type`), rather than printing richer information.  I'd like it if `#show` also printed out richer information such as source locations and docstrings, and if we also had a separate `#type` directive which worked for arbitrary expressions (including constructors, if something like #9005 is accepted).

**Comment by Octachron** [comment]
Since the requested feature has been implemented and there is a subsequent issue for some possible improvement, I am closing this issue.
