### ISSUE TITLE
Add the FreeBSD and OpenBSD autobuilts with SourceHut

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8952]
[SourceHut](https://sourcehut.org/) is a new very lightweight alternative for GitHub/GitLab-like workflow, but the interesting feature is the support of FreeBSD, OpenBSD, and NetBSD (work still in the progress for this one) autobuilds for their CI: 
- Manual https://man.sr.ht/builds.sr.ht/
- Supported build images https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd
- Using [dispatch.sr.ht](https://dispatch.sr.ht/) it's possible to integrate it for commits and pull requests, like Travis

See also https://github.com/ocaml/ocaml-ci-scripts/issues/307

**Comment by gasche** [comment]
If I understand correctly, your concrete proposal is to add testing on one of the BSD to the test matrix of our github CI.

Currently we test on a Linux distribution and on Windows (through AppVeyor), and the Linux tests are done on 32bits and 64bits. Adding a BSD machine would help catch configuration issues, non-portable includes, or reliance on GNU-specific idioms in build tools and scripts. (Most PRs fail due to functional correctness issues in the OCaml part, but a few PRs introduce such build-level issues that are harder to notice.)

Would you like to propose a Pull Request adding a BSD machine to our Travis tets?

(cc @shindere)

**Comment by shindere** [comment]
Thanks for the Cc, @gasche.

Two remarks:

1. We do test BSD through Inria's CI infrastructure, but this happens
only on trunk and the release branches.

2. Not sure how many portability issues we do actually catch that way,
since even on BSD we mostly use GNU tools, too, e.g. GNU make and bash.

This is not to say that it wouldn't be good to test PRs on BSD systems
even before theyget merged, it would be a good thing. I just wanted to
clarify these two points.

**Comment by gasche** [comment]
For configuration-relevant PRs we do tend to use `precheck` to use INRIA's CI infrastructure and catch those kind of issues. So maybe we don't need to add more BSDs to the Travis CI (saving on compute time), but we could consider adding more kinds of BSD machines on the INRIA CI, if we want to catch more build issues eventually.

I didn't remember that we already test some BSD there.

My general impression is that testing more BSDs would be nice-to-have, but have a low [extra compute costs / issue caught] ratio. It also requires more work on the part of the people working on the CI infrastructure (to add this support), which tend to be busy with other things as well.

I propose to close this issue, not because it's a bad idea (it's a good idea!), but to help focus work on more pressing issues. If someone does care about the matter, (1) collecting a list of issues on *BSD systems we haven't caught would encourage us to reconsider, and (2) sending a PR to do the CI-setup yourself (everything is in `tools/ci` in the source repository) would help.

**Comment by shindere** [comment]
Gabriel Scherer (2019/09/19 00:30 -0700):
> For configuration-relevant PRs we do tend to use `precheck` to use
> INRIA's CI infrastructure and catch those kind of issues.

Sure, but (1) this assumes an account on Iria's CI, which not everybody
has, and (2) it requires that someone has the idea that it would be
worth using precheck, which is not always the case, not even mentionning
the "burden" of having to do it.

> So maybe we
> don't need to add more BSDs to the Travis CI (saving on compute time),
> but we could consider adding more kinds of BSD machines on the INRIA
> CI, if we want to catch more build issues eventually.

Well we could add different versions of the OS, sure, but not different
architectures.

> My general impression is that testing more BSDs would be nice-to-have,
> but have a low (extra compute costs / issue caught) ratio. It also
> requires more work on the part of the people working on the CI
> infrastructure (to add this support), which tend to be busy with other
> things as well.

Yeah, I tend to feel more worried about brain-time than about CPU cycles
in htis precise case, I have to say. Also, there is not only the cost of
initial set-up, it turns out that there also is a non-negligible
maintainance cost.

> I propose to close this issue, not because it's a bad idea (it's a
> good idea!), but to help focus work on more pressing issues. If
> someone does care about the matter, (1) collecting a list of issues on
> *BSD systems we haven't caught would encourage us to reconsider, and
> (2) sending a PR to do the CI-setup yourself (everything is in
> `tools/ci` in the source repository) would help.

Fine with me. If we can rely on an external solution it's also great.
The ideal solution would be to do the CI just before merging and to
block the merge if CI fails.

**Comment by omasanori** [comment]
> I propose to close this issue, not because it's a bad idea (it's a good idea!), but to help focus work on more pressing issues. If someone does care about the matter, (1) collecting a list of issues on *BSD systems we haven't caught would encourage us to reconsider, and (2) sending a PR to do the CI-setup yourself (everything is in tools/ci in the source repository) would help.

So, I did (part of) (2) using my sr.ht account this weekend and caught a portability issue on NetBSD: https://github.com/ocaml/ocaml/issues/12413
You can see the dashboard at <https://builds.sr.ht/~omasanori/ocaml>.

Yes, it is just one bug for now, let's see...

**Comment by omasanori** [comment]
Another one: https://github.com/ocaml/ocaml/issues/12415
