### ISSUE TITLE
ocamltest ignores last line without a newline

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#8957]
If the last line of an `ocamltests` file has no newline, it is ignored.
Easy to fix, but it would be better to honor it.

**Comment by shindere** [comment]
(@mshinwell may also be interested by this issue)

The `ocamltests` files are read by a shell `read` embedded in
`testsuite/Makefile` rather than by ocamltest itself. It is thus the shell
which fails to read not properly terminated lines.

However, IMO trying to fix the code is not the right way to deal with the
situation. It indeed feels better to make sure the `ocamltests` files do
actually terminate with a newline.

Emacs users may refer to [the Emacs manual](http://www.gnu.org/s/emacs/manual/html_node/emacs/Customize-Save.html)
to see how thir favourite editor can be configured to do so. Moreover,
although that wouldn't help for code not commited yet, the `tools/pre-commit-githook`
script can be copied to `.git/hooks/pre-commit` to ensure that no file gets
commited which is not terminated by a newline.

Thus closing this issue.

**Comment by mshinwell** [comment]
I'd actually like to see this fixed if possible, even if there are workarounds.  It's wasted a certain amount of my time in the past; it sounds like @garrigue has had the same experience; and it seems likely others will trip up on it.  I don't know offhand what the solution for reading the lines with the shell is, but it seems unlikely there isn't a solution?  The problem sounds fairly commonplace.

**Comment by nojb** [comment]
This is actually a bug in the use of `read`, which correctly reads the last line but exists with a non-zero exit code if it is not terminated (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/read.html).

The fix is trivial: just replace `while read testfile` with `while read testfile || [ -n "$testfile" ]` in `testsuite/Makefile`.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2019/09/23 06:00 -0700):
> The fix is trivial: just replace `while read testfile` with `while
> read testfile || [ -n "$testfile" ]` in `testsuite/Makefile`.

Okay, I was not aware of this subtlety, sorry.

Just opened PR #8966

**Comment by gasche** [comment]
I would propose to fix this issue for good by getting rid of `ocamltests` file; in a test directory, let's just interpret any file that starts with `(* TEST` as a test file.

I remember asking @shindere about ocamltests file; the initial reason for having them was to deal with the transition period with a mix of Makefile-handled tests and ocamltest tests. Now that all tests are ocamltests, I don't see a reason to keep this file. It adds redundancy to the test system in a way that makes modifications more fragile than they should be.

**Comment by shindere** [comment]
Gabriel Scherer (2019/09/24 07:48 -0700):
> I would propose to fix this issue for good by getting rid of
> `ocamltests` file; in a test directory, let's just interpret any file
> that starts with `(* TEST` as a test file.

I will think about it and also discuss it with @damiendoligez.

> I remember asking @shindere about ocamltests file; the initial reason
> for having them was to deal with the transition period with a mix of
> Makefile-handled tests and ocamltest tests.

Correct.

> Now that all tests are ocamltests, I don't see a reason to keep this
> file. It adds redundancy to the test system in a way that makes
> modifications more fragile than they should be.

To some extent, I agree. However, I have to say I like the possibility
to "collect" the list of test files without having to scan all of them
but I understand it introduces problems.

Would e.g. an `-is-test` option to ocamltest be a good way to implement
the feature? For instance:

```bash
ocamltest -is-test foo.ml
```

would return 0 if foo.ml is a test, 1 if it's not and 2 if there is an
erorr (e.g. file not found)?
