### ISSUE TITLE
gen_primitives.sh locale issue

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#8985]
Re-posting this bug report here: https://sourceware.org/bugzilla/show_bug.cgi?id=25036

I am not sure if this is an OCaml bug or not, but according to `sed`'s documentation (referenced in the bug report, direct link: http://git.savannah.gnu.org/cgit/sed.git/tree/doc/sed.texi#n5685), we may want to robustify `gen_primitives.sh` by moving the `LC_ALL=C` line so that it encompases the `sed` invocation..

**Comment by sebras** [comment]
Yes, please! :)

**Comment by dra27** [comment]
IIUC the crux of this is that the regular expression `[a-z]` does not include `w` with `LC_COLLATE=sv_SE.UTF-8`. @sebras proposes that that's a bug in glibc but, regardless, we should fix the OCaml side both since there will presumably be buggy locale databases for a while and since we really mean C locale for that entire script.

**Comment by sebras** [comment]
> @sebras proposes that that's a bug in glibc

Yes, it highlighs a bug in glibc's locale database.

> we should fix the OCaml side both since there will presumably be 
> buggy locale databases for a while and since we really mean C 
> locale for that entire script.

There might be other languages where the regex `[a-z]` might exclude some (other?) characters on the same grounds. But in those cases it may not be valid to argue that localedata in glibc is incorrect.
So I wholeheartedly agree with this bugfix. :)
