### ISSUE TITLE
in ocamlopt, the mapping from ocaml name to C symbols is not injective

### ISSUE THREAD

**Issue by v-gb** [ocaml/ocaml#8998]
A function `b__c` in a.ml become a C symbol like "caml__A__b__c_NUMBER". A function `c` in a__b.ml can create the same C symbol. Example:

```
$ cd /tmp
$ echo "let b__c () = ()" > a.ml
$ echo "let c () = ()" > a__b.ml
$ ocamlopt a.ml a__b.ml
/usr/bin/ld: a.o: in function `camlA__b__c_1002':
:(.text+0x0): multiple definition of `camlA__b__c_1002'; a__b.o::(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```

There are a few consequences:
- unexpected link time errors as shown above
- parsing ocaml C symbol is ambiguous (the reason why I looked at this)
- possible segfault with shared objects, as clashing symbols at runtime is not an error

Example of segfault:

```bash
rm -rf /tmp/test
mkdir -p /tmp/test
cd /tmp/test
cat > common.ml <<EOF
type exn += E : 'a * ('a -> unit) -> exn
EOF
cat > a.ml <<EOF
let b__c str = Printf.printf "A.b__c\n%!input: %s\n%!" str
let () = raise (Common.E ("asd", b__c))
EOF
cat > a__b.ml <<EOF
let c x = Printf.printf "A__b.c\n%!input: %d\n%!" x
let () = raise (Common.E (12, c))
EOF
cat > main.ml <<EOF
let load name =
  print_endline ("loading " ^ name);
  try Dynlink.loadfile name
  with Dynlink.Error (Library's_module_initializers_failed (Common.E (x, f))) ->
    f x
let () = load "a.cmxs"
let () = load "a__b.cmxs"
EOF

ocamlopt -c common.ml
for name in common a a__b; do
    ocamlopt -linkall -shared $name.ml -o $name.cmxs
done
ocamlopt -I . common.cmx dynlink.cmxa main.ml
./a.out
```

outputs:

```
$ ./script
loading a.cmxs
A.b__c
input: asd
loading a__b.cmxs
A.b__c
./script : ligne 33 : 28382 Erreur de segmentation  (core dumped) ./a.out
```

**Comment by gasche** [comment]
If we always separate the module name from the value name by a given marker (here, two underscores), a solution to this specific problem is to ensure that this marker can occur neither in the mangling of module names nor in the mangling of function names. For example, we could escape multi-underscore sequences in module and term names by preserving single-underscores (the common case) and adding an extra underscore to all sequences of 2 or more underscores.

I suspect that there could be other issues with the mangling schemes, maybe the whole scheme is worth thinking about again.

@sliquister, would you like to propose a pull-request for the protect-multi-underscores strategy?

**Comment by xavierleroy** [comment]
I think (but didn't try) that we could use `$` as separator in generated symbol names, instead of `__`, e.g. `camlModule$value` instead of `camlModule__value`.  All assemblers we use seem to support `$` in symbols.  We also use `$`_nnn_ to encode special characters by their ASCII codes, but I hope no ambiguity arises, since OCaml identifiers cannot start with a number.

**Comment by v-gb** [comment]
@gasche I was thinking of something similar (though without escaping the module part because jenga/dune create compilation units of the form $lib__$file and these names do show up in gdb/pstack/perf/objdump/bloaty/etc), but it's not enough because you can have clashes without __: `A._b` and `A_.b`.

@xavierleroy `A.(@)` is transformed into `camlA__@_83` by `Compilenv.make_symbol`, and then `emit.mlp` for the relevant backend transforms that into `camlA__$40_83` or `camlA__.40_83`, depending on which backend. So the first step should be able to create `camlModule$value`, and aoid the current issue, but it would ultimately become `camlModule$xxvalue` in the assembly, so a bit less readable. And there's assembly for things like `caml_system__frame` would apparently need to be renamed if the convention changes.

**Comment by xavierleroy** [comment]
I'd like to avoid the ASCII encoding `$xx` in `camlModule$xxvalue`, for legibility and compactness of symbols.

This could be achieved by having `Compilenv.make_symbol` use a single dot `.` as separator, thus producing `camlModule.value`, then having `emit.mlp` transform `.` to `$` and use `$xx` escapes for other special characters.  

Also, the GNU assembler supports dots `.` in symbols, it's only MSVC that doesn't support them, so we could leave `.` as `.` in most emitters.

Also, I can't remember why Power and ARM use `.` instead of `$` for ASCII-escaping special characters.  Non-GNU assemblers, perhaps?

**Comment by gasche** [comment]
The proposal of @sliquister in #9108  is to escape multi-underscore sequences in the term name only, not in the compilation unit part. This remains injective because the original unit/term decomposition can be recovered by splitting at the rightmost occurrence of `__[^_]` (this also assumes that we prevent term names that start with an underscore).

The escaping scheme proposed in #9108 is not to add an extra underscore to multi-underscore sequences, but to turn all underscores but the first one in the sequence into dots: `a__b` becomes `a_.b`. Dots get mangled further down in the pipeline, but multi-underscore sequences are uncommon so the idea is that readability isn't affected in normal cases. (We are talking about corner cases that have not been noticed so far.) Anecdotally, the fact that we are just replacing one character per one character makes it easy to implement (it's just a `map`).

I don't know how the add-one-underscore idea could be extended to support terms that start with an underscore.

**Comment by v-gb** [comment]
I don't know if my proposal is what's best but it's fairly simple. It assumes that in valid ocaml names, replacing `_` by `.` doesn't create collisions (some other character could be used, like `;` or `\` where this is clearly true, but printed intermediate asts would probably start looking weird).

The suggested scheme `Module.value` -> `camlModule.value` -> `camlModule$value` should work. It assumes no names have `.` followed by a hex digit, which is true and can be easily asserted anyway. It's bit a more invasive, but nothing too bad: hand written assembly and things that parse ocaml C symbols would need to change.
Then for preserving the `.`, I looked at the git history for Power and s390x: they have always escaped with `.`, so no idea if `$` works. But even if the only valid characters were `[a-zA-Z_0-9.]`, it would be possible to preserve `.`: simply escape any hex digit that follows a `.`. `.a` -> `..61` for instance.

**Comment by xavierleroy** [comment]
Several of us have ideas for improving symbol management, ideas that should also fix this issue.  Keeping it open and assigning it to me.
