### ISSUE TITLE
Discrepancy between unary minus, its tilde version, redefinition, and precedence handling

### ISSUE THREAD

**Issue by grayswandyr** [ocaml/ocaml#9001]
According to the manual, the precedence of unary minus should be less than function application but:
```ocaml
# let f s = s ^ "f";;
val f : string -> string = <fun>
# let ( - ) s = "-" ^ s;;
val ( - ) : string -> string = <fun>
# ~- f "foo";; (* the tilde version hasn't been redefined as can be seen *)
Error: This expression has type string -> string
       but an expression was expected of type int
# - f "foo";; (* but ... *)
Error: This expression has type string but an expression was expected of type
         int
```
Say we now redefine the unary minus using its tilde version:
```ocaml
(* new session *)
# let ( ~- ) s = "~-" ^ s;;
val ( ~- ) : string -> string = <fun>
# - f "foo";; (* OK *)
- : string = "~-foof"
# ~- f "foo";; (* but... *)
Error: This expression has type string -> string
       but an expression was expected of type string
```

**Comment by dra27** [comment]
This is behaving correctly. The `-` symbol in the grammar can be used in both prefix and infix positions. In prefix position, the [manual indeed states](https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sec133) that it has lower precedence than function application. Hence:

```ocaml
# let f x = 2 * x;;
val f : int -> int = <fun>
# - f 2;;
- : int = -4
```

However, the precedence rules apply strictly to the `-` symbol. `~-` is a `prefix-symbol` in the lexer (since it begins with `~`) and that same precedence table shows that they have highest precedence, hence:

```ocaml
# ~- f 2;;
Error: This expression has type int -> int
       but an expression was expected of type int
```

Internally, when the `-` *symbol* is used in infix position, OCaml uses the `(-)` *function* and when used in prefix position it uses the `(~-)` *function*. Hence in your first redefinition of `(-)` has simply broken the infix operator:

```ocaml
# let (-) s = "-" ^ s;;
val ( - ) : string -> string = <fun>
# "a" - "b";;
Error: This function has type string -> string
       It is applied to too many arguments; maybe you forgot a `;'.
```

**Comment by grayswandyr** [comment]
OK, thank you, this is more or less what I had gathered but I wasn't aware for the internal mode you describe. 
Now I found that the fact prefix `-` is interpreted as `~-` is actually indicated [here](https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sec157).
