### ISSUE TITLE
Add syntactic sugar matchOP and ifOP ?

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#9010]
Following #1947 what do you think about adding syntactic sugar
```
matchOP E1 with P -> E2 => letOP *fresh* = E1 in match *fresh* with P -> E2
```
and
```
ifOP E1 then E2 => letOP *fresh* = E1 in if *fresh* then E2
```
?

**Comment by gasche** [comment]
## In favor

One way to understand `let! x = expr in body` is that we are treating the (monadic) computation `expr` like a value (we would write `let x = expr in body` is `def` was pure), by letting its effects be handled by the ambient context. With this view, `match! expr with ..` and `if! expr then ...` make perfect sense.

## Against

There is a smug quality to the expansion of `let! x = ...` into a `(let!)` operator: it is logical and discoverable, in the one direction that people seeing the operator definition will guess when and how it can be used. On the other hand, it's not immediately clear when I see `match! ..` that this is available because `(let!)` is defined, or conversely when seeing a `(let!)` definition that this enables the `match!` syntax. One could expect, instead, that a `(match!)` operator would have to be defined.

**Comment by yallop** [comment]
There's also an existing proposal for a different intepretation of `matchOP` in #1955.

**Comment by gasche** [comment]
For reference, @lpw25 had initially implemented a translation of

```
match+ expr with
| pat1 -> case1
| pat2 -> case2
```

into `(match+) (function | pat1 -> case1 | pat2 -> case2) expr`.

In theory the two translations could differ if we want to write a non-exhaustive match within a monad that supports partiality. (In practice I don't see how to implement this robustly inside `match+` with the proposed expansion; we probably would need to tweak it a bit).

Note: using exception clauses makes sense for neither of the `match` desugaring. This is obvious with the `(match+) (function ...)` proposal, but it should also be turned into an error in the `let+ .. match ..` proposal.

**Comment by yallop** [comment]
> Note: using exception clauses makes sense for neither of the `match` desugaring. 

There's discussion of how to treat exception clauses in the `match` desugaring in #1955.

**Comment by trefis** [comment]
I believe that @yallop has been hinting that it would be better to continue discussion on #1955 instead of here, and if that is the case then I agree with him.
So I'm closing this.
