### ISSUE TITLE
-short-paths can be too aggressive

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/ocaml#9072]
Hi all,

Consider the following example:

```ocaml
type age = int;;
let f (x : int) = x + 1;;
let g (x : age) = x + 1;;
#show age;;
```

Here is the output in a plain REPL, without `-short-paths`.

```ocaml
# type age = int;;
type age = int
# let f (x : int) = x + 1;;
val f : int -> int = <fun>
# let g (x : age) = x + 1;;
val g : age -> int = <fun>
# #show age;;
type nonrec age = int
```

Here, in contrast, is the output with `-short-paths`:

```ocaml
# type age = int;;
type age = int
# let f (x : int) = x + 1;;
val f : age -> age = <fun>
# let g (x : age) = x + 1;;
val g : age -> age = <fun>
# #show age;;
type nonrec age = age
```

The second output is quite confusing: ideally, `int` shouldn't be changed to `age` in the signature of `f` nor in the return type of `g` (I can see that it might be tricky to define the right heuristic, though). 

More importantly, the last line looks wrong; shouldn't the `int → age` replacement be disabled when printing the type of `age`?

Thanks to @trefis for the suggestions and the minimized example (original issue: https://github.com/ocaml/merlin/issues/1030).

**Comment by lpw25** [comment]
The printing of the type of `g` is correct with the "specification" of `-short-types` so there is nothing to change there. Also note that the implementation of short-paths in Merlin is unrelated to the one in the compiler. They both give the same result in this case because it is the intended result.

I think the last point is an issue with `#show`. Although it's not clear how to do better. Clearly you want to have the defined type available in order to print:
```ocaml
# type t = < foo : t>;;
type t = < foo : t >
# #show t;;
type nonrec t = < foo : t >
```
so I don't know what the correct rule should be.

**Comment by cpitclaudel** [comment]
> The printing of the type of g is correct with the "specification" of -short-types 

Hmm, I see. Then I guess I'm arguing for the spec to be changed, or rather I'm hoping to discuss an alternative, possibly under a different flag? I was going by the  `-help` string (which says `-short-paths  Shorten paths in types`) and the man page, which says this:

```
       -short-paths
              When  a  type is visible under several module-paths, use the shortest one when printing the type's name
              in inferred interfaces and error and warning messages.
```

Both of these talk about paths, but here the transformation is from a one-element path into another one-element path, right?

Here is another example which is similarly confusing:

```
# type age = int;;
type age = int
# type amount = int;;
type amount = age
# let f (a: age) (b: amount) = 1;;
val f : amount -> amount -> amount = <fun>
# #show age;;
type nonrec age = amount
# #show amount;;
type nonrec amount = amount
```

I find -short-paths very useful in some cases, but I've turned it off lately due to this problem of shadowing.  I wonder if a version that uses the original path when the shortened one has the same length would make sense.

**Comment by lpw25** [comment]
> Both of these talk about paths, but here the transformation is from a one-element path into another one-element path, right?

In such cases I believe that both implementations try to show the most recently added to the environment. After that they fall back to just picking one, although they still try to pick the same name consistently.

>  I wonder if a version that uses the original path when the shortened one has the same length would make sense.

The "original" path can be a little tricky to define in general and this means that the same type will get printed with different names in the same expression.

With code like
```ocaml
# type age = int;;
type age = int
# type amount = int;;
type amount = age
# let f (a: age) (b: amount) = 1;;
```
I would say that the real problem is the abuse of abbreviations in the code. If all `int`s are not both `age`s and `amount`s then those types should be made abstract. Of course there are always exceptions to this kind of rule, but in general I would say that the code is not ideal and short paths helps to show why.

**Comment by lpw25** [comment]
> I wonder if a version that uses the original path when the shortened one has the same length would make sense.

I should say that I do think that an approach along these lines is potentially worth exploring. I just wanted to point out that it is not a trivial change to do it in a well-specified way, and that there are downsides to be accounted for.

**Comment by yallop** [comment]
One related behaviour of `-short-paths` that I find surprising is that it sometimes prints longer type names than the standard printer.

Without `-short-paths`:
```
# type number = int;;
type number = int
# 2;;
- : int = 2
```

With `-short-paths`:
```
# type number = int;;
type number = int
# 2;;
- : number = 2
```

**Comment by yminsky** [comment]
Short-paths was originally modeled off of the rule that Mlton used, which was roughly: pick the type with the fewest number of dots, and between those with the same path length, pick the most recent definition.

That will of course sometimes pick names with more characters or with fewer, but that doesn't seem like an interesting distinction.  There is a question as to whether you prefer that way of breaking ties, or a different one. I think the virtue of this one is that it allows you to override type names, whereas picking the type that was defined first wouldn't let you revise such definitions.

Is there an alternate rule you have in mind? Are you suggesting using the number of characters in the type name to break ties?

**Comment by yallop** [comment]
I think there are two surprising things:
1. a difference between `-short-paths` and the standard printer even when no dotted paths are involved.  It'd be less surprising if `-short-paths` didn't change the behaviour when there are no dotted paths involved.
2. that `-short-paths` is performing search rather than resolution (i.e. introducing types that aren't reachable from the expression entered by the user).

So one partial tie-breaker rule could be: when choosing between paths of the same dot-length, prefer paths that can be reached by resolution.

**Comment by garrigue** [comment]
> So one partial tie-breaker rule could be: when choosing between paths of the same dot-length, prefer paths that can be reached by resolution.

This would still break the property that the same type constructor should be printed in a unique way. This is the reason we do search rather than resolution (or more precisely, resolve all paths and search for an optimal witness of the the resolved form, but not limiting ourselves to the paths we resolved, since this can change in the future).

**Comment by cpitclaudel** [comment]
This issue is still relevant to me.  Basically, I'd prefer it if "-short-paths" worked as it does now, except when the result of shortening is not in fact shorter (same number of dots): in that latter case, I'd prefer if it did nothing.  I *think* the implementation of that is straightforward?  No shortening unless it actually shortens.

**Comment by cpitclaudel** [comment]
This issue is still relevant to me. Basically, I'd prefer it if "-short-paths" worked as it does now, except when the result of shortening is not in fact shorter (same number of dots): in that latter case, I'd prefer if it did nothing. I think the implementation of that is straightforward? No shortening unless it actually shortens.

Also [GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)
