### ISSUE TITLE
[power] Why is `reserved_stack_space` added twice when computing `slot_offset`?

### ISSUE THREAD

**Issue by gretay-js** [ocaml/ocaml#9084]
`reserved_stack_space`  is already taken into account by `frame_size`, and then added on explicitly again for `Incoming` in `slot_offset`.

https://github.com/ocaml/ocaml/blob/03c33f500563f3e12355694f1add98e7bd1096ae/asmcomp/power/emit.mlp#L61

**Comment by stedolan** [comment]
After some confused googling, this code turns out to be correct. In the power ABI, there's a reserved area at the bottom of the stack, so stack layouts look like this (growing downwards):

```
   |          |
   |  locals  |
   |          |
   +----------+
   |          |
   |   args   |
   |          |
   +----------+
   |          |
   | reserved |
   |          |
   +----------+ <-- caller SP
   |          |
   |  locals  |
   |          |
   +----------+
   |          |
   | reserved |
   |          |
   +----------+ <-- callee SP
```

For the caller to access its incoming arguments, it must add to SP its own frame size (its reserved space + its locals) and then add the callers reserved space. There are two reserved spaces between the callee's stack pointer and the callee's incoming stack arguments!

**Comment by lpw25** [comment]
Maybe a comment in the code is in order?
