### ISSUE TITLE
Warning attribute -3 ignored with included modules

### ISSUE THREAD

**Issue by mmottl** [ocaml/ocaml#9085]
Consider the following code:

```ocaml
module M' : sig val x : unit [@@deprecated "whatever"] end = struct
  let x = ()
end

module M : sig val x : unit end = struct
  [@@@ocaml.warning "-3"]

  let x = M'.x
  (* include M' *)
end
```

`ocaml` will evaluate this file just fine as is, but only because warning `3` is turned off in module `M`.  If we now use `include M'` instead of explicit rebinding, warning `3` will be triggered, i.e. the attribute to turn it off will be ignored.  Note that passing `-w -3` on the command line will correctly suppress this warning again.

The compiler apparently does not handle warning attributes correctly when code that also contains such attributes is referenced via `include`.

**Comment by alainfrisch** [comment]
The warning is triggered when a deprecated value is explicitly referenced (M'.x), or when a module signature "forgets" the deprecation attribute.  In your case, if you declared M.x as deprecated, it is by design that we should not get the warning.  This means that the warning is triggered during the inclusion check between the signature inferred for M and the declared signature.  And in this scope, the warning 3 remains enabled (the scope of the disabling attribute is just the structure body).  Does it make sense?

**Comment by alainfrisch** [comment]
The warning is triggered when a deprecated value is explicitly referenced (M'.x), or when a module signature "forgets" the deprecation attribute.  In your case, if you declared M.x as deprecated, it is by design that we should not get the warning.  This means that the warning is triggered during the inclusion check between the signature inferred for M and the declared signature.  And in this scope, the warning 3 remains enabled (the scope of the disabling attribute is just the structure body).  Does it make sense?

**Comment by mmottl** [comment]
Yes, this makes sense, though it's probably not what people expect.  Shouldn't it be possible to interpret warning attributes that appear earlier in a module such that attributes in subsequently included module definitions are overridden?

**Comment by mmottl** [comment]
Btw., it is, of course, typically possible and not too much work to `include` a module and then just rebind problematic entries with attributes where the warning is turned off.  This seems to be the best workaround.

In my case, however, it was difficult to even figure out why the warning happened in the first place, because complicated module and signature definitions in a 3rd party library obscured the relationships.  I was just surprised why I couldn't turn off the warning by simply placing the appropriate attribute in the module body or attaching it to the `include` statement.
