### ISSUE TITLE
Bad usability when running `ocamlrun` on a `-custom` executable

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9234]
I just spent a dozen of fairly unpleasant minutes trying to understand what was wrong/broken in my development environment as I observed the following:

```
$ ./runtime/ocamlrun ./ocamltest/ocamltest
Fatal error: unknown C primitive `caml_has_symlink'
Aborted (core dumped)
```

The answer is that my compiler checkout was working perfectly fine (no need for supertitious `make distclean; make world.opt -j5`), but `ocamltest` is built as a `-custom` binary, so it does not need `ocamlrun` to run. I found the solution by mistakenly forgetting to invoke `ocamlrun` on my N-th test, and the executable worked perfectly.

I don't know anything about `-custom`; could someone that does please suggest a way to make the user experience less horrible when mistakenly invoking `ocamlrun` on custom executables?

(`caml_has_symlink` is a stub function provided by the ocamltest codebase, correctly linked into the ocamltest executable.)

**Comment by gasche** [comment]
(cc @xavierleroy @nojb @diml, who do know about custom executables)

**Comment by ghost** [comment]
The solution is to build ocamltest with `-output-complete-exe` rather than `-custom`. `-output-complete-exe` produces a real executable that `ocamlrun` won't try to execute.

FTR, the plan is to deprecate `-custom` (cf https://github.com/ocaml/ocaml/pull/8872#issuecomment-532228069).

**Comment by nojb** [comment]
I am preparing a PR with both fixes.

**Comment by gasche** [comment]
`ocamltest` is not the only executable built with `-custom` in the compiler distribution; it is also the case of `ocamldoc` and there it's not clear to me that we can "just" switch to -output-complete-exe. 

Indeed, a documentation comment in ocamldoc/Makefile says

```
# if shared-libraries are not supported, unix.cma and str.cma
# are compiled with -custom, so ocamldoc also uses -custom,
# and (ocamlrun ocamldoc) does not work.
```
I don't exactly understand why `{unix,str}.cma` would be built with `-custom` on no-shared-libs systems, and whether the output-complete-exe approach is applicable there. Would someone be able to clarify this question?

(Ironically, I am the person who wrote this documentation comment, on advice from @dra27 I believe.)

**Comment by ghost** [comment]
I didn't know you could pass `-custom` when assembling a `.cma`. I'm guessing it means: pass `-custom` when linking a bytecode executable using this library, but I need to double check.

**Comment by ghost** [comment]
Yes, that seems to be it.

**Comment by nojb** [comment]
I also forgot about this when I submitted #8872

What do you think we should do: allow to *also* record `-output-complete-exe` in libraries (changing the .cma format by adding an extra `bool` flag), or interpret `-custom` recorded in libraries as intending to use `-output-complete-exe` (this is backwards-incompatible)?

**Comment by gasche** [comment]
Jérémie nicely explained what `-custom` in archives does (thanks!), but what is the reason for using this? Why did we decide to compile {unix,str}.cma with `-custom` when no-shared-libs? (Maybe the justification can influence the decision of what to do for `-output-complete-exe` with `-custom` archives.)

**Comment by dbuenzli** [comment]
> Why did we decide to compile {unix,str}.cma with `-custom` when no-shared-libs?

Because you want to be able to write `ocamlc -o myexe unix.cma myexe.ml` without having to think whether shared libraries are supported on your platform or not.

**Comment by gasche** [comment]
I'm not sure I follow. Why would we need to record this information in the archive file, if the same decision could be made by `ocamlc` at link-time?

**Comment by dbuenzli** [comment]
I'm not sure either, but maybe to support stubs to C libraries that provide only C archives and no shared objects ? In that case you want to force custom mode (that's actually the vocabulary used in the cma [the descriptor](https://github.com/ocaml/ocaml/blob/e18564d8393475acd9e36f02fe3b0927fe8a0f5c/file_formats/cmo_format.mli#L53-L58))

**Comment by ghost** [comment]
By reading the changelog and the git history, my understanding is the following: initially one had to systematically pass `-custom` to `ocamlc` as soon as they were using at least one library that had C stubs. At some point, `ocamlc` started recording `-custom` inside cma files for convenience. Later on, support for dynamically loading the C stubs was added. At that point, `-custom` was no longer a hard requirement when using a C library that had C stubs in bytecode mode.

So in today's world, passing `-custom` when building a `.cma` seems only useful if you have a library with C stubs for which the C stubs cannot be dynamically loaded for some reason. I have no idea whether there are users who rely on that.

I propose the following:

- we build `ocamldoc` with `-output-complete-exe` rather than `-custom`
- we deprecate `-custom`
- when `-custom` is implicitly added by a library but neither `-custom` nor `-output-complete-exe` is passed on the command line when linking an executable, we print a warning
- we continue to sometimes pass `-custom` when building `unix.cma` and `str.cma` for the time being and just ignore the warning

We wait for feedback for a couple of years. If nobody complains, then we just get rid of `-custom`.

> What do you think we should do: allow to also record -output-complete-exe in libraries (changing the .cma format by adding an extra bool flag)

I would just find the following command a bit odd:

```
$ ocamlc -a -output-complete-exe -o foo.cma ...
```

i.e. it feels like we'd be asking the compiler to produce both an archive and an executable. But maybe another option such as `-requires-output-complete-exe` would be ok.

> or interpret -custom recorded in libraries as intending to use -output-complete-exe (this is backwards-incompatible)?

Not sure about this either. If we do that, why not just make `-custom` an alias for `-output-complete-exe` all the time? And IIRC, there were good reason why we didn't just change the meaning of `-custom`

**Comment by gasche** [comment]
Thanks for looking at the history. If I understand correctly, passing `-custom` to an archive is the right way to signal "by the way, I am using C stubs" on systems without dynamic linking. It would make sense to interpret its semantics in exactly this way (rather than specifically asking for a `-custom` executable).

On no-shared-libs systems, I think that it would be perfectly sensible for `-output-complete-exe` to work on binaries containing archives that use `-custom`: `-output-complete-exe` is also a valid way to create no-shared-libs executables (... right?).

The final question, discussed in Jérémie's post, is whether `-custom` archives should, by default, imply `-custom` or `-output-complete-exe` for binaries (using either option if specified explicitly). This should be a policy decision to make for people implied in the custom-vs-complete-exe debate (not me).

**Comment by ghost** [comment]
> On no-shared-libs systems, I think that it would be perfectly sensible for -output-complete-exe to work on binaries containing archives that use -custom: -output-complete-exe is also a valid way to create no-shared-libs executables (... right?).

Yes.  In fact it will eventually become the only way as `-custom` is being deprecated.

Regarding making `-custom` archives mean `-output-complete-exe` for binaries, I'm just a bit warry  that we'd be changing the meaning of an existing option and it could be surprising for some users. That said, that's also the simplest way forward and as @nojb pointed out it is backward compatible. So if others are happy with this solution let's go for it. /cc @dra27 and @glondu who also participated to the `-custom` discussion.

@dra27 and @glondu, to give a bit of context `-custom` is also allowed when building a cma file and it is recorded inside the cma. When linking a bytecode executable that has `-custom` recorded in, `-custom` is implicitely assumed.

**Comment by dra27** [comment]
I agree that the compiler distribution should be using `-output-complete-exe` for all its binaries.

I was aware of the ability of .cma to force `-custom` at the time of the original discussion, but didn't think it was relevant as we were adding a feature. Does it override `-output-complete-exe` i.e. does `ocamlc -o foo -output-complete-exe str.cma foo.ml` give a `-custom` bytecode executable or a `-output-complete-exe` executable? If it's the former, then I'd say that's a bug.

I think we should change the semantics of embedding `-custom` in `.cma` exactly at the point `-custom` is removed, not before. The reason is that at present you can use `ocamlc -make-runtime -o ocamlrun-with-str str.cma` (see [the manual](https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#s%3Acustom-runtime)) and that runtime would work with a `-custom` runtime-compiled executable. I don't think we should break that until the feature is removed. At that point, we may also need to consider having a flag to extend `-noautolink` (so that you can build a custom runtime, but also definitely build a bytecode-only image to pass to it).

In the meantime, given that the removal of `-custom` is several years away, the error message could be improved by introducing a second bytecode magic number which gets used for `-custom`. `ocamlrun` recognises both but can suggest running the executable directly if it uses the "custom" magic number. This could also be used (and kept) for `-use-runtime` executables. Note that the second magic number is more reliable than mucking around with shebang detection, which won't work on Windows. Much cleverer solutions can be added to both @gasche's and my desire for an `ocamlobjinfo` with a database of magic numbers!

**Comment by xavierleroy** [comment]
> I agree that the compiler distribution should be using -output-complete-exe for all its binaries.

Certainly not!  It should build "default" bytecode executables, those that use the standard ocamlrun + dynamic loading.  

The only reason ocamldoc.byte uses -custom today is that it runs before installation of the shared libraries containing the C stubs, but that's easily accommodated by running it with
```
ocamlrun -I ../otherlibs/str -I ../otherlibs/$UNIXLIB ocamldoc.byte
```

**Comment by dra27** [comment]
@xavierleroy - sorry, my agreement statement is unclear. I meant that it should be using `-output-complete-exe` where it presently uses `-custom` … i.e. for non-shared platforms.

**Comment by ghost** [comment]
> I was aware of the ability of .cma to force -custom at the time of the original discussion, but didn't think it was relevant as we were adding a feature. Does it override -output-complete-exe i.e. does ocamlc -o foo -output-complete-exe str.cma foo.ml give a -custom bytecode executable or a -output-complete-exe executable? If it's the former, then I'd say that's a bug.

It's the latter.

> I think we should change the semantics of embedding -custom in .cma exactly at the point -custom is removed, not before.

Just to make sure we are on the same page, your proposition is:
- today we deprecate `-custom` when building executables, but not when building libraries
- in 2 years:
  +  we remove `-custom` when building executables
  + we remove all the support for custom executables in the runtime
  + we repurpose `-custom` when building a library as meaning to pass `-output-complete-exe` when linking the final executable

Is that correct?

**Comment by dra27** [comment]
Yup. I *think* that on non-shared platforms, you don't have to specify `-custom` - it's automatically added if you use `-cclib` (or by `ocamlmklib` if you specify `.c` files).

**Comment by ghost** [comment]
Ok. That seems like a good plan to me. @nojb what do you think?

**Comment by nojb** [comment]
Sounds good! (and thanks @diml for shepherding the discussion). I will submit a PR soon.

**Comment by xavierleroy** [comment]
> I meant that it should be using -output-complete-exe where it presently uses -custom … i.e. for non-shared platforms.

Ah, OK.  I keep forgetting that those platforms still exist...

> on non-shared platforms, you don't have to specify -custom - it's automatically added if you use -cclib (or by ocamlmklib if you specify .c files).

Yes, the recommended (in the manual) way to create mixed OCaml/C libraries is to use `ocamlmklib`, and it will attach `-custom` to the library if necessary (C files and no shared library support).  As long as `ocamlmklib` is kept in sync with `ocamlc`, the switch away from `-custom`-in-libraries should be transparent.

I don't think `ocamlc -cclib` adds `-custom`, it just records stuff to be passed to the C linker if it is ever called.
