### ISSUE TITLE
ocamlobjinfo is inconsistent in metadata output

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#9276]
Some of the metadata fields of `.cma` and `.cmxa` fields are stored in reverse order w.r.t. to what was given on the cli. 

`ocamlobjinfo` reverse that list before output for "Extra C object files" (since #4949) but not for the other fields: 

```
> ocamlc -a -o bla.cma -cclib -ll0 -cclib -ll1 -ccopt a0 -ccopt a1 -dllib d0 -dllib d1
> ocamlobjinfo bla.cma
File bla.cma
Force custom: no
Extra C object files: -ll0 -ll1
Extra C options: a1 a0
Extra dynamically-loaded libraries: d1 d0
```
Same for: 
```
> ocamlopt -a -o bla.cmxa -cclib -ll0 -cclib -ll1 -ccopt a0 -ccopt a1                    
> ocamlobjinfo bla.cmxa
File bla.cmxa
Extra C object files: -ll0 -ll1
Extra C options: a1 a0
```

Unless people object on backward compatibility grounds I propose to print them in the right order (and will PR).

**Comment by gasche** [comment]
No objection here, but wouldn't it make even more sense to *store* them in the right order, rather than merely printing them in the right order?

**Comment by dbuenzli** [comment]
I'm not sure. 

1. There's quite a bit of tricky business that happens with ordering during linking. 
2. This would silently break compiler libs users. 

We can certainly handle 1. however I'm a bit more uncomfortable with 2. So I'll start with simply documenting the reversion in the formats and fix `ocamlobjinfo`'s output.

**Comment by glondu** [comment]
Note that usually C libraries must be given in "reverse" order (compared to the one an OCaml programmer would naturally give) to the C linker (ld, or ld called via gcc). IMHO, we should not change what is stored in the archives since it is the "right" order from the p.o.v. of ld. I would even argue to let them in this order when printing via ocamlobjinfo, to avoid surprises.

**Comment by dbuenzli** [comment]
@glondu I don't think this the right view on the issue. You are mixing how the C linker should be used and how it is driven by OCaml.

What gets written in these fields is the reverse of what *you* write, in order, as `-ccopt` and `-cclib` on the OCaml invocation. The order *you* write them is the order that is going to be put on the C link line. 

As such printing them in reverse in `ocamlobjinfo` is just plain confusing when you are debugging issues (as #4949 noticed).

**Comment by xavierleroy** [comment]
> The order you write them is the order that is going to be put on the C link line.

Are you sure?  My memory is that `-cclib` options would get reversed, because as @glondu writes, if B uses A, in OCaml you list A before B on the command-line, and for the C linker you list B before A.

**Comment by dbuenzli** [comment]
According to what I see here, yes.
```
> ocamlopt -a -o bla.cmxa -cclib -ll0 -cclib -ll1 -ccopt a0 -ccopt a1 
> touch a.ml                               
> ocamlopt -verbose bla.cmxa a.ml
+ clang -arch x86_64 -Wno-trigraphs -c  -o 'a.o' '/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/camlasmf0d272.s'
+ clang -arch x86_64 -Wno-trigraphs -c  -o '/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/camlstartup11a3c9.o' '/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/camlstartupdb4b21.s'
+ cc -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -Wl,-no_compact_unwind -o 'a.out'  '-L/Users/dbuenzli/.opam/4.09.0/lib/ocaml' a0 a1 '/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/camlstartup11a3c9.o' '/Users/dbuenzli/.opam/4.09.0/lib/ocaml/std_exit.o' 'a.o' 'bla.a' '/Users/dbuenzli/.opam/4.09.0/lib/ocaml/stdlib.a' '-ll0' '-ll1' '/Users/dbuenzli/.opam/4.09.0/lib/ocaml/libasmrun.a' -lm 
[...]
```

**Comment by dbuenzli** [comment]
I think it makes sense if you read the doc of `-cclib`, the doc of `-cclib` does simply say: 
```
-cclib <opt>  Pass option <opt> to the C linker
```
It doesn't talk about C libraries per se.

**Comment by gasche** [comment]
I must say that @glondu's reaction is giving me pause. When @dbuenzli wrote the issue/report, I thought that of course the reversal was an unintentional bug, but now it sounds like there is a chance that the reversal is intentional (but we don't know). Now @xavierleroy is in favor of the surprising order.

Now might be a good time to declare that it will be too hard/time-consuming to resolve the issue in a fully satisfying way (compatibility testing, etc.), and that it's just easier to (1) document the current choice (as the first part of this PR is doing, although maybe one should now also reflect the suggestion that this is the C-linking order) and (2) revert the change of behavior, adapting whatever comes later to deal with this meh legacy state that nobody really wants to touch.

**Comment by dbuenzli** [comment]
I think the confusion we are witnessing here is because this output from `ocamlobjinfo`: 
```
Extra C object files: -ll0 -ll1
```
is mislabelled. This should be "Extra C link flags" because that's what it is. Again we are not talking about C *objects*, we are talking about C linker *flags*.

I don't think there's any bug or thing to change here. The documentation about this has always been very clear:
```
-cclib <opt>  Pass option <opt> to the C linker
-ccopt <opt>  Pass option <opt> to the C compiler and linker
```

**Comment by xavierleroy** [comment]
> it sounds like there is a chance that the reversal is intentional (but we don't know).

The reversal was intended so that autolinking (of C stubs libraries) would work.  Consider two OCaml libraries:
* a.cmxa that autolinks `-cclib -lstubs_a`
* b.cmxa that uses a.cmxa and autolinks `-cclib -lstubs_b`.

The user links with the two libraries in OCaml order: definitions before use
```
      ocamlopt a.cmxa b.cmxa mycode.cmx
```
but the C linker expects `-lstubs_b -lstubs_a`, otherwise C functions from `stubs_a` that are referenced in `stubs_b` may not be linked in.

If the reversal doesn't occur, something is wrong.

This has little to do with the present PR, however.

**Comment by dbuenzli** [comment]
> If the reversal doesn't occur, something is wrong.

That reversal does occur (cf. below). But that's an *inter*-archive link flags reversal. The link flags in the field of the library archive itself are not reversed and provided in the order specified when the library was created.

```       
> ocamlopt -a -o l0.cmxa -cclib -ll00 -cclib -ll01 
> ocamlopt -a -o l1.cmxa -cclib -ll10 -cclib -ll11 
> touch a.ml                                       
> ocamlopt -verbose l0.cmxa l1.cmxa a.ml        
[...]
+ cc  [...] '-ll10' '-ll11' '-ll00' '-ll01' [...] 
```

**Comment by xavierleroy** [comment]
> That reversal does occur (cf. below). But that's an inter-archive link flags reversal. The link flags in the field of the library archive itself are not reversed and provided in the order specified when the library was created.

Ah, I see!  Thank you for the clarification.  (I tried to read your example on my phone, but couldn't quite follow the long lines...)

So, to summarize:
* "Inter-archive" reversal is important and must be preserved (no "unintentional bug" or "meh legacy state" here)
* Intra-archive behavior doesn't matter much; what we do currently (preserve command-line order) is OK with me.
* Whether -cclib and -ccopt options should be stored reversed or not in .cmx and .cmxa files is an implementation detail.  I would suggest not to change if it's not clearly broken.
* I have no strong opinion on how ocamlobjinfo should display those stored flags, so do what you think is most meaningful.
