### ISSUE TITLE
platform difference for 0x1p-1022

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#9303]
on Mac
```
# 0x1p-1022;;
- : float = 2.22507385850720138e-308
```
on windows
```
# 0x1p-1022;;
- : float = 2.2250738585072014e-308
```

**Comment by dra27** [comment]
OCaml version and Windows port used, please.

**Comment by bobzhang** [comment]
Sorry missed the info. Ocaml version 4.06.1 + mingw port

**Comment by dra27** [comment]
amd64 on both?

**Comment by xavierleroy** [comment]
The decimal representation of a FP number is not necessarily unique.  Both representations parse back to the same float:
```
# let a = 2.22507385850720138e-308
  and b = 2.2250738585072014e-308
  in (b -. a, b = a);;
- : float * bool = (0., true)
```
You can't expect that float -> string conversion will give the exact same results on different platforms.  If you want a unique string representation of a FP number, use hexadecimal format (`sprintf "%h"`).

**Comment by dra27** [comment]
The issue is the C runtime library's `sprintf` - mingw uses `msvcrt.dll` as found in Windows system which is a _very_ old C runtime. I expect the behaviour changed with the Universal CRT - the MSVC port built with the Windows 7 SDK behaves as Windows above; the MSVC port built with Visual Studio 2017 behaves as macOS above.

You can compile mingw-w64 to target the UCRT, but that means not using the Cygwin/MSYS2 built-in packages...

**Comment by bobzhang** [comment]
@dra27 I have some work around, thanks for the explanation
