### ISSUE TITLE
Inaccurracies in manual about infix attribute equivalence examples

### ISSUE THREAD

**Issue by codename68** [ocaml/ocaml#9327]
In chapter 8.12, in the examples presenting the equivalence between infix `[@attr]` attributes and the syntax without them, some examples seem confusing. And when passing them to `ocaml -dsource`, it gives a different output:

For example:
```
begin[@foo][@bar x] ... end       === (begin ... end)[@foo][@@bar x]
```
`ocaml -dsource` gives:
```
(begin ... end)[@foo][@bar x]
```

And for example:
```
let[@foo] x = 2
and[@bar] y = 3 in x + y           === (let x = 2 [@@foo] and y = 3 [@bar] in x + y)
```
`ocaml -dsource` gives:
```
(let x = 2 [@@foo] and y = 3 [@@bar] in x + y)
```

I assume the manual and `ocaml -dsource` should agree.

Thanks for consideration.

**Comment by gasche** [comment]
I don't understand what is the problem with the first example. (I tried myself and on 4.09 `-dsource` uses parentheses rather than `begin .. end` to reprint, but the two choices are equivalent and seem consistent with what the manual says.)

In the second example, I find it a bit confusing that a single-arobase attribute would get turned into a double-arobase attribute by desugaring, but this is the choice that was made at design time (note that, in the desugaring, using a single-arobse attribute in the same place would attach to the right-hand-side of the binding only, so it has a different meaning). It appears to me that the manual documents this behavior correctly, and that it is consistent with `-dsource` output. What is the problem that you are reporting?

**Comment by Octachron** [comment]
There is an inconsistency between algebraic and item levels in the translation: both levels appear on the right-hand side whereas fortunately the parser is consistent and pick only one attribute level for the two attributes (algebraic in the first case, item in the second one).

**Comment by gasche** [comment]
Ah, I see it now. Thanks!
