### ISSUE TITLE
String indexing ( .[] ) breaks when module String refers to another module

### ISSUE THREAD

**Issue by sonologico** [ocaml/ocaml#9370]
The following example code gives me `Error: Unbound value String.get`

```
let x = "abcd"

let y = x.[0]

module String = Int

let z = x.[0]
```

I would expect the behavior to be analogous to this other made up example that compiles without errors:

```
module Fake_array = struct
  type t = Repeated of int

  let ( .%[] ) x _ =
    match x with
    | Repeated v -> v
end

open Fake_array

let x = Repeated 2

let y = x.%[0]

module Fake_array = Int

let z = x.%[0]
```

I understand the underlying reason that string indexing predates the custom indexing operators and that their implementation differs.

This is, of course, known, but is it considered an issue or is it intended behavior? If an issue, could it be fixed or would it break backwards compatibility at an unacceptable level?

**Comment by dra27** [comment]
I think this is the same thing as in https://github.com/ocaml/ocaml/pull/69#issuecomment-45970090

**Comment by gasche** [comment]
I don't think the two code examples are really comparable. In the second example, the notation is made available in scope by `open`, and it is not shadowed by the redeclaration. If you shadowed the definition of `.(%[])`, you would observe issues similar to the shadowing of `String` or `String.get` in the first example.

It is certainly true that the specification of these two constructs is not consistent. In one case we desugar to a mere name in the lexical environment, `.(%[])`, that looks a bit odd visually, in the other we desugar to a qualified path that has natural but made-up name, `String.get` (made-up in the sense that it does not occur in the source syntax at all). Other than that, it is a lexical lookup in both cases, and the behavior with respect with shadowing/redefinition is more similar, I think, than @sonologico suggests.

The main question is: "are we going to change things here"? And I think the answer is "not in the medium-term future". And if we were to change things, I think we would not necessarily decide to make `foo.[bar]` behave like user-defined indexing operators (desugar into a rebindable `(.[]) foo bar`)); instead we may want to define `.()` and `.[]` as "builtin" (as opposed to lexically-scoped) operations that keep their primitive meaning in all cases, or possibly that are disambiguated in a type-directed way rather than by using lexical scoping; see . We were careful when introducing user-definable binding operators to reserve a *new* syntactic space for those that would not conflict with existing indexing notation, so that we can keep our options open for string- and array-indexing.

With all this, I propose to close the current issue. It's not wrong, but for now we are in-between a "won't fix", a "no change required", so there is not much value in leaving it open.
