### ISSUE TITLE
too many `unused value` warning when whole module is unused

### ISSUE THREAD

**Issue by ygrek** [ocaml/ocaml#9404]
Not sure if it should be treated as a bug but it is a bit of unpleasantry
```
# #warnings "+a";;
# let f () = let module X = struct let x = 2 let y = x + 1 let z = 3 end in 2 + 2;;
Line 1, characters 47-48:
1 | let f () = let module X = struct let x = 2 let y = x + 1 let z = 3 end in 2 + 2;;
                                                   ^
Warning 32: unused value y.
Line 1, characters 61-62:
1 | let f () = let module X = struct let x = 2 let y = x + 1 let z = 3 end in 2 + 2;;
                                                                 ^
Warning 32: unused value z.
Line 1, characters 22-23:
1 | let f () = let module X = struct let x = 2 let y = x + 1 let z = 3 end in 2 + 2;;
                          ^
Warning 60: unused module X.
val f : unit -> int = <fun>
```

**Comment by gasche** [comment]
I see arguments in favor, and arguments again the suggestion to silence the per-element warnings in this case.

What I first read the issue I agreed with @ygrek on the following basis: if a module is unused, then of course its elements are also unused, so it is kind of dumb to warn for each element in addition to the module.

But this reasoning of mine is actually wrong. There are two separate aspects at play here:
- is each module element (x, y, z) used outside *or inside* the module?
- is the module itself used?

The warnings for the unused elements can be fixed by changing the module definition (say adding `let () = ignore (y + z)`), without changing the code after the module declaration. So in a sense the reason for `y, z` being unused is not the same as the reason for the module `X` being unused.

On the other hand, adding a use of `X` is likely to create a use for some or all of its elements. So one might argue that the user should fix the lack of usage of `X` first, which would be a reason to elide the other warnings.

Personally I think that the current behavior is simpler and more predictable. I would agree with hiding a warning W1 when a warning W2 is shown such that fixing W2 would necessarily fix W1. But here we are not in this situation, W1 can be fixed by an independent change, it is not strictly subsumed by W2. Deciding to elide W1 amounts to making guesses, which I think is not so desirable when dealing with user code.

**Comment by ygrek** [comment]
I agree, better keep predictable behaviour
