### ISSUE TITLE
toplevel printing discrepancy

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#9418]
in ocaml:
```
type _ t = ..
type 'a t += T of 'a
T 0 
- : int t = T <poly>
```
whereas:
```
type 'a t = T of 'a
T 0
- : int t = T 0
```

**Comment by gasche** [comment]
Thanks for the report!

I looked at the implementation of `toplevel/genprintval` to understand the source of the difference. The toplevel has the type and it finds the constructor `T` just right (this happens in `tree_of_extension`), but then it tries to print the arguments (by calling `tree_of_constr_with_args`) with the argument types coming from the type declaration, with a parametric `'a` that results in `<poly>` being printed.

In contrast, printing a regular constructor calls `Ctype.apply` to instantiate the declaration type parameters with the specific type instances at the usage site, so that more precise type information is available. (There are several calls to `Ctype.apply` in this file, any one of them should give the idea.)

I would expect that the issue can be fixed by calling `Ctype.apply` in the right place in `tree_of_extension`. (I'm not completely sure what the right place is.)

**Comment by progman1** [comment]
Thanks for that.
by passing in the ty_list and instantiating the params as per a regular constructor, 
all is well again :)

```
    and tree_of_extension type_path ty_list depth bucket =
    ...
        let type_params =
          match (Ctype.repr cstr.cstr_res).desc with
            Tconstr (_,params,_) ->
             params
          | _ -> assert false
        in
        let args=
          List.map
            (function ty ->
                       try Ctype.apply env type_params ty ty_list with
                         Ctype.Cannot_apply -> abstract_type)
            cstr.cstr_args
        in
        tree_of_constr_with_args
           (fun x -> Oide_ident x) name (cstr.cstr_inlined <> None)
           1 depth bucket
           args false
```

**Comment by progman1** [comment]
I assume PR's are only submitted by the duly authorised?

**Comment by gasche** [comment]
Anyone can submit a PR, see [CONTRIBUTING.md](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md).

**Comment by progman1** [comment]
I do believe I have a PR going!
https://github.com/ocaml/ocaml/pull/9439

do you happen to know what minimum amount of a repository needs to be cloned
in order to submit a PR against it?
it seems not to work with --depth 1 but the alternative seems to be to copy the entire history back to the stone age. I haven't managed to find any answer to this.
thanks.

**Comment by nojb** [comment]
> do you happen to know what minimum amount of a repository needs to be cloned
> in order to submit a PR against it?
> it seems not to work with --depth 1 but the alternative seems to be to copy the entire history back to the stone age. I haven't managed to find any answer to this.
> thanks.

FWIW, unless you are severely resource-constrained, cloning the full history should not be a problem.
