### ISSUE TITLE
regression: arm32 failures in floating point

### ISSUE THREAD

**Issue by olafhering** [ocaml/ocaml#9431]
This was reported ocsigen/lwt#773 as failure in the ocaml-lwt tests with ocaml 4.10.0, but also Chris00/ocaml-benchmark and ocaml-community/biniou is affected. The latter aborts because the expected floating point format constraints are not met.

I rebuilt [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml) for openSUSE_Tumbleweed/armv7l with ocaml the 4.05, 4.06, 4.07 and 4.08 branches. 4.05 was known to work, and it turned out 4.06 and 4.07 work equally well. The failures in lwt, biniou and benchmark started with 4.08.

I do not know anything about ARM, I just happen to be the package maintainer of ocaml packages in the distro project mentioned above.

**Comment by xavierleroy** [comment]
Here is what I can say with the little information available.

The ARM32 port of OCaml works perfectly under Raspbian Linux.  Every single commit is tested on a Raspberry Pi running Raspbian as part of OCaml's CI.

Could you please run the OCaml test suite on your openSUSE packages?  It's the testsuite/ directory in the source distribution.

In 4.08 the autoconfiguration scripts were entirely rewritten, with a switch to autoconf.  So, if the openSUSE packages pass special options at OCaml configure time, they may need to be updated.

The symptoms mentioned are consistent with an ABI mismatch between OCaml and C.  There are two ABIs for ARM32: "soft float" and "hard float", differing in how FP function arguments and results are passed.  So, if openSUSE uses the "hard float" ABI but OCaml's configuration picks the "soft float" ABI, or the other way around, lots of FP values will be wrong.

**Comment by olafhering** [comment]
Well, `configure` does not allow any external `CFLAGS`. While I do tweak it slightly to pass additional warnings down to the OCaml eco system, nothing else will be changed.

There are failures in [4.08](https://build.opensuse.org/package/live_build_log/devel:languages:ocaml:408/ocaml/openSUSE_Tumbleweed/armv7l), while [4.07](https://build.opensuse.org/package/live_build_log/devel:languages:ocaml:407/ocaml/openSUSE_Tumbleweed/armv7l) succeeds.

4.08 and 4.10 is stuck in `testpreempt.`, the build VM gets killed by the host after a timeout. Using `-O1` changes nothing.

Attached is the complete build log for 4.10, `make check` starts at second `2109s`
[log.devel:languages:ocaml:410.ocaml.openSUSE_Tumbleweed.armv7l.txt.gz](https://github.com/ocaml/ocaml/files/4449561/log.devel.languages.ocaml.410.ocaml.openSUSE_Tumbleweed.armv7l.txt.gz)

````
[ 4406s] Summary:
[ 4406s]   2507 tests passed
[ 4406s]    38 tests skipped
[ 4406s]    65 tests failed
[ 4406s]   114 tests not started (parent test skipped or failed)
[ 4406s]     1 unexpected errors
[ 4406s]   2725 tests considered
[ 4406s] #### Something failed. Exiting with error status.
[ 4406s] 
[ 4406s] make[1]: *** [Makefile:262: report] Error 4
````

**Comment by olafhering** [comment]
Looking through `CFLAGS` usage, configure does nothing special. C code gets compiled with the compiler defaults.

There is most likely some arm32 assembler in the ocaml code base. Does this assembler code make any assumptions about the floating point environment?

Appending `-mfloat-abi=hard/softfp/soft` makes no difference, only `hard` can be used anyway. Is there a slim chance the 32bit emulation on those `aarch64` workers is broken?

Unfortunately I do not have access to armv7 hosts at the moment, the native armv7 workers are also not available for the time being.

**Comment by olafhering** [comment]
With autoconf the commandline is (everywhere in Tumbleweed): `./configure --host=armv7hl-suse-linux-gnueabi --build=armv7hl-suse-linux-gnueabi`.
With 4.07 `configure` the guessed system is: `armv7l-unknown-linux-gnueabihf`

This looks already fishy.

**Comment by xavierleroy** [comment]
> Appending -mfloat-abi=hard/softfp/soft makes no difference, only hard can be used anyway. 

The problem is not to tell GCC to use FP ABI that OCaml chose by default.  The problem is to tell OCaml to use the FP ABI that GCC uses on your system.

It seems that 
* SUSE wants the soft FP ABI (gnueabi)
* the `config.guess` script from FSF that OCaml's configure uses guessed the hard FP ABI (gnueabihf).

The solution is therefore to configure OCaml with armv7hl-suse-linux-gnueabi as the build system:
```
./configure --build=armv7hl-suse-linux-gnueabi
```
On my Raspberry PI this seems to produce the correct Makefile.config.  In particular SYSTEM is set to `linux_eabi`, which will select the soft float ABI.

If you SUSE folks want to update config.guess so that it guesses the right system for your ARM port, be my guest.

**Comment by olafhering** [comment]
I found this in `gcc.spec`, which explains why the change below appars to work:
````
%if "%{TARGET_ARCH}" == "armv7hl"
        --with-arch=armv7-a \
        --with-tune=cortex-a15 \
        --with-float=hard \
        --with-abi=aapcs-linux \
        --with-fpu=vfpv3-d16 \
        --disable-sjlj-exceptions \
%endif
````
```` diff
--- a/configure.ac
+++ b/configure.ac
@@ -852,7 +852,7 @@ AS_CASE([$host],
   [armv8*-*-linux-gnueabi],
     [arch=arm; model=armv8; system=linux_eabi],
   [armv7*-*-linux-gnueabi],
-    [arch=arm; model=armv7; system=linux_eabi],
+    [arch=arm; model=armv7; system=linux_eabihf],
   [armv6t2*-*-linux-gnueabi],
     [arch=arm; model=armv6t2; system=linux_eabi],
   [armv6*-*-linux-gnueabi],
````
4.08:
````
[ 4167s] Summary:
[ 4167s]   2392 tests passed
[ 4167s]    34 tests skipped
[ 4167s]     0 tests failed
[ 4167s]   101 tests not started (parent test skipped or failed)
[ 4167s]     0 unexpected errors
[ 4167s]   2527 tests considered
````

**Comment by olafhering** [comment]
Well, in the end this does not seem to be an OCaml bug, rather it just served to uncover an apparent inconsistency somewhere else.

**Comment by xavierleroy** [comment]
It looks like your GCC implements the EABI-HF calling conventions.  Then, don't give `--build=armv7hl-suse-linux-gnueabi`, because it's factually incorrect; give `--build=armv7hl-suse-linux-gnueabihf` or don't give any option, `config.guess` will guess correctly.

**Comment by olafhering** [comment]
I was told `armv7Hl` should be enough to identify hard vs. soft. 
`armv7*` is too generic to make a guess.

**Comment by gasche** [comment]
I tried to understand why @xavierleroy and @olafhering seem to be talking across each other, here and in #9435. My impression is as follows (please note that just like @olafhering I know nothing about ARM.)

1. Most of the world, and in particular Debian and the OCaml compiler configure script, expects ARM host triples of the form `<architecture model>-<os>-<compiler_abi>`, where the `<os>` part for Linux systems can be itself `linux` or `<distribution>-linux`. Examples include `armv6-rpi-linux-gnueabi`, `armv5te-none-linux-androideabi` or  `arm-linux-gnueabihf`. In the ABI part, the `hf` prefix is present when the ABI uses the hard-float convention, and otherwise soft-float is assumed.

2. Suse uses a different naming convention where the architecture (required by a binary RPM package provided for Suse) is described as `armv7l` or `arvm7hl`, where `l` indicates little-endian and `h`, when present, means that the code can use hard-float.

As a result, in the Suse world `armv7hl-suse-linux-gnueabi` is not an exotic architecture suffix for armv7 with soft-float gnueabi, it is in fact indicating an armv7 architecture with hard-float, so gnueabihf.

Case in point, see for example the [patch](https://build.opensuse.org/package/view_file/SUSE:SLE-12:GA/llvm/arm_suse_support.diff?expand=1) that Suse is applying to LLVM to make it understand its own, arguably broken, host-triple naming conventions:

```diff
   static const char *const ARMLibDirs[] = { "/lib" };
   static const char *const ARMTriples[] = { "arm-linux-gnueabi",
-                                            "arm-linux-androideabi" };
+                                            "arm-linux-androideabi",
+                                            "armv5tel-suse-linux-gnueabi"};
   static const char *const ARMHFTriples[] = { "arm-linux-gnueabihf",
-                                              "armv7hl-redhat-linux-gnueabi" };
+                                              "armv7hl-redhat-linux-gnueabi",
+                                              "armv7hl-suse-linux-gnueabi" };
```

The patch seems to suggest that Red Hat is doing the same non-standard thing, and indeed looking a bit I find a [similar question](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/2O4HBOK6PTQZAFAVIRDVMZGG2PYB2QHM/) by @rwmjones on the Fedora mailing-list, with a pointer to a [similar reply](https://bugzilla.redhat.com/show_bug.cgi?id=1134914#c9) on the Fedora bugtracker. (But then I didn't find any trace of a configure patch in the Fedora packages; maybe they have patched their autoconf instead?)

It seems that either configure.guess should be updated to take Suse's naming convention into account, or Suse should consider moving to the "Standard" host triples in the future. (It seems a bit silly to have to patch LLVM because one is using a different naming convention.)

**Comment by olafhering** [comment]
Perhaps you meant to say `configure.ac` instead of `configure.guess`?

It is not `config.guess` that is broken (this is [most likely] not even used with `%configure` and the resulting `./configure --host=x --build=y`), it would continue to provide the expected triple as it did in 4.07. 

It is the expectation in `configure.ac` which maps host triples to features. This mapping list is entirely within the domain of OCaml. And as you can see in the LLVM patch, there is an `arm-*-gnueabihf` and an `armv7hl-*-gnueabi`, just what my patch does as well. If LLVM had wildcards, no patch would be required.

I do not know who came up with all those combinations to describe the same thing. Debian is likely not the standard here, it just happens to use one set of possible values. In the end noone would rename the triple just for LLVM or OCaml.

**Comment by olafhering** [comment]
One more note: prior to 4.08 the `%configure` macro was not usable because it would pass unknown options to `configure`. Starting with 4.08 OCaml started to behave like every other package that uses autoconf, so using `%configure` was just natural.

And all that might just be a rpm thing. Some software archealogy is required to understand why  `config.guess` and `%configure` use different names.

**Comment by gasche** [comment]
Well arguably the "Debian way" is more correct because the ABI is different between soft-float and hard-float (this is why the gcc option is called `mfloat-abi`), so hf/sf should be specified in the ABI part. It does not feel "wrong" to indicate in the architecture whether a hard-float unit is available, but it *is* wrong to use `gnueabi`, which is understood to mean a specific ABI, when you mean a hard-float ABI called `gnueabihf` by the rest of the world.

It would be less confusing if Suse used something like `armv7hl-suse-linux-gnu`, where the last part does not claim to be precise on the ABI, but really the best choice would be to use `armv7hl-suse-linux-gnueabihf`, so that the hard-float information is given in the architecture (as Suse proposes, and sounds reasonable) and also in the ABI (as it should). In particular, if Suse used this host triple instead of its current one `armv7hl-suse-linux-gnueabi`, the OCaml configure script would work unchanged.

**Comment by gasche** [comment]
(My comment about config.guess is probably wrong because I know nothing about autoconf. Apologies for that.)

**Comment by olafhering** [comment]
The reported failures on arm32 are bugs in rpm and/or how rpm is configured on arm32.

The rpm `%configure` macro is supposed to drive an `configure` file which is generated by `autoconf`. Every author of `configure.ac`, who needs to work with `host/build` values to make decisions based on those values, has to work with values which are potentially returned by `config.guess`. The `%configure` macro per default passes `--host` and `--build` values to configure. On arm32 rpm uses values which will never be returned by `config.guess`.

rpm has all the liberty to use its own namespace for `%{_host}` and `%{_build}` for its own purpose. But when it comes to GNU autoconf it MUST use compatible values, because this is what is expected by `configure.ac`.

For short: OCaml `configure.ac` must not be changed because the bug is somewhere else.

**Comment by ausil** [comment]
Fedora uses --build=armv7hl-redhat-linux-gnu --host=armv7hl-redhat-linux-gnu
