### ISSUE TITLE
Type-checker reports type error without noticing that a variable is undefined

### ISSUE THREAD

**Issue by fpottier** [ocaml/ocaml#9438]
In the following code, the variable `x` is unbound in the definition of `g`. Yet, the OCaml type-checker does not notice it, and instead produces a confusing type error.

```
#  let rec f : 'a. 'a -> 'a =
      fun x -> g()
    and g () = x;;  
Error: This definition has type 'a -> 'a which is less general than
         'a0. 'a0 -> 'a0
```

**Comment by Octachron** [comment]
As far as can see, the type checker is just reporting the first error that it encounters
```ocaml
let g () = ()
let rec f: 'a. 'a -> 'a = g ()
```
yields
> Error: This definition has type 'a -> 'a which is less general than
         'a0. 'a0 -> 'a0

and
```ocaml
let rec g () = x
and f: 'a .'a -> 'a = fun x -> g ()
```
> Error: Unbound value x

And fortunately, the recent changes (in #1132 ) by @lpw25 to the typing of explicit polymorphic types make the typechecker picks the second error in trunk

```ocaml
#  let rec f : 'a. 'a -> 'a =
      fun x -> g()
    and g () = x;;  
```
> Error: Unbound value x

thus the issue will be fixed in 4.11 .

**Comment by fpottier** [comment]
Thanks Florian. I did not make this clear in my initial message, but I think it makes sense to report lexical errors before type errors. Indeed, I would like the type-checker to act as a guide and tell me where I must fix my code. Here, I expect to the type-checker to first tell me that `x` is unbound in `g`, so I can fix the definition of `g`.

**Comment by Octachron** [comment]
I agree that the error reported is far from ideal.

However, your criterion is kind of verified: before OCaml 4.11, the function `f` fails to type check for any definition of `g`:
```ocaml
let rec f : 'a. 'a -> 'a =
      fun x -> g x
and g x = x;;
```
> Error: This definition has type 'a -> 'a which is less general than
         'a0. 'a0 -> 'a0

without an explicit type annotation on `g`:

```ocaml
let rec f : 'a. 'a -> 'a = fun x -> g x
and g: 'a. 'a -> 'a = fun x -> x;;
```
and once the explicit annotation on `g` is added

```ocaml
 let rec f : 'a. 'a -> 'a = fun x -> g x
 and g: 'a. 'a -> 'a  = fun () -> x;;
```
the `Unbound value x` pops up again.

So it makes some sense to start by reporting the generality issue.

**Comment by xavierleroy** [comment]
>  I think it makes sense to report lexical errors before type errors.

Dear François: you probably meant "lexical scoping errors" above, because I can assure you lexical errors are detected even before parsing.  But, no, your wish is not possible because scoping resolution must be performed at the same time as type-checking, because of `open` and `include` among other niceties of the OCaml language.

Can we please close this report?
