### ISSUE TITLE
Can't compile a filename containing "-" character in OCaml 4.11 on AMD64

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#9461]
perl4caml contains an old test which is literally called `001-start.ml`.  This fails to compile on x86-64 only with the new compiler:
```
ocamlopt -w s -I wrappers -c test/001-start.ml
File "test/001-start.ml", line 1:
Warning 24: bad source file name: "001-start" is not a valid module name.
/tmp/camlasm8c525e.s: Assembler messages:
/tmp/camlasm8c525e.s:59: Error: expected comma after name `caml001' in .size directive
File "test/001-start.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasm8c525e.s
```
While we should obviously rename the test, this appears to be an unintentional regression.

**Comment by rwmjones** [comment]
I doubt the contents of the test itself matters, but in case it's here:
http://git.annexia.org/?p=perl4caml.git;a=tree;f=test

**Comment by nojb** [comment]
Thanks for the report. Can reproduce by compiling an empty file with a name containing a dash `-`. The culprit is https://github.com/ocaml/ocaml/blob/adc354c167a010ff5433cd4a9bf8bcf324b68daf/asmcomp/amd64/emit.mlp#L1149-L1150
from #8805 which uses `Compilenv.make_symbol` which does not escape special characters in the unit name.

**Comment by xavierleroy** [comment]
It's OK (and necessary!) to use  `Compilenv.make_symbol`, but the result must be properly escaped:
```
D.size frametable (ConstSub (ConstThis, ConstLabel (emit_symbol frametable)) )
```
(note the `emit_symbol`).
