### ISSUE TITLE
-annot can result in modified .cmx

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#9470]
With `trunk` compiler:
```
$ echo "type t = A" > a.ml
$ echo "let f (_ : A.t) = object end" > b.ml
$ ocamlopt -c a.ml
$ ocamlopt -c b.ml
$ md5sum b.cmx
7bbe2afa5aacd6db86eccde09bbd2593  b.cmx
$ ocamlopt -annot -c b.ml
$ md5sum b.cmx
c791ac713e562561aecff8e655e77f01  b.cmx
```

**Comment by nojb** [comment]
The issue seems to have been introduced by c19e8b23506e38fc47c110138d50b57fe93f7d7e (#2127)

**Comment by nojb** [comment]
cc @lpw25

**Comment by lthls** [comment]
It seems that `Clambda` uses for its identifiers the type `Ident`, which includes a unique stamp. So if some previous compiler pass uses more (or less) identifiers, the `Clambda` stamps will differ.
I guess that passing `-annot` means that the compiler has to print some types, which could create new identifiers. (Flambda is not affected as it uses its own identifier type, with its own stamps.)

Normally producing different `cmx` files is not a problem, as it can happen for example if you use `ocamlopt` vs `ocamlopt.opt` (because of different sharing).
If this causes a problem in your workflow, please elaborate; the reported behaviour is not a bug in my mind.

**Comment by nojb** [comment]
> It seems that `Clambda` uses for its identifiers the type `Ident`, which includes a unique stamp. So if some previous compiler pass uses more (or less) identifiers, the `Clambda` stamps will differ.
> I guess that passing `-annot` means that the compiler has to print some types, which could create new identifiers. (Flambda is not affected as it uses its own identifier type, with its own stamps.)

Do you understand why this behaviour appeared with the indicated commit? Before that commit the compiler did not have this problem.

**Comment by lthls** [comment]
Unfortunately, no, the type-checker looks like black magic to me.

**Comment by nojb** [comment]
> If this causes a problem in your workflow, please elaborate; the reported behaviour is not a bug in my mind.

We detected the problem in a slightly roundabout way, but should not be a big problem for us. Thanks for investigating.

**Comment by gasche** [comment]
Im someone wanted to investigate the issue: you don't need to build a .cmx to observe the issue with `-annot`, just run `-dcmm` or earlier `-dclambda` and observe that the identifier stamps are different between the two versions.

(Note: `Printtyp` uses `Ident.rename` in its `hide` function, this may be a source of different behavior from calling `-annot`, but I don't see how the commit pointed out by @nojb could affect this behavior.)
