### ISSUE TITLE
A surprising but serious limitation due to using Sys.command in the compiler

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#9482]
When calling the OCaml compiler to link an executable, it will call out the C compiler to perform the final link. For instance:

```
$ ocamlopt -o prog.exe unix.cmxa main.cmx -verbose
[...]
+ gcc -[...] -o 'prog.exe'  '-LXXX'  '/tmp/camlstartupec1259.o' \
  'XXX/std_exit.o' 'main.o' 'XXX/unix.a' 'XXX/stdlib.a' '-lunix' \
  'XXX/libasmrun.a' -lm -ldl
```

As can be seen, the various `.cmxa` files passed to `ocamlopt` end up being translated to viarious `-L<path>` and `-l<lib>` command line arguments to gcc.

One interesting detail is that the call to the C compiler is performed via `Sys.command`, which ultimately calls `/bin/sh`. More precisely, if we strace ocamlopt we can see that the whole gcc command line is packed into a single command line argument of `/bin/sh`:

```
$ strace -s 1000 -fe execve ocamlopt -o prog.exe unix.cmxa main.cmx
[...]
execve("/bin/sh", ["sh", "-c", "gcc [...] -o 'prog.exe' [...] -ldl"], [...]) = 0
```

This has one consequence: if we pass a large number of libraries to ocamlopt, eventually we will reach the limit imposed by the system on a single command line argument.

On Linux, this limit is 128KB. One might think this number is pretty high, however we did reach this limit last year at Jane Street. Working around this limitation has been difficult and we had to introduce some pretty ugly hacks in our build rules to deal with it. These hacks won't hold forever and keep getting in the way, so I would like to find a better long term solution.

# Proposed solution

I'd like to propose that we change the compiler to perform the call to external commands via an interface similar to `Unix.create_process`. If we do that, we will then be limited by the total number of command line arguments which is a much higher limit.

Not only it will sovle this problem but it will also make compilation faster as we won't need to go through `/bin/sh` for each command executed by the compiler.

# Difficulty

`Unix` is not part of the standard library and we can only use the standard library inside the compiler. So we cannot use `Unix.create_process` in the compiler.

We could move `Unix.create_process` to the standard library, however to be properly usable we would also need to move quite a few file descriptor and pid related functions. How do people feel about that?

A simpler compromise would be to add high-level functions for running programs to the `Sys` module and pass command line arguments as lists or arrays of strings. For instance:

```ocaml
val run
  :  prog:string
  -> argv:string list
  -> int

val run_capture_stdout
  :  prog:string
  -> argv:string list
  -> int * string

...
```

**Comment by gasche** [comment]
Currently the robust way to use Sys.command is to use Filename.quote_command first, see for example #9476 which adapted a part of the codebase to use it. Notice in particular that the built-in support for easily redirecting the stdout to a file is convenient.

Personally I like the `Sys.run_*` suggestion. I think that maybe we could have a bit more flexibility (than in your interface sketch) in deciding where to redirect stdout and stderr. Maybe we could have a version that captures them both as strings, and a version that takes a `filepath option` and redirects them to a file when a filepath is provided.

**Comment by gasche** [comment]
(Clarification: I'm not suggesting, of course, that `Filename.quote_command` would solve the problem you report, I want to suggest to take inspiration from its interface which is convenient in practice -- it is mostly identical to the proposition.)

**Comment by bschommer** [comment]
Why not use responsefiles, that would avoid the need to quote anything and I think there is already some logic in place to use them under windows.

**Comment by nojb** [comment]
> Why not use responsefiles, that would avoid the need to quote anything and I think there is already some logic in place to use them under windows.

Are response files supported by `gcc`? What about `clang`? (casual googling seems to indicate some degree of support, but could not find any hard documentation about it).

**Comment by ghost** [comment]
@gasche following the API of `Filename.quote_command` is a good suggestion. I hadn't looked at this  function yet.

@bschommer, as @nojb mentions it's not clear that response files are widely supported. They might also not be a standard interface. For instance, OCaml uses `-args` and other tools might use another interface. And regarding quoting, well if we use something similar to `Unix.create_process` there won't be any quoting involved. Or at least not at all on Unix, and I suppose less on Windows.

**Comment by bschommer** [comment]
> Are response files supported by `gcc`? What about `clang`? (casual googling seems to indicate some degree of support, but could not find any hard documentation about it).

`gcc` supports response files since at least [2005](https://gcc.gnu.org/wiki/Response_Files) and `clang` too has [support](http://llvm.org/docs/CommandLine.html#response-files) for this since it is needed for passing long command lines under windows anyway. `gcc` as well as all other binutils tool all use the `expandargv` function from the libiberty to my knowledge.

**Comment by ghost** [comment]
I suppose that might be a possibility then. However, all of this still seems somewhat unnecessarily complicated to me. When you think about it, when you go through `Sys.command` you basically:

1. you start with a list of strings
2. you encode this list of strings into a string, by quoting and concatenating everything
3. you pass the resulting string to an intermediate process that parses this string back into a list of string
4. the intermediate process calls fork/execve (or similar) with the original list of strings

By calling fork/execve directly in the main process, you avoid quite a lot of work for the same result. That seems strictly better to me.

**Comment by dra27** [comment]
I had toyed with the idea of proposing moving the process control _primitives_ into the runtime - the motivation at that point was how you would bootstrap both the compiler and Dune (a la the way `flexlink` is bootstrapped at the moment). At the time (just over a year ago) you could get a surprisingly looong way without Unix, but you can't escape the need for actual process control in a build system...

The discussion around that did yield a relevant point for here: systems like ocaml-freestanding don't like the addition of system calls to the runtime. So one possibility is that we could move the relevant primitives from Unix into the runtime, but not expose them in the standard library - i.e. put them in the compiler's stdlib. This way, the compiler driver gets the superior process control it needs, but other non-Unix supporting ports of the runtime (ocaml-freestanding, javascript etc.) can put dummy versions of those primitives in, because they know that they should only used if the Unix library is being loaded.

**Comment by gasche** [comment]
I think that response files are a reasonable solution for the specific problem of the C compiler invocation within the OCaml compiler, but if we can have a nice `Sys.run` function with a nice-to-use API that does not depend on Unix, this would solve the problem and also be a nice addition that other users (of other programs which may not support response file) would benefit from. (If we cannot agree on a `Sys.run` function, then responsefiles are a good plan B.)

(Edit: @dra27 wrote his answer at the same time as mine. If we want to hide the new runtime support, then we may just as well use responsefiles, I think, it is less work for the same visible result.)

**Comment by ghost** [comment]
@dra27 I thought about adding these to the compiler libs only. It feels like a smaller initial investment, but it seems strictly worse to me in the long run. The compiler mini stdlib has a much smaller scope and will naturally get less attention than the stdlib. Plus as @gasche points out this is a really nice feature to provide to users. It would be nice for duneboot.ml for instance :)

**Comment by jberdine** [comment]
Apologies for the noise, but can I just say that it makes me a bit sad to see nice improvements for the primary use case being avoided due to deficiencies in alternate deployments.

Also, while responsefiles might form a technical solution, I think it is worth noting that for debugging, it is preferable to use normal command line arguments. When something goes wrong, it is common to have a log of commands that were run. It is an additional consideration to make sure that all the responsefiles are still around when reading that log to know what was actually going on.

**Comment by diml** [comment]
@dra27 I thought about adding these to the compiler libs only. It feels like a smaller initial investment, but it seems strictly worse to me in the long run. The compiler mini stdlib has a much smaller scope and will naturally get less attention than the stdlib. Plus as @gasche points out this is a really nice feature to provide to users. It would be nice for duneboot.ml for instance :)

**Comment by nojb** [comment]
> By calling fork/execve directly in the main process, you avoid quite a lot of work for the same result. That seems strictly better to me.

One problem is that this will not be enough for Windows, as the implementation of `exec*` is buggy with respect to argv handling (see eg https://github.com/ocaml/ocaml/issues/9320#issuecomment-609005680). It seems to me you will end up having to call `CreateProcess`, so you will in fact have to copy a good part of the implementation of `Unix.create_process`.

**Comment by dra27** [comment]
I'm not sure how what I suggested would be worse in the long-run, it was merely a smaller step - moving the primitive in allows the bug to be fixed while the exact scope of how to expose the feature in a better way in the standard library can be deferred to a later discussion (I'm very much for it!). The only thing not being looked at much would be a small definition in the compiler stdlib for `Unix.create_process` (all the runtime changes would of course be utilised by the Unix library, and simply be code movement).

**Comment by xavierleroy** [comment]
I'm sad to learn that even Linux has arbitrary limitations on command-line arguments.

Here are some considerations and prior work to take into account:

* All OS have size limitations on command lines, sometimes very low (Windows), sometimes very high (Linux), so there will always be a situation where response files are the only option.  A createprocess-style API will solve the issue (of very long linker command lines) only under Linux.

* ocamltest already has a standalone implementation of Unix.create_process + extra features such as timeouts.  Read it to see that it's not completely trivial.

* Configuration needs more work when you can no longer assume that Sys.command will split at whitespace.  You can't just get
```
let ocamlc_cflags = "-O2 -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC"
```
by string substitution from a Makefile.config variable
```
OCAMLC_CFLAGS=-O2 -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC
```
Someone needs to do the parsing and splitting.  In CompCert, which uses `Unix.create_process` instead of `Sys.command`, we ended up with a nontrivial parser: https://github.com/AbsInt/CompCert/blob/master/lib/Readconfig.mll .  And in the end we still need to generate response files...

* Likewise, we may be taking for granted that the argument to `-ccopt` will be re-parsed by a shell, and may need to do our own shell-like parsing there.

**Comment by xavierleroy** [comment]
> The only thing not being looked at much would be a small definition in the compiler stdlib for Unix.create_process (all the runtime changes would of course be utilised by the Unix library, and simply be code movement).

`Unix.create_process` exposes Unix file descriptors, which drag much code in the Windows implementation.  Then there's also the primitives you need to wait for termination and deal with the exit code.  Again, look at the code @shindere wrote for ocamltest.

**Comment by ghost** [comment]
Would it be ok to parse the flags once and for all at configure time? We could even let the shell itself do the parsing by passing the string to a program that prints its command line arguments separated by null characters. What do you think?

Otherwise yeah, I'm definitely aware it's not trivial :) I happen to have already written two portable implementations of `create_process` like functions in Lwt and [spawn](https://github.com/janestreet/spawn). I had a look at the implementation in ocamltest and it looks like what I expected, except for the timeout part on Windows which I didn't know about.

It seems to me that If we use the same API as `Filename.quote_command` and don't provide advanced features such as timeouts, then the complexity should be manageable.

I also agree that this will only solve the problem on Linux. In Dune where we use `Unix.create_process` we did have to implement response files for Windows. And as @jberdine points out, we had to take special care so that the command lines are fully expanded in the logs.

@nojb I was indeed thinking of using `CreateProcess` on Windows.

@dra27 in this particular case, some API choices have already been made for `Filename.quote_command` so we can simply reuse the same choices. It doesn't seem necessary to me to go through an intermediate step.

**Comment by bschommer** [comment]
Note that the maximum size for arguments is still limited to for [example](https://www.in-ulm.de/~mascheck/various/argmax/) 1/4th of the stack size on modern linux and even smaller on older variants.

**Comment by ghost** [comment]
@bschommer indeed, though it's pretty high. I just looked on my Linux machine and it is more than 2 millions, which is more than enough.

**Comment by bschommer** [comment]
On Mac it seems to be still 256 KB.

**Comment by ghost** [comment]
Anyway, from what has been said so far we can conclude that if there exist people who do builds as large as we do at Jane Street on system other than Linux, then we will effectively have to implement response files no matter what. And if we implement response files, then the problem raised in this PR will be solved.

So the question is: should we bother changing the compiler to use a new `Sys.run` function rather than the current `Sys.command`?

Personally, I'd like to do it. It will remove intermediate shell processes which will result in slightly faster builds. And in general, I also like to avoid putting layers on top of other layers and I feel like going through `Sys.command` adds a few layers of quoting and parsing.

**Comment by bschommer** [comment]
Independent of the issue here, I think that a `Sys.run` function would be a good addition to the standard library.

**Comment by nojb** [comment]
I also think that `Sys.run` will be a nice addition.

However how would it work with `-ccopt` and `-cclib` ? Until now these were assumed to be strings that were concatenated to the command line passed to the shell. If we use `Sys.run` it looks like we will have to parse them back into lists of arguments. Is this the plan?

**Comment by ghost** [comment]
Agreed that `Sys.run` would be a nice addition.

> However how would it work with -ccopt and -cclib ? Until now these were assumed to be strings that were concatenated to the command line passed to the shell. If we use Sys.run it looks like we will have to parse them back into lists of arguments. Is this the plan?

We indeed need to be careful here, but I'm not even sure the current behaviour is very clear. i.e. in general build systems add `-cclib` and `-ccopt` before each argument without quoting them, and so effectively treating them as argument to be passed directly to a function such as `Unix.create_process`. At least, that's what we do in Dune, and IIRC that's what ocamlbuild does as well.

And the code in the compiler is not super clear either, it seems that we lightly parse cclib but not ccopt:

```
    let _cclib s = defer (ProcessObjects (Misc.rev_split_words s))
    let _ccopt s = first_ccopts := (s :: (!first_ccopts))
```

**Comment by ghost** [comment]
To be more precise, I'm not sure it is clear for users that you can write this:

```scheme
(library
 ...
 (c_library_flags "-x -y"))
```

I haven't tested if it works either.

**Comment by gasche** [comment]
I believe that we should separate two things:
1. the command-line-limitation bug, that we could or should fix by using responsefiles when invoking C compilers in the OCaml compiler
2. the feature request of having `Sys.run`, which everybody would want but some have warned may be impractically invasive in term of important Unix code (... so maybe it's not such a good idea after all).

I think that discussion would be easier if we separated the two threads. Jérémie, would you like to open a separate feature-request issue for `Sys.run`?

**Comment by shindere** [comment]
I fully support this approach, @diml.

Should you implement it, do not hesitate to assign me as a reviewer or
at least mention me because I only receive notifications when I am
mentionned or assigned.

**Comment by ghost** [comment]
@gasche  sure, I can do this. But just to be completely honest, from my point of view the priority is to solve this issue under Linux and committing to work on both adding `Sys.run` and support for response files feels like a too big commitment right now. So I would only work on whatever solution is accepted  and leave the other for someone else, or later if I find some time.

@shindere thanks for your support :)

**Comment by gasche** [comment]
My understanding of the discussion so far is that responsefiles are the safest choice: people have proposed various potential barriers for the other solution, but none for this (less ambitious) one.

Regarding responsefile: it would be nice if we could use responsefiles only above a certain size, and keep the usual invocation style before. The reasoning is that responsefiles are worse for debuggability: they may be removed by the compiler even in the case of failure, and their content is likely to not be available (or be hard to access) from any CI system or buildbot that sends us a failure report. The limit can be conservative (it's probably fine if we get the worst of Windows, OSX and Linux in terms of limitation, instead of trying to make finer-grained guesses), but it would be nice if "ordinary execution" would generally not hit it.

**Comment by bschommer** [comment]
I'm not sure if that would be enough but don't you just need to change the [line:](https://github.com/ocaml/ocaml/blob/8e15ad79df9e36fee3327ec0b8e3afaa51528153/utils/ccomp.ml#L43)

```OCaml
  if String.length s >= 4096 && Sys.os_type = "Win32"
```
to
```OCaml
  if (String.length s >= 4096 && Sys.os_type = "Win32") || String.length s >= <Constant>
```

and chose a constant that would be appropriate?

**Comment by xavierleroy** [comment]
Response files are the only complete solution to the problem reported in this issue, so that should be the priority.  I or @bschommer can tell you how CompCert handles them.

I have reservations on the usefulness of `Sys.run`, given that user programs can already get the same functionality using the Unix library.  So, you can put it as a feature wish or start working on it if you're so inclined, but that's low priority compared to fixing this issue.

**Comment by xavierleroy** [comment]
@bschommer: that's almost it, yes, but in CompCert we had to 1- make sure the compiler supports `@responsefile` (OK for gcc and clang), 2- quote things inside the response file.

**Comment by ghost** [comment]
Alright, I'll look at response files then and I'll leave the `Sys.run` addition to someone else. @xavierleroy or @bschommer, yes please let me know how CompCert handles them.

> 2- quote things inside the response file.

That makes me sad :disappointed:

**Comment by nojb** [comment]
Aren't we already quoting things inside the response files? https://github.com/ocaml/ocaml/blob/8e15ad79df9e36fee3327ec0b8e3afaa51528153/utils/ccomp.ml#L41

**Comment by bschommer** [comment]
> Aren't we already quoting things inside the response files?

I think you need to quote a little more than `Filename.quote` does. The code for quoting of a single argument for gcc can be found [here](https://github.com/AbsInt/CompCert/blob/438d541dbe5fe7d7fe6b7aacaa6e6ef070c2e237/lib/Responsefile.mll#L96) in CompCert.

**Comment by bluddy** [comment]
> Regarding responsefile: it would be nice if we could use responsefiles only above a certain size, and keep the usual invocation style before.

I think it makes more sense to use responsefiles uniformly. Having two paths just makes things more complex and confusing, as well as increasing the likelihood of breaking any one path. If debugging is the concern, the responsefile contents can be chunked and sent to the shell as comments for a nop.

**Comment by nojb** [comment]
> I think you need to quote a little more than `Filename.quote` does. The code for quoting of a single argument for gcc can be found [here](https://github.com/AbsInt/CompCert/blob/438d541dbe5fe7d7fe6b7aacaa6e6ef070c2e237/lib/Responsefile.mll#L96) in CompCert.

Do you know if the same routine works for clang? it looks a bit hairy if the needed quoting depends on the tool that will consume the response files.

**Comment by ghost** [comment]
Ah, if the quoting depends on the tool, I'm much less keen on going this way. It feels like we are opening a can of worms. Plus it's not even something we can decide at configure time since we can change the C compiler afterwards via `-cc`.

My original solution is less general, but at the end of the day no one has complained about this problem on systems other than Linux.

**Comment by xavierleroy** [comment]
I think Filename.quote is good for GCC and Clang, just like it is already for MSVC.  Will check.  Don't panic.

**Comment by bschommer** [comment]
> I think Filename.quote is good for GCC and Clang, just like it is already for MSVC. Will check. Don't panic.

Since Clang is compatible with GCC as well as MSVC it should support the same syntax. For CompCert we just needed another quoting mechanism for some commercial embedded compiler.

**Comment by ghost** [comment]
Haha, no panic. At the end of the day, if we can't find a clean solution at Jane Street we'd just stick a `LD_PRELOAD` to override the `system` library call. There is always a way :)

But obviously I prefer to fix this once and for all upstream.

**Comment by Khady** [comment]
> My original solution is less general, but at the end of the day no one has complained about this problem on systems other than Linux.

At Ahrefs we have a patch to use response files because we faced the problem on osx.

**Comment by aalekseyev** [comment]
Unfortunately, by fixing this problem at the boundary between OCaml and Linux, we only pushed it down "inside" gcc. Now it's the invocation of `collect2` by `gcc` that's failing, due to gcc passing its options via `COLLECT_GCC_OPTIONS` to `collect2`.

I'll try to construct a reproducer script.

**Comment by aalekseyev** [comment]
And here's a script that still fails for me:

```
#!/usr/bin/env bash

rm -rf reproduce-large-collect2-invocation
mkdir reproduce-large-collect2-invocation
cd reproduce-large-collect2-invocation

declare -a ocamlopt_cmdline

for x in {1..1200}; do
   dir=dir_with_100_long_name_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_$x
   mkdir "$dir"
   file=$dir/f_$x.ml
   echo 'Printf.printf "Hello world!\n"' > "$file"
   ocamlopt -c "$file"
   ocamlopt_cmdline+=(-I "$dir" f_$x.cmx)
done

ocamlopt "${ocamlopt_cmdline[@]}"
./a.out
```

That fails, at least with gcc 4.8.5 and with gcc 9.3.1.

Googling for this problem doesn't reveal too many hits, but I found Haskell-on-nix people encounter this: https://github.com/NixOS/nixpkgs/issues/41340

Which points to the gcc issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86030, which seems not fixed yet (it seems the expected fix is to use the response files for communication between gcc and collectd).

**Comment by nh2** [comment]
@aalekseyev Hi, i am the reporter of https://github.com/NixOS/nixpkgs/issues/41340.

There is only one good solution: Fix it in GCC.

If I started an Indiegogo or similar to build funding to do that, would Jane Street pitch in?

(Alternatively, if you decide to give it a shot yourselves, let me know! In either case, it would make for a pretty good blog post.)

**Comment by aalekseyev** [comment]
@nh2, I'm sure a contribution like that could be worth the money, but I don't know enough about the logistics or legal side to actually make something like that happen. @jeremiedimino should know more.

My guess would be that we won't be participating in such a crowdfunding, simply because I know of no such precedent.

As for fixing it ourselves, we are not suffering from this enough to dive into an unfamiliar codebase yet (and then backport the patch across many years of development), but as computers get bigger and software gets more bloated this may change.

As for "only one good solution", I'm not sure: from our perspective I think it would be a fine (or even great) solution to relax the limit in the kernel. Too bad this change probably can't make it upstream for one reason or another.
