### ISSUE TITLE
Confusing interaction between @tailcall and inlining

### ISSUE THREAD

**Issue by craigfe** [ocaml/ocaml#9510]
In the following example,
```ocaml
module A : sig end = struct
  let _ = fun () ->
    let f () =
      let rec aux k = if true then k () else (aux [@tailcall]) k in
      (aux [@tailcall]) (fun () -> ())
    in
    f (); ()
end
```

the second `[@tailcall]` annotation causes the program to be rejected:
```
File "example.ml", line 5, characters 6-38:
5 |       (aux [@tailcall]) (fun () -> ())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 51: expected tailcall
```

This happens due to a "used-once" inlining of `f`:

```bash
ᐅ ocamlopt.opt -dlambda example.ml
(let
  (A/80 =
     (seq
       (function param/86
         (seq
           (let (param/88 = 0a)
             (letrec
               (aux/82
                  (function k/83
                    (if 1a (apply k/83 0a) (apply aux/82 k/83 @tailcall))))
               (apply aux/82 (function param/84 0a) @tailcall)))
           0a))
       (makeblock 0)))
  (seq (setfield_ptr(root-init) 0 (global IO!) A/80) 0a))
```

If `f` is applied twice, or defined with `[@local never]`, the program is accepted.

This behaviour leads to inconsistencies according to the specific compiler being used. With a modified example,

```ocaml
module A : sig end = struct
  let f () =
    let rec aux k = if true then k () else (aux [@tailcall]) k in
    (aux [@tailcall]) (fun () -> ())

  let () = f ()
end
```

the code is accepted by `ocamlopt` (which does not inline in this case), but rejected by `ocamlc` and Flambda (which do inline).

CC: @mshinwell, @lthls.

**Comment by gasche** [comment]
I think that in general we cannot expect `@tailcall` to warn in exactly the same way in all possible development environments. For example, in some cases being a tailcall or not depends on the calling-convention of the architecture; and I think that the intent is really to get a warning when compiling on a machine where the call is not a tailcall (because the annotation indicates that we rely on it being a tailcall).

That said, in this specific case I think that we have a usability bug: it is correct to use `aux [@tailcall]` here because it means a tailcall relative to the surrounding function, not to the caller context (after inlining). When inlining, we should update the tailcallness assumption accordingly: they should only be preserved if the inlining point is itself in tail position in its own context.

Finally: note that wrong `@tailcall` is a warning by default, not an error, so if you get a build failure from this you are using a modified warning configuration. (When deciding to not make this an error by default, the potential fragility of the current check is something that was considered.)

**Comment by mshinwell** [comment]
I spent a fair while looking at this example earlier.  As far as I could see the warning is only emitted by checks on the `Lambda` code.  This surprised me; I thought it would have been done much later, in the backend.  So I'm not sure the architectural concerns are relevant with respect to the current implementation.  (This also makes me wonder how valuable this attribute actually is.)  Am I wrong about this?

@gasche You say that "it means" above.  However it isn't clear to me that we have a sufficiently precise statement of what this attribute is supposed to mean, such that a judgement like this can be made.  (For example see what the reference manual says: https://ocaml.org/releases/4.10/htmlman/attributes.html)

**Comment by gasche** [comment]
Yes, I believe the current check is in `lambda/simplif.ml`, so most forms of inlining will not be taken into account to decide whether to warn (but some of the other rewrites in simplif may be).

I worked on this recently in the context of TRMC (#181), a reimplementation of that, and some buildup PRs ( #9442 is pure refactoring and still looking for approvers, if they are any takers ).

I would be happy to contribute to clarification on the intent and meaning of the attribute. To me it seems clear (even obvious) that the attribute is relative to the function in which it is used -- I don't see any other sensible choice. The question is rather of what we call "being a tailcall" (is it a criterion on a source-level operational semantics, or something about "pushing a stack frame" in the compiled program, or something in between), but again this does not come into play in the current issue. I just thought it would be useful to point out that yes, in general the warning may be system-dependent (although its current implementation currently is not / should not).

**Comment by lthls** [comment]
I'm trying to see if I can make a patch for this issue (the bad interaction between `[@tailcall]` and the local function transformation).

My first idea is that calls in tail position in the function being transformed can be stripped of their `[@tailcall]` annotations (if any), because the context in which they were supposed to be tail disappears. This would solve the problem reported here, and since recursive functions are never considered for the local function transformation I assume that this would not break anybody's expectations.
However, I'm worried about the following example:
```
let log g x =
  do_something ();
  (g[@tailcall]) x
in
let rec f x =
  (log[@tailcall]) f x;
  ()
```
In this example, with trunk we get a warning on the call to `g`, which is not ideal, but with my proposal we would get no warning at all, which is worse in my opinion.

So I looked at a second possibility: moving the `[@tailcall]` check before any simplification occurs, to prevent these simplifications from erasing the relevant attributes. This emits a reasonable warning for my example above, complaining that the call to `log` isn't a tail call. However, this seems to go against the idea which #10426 is based on, that we want the warnings to be as precise as possible.

I've also considered emitting warnings for the removed applications during the local function simplification. Combined with my first idea, this should give us the best end result, but at the cost of some amount of code duplication.

I'll wait until #10426 is resolved before making a PR, but I'd welcome comments on my proposals.
