### ISSUE TITLE
Architecture-specific command-line options are not exposed through OCAMLPARAM.

### ISSUE THREAD

**Issue by nwf** [ocaml/ocaml#9549]
OCAMLPARAM is parsed using a bespoke parser in `driver/compenv.ml` while command line arguments are parsed using the machinery in `utils/clflags.ml` and its dependencies, with the architecture-specific commands coming in from `driver/optmain.ml`.

Ideally, `OCAMLPARAM` would reuse the same machinery as the command line.

This is especially irritating to me, right now, because I cannot easily pass `-flarge-toc` while building a variety of packages through `opam` on my ppc64le workstation.  It's very frustrating how many layers exist and are all fighting me in getting that one flag set!

**Comment by dra27** [comment]
Indeed, `$(ocamlopt -where)/ocaml_compiler_internal_params` doesn't help either, as that's the same machinery. The best workaround at the moment, as you say you're using opam, would be to add `["sed" "-i" "-e" "s/big_toc =.*/ref true/" "asmcomp/power/arch.ml"]` either before or after the `configure` call in the recipe for the ocaml-base-compiler or ocaml-variants package you are using and at least change the default for the switch to `-flarge-toc`.

**Comment by dra27** [comment]
The "obvious" fix is that `Arch.command_line_options` should be extended to include details of how/what to parse from `OCAMLPARAM` or `ocaml_compiler_internal_params` which `Optmain` can then pass through to `Compenv`. For `ocaml_compiler_internal_params` this is fine, but from a UX perspective, it's not great that `large-toc` in `OCAMLPARAM` will cause a warning about the option not being _recognised_ if applied to other backends, as opposed to _invalid_. It's also not great that `ocamlopt -help` (and the manual) contain no or little reference to backend-specific options. At present we have:

- `-fPIC`, `-fno-PIC` (amd64, arm and s390x **only documented for amd64 and only in the manual**)
- `-farch <arch>` (arm **only in the manpage for ocamlopt**)
- `-ffpu <fpu>` (arm **only in the manpage for ocamlopt**)
- `-fthumb`, `-fno-thumb` (arm  **only in the manpage for ocamlopt**)
- `-ffast-math` (i386 **only in the manual for ocamlopt**)
- `-flarge-toc` (power **completely undocumented**)

The documentation is somewhat haphazard for these. I would rather propose that backend-specific options should be defined, with their documentation, in the driver itself and _enabled_ by `arch.ml`. That would allow `ocamlopt -help` always to list all its options all the time. `ocamlopt -help` can indicate whether the option is *available* or not - that means that the only thing I'm proposing embedding in the driver is the name and details of the option, **not** the architectures it applies to (which is still taken from `arch.ml`). This would also allow `Compenv` to report `large-toc` read from `OCAMLPARAM` as a warning that it's not available, rather than not recognised (for `ocaml_compiler_internal_params`, having an unavailable option should probably be a hard error?).

I don't think the second option is particularly more work than the first - I'd be happy to hack on it, given some consensus on which solution to do.

**Comment by nwf** [comment]
FWIW, I worked around it by exploiting $PATH to shim a shell script wrapper around `ocamlopt` (and `ocamlopt.opt`, since some tools looked for that specifically, and a bunch of other `ocaml` tools since not everyone honored PATH the way they should have, instead assuming that all `ocaml*` programs lived in the same directory).

**Comment by xavierleroy** [comment]
For the record: I am not very happy with the handling of architecture-specific options, and definitely unhappy with the handling of OCAMLPARAM, but let's not rush a full refactoring of these aspects.

What we could do right now is to make `-flarge-toc` the default for PowerPC.  It will generate even bigger and even slower code, but I gather from @nwf and others that a significant number of OPAM packages will simply not compile in the "small TOC" model.

**Comment by dra27** [comment]
I wasn't rushing 🙂 Is it safe enough to change that default for the next 4.11 alpha release? There is only `-flarge-toc` - if the default is changed, should we also introduce either `-fnolarge-toc` or the possibly better named `-fsmall-toc`?

**Comment by xavierleroy** [comment]
`-fsmall-toc` is fine.  

The choice of TOC model (small vs big) has a very localized effect:
https://github.com/ocaml/ocaml/blob/c920ea142b9f9cc0c0eaca6903f0e782da1036d1/asmcomp/power/emit.mlp#L213-L218
and
https://github.com/ocaml/ocaml/blob/c920ea142b9f9cc0c0eaca6903f0e782da1036d1/asmcomp/power/emit.mlp#L605-L610
So, my hope is that the big TOC model can be adequately tested by our usual CI plus some tests with OPAM.

**Comment by dra27** [comment]
The behaviour in 4.11 should make `-flarge-toc` the default and there is now `-fsmall-toc`.

@nwf - if you are able to test the next alpha release of 4.11 which includes this, that would be great, thanks!

**Comment by dra27** [comment]
I'm going to leave the issue open as the underlying problem with the driver and `OCAMLPARAM` hasn't yet been addressed.

**Comment by nwf** [comment]
@dra27 I should be able to. :)
