### ISSUE TITLE
Typechecking bug in presence of constraints and polymorphic types

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#9603]
The relaxing of the handling of polymorphic type in #1132 has unearthed a bug in the handling of polymorphic type unification when constraints are involved.
For example, the following code fails
```ocaml
type 'p pair = 'a * 'b constraint 'p = < left:'a; right:'b>
let foo : 
  < m : 'left 'right. <left:'left; right:'right> pair > 
   -> < m : 'left 'right. <left:'left; right:'right> pair >
= fun x -> x
```
for OCaml version starting from at least version 4.01 .

With the heavier reliance on explicitly polymorphic type unification, the following code fails starting with 4.11 : 
```ocaml
type 'p pair = 'a * 'b constraint 'p = < left:'a; right:'b>
let error: 'left 'right.
  <left:'left; right:'right> pair -> <left:'right; right:'left> pair =
  fun (x,y) -> (y,x)
```
Note that this failure has been kind of observed in the wild, since it affects at least of my own library (and one that is not completely a toy): https://github.com/Octachron/orec/blob/master/src/namespace.ml#L307.

**Comment by garrigue** [comment]
Looking again at this problem (using ocamldebug), I see know that this is a known one: since we do not allow unifying normal type variables with types containing universal type variables, and since constrained type parameters are instantiated through unification of types containing normal type variables, one cannot expand a type containing free universal type variables in a constrained parameter position.

I'm going to look for a solution for this long standing limitation, but it means that we cannot rely on the unification of types containing universal type variables for the type checking of polymorphic recursion. We need another way to do that, such as the one used before.

@lpw25 Sorry for not recalling this limitation when I reviewed your PR.

**Comment by garrigue** [comment]
@lpw25 My conclusion for the time being is that one shouldn't use unification of first-class polymorphic types for anything other than polymorphic methods.

`polyfy`/`reify_univars` is only used in two places.
* #1132: actually, I'm not completely sure of why unification is needed them, since the type bodies are already unified, and there is a check that the type is polymorphic enough before that. I remember something about types possibly escaping, but I see no examples in the test suite. The only change in the test suite is a subtle case with polymorphic variants, which may a different solution.
* `Type.enrich_typedecl` uses `mcomp` rather than unify, and I'm not sure why it does that.

For #1132, we need either to fix the problem, or revert it, because the extra power doesn't seem to justify breaking existing programs.

**Comment by lpw25** [comment]
> I'm not completely sure of why unification is needed them

I'd have to check but I think you need it for things like ensuring that `'a 'b. 'a -> 'b` isn't implemented as `'a. 'a -> 'a`.

> we need either to fix the problem, or revert it,

I can see relatively quick fixes that I think would work for 4.11. I would like to try to do those before we revert. (I would have done it on Wednesday but something urgent came up, I should have time this evening).

More long term I think that we should try to get rid of occur_univar and use levels and scopes to prevent escape of univars. That is too large of a change for 4.11 but I think that we should aim to have a single mechanism for detecting scope escape long term to improve maintainability.

**Comment by garrigue** [comment]
I have done a fix in #9617. Of course only polymorphic recursion.

**Comment by garrigue** [comment]
> More long term I think that we should try to get rid of occur_univar and use levels and scopes to prevent escape of univars. That is too large of a change for 4.11 but I think that we should aim to have a single mechanism for detecting scope escape long term to improve maintainability.

That would be nice, but it can be tricky. Remember that we can have first-class polymorphism in recursive types. So we are talking of scopes in cyclic graphs, which cannot be structural. On the other hand, this may help to explain the regularity restriction.

**Comment by lpw25** [comment]
> That would be nice, but it can be tricky. Remember that we can have first-class polymorphism in recursive types. So we are talking of scopes in cyclic graphs, which cannot be structural. On the other hand, this may help to explain the regularity restriction.

To be sure that I understand the difficulty, do you basically mean that it is hard to make sure that:
```ocaml
< m : 'a . 'a -> 'b > as 'b
```
unifies with
```ocaml
< m : 'a . 'a -> < m : 'b . 'b -> 'c> > as 'c
```
but not also with:
```ocaml
< m : 'a . 'a -> < m : 'b . 'a -> 'c> > as 'c
```

**Comment by garrigue** [comment]
Yes, this kind of situations need to be handled properly.

**Comment by garrigue** [comment]
François Pottier has a paper on a closely related subject:
http://gallium.inria.fr/~fpottier/publis/gauthier-fpottier-icfp04.pdf

**Comment by Octachron** [comment]
Since the specific issue that was hindering the 4.11.0 release is fixed, I am closing the issue.
