### ISSUE TITLE
Compiling OCaml under the Windows Subsystem for Linux.

### ISSUE THREAD

**Issue by MisterDA** [ocaml/ocaml#9605]
I have tried to compile OCaml 4.10.0 and OCaml 4.11 (e3b70486e5e4d9ff3f827b7635a61172a7f98763 as the
time of writing) under the Windows Subsystem for Linux, using MSVC64
2019 and mingw-w64.

I know that Cygwin is the supported build platform for Windows, but I
figure I’d give it a shot, considering that WSL is the new trend. I’m
trying to see what happens if one replaces Cygwin with WSL.

WSL has the "issue" that it considers that `prog.exe` and `prog` are
two different files when calling, contrary to Cygwin that resolves
`prog` to `prog.exe`. Also, creating a symlink to an executable and
executing the symlink does not work, leading to rather contrived
scripts as we’ll see below.

## MSVC64 setup

First, open the "x64 Native Tools Command Prompt for VS 2019". Then,
start `wsl.exe`. Setup msvc64 like this:

```sh
mkdir ~/bin
# Tune to your install
for file in "/mnt/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/HostX64/x64/"*.exe; do
  filename="$(basename -- "$file")"
  cmd=~/bin/"${filename%%.*}"
  cat > "$cmd" <<EOF
#!/bin/sh
exec "$file" "\$@"
EOF
  chmod +x "$cmd"
done
export PATH="$HOME/bin:$PATH"
```

## Building OCaml

```sh
ocaml_version=e3b70486e5e4d9ff3f827b7635a61172a7f98763
flexdll_version=bd636def70d941674275b2f4b6c13a34ba23f9c9
curl -L https://github.com/ocaml/ocaml/archive/$ocaml_version.tar.gz | tar xz
curl -L https://github.com/alainfrisch/flexdll/archive/$flexdll_version.tar.gz | tar xz
cp -r flexdll-$flexdll_version/* ocaml-$ocaml_version/flexdll

cd ocaml-$ocaml_version

./configure --host=x86_64-pc-windows # for msvc64
./configure --host=x86_64-w64-mingw32 # for mingw-w64

make flexdll
```
```
make[1]: Leaving directory '/home/user/ocaml-e3b70486e5e4d9ff3f827b7635a61172a7f98763/runtime'
cp runtime/ocamlrun.exe boot/ocamlrun.exe
make -C stdlib COMPILER=../boot/ocamlc \
                  stdlib.cma std_exit.cmo camlheader
make[1]: Entering directory '/home/user/ocaml-e3b70486e5e4d9ff3f827b7635a61172a7f98763/stdlib'
../boot/ocamlrun ../boot/ocamlc -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -safe-string -strict-formats  -nopervasives -c camlinternalFormatBasics.mli
make[1]: ../boot/ocamlrun: Command not found
Makefile:206: recipe for target 'camlinternalFormatBasics.cmi' failed
make[1]: *** [camlinternalFormatBasics.cmi] Error 127
```

With msvc64, the file `boot/ocamlrun.exe` does not have the executable
bit set.

As a workaround, I’m creating a new file:

```sh
cat <<'EOF' > boot/ocamlrun
#!/bin/bash
exec "${0}.exe" "$@"
EOF

chmod +x boot/ocamlrun
chmod +x boot/ocamlrun.exe # with msvc64
```

Having applied the workaround above, let’s retry:

```
$ make flexdll

# …

../boot/ocamlrun ../boot/ocamlc -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -safe-string -strict-formats  -nopervasives -no-alias-deps -w -49  -pp "$AWK -f ./expand_module_aliases.awk" -c stdlib.mli
'\\wsl$\Ubuntu\home\user\ocaml-e3b70486e5e4d9ff3f827b7635a61172a7f98763\stdlib'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'gawk' is not recognized as an internal or external command,
operable program or batch file.
File "\wsl$\Ubuntu\home\user\ocaml-e3b70486e5e4d9ff3f827b7635a61172a7f98763\stdlib\stdlib.mli", line 1:
Error: Error while running external preprocessor
Command line: gawk -f ./expand_module_aliases.awk "stdlib.mli" > C:\Users\User\AppData\Local\Temp\ocamlppd32321

Makefile:206: recipe for target 'stdlib.cmi' failed
```

gawk is installed by default in the WSL, and the error messages come
from a `cmd.exe`. My conclusion is that external preprocessors are
called in cmd.exe and not in an unix shell. That’s weird, and that’s
bad.

**Comment by nojb** [comment]
@dra27

**Comment by dra27** [comment]
Newish trend 🙂 I've dusted off my patches... these were originally written for either OCaml 4.03 or 4.04 in 2016 when WSL was first released, I shifted them forwards to an early dev version of 4.08 (pre-autoconf) in 2018 when I had a brief foray into getting OCaml on Windows 10 ARM64 working. They work for msvc and msvc64:

From either x86 or x64 Tools command prompt:
```sh
git clone https://github.com/dra27/ocaml.git -b wsl-build
cd ocaml
git submodule update --init
cd flexdll
git remote add -f dra27 https://github.com/dra27/flexdll.git
git checkout dra27/wsl-build
cd ..
bash
cd /mnt/c/location-of-your-clone
cp config/s-nt.h config/s.h
cp config/m-nt.h config/m.h
cp config/Makefile.msvc64 config/Makefile
make -j flexdll
make -j world.opt
```
(copy `config/Makefile.msvc` for the 32-bit build). The testsuite does not work (I was part-way through that, looking at the state of the working tree on the VM I took this from!), but the compiler fully builds.

To answer your specific questions so far:
- I worked around the `AWK` problem by explicitly generating the files, rather than using `-pp`
- I think the chmod +x problem is because you're building in a virtualised home directory - use a normal directory (e.g. `C:\Users\you\Documents\ocaml`) and then `/mnt/c/Users/you/Documents/ocaml` and I expect you'll find the default permissions will just work).

**Comment by dra27** [comment]
In 2016, `ocamltest` was in progress, but virtually the entire testsuite was still using a complex array of `Makefile`s. My findings with WSL1 back then was that the main build was faster, but only by a bit, but the testsuite was considerably faster (like 4 or 5 minutes quicker), because WSL1 has an efficient implementation of `fork` which Cygwin has to emulate. I would expect the difference in performance to have narrowed, therefore (based on this and other experiments in Dune, Cygwin gets more blame than it deserves - for reasons we'll one day get to the bottom of, OCaml programs on Windows are just slower, including the compiler). The patches weren't too hideous, with one exception - it was really difficult to pass environment variables from `make` back to the process (so `OCAML_FLEXLINK` and others were hurting). However, I logged an issue in WSL for that, and eventually (for that, and other users!), `WSLENV` was added which these 2018 revised patches started to use.

Calling from WSL -> native is pretty easy. Some shenanigans if you want environment variables to persist, but otherwise it's just a matter of ensuring everything ends with `.exe`. Going the other way is hard (see the hack in `ocamldoc/Makefile` to call `remove_DEBUG`) as you have to wrap everything in a script. I have a feeling that `C:\Windows\System32\bash -c` certainly didn't work then (it's not a real bash executable, but a shim which launches the LXSS subsystem).

This is definitely worth working on, but there are several things which for the time being block switching it to be the main build system:
- CI support is hard (WSL requires Windows 10 or Windows Server 2019) and it also drops support for developers on older versions of Desktop Windows (although now that Windows 7 is out of support, that should be virtually a non-issue as I have no idea why anyone would use Windows 8.1 instead of Windows 10...)
- We still need to support the Cygwin build of OCaml for other reasons (well, I think we more normally call them users!)
- For the mingw-w64 ports of OCaml, it feels odd to jump through _a lot_ of hoops to build a native Windows ocamlopt which calls into a VM to invoke a C cross-compiler and then pull those artefacts back out to native Windows... the WSL version will work much more easily when cross-compilation lands in the compiler, and I anticipate it will be easier to make finding MSVC more of an exception. Indeed, I anticipate the mingw-w64 port existing entirely through cross-compilation only once we have first class support for it (it makes much more sense to have a Cygwin-compiled `ocamlopt` which always understands its symlinks and the like than a native `ocamlopt` which just about manages to invoke `x86_64-w64-mingw32-as` most of the time)

**Comment by dra27** [comment]
There are steps towards this becoming a reality with my recent work to excise scripts from the build system.

**Comment by damiendoligez** [comment]
@dra27 do you want to reopen this?

**Comment by dra27** [comment]
I had been debating leaving it closed, but here's an update on the status instead: this is most likely to land as part of first class cross-compilation: so, within WSL, being able to run `./configure --build=x86_64-pc-linux-gnu --host=x86_64-pc-windows`. The "no-scripting" work of mine is slowly edging forwards, now that the sequential glaciation is over!
