### ISSUE TITLE
Dynlink is very slow on OSX

### ISSUE THREAD

**Issue by ppedrot** [ocaml/ocaml#9705]
This is an issue that has been discovered through the native compilation feature of Coq in https://github.com/coq/coq/issues/11178.

It seems that dynlinking on OSX is orders of magnitude slower than on Linux. The original reporter mentioned using OCaml 4.09.0, but the problem seems to be appearing haphazardly depending on the exact configuration.

(I am sorry, but I don't have an OSX machine myself to get a reproducible example.)

**Comment by xavierleroy** [comment]
I read the very long discussion and am not sure what to conclude from it, in particular whether the finger should be pointed at Dynlink like you do here.

At any rate, OCaml uses the standard C interface [ `dlopen`](https://pubs.opengroup.org/onlinepubs/009695399/functions/dlopen.html) to perform dynamic loading of code, both under Linux and under macOS, so if macOS's implementation of `dlopen` is slower than that of Linux, there is nothing we can do about it.

I'm not aware of differences between OCaml-on-macOS and OCaml-on-Linux that would impact dynamic loading time in a major way.

**Comment by xavierleroy** [comment]
One thing to keep in mind: antivirus software on Windows and on macOS has been known to degrade the performance of many operations (as simple as opening a file) dramatically.  So maybe your users are just measuring the differences between macOS + nosy antivirus and macOS + no or better antivirus.

**Comment by m-schmidt** [comment]
Just a guess, but Catalina does notarization checks (by contacting Apple's servers) when code is run the first time. Perhaps one should disable System Integrity Protection to test whether the slowdowns are then gone.

[Catalina Slow by Design](https://sigpipe.macromates.com/2020/macos-catalina-slow-by-design/)

**Comment by ppedrot** [comment]
cc @julesjacobs @llelf

**Comment by dbuenzli** [comment]
@m-schmidt thanks for that interesting observation. 

I had noticed some of the executables I'd create would run slow or hang a bit on the *first* invocation. 

And indeed if you keep an eye on your console and execute a simple  

```
> echo 'let () = print_endline "Ho!"' > a.ml
> ocamlopt a.ml                            
> ./a.out 
```
You'll see a bunch of `syspolicyd` daemon entries related to that showing up in the console. 

A few random readings on the internet pointed to a checkbox to tick in the System Preferences: 

<img width="780" alt="security-policy" src="https://user-images.githubusercontent.com/485596/85631088-2b2cb300-b675-11ea-8784-dcc39b7e8672.png">

Ticking the box, the syspolicyd messages I mentioned no longer show in the console when I run the executable for the first time in Terminal.app.

That still happens though if I run `ocamlopt a.ml && ./a.out` from the compilation mode of Emacs.app. I tried to add the app to the list but it doesn't seem to work (maybe related to how processes are spawned by emacs ?). It's still something you could try with the COQIde app if that turns out to be the problem. 

Well at least my terminal runs are a bit more snappy now. Thanks !

**Comment by llelf** [comment]
> Just a guess, but Catalina does notarization checks (by contacting Apple's servers) when code is run the first time

My slow  results were from tests on High Sierra. And IIRC I even signed `coqc` binary to make sure (but I'll try to re-run and post results again).
