### ISSUE TITLE
Recompacting the heap can segfault with best-fit

### ISSUE THREAD

**Issue by lpw25** [ocaml/ocaml#9736]
When compaction has finished rearranging all the blocks into the earliest chunks, it has to add any left over space in the remaining chunks to the free list. Which it does with the call to `caml_make_free_blocks` currently on line 423 of compact.c. Whilst not generally guaranteed by calls to this function, historically this would always produce `Caml_blue` blocks because they could not be merged with anything else around them. With best-fit however, these blocks make now be `Caml_white` if they are less than 16 words.

Making the new free blocks `Caml_white` is not normally a problem, because they will only be seen by `sweep_slice` which does not care about their contents. However, very rarely a "recompaction" is triggered, which immediately does a second compaction. Compaction scans `Caml_white` blocks looking for pointers to reverse. Since the data in these `Caml_white` blocks is essentially arbitrary this can easily segfault.

I'm not sure what the best fix is. The blocks going onto the freelist could possibly be given a no scan tag. The compactor could possibly treat `Caml_white` blocks as free. Either or those seems fine to me, but I'm not confident enough in my knowledge of all the invariants in the GC to make the decision.

**Comment by lpw25** [comment]
cc @damiendoligez

**Comment by damiendoligez** [comment]
Nice catch, but I don't think it can be triggered on 64-bit. Here's why:
- recompaction only happens when there is a single heap chunk and "too much" free space (i.e. much more than mandated by the `space_overhead` parameter).
- on a 64-bit architecture, the free space will be a single block, much larger than the 16-field limit, so it will be blue.

Still, the bug could trigger on 32-bit. Moreover, I would like to maintain the property that compaction can be done whenever the major GC is idle (i.e. at the end of any sweep phase) and it is broken by this remnant business. I'll submit a PR soon.

**Comment by lpw25** [comment]
To be clear, I found this bug by it happening on a 64bit machine. I think that recompaction can happen with more than one heap chunk, and indeed in the case where I saw this bug recompaction was triggered with 3 heap chunks. The small block was not in the large chunk with left-over space but in one of the smaller chunks.

**Comment by damiendoligez** [comment]
Oh that's right I didn't think of this case.
