### ISSUE TITLE
use of lookup vs jump table with match depends on whether there is a duplicate case

### ISSUE THREAD

**Issue by markghayden** [ocaml/ocaml#9741]
It appears that compilation of simple switch from constant to constant has different compilation based on whether any results are duplicates.

With no duplicate results, the code compiles as simple lookup table, which is the preferred result.  With any duplicates, the code compiles as a jump table, which is a poorer result, both in compiled code side and execution speed.

I believe the "correct" (preferred) compilation should be that both cases compile to use a lookup table.

This was done with ocaml 4.10.0

```
type foo =
  | A
  | B
  | C
  | D
  | E
  | F
;;

(* lookup table *)
let bar0 = function
  | A -> B
  | B -> C
  | C -> D
  | D -> E
  | E -> F
  | F -> A
;;

(* jump table *)
let bar1 = function
  | A -> B
  | B -> C
  | C -> D
  | D -> E
  | E -> F
  | F -> F				(* duplicate of E *)
;;
```
Here is the CMM (-dcmm): 

```
(data "camlMatch__1": int 3 int 5 int 7 int 9 int 11 int 1)
(data global "camlMatch__gc_roots" "camlMatch__gc_roots": int 0)
(function{match.ml:13,11-85} camlMatch__bar0_8 (param/99: val)
 (load_mut val (+a (+a "camlMatch__1" (<< (or param/99 1) 2)) -4)))

(function{match.ml:23,11-85} camlMatch__bar1_21 (param/106: val)
 (catch
   (switch (>>s param/106 1) 
   case 0: 3a
   case 1: 5a
   case 2: 7a
   case 3: 9a
   case 4:case 5: (exit 2))
 with(2) 11a))
```

And the assembly:

```
_camlMatch__bar0_8:
	.cfi_startproc
L100:
	orq	$1, %rax
	movq	_camlMatch__1@GOTPCREL(%rip), %rbx
	movq	-4(%rbx,%rax,4), %rax
	ret
	.cfi_endproc
	.text
	.align	4
	.globl	_camlMatch__bar1_21
_camlMatch__bar1_21:
	.cfi_startproc
L106:
	sarq	$1, %rax
	leaq	L107(%rip), %rdx
	movslq	(%rdx,%rax,4), %rax
	addq	%rax, %rdx
	jmp	*%rdx
	.align	2
L107:
	.long	L105 - L107
	.long	L104 - L107
	.long	L103 - L107
	.long	L102 - L107
	.long	L101 - L107
	.long	L101 - L107
	.text
	.align	2
L105:
	movl	$3, %eax
	ret
	.align	2
L104:
	movl	$5, %eax
	ret
	.align	2
L103:
	movl	$7, %eax
	ret
	.align	2
L102:
	movl	$9, %eax
	ret
	.align	2
L101:
	movl	$11, %eax
	ret
```

**Comment by stedolan** [comment]
The two functions compile to the following Lambda:
```
(bar0/87 =
       (function param/89
         (switch* param/89
          case int 0: 1a
          case int 1: 2a
          case int 2: 3a
          case int 3: 4a
          case int 4: 5a
          case int 5: 0a)))
(bar1/90 =
       (function param/92
         (catch
           (switch* param/92
            case int 0: 1a
            case int 1: 2a
            case int 2: 3a
            case int 3: 4a
            case int 4: (exit 1)
            case int 5: (exit 1))
          with (1) 5a)))
```
The code for detecting duplicate expressions in `switch.ml` has detected that two cases of `bar1` are identical, and therefore has introduced a block and a jump for the common code. This defeats the later optimisation that optimises switches containing only constants.

The quickest fix would be to disable the sharing when the code being shared is very small. Introducing a jump to avoid sharing an integer constant is probably not worth it.

An alternative and possibly better fix would be to move the constant-table optimisation earlier in the compiler, and have `switch.ml` detect and build constant tables itself rather than building jump tables that are later optimised. (I think this approach would also fix a related issue, which is that the optimisation does not apply to small matches)

**Comment by gasche** [comment]
Disabling sharing for small constants could make sense (but see below). I looked at where to do this in the code, it is not obvious (the code does not check for equality to share after the fact, it is designed to compute a canonical "key" for each action). The best answer I found is in `Lambda.make_key`, raise the `Not_simple` opt-out in some constant cases. 

Note: there is a small inconsistency in this `Lambda.make_key` function, which opt-outs of sharing for constants in the `Const_base (Const_string _)` case because of mutability, and should also opt out in the `Const_float_array` case. We should probably fix this.

That said, I would be worried about disabling sharing of constants, because sometimes constants can be shared many times. Consider the following:

```
(function
|  'a' | 'e' | 'i' | 'o' | 'u' | 'y' -> true
| _ -> false)

(function
| 'a'..'z' | 'A'..'Z' | '0'..'9' -> true
| _ -> false)
```

Disabling sharing in those cases could result in large code blowups.

**Comment by lthls** [comment]
My take on this issue:
- When the switch cannot be compiled to a constant table, sharing constants is better. In the native backend, each lost sharing opportunity will cost two additional instructions: moving the constant to the appropriate register, then jumping to the appropriate handler. I think the cost is similar in bytecode.
- But constant tables are better than jump tables, so it would make sense to make `Switch` aware of that and disable sharing if all actions are constant (in native mode only, I don't think bytecode can optimise constant switches).

One other possibility would be to try to detect constant switches during `Simplif` (`simplify_exits` can already replace the exits by their handlers, all that's missing is a way to detect when it's beneficial).

> Note: there is a small inconsistency in this `Lambda.make_key` function, which opt-outs of sharing for constants in the `Const_base (Const_string _)` case because of mutability, and should also opt out in the `Const_float_array` case. We should probably fix this.

In theory, you're right; but in practice each `Const_float_array` is fed directly into a `Pduparray` primitive. As long as that invariant holds it's fine to share the constants.

**Comment by gasche** [comment]
My own foray into this issue (also motivated by the stale bot) led to a small, mostly-unrelated refactoring/cleanup/documentation PR #10500.

**Comment by gasche** [comment]
>  it would make sense to make Switch [...] disable sharing if all actions are constant (in native mode only, I don't think bytecode can optimise constant switches).

When I read your comment I was not sure whether you meant that bytecode does not currently optimize constant switches (which is true, the optimization is in `asmcomp/cmm_helper.ml -> make_switch -> make_table_lookup`), or that the bytecode lacks expressiveness to make this optimization worthwhile (for example because creating constant tables is not compact enough).

I looked at this and I think that we could in fact extend the constant-switch (and the affine-switch) optimization to bytecode, and we would get benefits there. Improving bytecode compilation does not matter much, but moving the logic earlier in the shared pipeline would still make a lot of sense if it can simplify things.

Here is how I ran this thought experiment:

```
type t = A | C | D

let with_match t =
  match t with
  | A -> 'A'
  | C -> 'C'
  | D -> 'D'

let table = [| 'A'; 'C'; 'D' |]
let with_table t =
  Array.unsafe_get
    table
    (match t with
     | A -> 0
     | C -> 1
     | D -> 2
    )

let with_obj_table t =
  Array.unsafe_get
    table
    (Obj.magic t : int)
```

With `ocamlopt`, these three functions generate almost exactly the same code, thanks to the constant-switch optimization for `with_match` and the affine-switch optimization for `with_table`. (Nitpick: The -dcmm output for `with_match` looks slightly worse than the other two, with two chained addition operations, but on x86_64 the assembly of `with_match` and `with_table_obj` are identical, probably due to addressing mode magic, and the one of `with_table` is slightly worse.)

With `ocamlc -dinstr`, currently `with_match` gives

```
L3:	acc 0
	switch 7 6 5/
L7:	const 'A'
	return 1
L6:	const 'C'
	return 1
L5:	const 'D'
	return 1
```

while `with_table` and `with_table_obj` share the constant table construction code

```
	push
	const 'D'
	push
	const 'C'
	push
	const 'A'
	makeblock 3, 0
	push
```

and `with_table` gives

```
L2:	acc 0
	switch 11 10 9/
L11:	const 0
	branch L8
L10:	const 1
	branch L8
L9:	const 2
	branch L8
L8:	push
	envacc 2
	getvectitem
	return 1
```

but `with_table_opt` gives

```
L1:	acc 0
	push
	envacc 2
	getvectitem
	return 1
```

My take-away is that if we used the `with_table_obj` code-generation strategy to optimize the `with_match` code in bytecode (or if we also implemented affine-switch optimization), we would get some benefits for both performance (`pushenvacc; getitem`, against `switch; const` and, in the non-tail case, a jump) and code size (building the array is a sequence of `pushconst`, more compact than the switch + `const; branch` sequence in each case).

**Comment by gasche** [comment]
I spent a bit of time looking at the code today, inspired by @lthls's comments. In the short run, we don't have to do anything! In the long run, I think that it would be nice to have the constant-table and affine-table logic integrated at the level of the "switcher" (`lambda/switch.ml` functors and its users), typically at the level of the `make_switch` function of the `Switch.Make` functor argument -- the logic could either be implemented inside Switch.Make so shared by all callers, or could be provided at functor-application time by the implementation of `make_switch` in the functor argument.

However, this plan is thwarted right now by the fact that the switch-compilation logic in `Switch.Make` and the duplication-avoidance logic in `Switch.Store` are not aware of each other: they are implemented as separate functions that provide orthogonal services. `Store` is used in other, non-switch parts of the code generation (typically `make_test_sequence` in lambda/matching.ml); and `Switch.Make` assumes an abstract type of action, unaware that these actions are shared and unable to "see" through exits that would be introduced by sharing.

I would see two possible directions ahead if we wanted to do this:
- Let `Switch.Make` ask whether its argument is "in fact a constant", for example by revealing that its argument is always using a "store", and enrich store operations to check for constantness. (We would need even more if we wanted to handle affine switches as well.)
- Drop the separation between Switch.Store and Switch.Make, making the same code in charge of both aspects; in particular we could add "code generation for sparse switches by a dichotomy of tests" as a feature of Switch.Make to remove this separate use-case of Switch.Store.

(Again, none of this is urgent. For me it was mostly an excuse to re-learn about Switch code generation.)
