### ISSUE TITLE
Config variable for memprof in 4.11

### ISSUE THREAD

**Issue by Gbury** [ocaml/ocaml#9769]
While trying out 11.0's beta and playing with some conditional building for things relying on memprof, I thougt it would be useful if `ocamlc -config` had a line specifying whether memprof is available. Of course matching on ocaml's version also allows one to determine whether memprof is there or not, and memprof is not something that can be turned on or off, but I wondered if a discussion about that had taken place.

**Comment by dra27** [comment]
I don't _think_ we have any other things in `ocamlc -config` which aren't actually configurable. Given that you can't turn off statmemprof, it does feel a bit odd to me to include it?

**Comment by dra27** [comment]
(I don't think there has been any discussion, given that statmemprof is simply a feature of 4.11)

**Comment by jhjourdan** [comment]
I have no problem with doing so, but I still have a concern: recall that, as explained in the module `Gc`, the API is currently experimental since it evolved quite a bit during the development of memprof.

Therefore, if you have a project which depends on the current API of memprof, you'd better check the version of OCaml rather than a config flag.
