### ISSUE TITLE
4.11 beta3+flambda: stack overflow when compiling uunf

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/ocaml#9839]
I found a regression in 4.11-beta3+flambda which results in a stack overflow when trying to compile [`uunf`](https://github.com/dbuenzli/uunf).

The stack trace looks like:

```
Fatal error: exception Stack overflow
Raised by primitive operation at Stdlib__map.Make.bal in file "map.ml", line 114, characters 12-67
Called from Spill.reload in file "asmcomp/spill.ml", line 161, characters 32-51
Called from Spill.reload in file "asmcomp/spill.ml", line 161, characters 32-51
Called from Spill.reload in file "asmcomp/spill.ml", line 161, characters 32-51
...
Called from Spill.reload in file "asmcomp/spill.ml", line 161, characters 32-51
```

This doesn't happen in 4.10

**Comment by anmonteiro** [comment]
different stacktrace with `ulimit -s 32000`:

```
Fatal error: exception Stack overflow
Raised by primitive operation at Stdlib__map.Make.bal in file "map.ml", line 114, characters 12-67
Re-raised at Misc.try_finally in file "utils/misc.ml" (inlined), line 45, characters 10-56
Called from Profile.record_call in file "utils/profile.ml" (inlined), line 92, characters 2-307
Called from Profile.record in file "utils/profile.ml" (inlined), line 100, characters 34-78
Called from Asmgen.compile_fundecl in file "asmcomp/asmgen.ml" (inlined), line 94, characters 5-58
Called from Asmgen.(++) in file "asmcomp/asmgen.ml" (inlined), line 79, characters 15-18
Called from Asmgen.compile_fundecl in file "asmcomp/asmgen.ml" (inlined), line 84, characters 2-624
Called from Asmgen.compile_fundecl in file "asmcomp/asmgen.ml", line 84, characters 2-624
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 155, characters 49-75
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__list.iter in file "list.ml" (inlined), line 108, characters 13-64
Called from Stdlib__list.iter in file "list.ml" (inlined), line 110, characters 17-25
Called from Stdlib__list.iter in file "list.ml" (inlined), line 108, characters 13-64
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 155, characters 38-76
Called from Profile.record.(fun) in file "utils/profile.ml" (inlined), line 100, characters 74-77
Called from Misc.try_finally in file "utils/misc.ml" (inlined), line 31, characters 8-15
Called from Profile.record_call in file "utils/profile.ml" (inlined), line 92, characters 2-307
Called from Profile.record in file "utils/profile.ml" (inlined), line 100, characters 34-78
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 155, characters 5-76
Called from Asmgen.(++) in file "asmcomp/asmgen.ml" (inlined), line 79, characters 15-18
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 153, characters 2-128
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 153, characters 2-128
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 155, characters 5-76
Called from Asmgen.(++) in file "asmcomp/asmgen.ml" (inlined), line 79, characters 15-18
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml" (inlined), line 153, characters 2-128
Called from Asmgen.end_gen_implementation in file "asmcomp/asmgen.ml", line 153, characters 2-128
Re-raised at Misc.try_finally in file "utils/misc.ml" (inlined), line 45, characters 10-56
```

**Comment by Octachron** [comment]
The problem appears to be somehow caused by #9165 switching on the flambda `-O3` optimisation level compilation for the compiler. Notably, the problem also appears with the release candidate for 4.10.1 .

Interestingly, trying to compile a standalone version of the`uunf` module with the bytecode version of the native compiler fails with 4.09.0 or 4.10.0 .

This requires further investigation, but if the problem is still here tomorrow, I propose to revert this change for 4.11.0 and 4.10.1 .

**Comment by dra27** [comment]
The problem file is `src/uunf_data.ml` which contains the definitions of 7 records containing very large arrays constants. The file's not checked in to the source repo, so I've put it at https://gist.github.com/dra27/8d63edfcd4e170f88a6540d38ae69205 for convenient browsing.

**Comment by dra27** [comment]
@anmonteiro On my system, I just needed to increase the stack by a megabyte - are you sure the increase to 32MB worked?

**Comment by mshinwell** [comment]
First of all, I think it was a mistake for the function sections change to be mixed up with the `-O3` change; apologies as I should have spotted that earlier.

What appears to have happened is that the code generated by the Flambda compiler for its own `Spill` pass uses more stack space on this example than it did previously.  Flambda should not transform code such that the space complexity of stack usage is changed.  I haven't checked the differences in code generation but I suspect, in this case, it has satisfied this criterion.  @dra27 kindly did some experiments and showed that without `-O3` this example needed around 7.6Mb of stack, so in fact, it was only just managing to compile under an 8Mb stack limit (which seems to be the default on various systems such as Ubuntu and macOS).  With `-O3`, it needed about another megabyte, although this does seem at odds with the report above.  (Perhaps the original poster has a separate limit in place that meant the `ulimit` change did not actually take effect?)

I have seen similar fragility with the `uucp` package too, which like `uunf` contains very large array constructions at toplevel.  @dbuenzli I would recommend splitting those arrays up and then concatenating them together.

It isn't clear to me that for a maintenance release the compiler failing to compile files that are on the edge of failing to compile anyway is a regression, although I suspect others will disagree, and @dra27 I believe is preparing a patch to revert everything other than the function-sections change (which is unrelated to this regression).  For the 4.11 release I wouldn't have thought anything needs to be reverted.

**Comment by dbuenzli** [comment]
> I have seen similar fragility with the `uucp` package too,

Is release 13.0.0 still problematic ? Since that release the code generation does structure sharing in a lot of cases (reducing `uucp.cmxs` from 7.8Mo to 4.6Mo). I didn't get to port that to `uunf` though. I can try to do it for `uunf` more quickly than I would like if that avoids the problem. 

> very large array constructions at toplevel. @dbuenzli I would recommend splitting those arrays up and then concatenating them together.

That it doesn't do and seems a bit more annoying to do. Wouldn't the above help and suffice ? I mean the length of the [toplevel array](https://github.com/dbuenzli/uucp/blob/master/src/uucp_tmap.ml#L10) of uucp's bit tries is ~~8191~~ 272 which doesn't sound horribly large.

**Comment by dbuenzli** [comment]
> uucp's bit tries is 8191 which doesn't sound horribly large.

Sorry that was wrong that should have [read 272](https://github.com/dbuenzli/uucp/blob/master/src/uucp_tmap.ml#L14).

**Comment by anmonteiro** [comment]
> @anmonteiro On my system, I just needed to increase the stack by a megabyte - are you sure the increase to 32MB worked?

I can't believe I got bitten by this again. I set it on the parent shell, but the new one that spawned the build process started with the default stack size. You're right, of course.

**Comment by Octachron** [comment]
@mshinwell :
> It isn't clear to me that for a maintenance release the compiler failing to compile files that are on the edge of failing to compile anyway is a regression

I would agree if the failure was intended and known in advance. But in this case, we have a existing library which has been broken by a side-remark in a PR. This feels like a regression to me.

**Comment by xavierleroy** [comment]
If I understand correctly, one of the -O3 optimizations is increasing the stack memory usage of some compiler functions (perhaps `Spill.reload`, perhaps other functions) compared with unoptimized code.  

To me, an optimization that increases stack consumption is not an optimization and borders on miscompilation.  Perhaps  it's just a bug in the implementation of a legitimate optimization.  Perhaps the optimization is broken (w.r.t. stack usage) by design.  In either case we need to identify the optimization in question and see what to do about it.  Shrugging it off as "oh well ocamlopt overflows the stack sometimes" is not enough.

**Comment by lthls** [comment]
I've done a bit of investigating on this, and it turns out that for `Spill.reload`, the stack frame for the function is bigger when compiled with -O3 than with the default options.
This is kind of expected: the inlining parameters given with the -O3 flag make it more likely to create big functions, and big functions are more likely to need bigger stack frames.
There is no practical way currently for the middle-end to have any control on the actual size of the stack frames (this is all decided during register allocation), so the middle-end wouldn't even know that it's generating bigger stack frames.
The number of values live across the recursive call doesn't change (only two virtual registers are live across the call in both cases), so if the backend is changed to shrink and grow back the stack around recursive calls as much as possible, this would solve this problem, at the cost of adding more instructions.
Finally, I strongly suspect that this behaviour would also occur with the closure backend with big enough values of `-inline`.
For the curious, the peak virtual register usage (with -O3) occurs in the `Iswitch` case of `reload`, after inlining of both `Array.map` and its argument, in the (inlined) `max !date_join !current_date` call, with 13 virtual registers live across a call to `caml_greaterequal`.

**Comment by kit-ty-kate** [comment]
The latest release of uunf (13.0.0) and all previous releases still stack overflow using the latest 4.12 branch (0046bcb1a3f80305dfff4de4a3fe9e66d9eabbc1) with the default stack size (8192)

**Comment by lthls** [comment]
Only with flambda ? Or also with the default config ?

**Comment by kit-ty-kate** [comment]
only with flambda

**Comment by gretay-js** [comment]
The PR #9840  was applied on 4.10 and 4.11 but not on trunk when it was merged in, so it didn't make it into 4.12.

**Comment by Chris00** [comment]
@kit-ty-kate I had the same problem with color-brewery.  [A patch of the opam file](https://github.com/Chris00/color_brewery/commit/91eb36ff7bf9361bbfbc42aef01d71bd4ac74a76#diff-cecf8ffdf1630ecae9b24a9a2fefeb164987a9db05107df9a3216a024fd52251R11) was necessary.

**Comment by kit-ty-kate** [comment]
Hi, sorry if this is unrelated but could someone have a look at https://github.com/ocaml/opam-repository/pull/18024? This package also stack overflows with flambda on 4.11.1.
```
#=== ERROR while compiling timere.0.1.0 =======================================#
# context              2.1.0~beta4 | linux/x86_64 | ocaml-variants.4.11.1+flambda | pinned(https://github.com/daypack-dev/timere/releases/download/v0.1.0/v0.1.0.tar.gz)
# path                 ~/.opam/4.11/.opam-switch/build/timere.0.1.0
# command              ~/.opam/4.11/bin/dune build -p timere -j 47
# exit-code            1
# env-file             ~/.opam/log/timere-19-62c75d.env
# output-file          ~/.opam/log/timere-19-62c75d.out
### output ###
#     ocamlopt tzdb-full/.timere_tzdb_full.objs/native/timere_tzdb.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.11/bin/ocamlopt.opt -w +a-4-9-29-37-40-42-44-48-50-32-30@8 -g -I tzdb-full/.timere_tzdb_full.objs/byte -I tzdb-full/.timere_tzdb_full.objs/native -I tzdb-module/.timere_tzdb.objs/byte -I tzdb-module/.timere_tzdb.objs/native -intf-suffix .ml -no-alias-deps -open Timere_tzdb__timere_tzdb_full__ -o tzdb-full/.timere_tzdb_full.objs/native/timere_tzdb.cmx -c -impl tzdb-full/timere_tzdb.ml)
# Fatal error: exception Stack overflow
```

**Comment by gasche** [comment]
`timere` generates a `.ml` file of 4Mib of very long list literals to represent timezone information:
  https://github.com/daypack-dev/timere/blob/6d7689a/gen-artifacts/time_zone_data.ml

This is clearly a case of program-generated code that, according to the current doxa, should be rewritten to concatenate smaller literals instead.

**Comment by dbuenzli** [comment]
> I didn't get to port that to `uunf` though.

I ported the patches @pqwy made for `uucp` for interning strings over to `uunf`. It will be in the next release (14.0.0), we will see if that improves things.

**Comment by kit-ty-kate** [comment]
I'm still getting the same stack overflow with uunf.14.0.0 on PPC64 (vanilla), at this exact line:
https://github.com/ocaml/ocaml/blob/62b6fc9dbeb5ea7f43447cb68b3fad8c3327b6d8/asmcomp/spill.ml#L305

**Comment by dbuenzli** [comment]
We are [getting stackoverflows](https://github.com/ocaml/opam-repository/pull/19599) on both  `ppc64` and `aarch64` with the regular OCaml compiler 4.12. The problem of the "current doxa" is that it's unclear to the programmer what is acceptable, what is not and what you have to do about it when you hit the problem. 

The advice "concatenate your large arrays" seems a bit off to me in this case.

For reference I uploaded the generated file we are talking about [here](https://gist.github.com/dbuenzli/faf1716117dd1a4a3431117cddc04752). @kit-ty-kate [tracked](https://github.com/ocaml/ocaml/issues/9839#issuecomment-920823571) (thanks!) the problem on ppc64 to the compilation of [this data structure](https://gist.github.com/dbuenzli/faf1716117dd1a4a3431117cddc04752#file-uunf_data-ml-L2368) literal. 

More specifically, this data structure is a sparse [trie map](https://github.com/dbuenzli/uucp/blob/12fde1afdd324301103180be001e5845f3d380b0/src/uucp_tmap.ml#L10) on the integers of Unicode characters, that is the bits `0x1FFFFF` decomposed as `0x1FF - 0xFF - 0xF`. Taking into account `Uchar.max` this means the size of the individual nested arrays is respectively, 272, 256, 16 and the final leaves, if we reach them, are small (I'd say 1-4) arrays of integers. So the problem is clearly not about large arrays.

Since @pqwy's patches for interning the strings easily allowed for it, we [tried](https://github.com/dbuenzli/uunf/commit/238d7026458de2926385f749acb8ea9cdd080faa) to `let`-define the leaves of the array, that didn't improve anything – there's anyway not much to share here since it is character decomposition maps (é -> e + ´) which are pretty unique to each character. 

So who gets to fix the stuff, me or the compiler team :-) ? And if it's the former what is the robust fix here ?

**Comment by gasche** [comment]
I think your question is valid and I don't have a good answer. On the specific example: if I understand correctly, you have tried to replace `[| [| a00; a01 |]; [| a10; a11 |]` by

```ocaml
let a0 = [| a00; a01 |] in
let a1 = [| a10; a11 |] in
[| a0; a1 |]
```

I wonder what would happen with

```ocaml
let a0 = Sys.opaque_identity [| a00; a01 |] in
let a1 = Sys.opaque_identity [| a10; a11 |] in
[| a0; a1 |]
```

which might prevent some inlining from going back to step 0.

**Comment by kit-ty-kate** [comment]
@gasche yes, I've tried that and a variety of similar approaches for several hours yesterday without success sadly :(

**Comment by lthls** [comment]
Your problem is that the compiler produces roughly one instruction for each array cell, to initialise the array to its value. All these instructions occur one after the other in the main module's initialisation code, and since the compiler isn't tail recursive on sequences of operations you get very high stack usage while compiling.

So simply splitting the file into several parts will make the various initialisation operations split into several functions and avoid the stack overflows. You don't even need to concatenate arrays: if you have several arrays defined at toplevel, you can have each array into its own file; if that's not enough, you could start looking at having separate files for sub-arrays (though I hope you won't need that).

If you're willing to listen to dangerous advice, you could also look at patching your generators to use statically allocated structures instead of arrays, and then cast those structures into arrays with `Obj.magic`. (Concretely, for arrays of size `> 1` you can use tuples, for arrays of size `1` you can use `Some x`, and for arrays of size `0` you can use the normal empty array `[| |]`). Or use lists instead of arrays, though I expect that this will have an impact on performance.

(I don't think that `Sys.opaque_identity` is going to change anything)

**Comment by dbuenzli** [comment]
Thanks @lthls for the explanation, at least I understand the problem now.

> So simply splitting the file into several parts will make the various initialisation operations split into several functions and avoid the stack overflows.

That seems a reasonable solution on me. I'll try it at some point (at least for the next Unicode release).

> If you're willing to listen to dangerous advice,

Thanks but I'm not :-) I also have my own doxas…

> Or use lists instead of arrays, though I expect that this will have an impact on performance.

And memory consumption.

**Comment by lthls** [comment]
> > Or use lists instead of arrays, though I expect that this will have an impact on performance.
> 
> And memory consumption.

Not really, the whole point of using lists is that everything gets statically allocated so you get 0 memory consumption. You get bigger executables though.

**Comment by dbuenzli** [comment]
I'm a bit puzzled by your comment. There should be quite a difference in representation between `int list` and `int array`. The latter has much less fat pointers.

**Comment by bluddy** [comment]
I think the suggestion is not to do `Obj.magic` on lists, but to simply switch to using lists altogether.

Why are lists statically allocated while arrays are not though? Arrays are a much more natural fit for static allocation I would think.

**Comment by lthls** [comment]
(I'm speaking for the native compiler only. In bytecode you're right that lists consume more memory).

Constant lists, even enormous ones, can be statically allocated in the data section of the object file. So they do take space in memory, but no allocation takes place at runtime. They do get registered as GC roots (because we're not trying too hard to find if they cannot refer to any GC-allocated pointer), so it could have an impact on execution speed.

> Why are lists statically allocated while arrays are not though? Arrays are a much more natural fit for static allocation I would think.

Arrays are mutable.

**Comment by kit-ty-kate** [comment]
I've just proposed a fix to the compiler: https://github.com/ocaml/ocaml/pull/10643 which makes `uunf` compile perfectly on ppc64 with the default stack size.

Feel free to test it and comment on it.

**Comment by xavierleroy** [comment]
The first thing to try is `ulimit -s unlimited`.  It works great under Linux.  My guess is that if @kit-ty-kate was to add that to the OPAM build instructions for this package, the problem would go away.

**Comment by xavierleroy** [comment]
Second, the compiler back-end uses stack roughly proportional to the size of each function, but independent of the number of functions.  (The initialization code for the compilation unit is a function too.) So, to take a silly example, to initialize a very big array, dont' do
```
let _ =
  a.(0) <- a0;
  ...
  a.(999_999) <- a999_999
```
but do something like
```
let f0 () = a.(0) <- a0; ... a.(999) <- a999
...
let f999 () = a.(999_000) <- a999_000; ... a.(999_999) <- a999_999

let _ =
  f0 (); ... f999()
```
(It's prudent to add "inline never" annotation to the functions.)

**Comment by xavierleroy** [comment]
Third, array literals `[| ... |]` consisting of compile-time constants are allocated statically, then copied into the heap when the literal is evaluated, so as to avoid problems with mutability.  So, a very big array like
```
  [| 0; ... ; 999_999 |]
```
will still be compiled efficiently and quickly.  However, such an array of constants is not a compile-time constant, so if you nest arrays
```
  [| [|0|]; ... ; [|999_999|] |]
```
the outer array cannot be statically allocated then copied, it has to be filled one entry at a time.

That's the biggest difference with lists: lists being immutable, lists of constants can always be statically allocated, even when nested.

**Comment by dbuenzli** [comment]
Thanks for the further explanations. 

> Constant lists, even enormous ones, can be statically allocated in the data section of the object file. So they do take space in memory, but no allocation takes place at runtime.

I see. My initial comment was rather referring to the cons cells vs the compact representation of an array. Especially if your data are integers.

> The first thing to try is `ulimit -s unlimited`. It works great under Linux. My guess is that if @kit-ty-kate was to add that to the OPAM build instructions for this package, the problem would go away.

That works. 

At @mseri's suggestion we added an opam `post-messages` on failures of these packages on these architectures that entices the user to do that.  

Doing it automatically in the build is possible but people may not like their package manager taking these kind of decisions for them. In the long term, I'll rather try to fix things by splitting this file.

**Comment by xavierleroy** [comment]
> Doing it automatically in the build is possible but people may not like their package manager taking these kind of decisions for them.

I like to think of it this way.  Memory is memory.  An application can use memory for heap or for stack, which is a special kind of heap with fast but constrained allocation and deallocation mechanisms.

It's a twentieth-century superstition that using a lot of stack space is wrong, while using a lot of heap space is fine.  Both are fine.

After a long wait, Linux (and maybe some other kernels) agreed to lift a priori limits on stack usage and support `ulimit -s unlimited` gracefully.  Let's take advantage of this rather than continuing the superstition.

I'm actually tempted to add `setrlimit(RLIMIT_STACK, RLIM_INFINITY);` to the start-up of the OCaml runtime system, just to make the point above clear for everyone.

**Comment by dbuenzli** [comment]
> I like to think of it this way. Memory is memory. An application can use memory for heap or for stack, which is a special kind of heap with fast but constrained allocation and deallocation mechanisms.

I don't disagree with this view. I dislike having to make my functions tail-recursive, I feel like a circus monkey dancing to trade stack space for heap space…

**Comment by kit-ty-kate** [comment]
> I'm actually tempted to add `setrlimit(RLIMIT_STACK, RLIM_INFINITY);` to the start-up of the OCaml runtime system, just to make the point above clear for everyone.

I'd be in favour of that.
The other day I was actually wondering what the implications would be if opam was doing the same globally

**Comment by anmonteiro** [comment]
FWIW `uunf` currently fails to compile with trunk, no matter what stack limit amount is set.

**Comment by gasche** [comment]
You now have to use `OCAMLRUNPARAM="l=123456789"`, and you should be able to find a setting (maybe 123456789 :-) that works -- on any system/architecture now!

**Comment by anmonteiro** [comment]
Can confirm this works. Thanks @gasche!

**Comment by gasche** [comment]
See #10795 for more discussion on our default stack size settings.

**Comment by nojb** [comment]
This can be closed.
