### ISSUE TITLE
Telling ocamlopt about the probability of conditional branches

### ISSUE THREAD

**Issue by stefan-kral** [ocaml/ocaml#9845]
On modern Intel64/AMD64 CPUs (and presumably on ARM64, too), conditional branches are noticeably slower when they are taken&mdash;even if the taken/not-taken decision and the branch target are both *perfectly* predicted:

- *taken*: latency: 2 cycles, throughput: at most 1 taken branch every other cycle.
- *not taken*: latency: 0 cycles, throughput: at most 2 not-taken branches per cycle.

To exploit this, `gcc` offers `__builtin_expect` for specifying the likelyhood of a branch being taken.

Having something similar in `ocamlopt` would be great! An attribute like `inlined` could fit nicely.

P.S. I'm aware that (a) there are many applications that might not profit from this and (b) abusing this feature may well be a de-optimization. With my application (ISO-conforming Prolog system), however, I *know* that I have to do *a lot of runtime tests* all of which *will never fail* in functioning code.

**Comment by gretay-js** [comment]
I wonder if basic block layout optimization using [ocamlfdo](https://github.com/gretay-js/ocamlfdo) would do the right thing for your application. The tool requires an execution profile instead of code annotations. Currently, compiler support for ocamlfdo is not yet entirely merged in upstream, but if you use opam and build with dune it should be possible to try.
