### ISSUE TITLE
Older OCaml for MinGW versions (4.07.1, 4.08.1) don't build any more after Cygwin MinGW header update

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/ocaml#9938]
Since (afaik) this only affects older versions of OCaml this is more to make you aware of the situation and not a request to fix it. I reported this to (https://github.com/fdopen/opam-repository-mingw/issues/77) and supplied a patch so it will likely be fixed there with an opam patch.

As far as I can tell the trunk version is not affected by this.

The root cause is that function `snprintf` was not defined and emulated before and is now defined after the MinGW header update which interfers with the emulation.

**Comment by dra27** [comment]
I'm seeing this on trunk as well - are you sure?

**Comment by MSoegtropIMC** [comment]
I didn't try it but I couldn't find the failing piece of code in trunk. But it might be that I just searched for `misc.h` and not for `snprintf`.

In case it fails in your CI I can definitely have a look at trunk and try to fix it there as well (maybe in a more appropriate way).

**Comment by dra27** [comment]
It's anywhere where `stdio.h` is `#include`'d after `misc.h`. It's very easy to have that happen since `mlvalues.h` pulls in `domain_state.h` which pulls in `stdio.h` (correctly ~IIRC~, as it needs `FILE`). So it's more any C file which _doesn't_ explicitly include `stdio.h` will probably implicitly pull it in at the wrong point.

The issue is that [bfd33f6](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/bfd33f6c0ec5e652cc9911857dd1492ece8d8383/) in mingw-w64 enabled mingw-w64's ANSI stdio shims for more versions. mingw-w64 has always defined an inline snprintf, but it didn't matter before because it pushed and popped our `snprintf` macro before doing so. The `__USE_MINGW_ANSI_STDIO` case doesn't push and pop `snprintf` so we get this error.

I'm working on a fix.
