### ISSUE TITLE
Flambda creates spurious roots

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/ocaml#9978]
Consider the following program:

```ocaml
let root = ref [||]
let free () = root := [||]; Gc.full_major ()
let () =
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ();
  root := Array.make 100000000 0;
  free ()
```

In trunk, and when flambda is enabled, the heap is grown up to several gigabytes, but stays under 1GB when flambda is disabled.
The issue exists both with the default optimzation level of flambda and with `-O3`.

The reason is that flambda creates spurious global roots each time `Array.make` is called, so that the corresponding arrays are never reclaimed by the GC. These roots are called `camlTest__Pccall_xxx`, where xxx is an integer.

Not only this is a memory leak, but I would argue that this is also a performance regression, since it seems like there is a write and a read to this spurious root each time a C function is called. These memory accesses seem purely useless and should be removed.

**Comment by lthls** [comment]
Flambda has some specific code patterns for toplevel code that are there to try to emulate Closure (which allocates statically in some cases that look very similar to this one from flambda's point of view).
The fix I would suggest is to do all your tests in a function with `[@inline never]`, to avoid the particular issues with toplevel compilation.
I can provide you with examples that are as problematic (keeping allocations alive while they should be reclaimed), but only with Closure and not with Flambda, if you're interested.

If you want a real fix, this will not be doable in a rush as we need to preserve static allocation of toplevel expressions in the general case.

**Comment by jhjourdan** [comment]
What I understand from your answer is that:

1- With flambda, any temporary variable at the toplevel is turned into a top-level let-binding (and not a nested let-binding : a real top-level let-binding), and flambda has no way to distinguish this new kind of let-binding.
2- A top-level let-binding is always turned into a global root.

As a result, any temporary variable used in top-level code is turned into a global root. Is my interpretation right?

I do not know whether the right fix is to change 1- or 2-, but in any case, the result seems very wrong to me: yes, toplevel code may allocate large amount of memory and this memory should not be bound to a global root, except maybe if the user *explicitly* bound it to a top-level let-binding.

My first feeling is that 2- is the culprit: if a top-level let-binding does not appear in the module signature (either .mli file/module signature or the one that could be inferred from the .ml file), then it should not be considered as a global root. But then you seem to disagree since you say that
> we need to preserve static allocation of toplevel expressions in the general case.

Why so? Do you have examples of actual code which depends on the fact that every top-level let-binding is turned into a global root, even if this top-level let-binding does not appear in the module's interface?

In addition, if you really want to enforce 2-, then apparently what you do is not enough since you write:
> I can provide you with examples that are as problematic (keeping allocations alive while they should be reclaimed), but only with Closure and not with Flambda, if you're interested.

(BTW, yes, I am interested). Thus, the mechanism you are speaking about tries to reproduce the behavior of Closure, but fails to do so since some global roots introduced by Closure do not exist with flambda, but at the same time it creates memory leaks... This really leads me to question the very existence of this mechanism.

Anyway, if you have a good reason to "emulate" this behavior of Closure, then, well, you need change 1-, which mean that local let-binding and temporaries should be given a special status so that they don't end up being turned into global roots.

**Comment by xavierleroy** [comment]
> I can provide you with examples that are as problematic (keeping allocations alive while they should be reclaimed), but only with Closure and not with Flambda, if you're interested.

Let's not get into a pot-and-kettle fight.  I'm pretty sure Closure can also keep things alive for too long, but I would hope it doesn't keep those things alive forever, as happens when putting those things into global roots.   

So, we have an Flambda bug here that needs fixing.

**Comment by jberdine** [comment]
>> we need to preserve static allocation of toplevel expressions in the general case.
>
> Why so?

I don't claim to know the original intended semantics, but as a data point, I expect top-level module items to be statically allocated, whether they appear in the external signature or not (presuming that they are referenced elsewhere in the module). We have code that does a sort of static memoization of some constant expressions that relies on physical equality of such top-level module items. This would break if for instance such an expression was not considered to be live forever and instead was re-evaluated multiple times across the program execution. As far as I understand this doesn't have any bearing on intermediate values, and values that end up being compiled into top-level items when they were not in the source.

**Comment by lthls** [comment]
I have examples where closure keeps unneeded values alive forever, and Flambda doesn't, but I agree that it's mostly unrelated to this bug report.

The main reason why Flambda allocates the result of toplevel computations into static storage (which get registered as global roots) is to be as efficient as Closure on this common pattern:
```ocaml
(* foo.ml *)
exception E

let f x =
  try if x then raise E else ()
  with E -> ()
```
```ocaml
(* foo.mli *)

val f : bool -> unit
```

The main issue here is that we want to compile `f` into a closed function, despite its dependency on `E`.
If you look at the output of `-dlambda` for this program, with `ocamlc` and `ocamlopt`, you'll notice that the definition of `f` is not closed in the lambda generated for bytecode, not closed in the lambda generated for Flambda, but closed in the lambda generated for Closure.
This is because there are two different translation strategies to generate lambda terms:
- The "normal" one, which translates the file `foo.ml` almost exactly as:
`module Foo : sig (* foo.mli *) end = struct (* foo.ml *) end`
- The "store" one which is used when compiling for the Closure backend, which can be sort of explained as translating the file to:
`module Foo : sig (* foo.mli *) (* rest of the inferred interface for foo.ml *) end = struct (* foo.ml *) end`

As a result, with Closure the exception `E` is part of the module's "signature" and is allocated statically, while in bytecode and Flambda the exception is local and needs to be part of `f`'s closure.
(The issue is not restricted to exceptions, other toplevel values end up statically allocated with Closure but not with Flambda because of this, but exceptions are the most common cause of functions becoming non-closed with Flambda.)

So to get back to the same level of performance as Closure (and because it makes sense most of the time anyway), Flambda lifts all values defined at toplevel (meaning, during the evaluation of the module's initialisation code and not inside functions, loops or conditional branches), and stores their result into statically allocated symbols. This way, functions can refer to them by symbol instead of by variable, and then can become closed, which allows to statically allocate their closures too (which later helps with inlining).

However, there is no easy way at the Flambda stage to make a difference between values bound to a toplevel variable in the original file, that Closure would have lifted, and values which only became bound at toplevel because of some simplification, either during translation to lambda, or lambda simplification, or flambda simplification. So the default is still to lift everything, but since we can also remove those static allocations if they are/become unused, in practice it almost always leads to statically allocating what is needed and no more, the main exception being small tests with all their code at toplevel.

Finally, it could be deduced from the above details, but here is an example of program that will keep a value live with Closure but not Flambda (nor in bytecode):
```ocaml
(* bar.mli, empty *)
```
```ocaml
(* bar.ml *)
let a = Array.make 100000000 0

let _ = Gc.full_major ()

(* rest of the code, not using a *)
```
With Closure, the array `a` will stay alive in the rest of the code, including compilation units linked after `Bar`. With the regular compilation scheme, `a` is not exported in the interface so it will become dead and collected at some point (though not necessarily at the first `Gc.full_major ()`, at least in bytecode I think `a` would still be reachable at that point).

**Comment by jhjourdan** [comment]
> This would break if for instance such an expression was not considered to be live forever and instead was re-evaluated multiple times across the program execution.

I agree that re-evaluating multiples times an expression (even a constant) because we decided not to keep the corresponding let-binding could be harmfull and should be not be taken lightly. But I do not think this is the problem here: it seems very possible to me to use the same value several times, either by storing it in the closures of the corresponding functions or (as is preferable for performance reason as @lthls explained) by using static storage, *but not when this is just a local variable*.

**Comment by jhjourdan** [comment]
Thanks @lthls for the detailed explanations. It is much clearer now!

> So the default is still to lift everything, but since we can also remove those static allocations if they are/become unused, in practice it almost always leads to statically allocating what is needed and no more, the main exception being small tests with all their code at toplevel.

Then it seems that the right thing to do is to improve this optimization so that it does not move declarations to static storage unless they are indeed used in functions which:
  - would become closures if these declarations were not moved to static storage
  - are themselves top-level declarations which we want to keep in the static storage, either transitively or because they appear in the signature.

**Comment by lthls** [comment]
I've had the opportunity to discuss this with other Flambda developers, and the conclusion is that implementing @jhjourdan's suggestion would be a non-trivial patch to a non-trivial part of the code, for something that we do not consider a bug (after all, nothing in the semantics of the language says at which point values are expected to become collected by the GC), and which has only been reported on manually crafted test programs. We're not planning to address this issue on the current Flambda codebase, but will keep this problem in mind for future versions.

As there is a workaround available, I would suggest closing this issue.

**Comment by jhjourdan** [comment]
At which point the GC collects values is indeed not well specified. However, it is still very unexpected that temporary variables get transformed into global roots... So I still consider this as a bug, please do not close the issue.

By deciding that you will not fix this issue, you are assuming something about the source program which might be right for the majority of programs you are thinking about but not for some others. That's usually not the way compilers are designed. They should be correct for all input programs. Essentially, you are waiting for someone reporting a bug which is hard to understand (as most memory leaks) in order to fix an issue you already know about...

**Comment by lthls** [comment]
> it is still very unexpected that temporary variables get transformed into global roots...

It is unexpected, but it is actually better than not doing so in most cases. For example, inlining of functor applications at toplevel produce very similar siituations, and statically allocating the result of the computations coming from the functor's body definitively helps.
In a way, Flambda considers everything that happens at toplevel to be initialisation code: it will only be run once at the start of the program, and then becomes irrelevant. We assume that everything important occurs in non-toplevel code. This is a conscious design choice, and leads us to produce bad code when this assumption does not hold, but allows us to produce good code whenever the assumption holds (in most real world programs) without making our compiler too complex.


> By deciding that you will not fix this issue, you are assuming something about the source program which might be right for the majority of programs you are thinking about but not for some others. That's usually not the way compilers are designed.

I'd like to know where you got this idea. As long as the input language is complex enough (Turing-complete being as complex as you can get), an optimising compiler will be tailored to the kind of inputs it expects and will produce non-optimal code for all the rest. That Closure and Flambda have different kinds of expected inputs should not come as a surprise.

> They should be correct for all input programs.

I strongly disagree that the Flambda compiler is incorrect on your program. That it generates bad code I can accept, but it doesn't generate wrong code.

I'm suggesting to close this issue not to assert that there is nothing wrong (though I'm not sure I would call it a bug), but as a way to sort this issue into the "Won't fix" category. I won't close it unilaterally, I don't really know if our policy is to keep such issues open or or not anyway.

**Comment by lpw25** [comment]
I think "won't fix" is too strong. Whilst the definition of "bug" is debatable, this is clearly a bad behavior that we would like the compiler not to have. My understanding is that this issue will be addressed in flambda 2, but that it would be a lot of work to address it in flambda 1 and no one is inclined to spend too much time on a version of the code that is on its way out. I think it is perfectly reasonable to say that we don't intend to fix the behavior in flambda 1, but labeling the issue "won't fix" implies that either we don't think it is an issue or that we never intend to have it fixed -- neither of which is true to my knowledge.

**Comment by mshinwell** [comment]
I confirm that Flambda 2 does not exhibit this bad behaviour (at least on this example) so I think we can close this.
