### ISSUE TITLE
 make inconsistent assumptions over implementation Stdlib__sys Error 

### ISSUE THREAD

**Issue by quantshayan** [ocaml/ocaml#9995]
I have ocaml num installed in my system, while building Scilab which uses ocaml as one of it dependecies I am getting this error. 
"make inconsistent assumptions over implementation Stdlib__sys" 

After checking out other "softwares" which has this dependencies few are reporting the same error while building.

Can anyone explain a method to resolve this, i think some package management is required.'

PS: i am not very savvy with ocaml ecosystem

**Comment by Octachron** [comment]
This kind of error is a sign of mixing different versions of the compiler. It might be an OS-level packaging problem, an issue with Scilab build process, or multiple OCaml installation overlapping. It would be helpful to precise what is your system and how you are compiling Scilab.

Since the error is not related to the compiler, I am closing this issue.
However, please feel free to ask more question here or in https://discuss.ocaml.org !
